import { describe, expect, test } from "bun:test";
import { runReportCorpusBenchmark, type ReportCorpusFixture } from "../adapters/reportCorpusBenchmark.ts";
import { source } from "./helpers/adapterRegressionFixtures.ts";

describe("adapter report extraction readiness", () => {
  test("builds Program BB readiness across malformed unsupported stale duplicate policy and multilingual fixtures", () => {
    const fixtures: ReportCorpusFixture[] = [
      { id: "vendor_report_ready", fixtureClass: "vendor_report", source: source("src_report_vendor", "static_web", "https://vendor.example.test/reports/apt29"), profileInput: { sourceType: "static_web", url: "https://vendor.example.test/reports/apt29", contentType: "text/html", language: "en" }, title: "APT29 vendor report", text: "APT29 public report describes malware tooling, infrastructure, and CVE-2026-2929 exploitation against government victims.", publishedAt: "2026-05-20T00:00:00.000Z", expectedLanguage: "en", expectedQueryClasses: ["actor", "malware_tool", "cve", "infrastructure", "victim_company"] },
      { id: "cert_advisory_ready", fixtureClass: "advisory", source: source("src_report_cert", "static_web", "https://cert.example.test/advisories/cve-2026-4242"), profileInput: { sourceType: "static_web", url: "https://cert.example.test/advisories/cve-2026-4242", contentType: "text/html", language: "en" }, title: "CERT advisory CVE-2026-4242", text: "CERT advisory for CVE-2026-4242 describes exploitation risk, affected versions, mitigations, and energy sector impact.", publishedAt: "2026-05-21T00:00:00.000Z", expectedLanguage: "en", expectedQueryClasses: ["cve", "sector"] },
      { id: "multilingual_report_review", fixtureClass: "multilingual_report", source: source("src_report_multilingual", "pdf", "https://vendor.example.test/reports/rapport-apt42.pdf"), profileInput: { sourceType: "pdf", url: "https://vendor.example.test/reports/rapport-apt42.pdf", contentType: "application/pdf" }, title: "APT42 rapport", text: "Le rapport APT42 décrit une attaque de phishing contre des victimes gouvernementales.", publishedAt: "2026-05-20T00:00:00.000Z", expectedLanguage: "fr", pageCount: 8, scannedPageCount: 0, ocrAvailable: true, ocrConfidence: 0.88 },
      { id: "malformed_pdf_hold", fixtureClass: "malformed_pdf", source: source("src_report_malformed", "pdf", "https://vendor.example.test/reports/broken.pdf"), profileInput: { sourceType: "pdf", url: "https://vendor.example.test/reports/broken.pdf", contentType: "application/pdf" }, title: "Malformed PDF report", text: "", publishedAt: "2026-05-20T00:00:00.000Z", parserWarnings: ["malformed xref table"], pageCount: 0, scannedPageCount: 0, ocrAvailable: false },
      { id: "unsupported_mime_hold", fixtureClass: "unsupported_mime", source: source("src_report_archive", "pdf", "https://vendor.example.test/reports/archive.zip"), profileInput: { sourceType: "pdf", url: "https://vendor.example.test/reports/archive.zip", contentType: "application/zip" }, title: "Unsupported report archive", text: "Archive wrapper is not a parseable public report body.", publishedAt: "2026-05-20T00:00:00.000Z" },
      { id: "stale_report_watch", fixtureClass: "stale_report", source: source("src_report_stale", "static_web", "https://vendor.example.test/reports/old-campaign"), profileInput: { sourceType: "static_web", url: "https://vendor.example.test/reports/old-campaign", contentType: "text/html", language: "en" }, title: "Old campaign report", text: "Old campaign report describes APT29 historical phishing infrastructure and malware tooling.", publishedAt: "2025-01-01T00:00:00.000Z" },
      { id: "duplicate_report_hold", fixtureClass: "duplicate_canonical", source: source("src_report_duplicate", "static_web", "https://mirror.example.test/reports/apt29-copy"), profileInput: { sourceType: "static_web", url: "https://mirror.example.test/reports/apt29-copy", contentType: "text/html", language: "en" }, title: "APT29 mirrored report", text: "APT29 public report duplicate mirror with the same malware tooling and infrastructure claims.", publishedAt: "2026-05-20T00:00:00.000Z", canonicalUrlHash: "sha256:canonical-apt29-report", duplicateCanonicalKey: "canonical-apt29-report" },
      { id: "policy_hold_report", fixtureClass: "restricted_policy_hold", source: source("src_report_policy_hold", "static_web", "https://restricted.example.test/reports/private"), profileInput: { sourceType: "static_web", url: "https://restricted.example.test/reports/private", contentType: "text/html", failureCategory: "policy_hold" }, title: "Policy hold report", text: "Restricted target metadata is held without raw report extraction.", publishedAt: "2026-05-20T00:00:00.000Z", failureCategory: "policy_hold", robotsAllowed: false, legalNotes: "Policy hold fixture." }
    ];
    const report = runReportCorpusBenchmark(fixtures, "2026-05-24T00:00:00.000Z");
    expect(report.summary).toMatchObject({ total: 8, extractionReady: 2, extractionWatch: 2, extractionHold: 4, unsupportedMedia: 1, staleReports: 1, duplicateCanonicalReports: 1, languageReview: 1 });
    expect(report.fixtureCoverage).toMatchObject({ vendor_report: 1, advisory: 1, multilingual_report: 1, malformed_pdf: 1, unsupported_mime: 1, stale_report: 1, duplicate_canonical: 1, restricted_policy_hold: 1 });
    expect(report.rows.find((row) => row.fixtureId === "vendor_report_ready")?.extractionReadiness).toMatchObject({ status: "pass", queryClasses: ["actor", "malware_tool", "cve", "infrastructure", "victim_company"], handoffs: { agent03Adapter: "certify_fixture", agent09Api: "safe_to_surface", agent10Release: "green" } });
    expect(report.rows.find((row) => row.fixtureId === "multilingual_report_review")?.extractionReadiness).toMatchObject({ status: "pass", handoffs: { agent03Adapter: "certify_fixture", agent07Quality: "accept" } });
    expect(report.rows.find((row) => row.fixtureId === "malformed_pdf_hold")?.mediaReadiness).toMatchObject({ status: "malformed", blockers: expect.arrayContaining(["malformed_report_parser_warning"]) });
    expect(report.rows.find((row) => row.fixtureId === "unsupported_mime_hold")?.mediaReadiness).toMatchObject({ status: "unsupported", blockers: expect.arrayContaining(["unsupported_media:application/zip"]) });
    expect(report.rows.find((row) => row.fixtureId === "stale_report_watch")?.extractionReadiness).toMatchObject({ status: "watch", warnings: expect.arrayContaining(["stale_publication"]) });
    expect(report.rows.find((row) => row.fixtureId === "duplicate_report_hold")?.extractionReadiness).toMatchObject({ status: "hold", blockers: expect.arrayContaining(["duplicate_canonical_report"]) });
    expect(report.rows.find((row) => row.fixtureId === "policy_hold_report")?.extractionReadiness).toMatchObject({ status: "hold", blockers: expect.arrayContaining(["policy_or_robots_hold"]), handoffs: { agent03Adapter: "block_promotion", agent06Evidence: "hold_capture_replay", agent09Api: "hold_route_output", agent10Release: "hold" } });
    expect(report.rows.every((row) => row.provenanceContract.collectedItemCompatible)).toBe(true);
    expect(report.rows.every((row) => row.provenanceContract.canonicalUrlHash)).toBe(true);
    expect(report.routeContract.stableFields).toEqual(expect.arrayContaining(["fixtureCoverage"]));
    expect(report.routeContract.forbiddenFields).toEqual(expect.arrayContaining(["rawUrl", "unsafeUrl", "rawText", "objectKey", "ocrVendor"]));
    const serialized = JSON.stringify(report);
    for (const forbidden of ["https://vendor.example.test/reports/apt29", "https://cert.example.test/advisories/cve-2026-4242", "https://restricted.example.test/reports/private"]) expect(serialized).not.toContain(forbidden);
  });
});
