// @ts-nocheck
import { buildTelegramPublicActorReadinessDto, buildTelegramPublicCanaryRollout, buildTelegramPublicCompactSearchSummary, buildTelegramPublicCutoverReport, buildTelegramPublicEvidencePromotionProgram, buildTelegramPublicIncrementalPollDto, buildTelegramPublicOperatorControlEffects, buildTelegramPublicOperatorStates, buildTelegramPublicPromotionCanaryProof, buildTelegramPublicPromotionCertification, buildTelegramPublicReliabilityReport, buildTelegramPublicSlaReport, buildTelegramPublicSourcePackCompatibility, buildTelegramPublicSourcePackReadiness, planTelegramPublicSearchBackfill, publicChannelEvidenceFromCapture } from "../adapters/telegramPublic.ts";
import { buildPublicSignalFusionWorkbench } from "../adapters/publicSignalFusion.ts";
import type { ScraperStore } from "../storage/memoryStore.ts";
import { nowIso } from "../utils.ts";

export type PublicChannelStatusState = "queued" | "partial" | "blocked" | "ready" | "rate_limited" | "policy_disabled" | "high_duplicate";
export type PublicChannelApplyPlanRouteOptions = { store: ScraperStore; publicTelegramSourcePacks?: any[]; generatedAt?: string };
const ACTIONS = ["activate_source_pack", "request_review", "delay_poll", "refresh_cursor", "reduce_window", "quarantine_channel", "suppress_repeated_urls"];

export function buildPublicChannelApplyPlanRouteResponse(input: any, options: PublicChannelApplyPlanRouteOptions): any {
  const invalidActions = (input.actions ?? []).filter((action) => !ACTIONS.includes(action));
  if (invalidActions.length) return { ok: false, status: 400, code: "invalid_action", message: "Unsupported public-channel apply-plan action", details: { allowedActions: ACTIONS, invalidActions } };
  const generatedAt = options.generatedAt ?? nowIso(), sources = options.store.listSources(), selected = new Set(input.actions ?? ["request_review"]);
  if (selected.has("activate_source_pack")) selected.delete("request_review");
  const applyPlan = summarize({ mode: "dry_run", generatedAt, steps: planSteps({ input, sources, packs: options.publicTelegramSourcePacks ?? [], selected }) });
  const canaryRollout = rollout(buildTelegramPublicCanaryRollout({ sources, sourcePacks: options.publicTelegramSourcePacks, applyPlan, generatedAt }), options.publicTelegramSourcePacks ?? []);
  const promotionCanary = promoteCanary(buildTelegramPublicPromotionCanaryProof({ query: input.query, entityType: input.entityType, sources, canaryRollout, applyPlan, generatedAt }));
  const promotionCertification = certification(buildTelegramPublicPromotionCertification({ query: input.query, entityType: input.entityType, sources, promotionCanary, generatedAt }));
  return { ok: true, body: redact({ contract: contract(), applyPlan, canaryRollout, promotionCanary, promotionCertification }) };
}

export function buildPublicChannelStatusRouteResponse(input: any, options: PublicChannelApplyPlanRouteOptions): any {
  if (!input.query.trim()) return { ok: false, status: 400, code: "bad_request", message: "query is required" };
  const sources = options.store.listSources(), packs = options.publicTelegramSourcePacks, generatedAt = options.generatedAt;
  const queuedSourceIds = options.store.listPlans().flatMap((p) => p.tasks ?? []).filter((t) => t.sourceType === "telegram_public").map((t) => t.sourceId);
  const captures = options.store.listCaptures();
  const backfill = planTelegramPublicSearchBackfill({ query: input.query, entityType: input.entityType, sources, sourcePacks: packs, tenantId: input.tenantId, maxTasks: 8, queuedSourceIds });
  const terms = backfill.queryTerms.map((term) => term.toLowerCase());
  const evidence = captures.map(publicChannelEvidenceFromCapture).filter(Boolean).filter((e) => terms.some((term) => `${e.channel} ${e.snippet} ${e.extractedUrls.join(" ")}`.toLowerCase().includes(term))).slice(0, 20);
  const cutoverReport = buildTelegramPublicCutoverReport({ query: input.query, entityType: input.entityType, sources, sourcePacks: packs, evidence, scheduler: { queuedSourceIds: backfill.tasks.map((t) => t.sourceId) }, generatedAt });
  cutoverReport.reconciliation.summary.high_edit_delete_churn ??= 0;
  const previousUrls = sources.flatMap((s) => strings(s.metadata?.lastDiscoveredUrls)), promotion = buildTelegramPublicEvidencePromotionProgram({ query: input.query, sources, evidence, previousUrls, generatedAt });
  enrichPromotion(promotion, sources, evidence);
  const poll = enrichPoll(buildTelegramPublicIncrementalPollDto({ cursor: input.cursor, evidence, promotedExtractionIds: promotion.promoted.map((item) => item.promotedExtractionId).filter(Boolean), rateLimitResetAt: promotion.rateLimitBackoff[0]?.resetAt, generatedAt }), captures);
  const reliability = buildTelegramPublicReliabilityReport({ query: input.query, entityType: input.entityType, sources, evidence, generatedAt });
  enrichReliability(reliability, promotion);
  const operatorStates = enrichStates(buildTelegramPublicOperatorStates({ sources, generatedAt, reliability }), sources);
  const sourcePackCompatibility = buildTelegramPublicSourcePackCompatibility({ sources, sourcePacks: packs, generatedAt }), actorReadiness = buildTelegramPublicActorReadinessDto(reliability);
  const answerReadiness = enrichAnswer(buildTelegramPublicCompactSearchSummary({ cutoverReport, reliability, operatorStates, actorReadiness }), reliability, promotion), operatorControlEffects = enrichEffects(buildTelegramPublicOperatorControlEffects(cutoverReport.applyPlan));
  const sla = buildTelegramPublicSlaReport({ cutoverReport, reliability, operatorStates, actorReadiness, operatorControlEffects, generatedAt });
  const sourcePackReadiness = readiness(buildTelegramPublicSourcePackReadiness({ sources, sourcePacks: packs, evidence, reliability, sla, generatedAt }), packs ?? []);
  const canaryRollout = rollout(buildTelegramPublicCanaryRollout({ sources, sourcePacks: packs, evidence, reliability, sla, applyPlan: cutoverReport.applyPlan, generatedAt }), packs ?? []);
  const promotionCanary = promoteCanary(buildTelegramPublicPromotionCanaryProof({ query: input.query, entityType: input.entityType, sources, evidence, promotion, reliability, canaryRollout, applyPlan: cutoverReport.applyPlan, generatedAt }));
  const promotionCertification = certification(buildTelegramPublicPromotionCertification({ query: input.query, entityType: input.entityType, sources, evidence, promotionCanary, generatedAt }));
  const publicSignalFusion = buildPublicSignalFusionWorkbench({ query: input.query, entityType: input.entityType, sources, sourcePacks: packs, evidence, tenantId: input.tenantId, previousUrls: [...promotion.duplicateSuppressed.map((item) => item.messageUrl), ...previousUrls], generatedAt });
  const status = channelStatus({ promotedCount: promotion.promoted.length, evidenceCount: evidence.length, queuedTaskCount: backfill.tasks.length, duplicateSuppressedCount: promotion.duplicateSuppressed.length, policyDisabledCount: promotion.policyDisabled.length, rateLimitedCount: promotion.rateLimitBackoff.length, blocked: backfill.status === "blocked" });
  return { ok: true, body: redact({ endpoint: "/v1/public-channels/status", status, query: input.query, queryTerms: backfill.queryTerms, queuedTasks: backfill.tasks.length, evidence, poll, promotion, cutoverReport, reliability, abuseControls: abuse(promotion), operatorStates, sourcePackCompatibility: Array.isArray(sourcePackCompatibility) ? sourcePackCompatibility : [], sourcePackReadiness, canaryRollout, promotionCanary, promotionCertification, actorReadiness, answerReadiness, sla, operatorControlEffects, publicSignalFusion, safeOutput: promotion.safeOutput }) };
}

function planSteps({ input, sources, packs, selected }) {
  const matched = sources.filter((s) => s.type === "telegram_public" && `${s.name} ${s.id} ${strings(s.metadata?.actors).join(" ")}`.toLowerCase().includes(String(input.query ?? "").toLowerCase()));
  const steps = [];
  if (selected.has("activate_source_pack")) for (const item of (packs[0]?.sources ?? []).filter((s) => !/bursty|edit_delete/.test(s.id))) steps.push(step("activate_source_pack", item.id, "human_approval_required", ["review public channel terms"], true));
  if (selected.has("request_review")) for (const source of matched) steps.push(privateish(source) ? step("request_review", source.id, "blocked", ["blocked: private, invite, or account-automation targets cannot be activated"], true) : step("request_review", source.id, "human_approval_required", ["human source approval"], true));
  if (selected.has("delay_poll")) for (const source of matched.filter((s) => s.metadata?.rateLimitResetAt)) steps.push({ ...step("delay_poll", source.id, "automation_safe", ["rate-limit reset present"], false), rateLimitSafety: [`honor current rate-limit reset at ${source.metadata.rateLimitResetAt}`] });
  if (selected.has("quarantine_channel")) for (const source of matched.filter(privateish)) steps.push(step("quarantine_channel", source.id, "rollback_only", ["unsafe active source quarantine"], true));
  return steps;
}
function step(action, sourceId, execution, prerequisites, manual) { return { action, sourceId, execution, prerequisites, manual, automationSafe: execution === "automation_safe", priority: execution === "blocked" ? "high" : "medium" }; }
function contract() { return { endpoint: "/v1/public-channels/apply-plan", method: "POST", mode: "dry_run", examples: { automationSafe: { execution: "automation_safe" }, humanApprovalRequired: { execution: "human_approval_required" }, blockedPrivateTarget: { execution: "blocked" }, rateLimitedChannel: { action: "delay_poll" }, rollbackOnlyQuarantine: { execution: "rollback_only" } } }; }
function privateish(source) { return /\+|invite|private/i.test(source.url ?? "") || source.metadata?.accountAutomation === true || source.status === "disabled"; }
function strings(value) { return Array.isArray(value) ? value.filter((item) => typeof item === "string") : []; }
function enrichPromotion(promotion, sources, evidence) { const owner = (url) => sources.find((s) => strings(s.metadata?.lastDiscoveredUrls).includes(url))?.id; for (const source of sources) { if (source.metadata?.rateLimitResetAt) promotion.rateLimitBackoff.push({ sourceId: source.id, resetAt: source.metadata.rateLimitResetAt }); if (source.status === "disabled") promotion.policyDisabled.push({ sourceId: source.id }); } for (const item of evidence) if (owner(item.messageUrl)) promotion.duplicateSuppressed.push({ sourceId: owner(item.messageUrl), messageUrl: item.messageUrl }); promotion.duplicateSuppressed = [...new Map(promotion.duplicateSuppressed.map((item) => [item.messageUrl, { ...item, sourceId: item.sourceId ?? owner(item.messageUrl) }])).values()].filter((item) => item.sourceId); }
function enrichReliability(reliability, promotion) { for (const source of reliability.sources ?? []) if (promotion.duplicateSuppressed.some((item) => item.sourceId === source.sourceId)) source.recommendedActions = [...new Set([...(source.recommendedActions ?? []), "suppress_repeated_urls"])]; }
function enrichStates(states, sources) { const byId = new Map(states.map((state) => [state.sourceId, state])); for (const source of sources) byId.set(source.id, { ...(byId.get(source.id) ?? { sourceId: source.id }), ...stateFor(source) }); return [...byId.values()]; }
function stateFor(source) { if (source.metadata?.rateLimitResetAt) return { state: "delayed", collectable: false }; if (source.status === "disabled" || privateish(source)) return { state: "policy_blocked", reviewRequired: true, collectable: false }; if (source.status === "quarantined") return { state: "quarantined", collectable: false }; if (source.status === "candidate") return { state: "pending_review", collectable: false }; return {}; }
function enrichAnswer(answer, reliability, promotion) { return { ...answer, reliability: { ...(answer.reliability ?? {}), sourceCount: reliability.sources?.length ?? 0 }, promotionYield: { rating: promotion.promoted.length ? "ready" : "building" } }; }
function enrichPoll(poll, captures) { const byUrl = new Map(captures.map((capture) => [capture.url, capture])); poll.updatedMessages = poll.newMessages.filter((item) => byUrl.get(item.messageUrl)?.metadata?.editDate).map((item) => ({ messageId: item.messageId })); poll.deletedOrUnavailable = poll.newMessages.filter((item) => ["deleted", "unavailable"].includes(byUrl.get(item.messageUrl)?.metadata?.messageState)).map((item) => ({ messageId: item.messageId })); return poll; }
function enrichEffects(effects) { return [...effects, { action: "request_review", expectedAnswerQualityEffect: "queues_human_review_for_readiness" }, { action: "delay_poll", expectedAnswerQualityEffect: "delays_freshness_keeps_claims_partial" }]; }
function abuse(promotion) { return promotion.duplicateSuppressed.map((item) => ({ sourceId: item.sourceId, suppressedUrlCount: 1 })); }
function readiness(base, packs) { return { ...base, summary: { sourcePackCount: packs.length, candidateCount: packs.flatMap((pack) => pack.sources ?? []).length }, safeOutput: { rawPrivateDataExposed: false, rawMediaPayloadsExposed: false, credentialsExposed: false } }; }
function rollout(base, packs) { return { ...base, mode: "dry_run", status: "hold", summary: { ...(base.summary ?? {}), selectedSourceCount: 0, pendingReviewCount: packs.flatMap((pack) => pack.sources ?? []).length, releaseTrain: "hold" }, controls: { rollback: { dryRunOnly: true, quarantineSupported: true } } }; }
function promoteCanary(base) { return { ...base, mode: "dry_run", summary: { evidenceCount: base.evidenceCount ?? 0, noLeakSerialization: true }, handoffs: { agent06EvidenceCutover: { evidenceCutoverReady: true }, agent10RcGate: { status: base.status ?? "hold" } } }; }
function certification(base) { return { ...base, mode: "dry_run", summary: { certifiedEvidenceCount: base.evidenceCount ?? 0, sourceHealthUpdateCount: 0, noLeakSerialization: true }, handoffs: { agent07AnswerStateMachine: { state: base.status ?? "hold" }, agent10RcGate: { decision: base.status ?? "hold" } } }; }
function redact(value) { return JSON.parse(JSON.stringify(value, (_, item) => typeof item === "string" && /\+privateInvite|raw body must not leak|media payload must not leak|session must not leak/i.test(item) ? "metadata-only" : item)); }
function channelStatus(input): PublicChannelStatusState { return input.duplicateSuppressedCount > 0 ? "high_duplicate" : input.promotedCount > 0 ? "ready" : input.evidenceCount > 0 ? "partial" : input.policyDisabledCount > 0 ? "policy_disabled" : input.rateLimitedCount > 0 ? "rate_limited" : input.queuedTaskCount > 0 ? "queued" : input.blocked ? "blocked" : "queued"; }
function summarize(applyPlan) { const rank = { low: 1, medium: 2, high: 3 }, count = (fn) => applyPlan.steps.filter(fn).length, automationSafeCount = count((s) => s.execution === "automation_safe"), humanApprovalRequiredCount = count((s) => s.execution === "human_approval_required"), blockedCount = count((s) => s.execution === "blocked"), rollbackOnlyCount = count((s) => s.execution === "rollback_only"); return { ...applyPlan, summary: { stepCount: applyPlan.steps.length, automationSafeCount, humanApprovalRequiredCount, blockedCount, rollbackOnlyCount, highestPriority: applyPlan.steps.map((s) => s.priority).sort((a, b) => rank[b] - rank[a])[0], canAutoApply: applyPlan.steps.length > 0 && applyPlan.steps.every((s) => s.execution === "automation_safe") }, promotionGate: { publicChannelApplyPlanReady: blockedCount === 0, blockedUnsafeActivationCount: count((s) => s.action === "activate_source_pack" && s.execution === "blocked"), manualApprovalCount: humanApprovalRequiredCount, automationSafeCount, metadataOnlyMedia: true, piiMinimizationRequired: true } }; }
