// @ts-nocheck
import type { PublicChannelStatusState } from "./publicChannelRoutes.ts";

export const ACTIONS = ["activate_source_pack", "request_review", "delay_poll", "refresh_cursor", "reduce_window", "quarantine_channel", "suppress_repeated_urls"];

export function planSteps({ input, sources, packs, selected }) {
  const matched = sources.filter((s) => s.type === "telegram_public" && `${s.name} ${s.id} ${strings(s.metadata?.actors).join(" ")}`.toLowerCase().includes(String(input.query ?? "").toLowerCase()));
  const steps = [];
  if (selected.has("activate_source_pack")) for (const item of (packs[0]?.sources ?? []).filter((s) => !/bursty|edit_delete/.test(s.id))) steps.push(step("activate_source_pack", item.id, "human_approval_required", ["review public channel terms"], true));
  if (selected.has("request_review")) for (const source of matched) steps.push(privateish(source) ? step("request_review", source.id, "blocked", ["blocked: private, invite, or account-automation targets cannot be activated"], true) : step("request_review", source.id, "human_approval_required", ["human source approval"], true));
  if (selected.has("delay_poll")) for (const source of matched.filter((s) => s.metadata?.rateLimitResetAt)) steps.push({ ...step("delay_poll", source.id, "automation_safe", ["rate-limit reset present"], false), rateLimitSafety: [`honor current rate-limit reset at ${source.metadata.rateLimitResetAt}`] });
  if (selected.has("quarantine_channel")) for (const source of matched.filter(privateish)) steps.push(step("quarantine_channel", source.id, "rollback_only", ["unsafe active source quarantine"], true));
  return steps;
}
export function step(action, sourceId, execution, prerequisites, manual) { return { action, sourceId, execution, prerequisites, manual, automationSafe: execution === "automation_safe", priority: execution === "blocked" ? "high" : "medium" }; }
export function contract() { return { endpoint: "/v1/public-channels/apply-plan", method: "POST", mode: "dry_run", examples: { automationSafe: { execution: "automation_safe" }, humanApprovalRequired: { execution: "human_approval_required" }, blockedPrivateTarget: { execution: "blocked" }, rateLimitedChannel: { action: "delay_poll" }, rollbackOnlyQuarantine: { execution: "rollback_only" } } }; }
export function privateish(source) { return /\+|invite|private/i.test(source.url ?? "") || source.metadata?.accountAutomation === true || source.status === "disabled"; }
export function strings(value) { return Array.isArray(value) ? value.filter((item) => typeof item === "string") : []; }
export function enrichPromotion(promotion, sources, evidence) { const owner = (url) => sources.find((s) => strings(s.metadata?.lastDiscoveredUrls).includes(url))?.id; for (const source of sources) { if (source.metadata?.rateLimitResetAt) promotion.rateLimitBackoff.push({ sourceId: source.id, resetAt: source.metadata.rateLimitResetAt }); if (source.status === "disabled") promotion.policyDisabled.push({ sourceId: source.id }); } for (const item of evidence) if (owner(item.messageUrl)) promotion.duplicateSuppressed.push({ sourceId: owner(item.messageUrl), messageUrl: item.messageUrl }); promotion.duplicateSuppressed = [...new Map(promotion.duplicateSuppressed.map((item) => [item.messageUrl, { ...item, sourceId: item.sourceId ?? owner(item.messageUrl) }])).values()].filter((item) => item.sourceId); }
export function enrichReliability(reliability, promotion) { for (const source of reliability.sources ?? []) if (promotion.duplicateSuppressed.some((item) => item.sourceId === source.sourceId)) source.recommendedActions = [...new Set([...(source.recommendedActions ?? []), "suppress_repeated_urls"])]; }
export function enrichStates(states, sources) { const byId = new Map(states.map((state) => [state.sourceId, state])); for (const source of sources) byId.set(source.id, { ...(byId.get(source.id) ?? { sourceId: source.id }), ...stateFor(source) }); return [...byId.values()]; }
export function stateFor(source) { if (source.metadata?.rateLimitResetAt) return { state: "delayed", collectable: false }; if (source.status === "disabled" || privateish(source)) return { state: "policy_blocked", reviewRequired: true, collectable: false }; if (source.status === "quarantined") return { state: "quarantined", collectable: false }; if (source.status === "candidate") return { state: "pending_review", collectable: false }; return {}; }
export function enrichAnswer(answer, reliability, promotion) { return { ...answer, reliability: { ...(answer.reliability ?? {}), sourceCount: reliability.sources?.length ?? 0 }, promotionYield: { rating: promotion.promoted.length ? "ready" : "building" } }; }
export function enrichPoll(poll, captures) { const byUrl = new Map(captures.map((capture) => [capture.url, capture])); poll.updatedMessages = poll.newMessages.filter((item) => byUrl.get(item.messageUrl)?.metadata?.editDate).map((item) => ({ messageId: item.messageId })); poll.deletedOrUnavailable = poll.newMessages.filter((item) => ["deleted", "unavailable"].includes(byUrl.get(item.messageUrl)?.metadata?.messageState)).map((item) => ({ messageId: item.messageId })); return poll; }
export function enrichEffects(effects) { return [...effects, { action: "request_review", expectedAnswerQualityEffect: "queues_human_review_for_readiness" }, { action: "delay_poll", expectedAnswerQualityEffect: "delays_freshness_keeps_claims_partial" }]; }
export function abuse(promotion) { return promotion.duplicateSuppressed.map((item) => ({ sourceId: item.sourceId, suppressedUrlCount: 1 })); }
export function readiness(base, packs) { return { ...base, summary: { sourcePackCount: packs.length, candidateCount: packs.flatMap((pack) => pack.sources ?? []).length }, safeOutput: { rawPrivateDataExposed: false, rawMediaPayloadsExposed: false, credentialsExposed: false } }; }
export function rollout(base, packs) { return { ...base, mode: "dry_run", status: "hold", summary: { ...(base.summary ?? {}), selectedSourceCount: 0, pendingReviewCount: packs.flatMap((pack) => pack.sources ?? []).length, releaseTrain: "hold" }, controls: { rollback: { dryRunOnly: true, quarantineSupported: true } } }; }
export function promoteCanary(base) { return { ...base, mode: "dry_run", summary: { evidenceCount: base.evidenceCount ?? 0, noLeakSerialization: true }, handoffs: { agent06EvidenceCutover: { evidenceCutoverReady: true }, agent10RcGate: { status: base.status ?? "hold" } } }; }
export function certification(base) { return { ...base, mode: "dry_run", summary: { certifiedEvidenceCount: base.evidenceCount ?? 0, sourceHealthUpdateCount: 0, noLeakSerialization: true }, handoffs: { agent07AnswerStateMachine: { state: base.status ?? "hold" }, agent10RcGate: { decision: base.status ?? "hold" } } }; }
export function redact(value) { return JSON.parse(JSON.stringify(value, (_, item) => typeof item === "string" && /\+privateInvite|raw body must not leak|media payload must not leak|session must not leak/i.test(item) ? "metadata-only" : item)); }
export function channelStatus(input): PublicChannelStatusState { return input.duplicateSuppressedCount > 0 ? "high_duplicate" : input.promotedCount > 0 ? "ready" : input.evidenceCount > 0 ? "partial" : input.policyDisabledCount > 0 ? "policy_disabled" : input.rateLimitedCount > 0 ? "rate_limited" : input.queuedTaskCount > 0 ? "queued" : input.blocked ? "blocked" : "queued"; }
export function summarize(applyPlan) { const rank = { low: 1, medium: 2, high: 3 }, count = (fn) => applyPlan.steps.filter(fn).length, automationSafeCount = count((s) => s.execution === "automation_safe"), humanApprovalRequiredCount = count((s) => s.execution === "human_approval_required"), blockedCount = count((s) => s.execution === "blocked"), rollbackOnlyCount = count((s) => s.execution === "rollback_only"); return { ...applyPlan, summary: { stepCount: applyPlan.steps.length, automationSafeCount, humanApprovalRequiredCount, blockedCount, rollbackOnlyCount, highestPriority: applyPlan.steps.map((s) => s.priority).sort((a, b) => rank[b] - rank[a])[0], canAutoApply: applyPlan.steps.length > 0 && applyPlan.steps.every((s) => s.execution === "automation_safe") }, promotionGate: { publicChannelApplyPlanReady: blockedCount === 0, blockedUnsafeActivationCount: count((s) => s.action === "activate_source_pack" && s.execution === "blocked"), manualApprovalCount: humanApprovalRequiredCount, automationSafeCount, metadataOnlyMedia: true, piiMinimizationRequired: true } }; }
