// @ts-nocheck
import { promoteSearchResultToCanonicalCapture } from "../src/adapters/clearWebPromotion.ts"; import { handleApiRequest } from "../src/api/server.ts";
import { FocusedFrontier } from "../src/frontier/frontier.ts"; import { processCollectedItem } from "../src/pipeline/pipeline.ts"; import { InMemoryScraperStore } from "../src/storage/memoryStore.ts";
import { hashContent } from "../src/utils.ts";

const at = "2026-05-24T00:00:00.000Z";
const fixtures = [
  ["APT29", "actor", "apt29", "APT29 phishing campaign", ["apt29", "phishing", "government", "cve-2026-1001", "wellmess"], ["scattered spider", "volt typhoon", "akira ransomware", "turla"], "APT29 used phishing against government targets. The report links WellMess activity to CVE-2026-1001 and apt29-command.example.org."],
  ["Scattered Spider", "actor", "scattered-spider", "Scattered Spider intrusion", ["scattered spider", "sms phishing", "telecommunications", "credential dumping", "anydesk"], ["apt29", "volt typhoon", "akira ransomware", "turla"], "Scattered Spider targeted telecommunications help desks with SMS phishing, credential dumping, and AnyDesk. Victim: Example Telecom."],
  ["Volt Typhoon", "actor", "volt-typhoon", "Volt Typhoon activity", ["volt typhoon", "energy", "living off the land", "china", "persistence"], ["apt29", "scattered spider", "akira ransomware", "turla"], "Volt Typhoon focused on energy organizations. Analysts observed living off the land persistence attributed to China-nexus operations."],
  ["Akira ransomware", "actor", "akira-ransomware", "Akira campaign", ["akira ransomware", "manufacturing", "ransomware", "exfiltration", "cve-2026-2222"], ["apt29", "scattered spider", "volt typhoon", "turla"], "Akira ransomware operators targeted manufacturing with data exfiltration and CVE-2026-2222 exploitation."],
  ["Turla", "actor", "turla", "Turla Snake malware", ["turla", "snake", "government", "ukraine", "command and control"], ["apt29", "scattered spider", "volt typhoon", "akira ransomware"], "Turla used Snake malware and command and control infrastructure against government organizations in Ukraine."],
  ["CVE-2026-12345", "cve", "cve-2026-12345", "CVE-2026-12345 advisory", ["cve-2026-12345", "exploit", "intrusion", "indicator", "ransomware"], ["apt29", "scattered spider", "volt typhoon", "turla"], "CVE-2026-12345 exploitation was observed in intrusion activity with malicious domain cve-2026-12345-watch.example.com."]
].map(([query, entityType, slug, title, expectedTerms, disallowedTerms, body]) => ({ query, entityType, slug, title, expectedTerms, disallowedTerms, body }));
const restricted = [{ query: "Fjord Energy AS", entityType: "free_text", slug: "fjord-energy", title: "Akira Fjord Energy claim", expectedTerms: ["fjord energy as", "akira", "18,432", "employees and customers", "42 gb", "2026-05-20", "payment within 72 hours"], disallowedTerms: ["apt29", "scattered spider", "volt typhoon", "turla"], body: "" }];

async function main() {
  const cold = new InMemoryScraperStore(), captured = new InMemoryScraperStore(), metadata = new InMemoryScraperStore();
  await seedCaptured(captured); seedRestricted(metadata);
  const sourcePacks = [{ version: 1, name: "measured-safe-public-source-pack", description: "Synthetic public source pack for product measurement.", generatedAt: at, sources: fixtures.flatMap((f) => ["rss", "static_web"].map((type) => sourceFor(f, type))) }];
  const scenarios = [await scenario("empty_store_on_demand_source_pack", cold, { sourcePacks, publicClearWebFetcher: fetcher() }), await scenario("captured_clear_web_evidence", captured, { sourcePacks, publicClearWebFetcher: fetcher() }), await scenario("restricted_metadata_only_leak_claims", metadata, { disableBundledSourcePack: true, disableOnDemandClearWebCapture: true }, restricted)];
  console.log(JSON.stringify({ measuredAt: new Date().toISOString(), purpose: "/v1/intel/search buyer-visible usefulness: fact recall, relevant evidence, latency.", scenarios }, null, 2));
}
async function scenario(name, store, options = {}, queryFixtures = fixtures) {
  const frontier = new FocusedFrontier(), queries = [];
  for (const fixture of queryFixtures) { const start = performance.now(); const response = await handleApiRequest(new Request(`http://local/v1/intel/search?q=${encodeURIComponent(fixture.query)}&entityType=${fixture.entityType}`), { store, frontier, ...options }); queries.push(score(fixture, await response.json(), round(performance.now() - start))); }
  return { scenario: name, aggregate: { queryCount: queries.length, medianLatencyMs: percentile(queries.map((q) => q.latencyMs), 0.5), p95LatencyMs: percentile(queries.map((q) => q.latencyMs), 0.95), averageExpectedFactRecall: avg(queries.map((q) => q.expectedFactRecall)), usefulAnswerRate: avg(queries.map((q) => q.usefulAnswer ? 1 : 0)), averageSourceCount: avg(queries.map((q) => q.sourceCount)), averageEvidenceItemCount: avg(queries.map((q) => q.indicatorCount + q.entityCount)), totalUnexpectedCrossTalkTerms: queries.reduce((sum, q) => sum + q.unexpectedCrossTalkTerms.length, 0) }, queries };
}
function score(fixture, payload, latencyMs) {
  const text = strings({ actorProfile: payload.actorProfile, answer: payload.answer, summary: payload.summary }).join("\n").toLowerCase();
  const matchedExpectedTerms = fixture.expectedTerms.filter((term) => text.includes(term.toLowerCase()));
  const unexpectedCrossTalkTerms = fixture.disallowedTerms.filter((term) => text.includes(term.toLowerCase()));
  const datasets = obj(obj(payload.actorProfile).datasets ?? obj(payload.answer).datasets), quality = obj(payload.quality), stages = obj(quality.evidenceStageCounts ?? datasets.evidenceStageCounts);
  const sourceCount = num(datasets.sourceCount), indicatorCount = num(datasets.indicatorCount), entityCount = num(datasets.entityCount);
  const expectedFactRecall = round(matchedExpectedTerms.length / fixture.expectedTerms.length), capturedPageCount = num(stages.captured_page), metadataOnlyClaimCount = num(stages.metadata_only_claim);
  return { query: fixture.query, status: payload.status ?? "unknown", latencyMs, expectedFactRecall, matchedExpectedTerms, unexpectedCrossTalkTerms, usefulAnswer: expectedFactRecall >= 0.6 && (capturedPageCount || metadataOnlyClaimCount) && indicatorCount + entityCount > 0, sourceCount, indicatorCount, entityCount, capturedPageCount, metadataOnlyClaimCount, summary: strings(obj(payload.actorProfile).summary ?? payload.summary).slice(0, 3) };
}
async function seedCaptured(store) { for (const [index, fixture] of fixtures.entries()) for (const source of ["primary", "corroborating"].map((variant, i) => sourceFor(fixture, "static_web", variant, i))) { store.saveSource(source); await promoteSearchResultToCanonicalCapture(store, source, { query: fixture.query, provider: "fixture_public_search", resultId: `fixture-${fixture.slug}-${source.id}`, title: fixture.title, snippet: fixture.body.slice(0, 180), url: `https://measure.example.test/research/${fixture.slug}`, rank: index + 1, observedAt: at, confidence: 0.78 }, { checkRobots: false, fetcher: fetcher() }); } }
function seedRestricted(store) {
  const source = { id: "src_measure_restricted_metadata", name: "Measured Restricted Metadata Source", type: "tor_metadata", url: "restricted-metadata://approved/hash-only", accessMethod: "approved_proxy", status: "active", risk: "high", trustScore: 0.72, language: "en", crawlFrequencySeconds: 3600, legalNotes: "Synthetic restricted metadata fixture; metadata only.", createdAt: at, updatedAt: at, approvedAt: at, approvedBy: "operator", governance: { approvalRequired: true, approvalState: "approved", metadataOnly: true, policyVersion: "collection-policy:v1" } };
  const rawText = "actor: Akira | victim: Fjord Energy AS | accounts affected: 18,432 | account subjects: employees and customers | dataset size: 42 GB | actor statement: payment within 72 hours | date: 2026-05-20 | sector: energy | country: Norway";
  store.saveSource(source); store.savePipelineResult(processCollectedItem({ sourceId: source.id, taskId: "task_restricted_metadata_measurement", url: "restricted-metadata://hash/hash_restricted_fjord_energy", collectedAt: at, publishedAt: "2026-05-20T09:30:00.000Z", title: "Akira / Fjord Energy AS restricted metadata claim", rawText, contentHash: hashContent(rawText), links: [], metadata: { adapter: "darknet_metadata", evidenceStage: "metadata_only_claim", safeExcerpt: rawText, leakSite: { actorName: "Akira", victimName: "Fjord Energy AS", affectedAccounts: "18,432", accountSubjects: "employees and customers", datasetSize: "42 GB", actorStatement: "payment within 72 hours", claimDate: "2026-05-20", claimedSector: "energy", claimedCountry: "Norway", confidence: 0.68 } }, sensitive: true }));
}
function fetcher() { return async (input) => { const url = new URL(typeof input === "string" || input instanceof URL ? input.toString() : input.url); if (url.pathname === "/robots.txt") return new Response("User-agent: *\nAllow: /\n"); const fixture = fixtures.find((f) => url.pathname.endsWith(`/research/${f.slug}`) || url.pathname.endsWith(`/feeds/${f.slug}.xml`)); if (!fixture) return new Response("Not found", { status: 404 }); if (url.pathname.includes("/feeds/")) return new Response(`<?xml version="1.0"?><rss version="2.0"><channel><item><title>${esc(fixture.title)}</title><link>https://measure.example.test/research/${fixture.slug}</link><description>${esc(fixture.body)}</description></item></channel></rss>`, { headers: { "content-type": "application/rss+xml" } }); return new Response(`<!doctype html><html><head><title>${esc(fixture.title)}</title></head><body><article><h1>${esc(fixture.title)}</h1><p>${esc(fixture.body)}</p></article></body></html>`, { headers: { "content-type": "text/html" } }); }; }
function sourceFor(fixture, type, variant = type, index = 0) { const rss = type === "rss"; return { id: `src_measure_${fixture.slug.replace(/-/g, "_")}_${variant}`, name: `Measured ${variant} ${fixture.title}`, type, url: rss ? `https://measure.example.test/feeds/${fixture.slug}.xml` : `https://measure.example.test/research/${fixture.slug}`, accessMethod: "public_http", status: "active", risk: "low", trustScore: index === 0 ? 0.9 : 0.82, language: "en", crawlFrequencySeconds: 3600, legalNotes: "Synthetic safe public CTI measurement source.", createdAt: at, updatedAt: at, tags: ["public", "measurement", fixture.entityType], catalog: { canonicalId: `measurement:${fixture.slug}:${variant}`, publisher: { name: "Measurement", country: "US", homepage: "https://measure.example.test", trustBasis: "research" }, tier: rss ? "tier_1" : "tier_2", approvalScope: "safe_public_auto", license: "Synthetic measurement content.", legalBasis: "Synthetic defensive CTI fixture.", reliability: 0.86, intelligenceValue: 0.86, retentionClass: "standard", coverage: { topics: [fixture.entityType], actors: fixture.entityType === "actor" ? [fixture.query] : [], languages: ["en"], queryPatterns: [fixture.query] }, collection: { freshnessTargetSeconds: 3600, collectionSlaSeconds: 3600, budgetClass: "low", crawlCadenceSeconds: 3600 }, adapterCompatibility: [type], rollback: {} } }; }
function obj(value) { return value && typeof value === "object" && !Array.isArray(value) ? value : {}; }
function num(value) { return typeof value === "number" && Number.isFinite(value) ? value : 0; }
function strings(value) { return typeof value === "string" ? [value] : Array.isArray(value) ? value.flatMap(strings) : value && typeof value === "object" ? Object.values(value).flatMap(strings) : []; }
function avg(values) { return values.length ? round(values.reduce((sum, value) => sum + value, 0) / values.length) : 0; }
function percentile(values, q) { const sorted = [...values].sort((a, b) => a - b); return sorted[Math.min(sorted.length - 1, Math.max(0, Math.ceil(sorted.length * q) - 1))] ?? 0; }
function round(value) { return Math.round(value * 1000) / 1000; }
function esc(value) { return value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
await main();
