import type { RouteCheck } from "./routeInventoryTypes.ts";

export function routeChecks(): RouteCheck[] {
  return [
    { owner: "Agent 09", name: "health", method: "GET", path: "/v1/health", expectKeys: ["ok", "service"] },
    { owner: "Agent 09", name: "metrics", method: "GET", path: "/v1/metrics", expectKeys: ["runs", "sources", "frontier"] },
    { owner: "Agent 10", name: "product_slo", method: "GET", path: "/v1/ops/product-slo?proofMode=local&generatedAt=2026-06-20T12:00:00.000Z", expectKeys: ["schemaVersion", "dashboard", "metrics", "paidProductEconomics", "sourceMonetizationGate", "slos", "productLaunch", "dailySnapshot", "deploymentProof", "resourceGuardrails"] },
    { owner: "Agent 09", name: "contracts", method: "GET", path: "/v1/contracts", expectKeys: ["endpoint", "routeInventory", "routeTruthAudit", "publicWrapperResponsiveAudit", "publicWrapperDeltaAudit", "enterpriseApiSurface", "sdkIntegration", "openapi", "surfaces", "publicCompatibility", "semantics"] },
    { owner: "Agent 01", name: "analyst_loop", method: "GET", path: "/v1/analyst/loop?q=Fjord%20Energy%20AS", expectKeys: ["contract", "state", "runStatusClarity", "reviewTasks", "sourceActivationPackets", "notificationPackets", "claimLedger"] },
    { owner: "Agent 01", name: "analyst_persistence_readiness", method: "GET", path: "/v1/analyst/persistence-readiness", expectKeys: ["endpoint", "migration", "workflowTables", "readiness", "noLeakGuardrails"] },
    { owner: "Agent 01", name: "analyst_metadata_review_tasks", method: "GET", path: "/v1/analyst/metadata-review-tasks", expectKeys: ["contract", "runStatusClarity", "tasks", "notificationPackets", "claimLedger"] },
    { owner: "Agent 01", name: "analyst_source_activation_packets", method: "GET", path: "/v1/analyst/source-activation-packets", expectKeys: ["contract", "runStatusClarity", "packets"] },
    { owner: "Agent 01", name: "analyst_source_activation_packet_execution_preview", method: "GET", path: "/v1/analyst/source-activation-packets/activation_inventory_fjord/execution-preview", expectKeys: ["contract", "readiness", "packet", "executionPreview", "forbiddenOperations"] },
    { owner: "Agent 01", name: "analyst_source_activation_packet_action", method: "POST", path: "/v1/analyst/source-activation-packets/activation_inventory_fjord/actions", body: { action: "approve_metadata_only", dryRun: true, reason: "route inventory proof" }, expectKeys: ["contract", "dryRun", "action", "packet", "result"] },
    { owner: "Agent 01", name: "analyst_victim_notification_packets", method: "GET", path: "/v1/analyst/victim-notification-packets", expectKeys: ["contract", "runStatusClarity", "packets"] },
    { owner: "Agent 01", name: "analyst_victim_notification_packet_export", method: "GET", path: "/v1/analyst/victim-notification-packets/notification_inventory_fjord/export", expectKeys: ["contract", "readiness", "packet", "delivery"] },
    { owner: "Agent 01", name: "analyst_victim_notification_packet_action", method: "POST", path: "/v1/analyst/victim-notification-packets/notification_inventory_fjord/actions", body: { action: "approve_packet", dryRun: true, reason: "route inventory proof" }, expectKeys: ["contract", "dryRun", "action", "packet", "result"] },
    { owner: "Agent 01", name: "sources_list", method: "GET", path: "/v1/sources?limit=2", expectKeys: ["sources"] },
    { owner: "Agent 01", name: "sources_apply_plan", method: "POST", path: "/v1/sources/apply-plan", body: { queryScope: { queries: ["APT29"], entityTypes: ["actor"] }, selectedActions: ["approve", "quarantine", "retire", "request_legal_notes", "leave_unchanged"], includeExecutionPreview: true }, expectKeys: ["applyPlan"] },
    { owner: "Agent 01", name: "sources_coverage_plan", method: "POST", path: "/v1/sources/coverage-plan", body: { queries: ["APT29", "Scattered Spider"], entityTypes: ["actor"] }, expectKeys: ["endpoint", "queries"] },
    { owner: "Agent 01", name: "sources_marketplace", method: "POST", path: "/v1/sources/marketplace", body: { queries: ["APT29", "Akira ransomware victims", "CVE-2024-1234"] }, expectKeys: ["endpoint", "marketplace", "parserCapabilityMatrix", "activationReadiness"] },
    { owner: "Agent 01", name: "sources_atlas", method: "POST", path: "/v1/sources/atlas", body: { queries: ["APT29", "Akira ransomware victims", "CVE-2024-1234"], recordLimit: 500 }, expectKeys: ["endpoint", "summary", "records", "importPlans", "coverageMatrix", "activationCanary"] },
    { owner: "Agent 01", name: "sources_atlas_export", method: "POST", path: "/v1/sources/atlas/export", body: { queries: ["APT29", "Akira ransomware victims", "CVE-2024-1234"], planLabel: "first_100", recordLimit: 500 }, expectKeys: ["endpoint", "summary", "reviewQueue", "exportManifest", "approvalPacket", "rollbackPacket"] },
    { owner: "Agent 01", name: "sources_activation_batches", method: "POST", path: "/v1/sources/activation-batches", body: { queries: ["APT29"], entityTypes: ["actor"] }, expectKeys: ["endpoint", "queries", "coordination", "executionReadiness"] },
    { owner: "Agent 01", name: "sources_coverage_closeout", method: "POST", path: "/v1/sources/coverage-closeout", body: { queries: ["APT29", "Akira ransomware victims", "CVE-2024-1234", "campaign infrastructure"], entityTypes: ["actor"] }, expectKeys: ["endpoint", "queries", "activationWaves", "executionReadiness", "releasePacket"] },
    { owner: "Agent 02", name: "frontier_snapshot", method: "GET", path: "/v1/frontier", expectKeys: ["queue", "summary", "scheduler"] },
    { owner: "Agent 02", name: "frontier_status", method: "GET", path: "/v1/frontier/status?q=APT29", expectKeys: ["endpoint", "summary", "scheduler"] },
    { owner: "Agent 02", name: "frontier_apply_plan", method: "POST", path: "/v1/frontier/apply-plan", body: { scenario: "normal", includeExecutionPreview: true }, expectKeys: ["applyPlan"] },
    { owner: "Agent 07", name: "canary_readiness", method: "GET", path: "/v1/ops/canary/readiness?requiredQueries=APT42,Turla", expectKeys: ["readiness", "operatorView"] },
    { owner: "Agent 07", name: "canary_soak", method: "GET", path: "/v1/ops/canary/soak?minCycles=1", expectKeys: ["soak", "operatorView"] },
    { owner: "Agent 07", name: "canary_operator_console", method: "GET", path: "/v1/ops/canary/console", expectKeys: [], expectText: ["TI Canary Ops", "Active Sources", "Public Answer Readiness", "Why Partial"], expectContentType: "text/html" },
    { owner: "Agent 04", name: "public_channel_status", method: "GET", path: "/v1/public-channels/status?q=APT29&entityType=actor", expectKeys: ["status"] },
    { owner: "Agent 04", name: "public_channel_apply_plan", method: "POST", path: "/v1/public-channels/apply-plan", body: { selectedActions: ["activate_source_pack"], dryRun: true, query: "APT29" }, expectKeys: ["applyPlan"] },
    { owner: "Agent 05", name: "restricted_metadata_apply_plan", method: "POST", path: "/v1/restricted-metadata/apply-plan", body: { sourceIds: ["src_restricted"], dryRun: true }, expectKeys: ["applyPlan"] },
    { owner: "Agent 05", name: "restricted_metadata_nested_apply_plan", method: "POST", path: "/v1/sources/src_restricted/restricted-metadata/apply-plan", body: { dryRun: true }, expectKeys: ["applyPlan"] },
    { owner: "Agent 05", name: "darkweb_index_status", method: "GET", path: "/v1/darkweb/status", expectKeys: ["status", "contract"] },
    { owner: "Agent 05", name: "darkweb_index_search", method: "GET", path: "/v1/darkweb/search?q=akira&network=tor&limit=5", expectKeys: ["darkwebIndex", "contract"] },
    { owner: "Agent 06", name: "captures", method: "GET", path: "/v1/captures", expectKeys: ["captures"] },
    { owner: "Agent 06", name: "evidence_replay_plan", method: "GET", path: "/v1/evidence/replay-plan?q=APT29&runId=run_inventory", expectKeys: ["contract", "replayPlan"] },
    { owner: "Agent 06", name: "evidence_cutover_report", method: "GET", path: "/v1/evidence/cutover-report?q=APT29&runId=run_inventory", expectKeys: ["contract", "cutoverReport"] },
    { owner: "Agent 07", name: "intel_search_quality", method: "GET", path: "/v1/intel/search?q=APT29&entityType=actor", expectKeys: ["query", "quality", "actorProfile", "sla", "qualityRegressionSuite"] },
    { owner: "Agent 07", name: "quality_evaluate", method: "GET", path: "/v1/quality/evaluate?q=APT29", expectKeys: ["query", "quality", "dashboard", "entityResolutionWorkbench", "timelinessGroundTruth", "attackMappingQuality", "analystFeedbackLoop", "qualityRegressionSuite", "examples"] },
    { owner: "Agent 08", name: "graph_review_plan", method: "GET", path: "/v1/graph/review-plan?runId=run_inventory&dryRun=true&includeExamples=true", expectKeys: ["contract", "reviewPlan"] },
    { owner: "Agent 08", name: "graph_cutover_report", method: "GET", path: "/v1/graph/cutover-report?runId=run_inventory&dryRun=true", expectKeys: ["contract", "cutoverReport"] },
    { owner: "Agent 08", name: "stix_readiness", method: "GET", path: "/v1/exports/stix?runId=run_inventory&dryRun=true", expectKeys: ["contract", "readiness"] },
    { owner: "Agent 09", name: "intel_plan", method: "POST", path: "/v1/intel/plan", expectedStatus: 201, body: { query: "APT29", entityType: "actor", includeClearWeb: true }, expectKeys: ["plan"] },
    { owner: "Agent 09", name: "intel_run_status", method: "GET", path: "/v1/intel/runs/run_inventory", expectKeys: ["run", "frontier"] },
    { owner: "Agent 09", name: "intel_run_results", method: "GET", path: "/v1/intel/runs/run_inventory/results?include=captures,incidents,indicators,entities,relationships", expectKeys: ["run", "results"] },
    { owner: "Agent 09", name: "stix_export", method: "POST", path: "/v1/exports/stix", body: { runId: "run_inventory", producerName: "route-inventory-proof" }, expectKeys: ["bundle"] }
  ];
}
