import type { AnalystClaimLedgerEntry, AnalystLoopSnapshot, AnalystMetadataReviewTask, AnalystSourceActivationPacket, AnalystVictimNotificationPacket } from "../src/types.ts";

const now = "2026-05-24T04:44:32.036Z";
const provenance = { sourceId: "src_restricted", captureId: "cap_inventory_restricted_metadata", unsafeMaterialAccessed: false };
const whatWasNotAccessed = ["No restricted dataset was downloaded or opened.", "No credentials, cookies, private channels, or invite-only areas were accessed.", "No threat actor interaction was performed."];

export function analystFixtures() {
  const reviewTask: AnalystMetadataReviewTask = { id: "review_inventory_fjord", tenantId: "tenant_inventory", planId: "plan_inventory", runId: "run_inventory", taskId: "task_inventory_restricted", sourceId: "src_restricted", captureId: "cap_inventory_restricted_metadata", status: "open", resultState: "metadata_review", company: "Fjord Energy AS", victim: "Fjord Energy AS", affectedAccounts: "50k accounts", affectedAccountsCount: 50_000, accountSubjects: ["employees"], datasetSize: "20 GB", datasetSizeBytes: 20_000_000_000, actorStatement: "Actor claims Fjord Energy AS leaked, 50k accounts, 20 GB.", claimedAt: "2026-05-20T00:00:00.000Z", observedAt: now, sourceHash: "hash_inventory_fjord", provenance, allowedActions: ["notify_company", "mark_duplicate", "request_approval", "escalate"], confidence: 0.82, unsafeMaterialAccessed: false, whatWasNotAccessed, createdAt: now, updatedAt: now };
  const activationPacket: AnalystSourceActivationPacket = { id: "activation_inventory_fjord", tenantId: "tenant_inventory", planId: "plan_inventory", runId: "run_inventory", sourceId: "src_restricted", action: "request_operator_approval", execution: "approval_required", reason: "Operator approval required before metadata-only source restoration.", expectedEffect: "Queue safe metadata only.", rollback: "Keep source disabled.", dryRun: true, createdAt: now };
  const notificationPacket: AnalystVictimNotificationPacket = { id: "notification_inventory_fjord", tenantId: "tenant_inventory", reviewTaskId: reviewTask.id, status: "draft", company: "Fjord Energy AS", victim: "Fjord Energy AS", claimSummary: "Fjord Energy AS was named in a metadata-only leak claim; 50k accounts and 20 GB were claimed.", affectedAccounts: "50k accounts", datasetSize: "20 GB", actorStatement: reviewTask.actorStatement, claimedAt: reviewTask.claimedAt, observedAt: reviewTask.observedAt, sourceHash: reviewTask.sourceHash, confidence: 0.82, provenance: reviewTask.provenance, redactions: ["restricted_dataset_material", "credential_material", "private_access_material", "actor_interaction"], whatWasNotAccessed, safeToSend: false, createdAt: now, updatedAt: now };
  const claimLedgerEntry: AnalystClaimLedgerEntry = { id: "claim_inventory_fjord_dataset", tenantId: "tenant_inventory", normalizedQuery: "fjord energy as", reviewTaskId: reviewTask.id, captureId: reviewTask.captureId, sourceId: reviewTask.sourceId, claimKind: "dataset_size_claim", company: "Fjord Energy AS", victim: "Fjord Energy AS", claimTextSummary: "20 GB was claimed as dataset size or volume.", sourceHash: reviewTask.sourceHash, confidence: 0.82, ledgerStatus: "metadata_review", observedAt: reviewTask.observedAt, provenance: reviewTask.provenance, createdAt: now };
  const snapshot: AnalystLoopSnapshot = { id: "snapshot_inventory_fjord", tenantId: "tenant_inventory", planId: "plan_inventory", runId: "run_inventory", normalizedQuery: "fjord energy as", resultState: "metadata_review", headline: "1 metadata review item needs analyst action.", queuedTasks: 0, reviewTasks: 1, rejectedSources: 0, blockedUnsafeTargets: 0, meaningfulWorkCount: 1, nextSteps: [{ state: "metadata_review", label: "Review leak metadata", detail: "Review actor/victim/account/dataset metadata and prepare notification without opening leaked payloads.", tone: "watch" }], reviewTaskIds: [reviewTask.id], activationPacketIds: [activationPacket.id], victimNotificationPacketId: notificationPacket.id, capturedAt: now };
  return { reviewTask, activationPacket, notificationPacket, claimLedgerEntry, snapshot };
}
