import type { AdapterFailureObservationDto, AdapterObservatorySourceFamily } from "./adapterFailureObservatory.ts";
import type { ParserProfileName } from "./parserProfiles.ts";
import { hashContent } from "../utils.ts";

export type AdapterRuntimePoolName = "static_html" | "rss_feed" | "dynamic_public_browser" | "pdf_report" | "public_channel_handoff" | "advisory_signal";
export type AdapterRuntimeReadinessState = "enabled" | "canary_only" | "disabled" | "blocked";
export type AdapterRuntimeCanarySourceInput = { source: any; sourceFamily: AdapterObservatorySourceFamily; parserProfile: any; canonicalUrl?: string; robotsAllowed: boolean; legalNotesPresent?: boolean; maxBytes: number; observedContentLengthBytes?: number; expectedEvidenceYield?: number };
export type AdapterRuntimeEnablementInput = { generatedAt: string; observatory: any; browserPlan: any; canarySources: AdapterRuntimeCanarySourceInput[]; poolCaps: any; thresholds: any };
export type AdapterRuntimeReadinessDto = any; export type AdapterRuntimeEnablementPacketDto = any;
type RuntimeConfig = { adapter: AdapterRuntimePoolName; sourceFamily: AdapterObservatorySourceFamily; parserProfile: ParserProfileName; enabled: boolean; canary: boolean; workers: string; memory: number; timeout: number; bytes: number; threshold: string };

export function buildAdapterRuntimeEnablementPacket(input: AdapterRuntimeEnablementInput): AdapterRuntimeEnablementPacketDto {
  const observations = new Map<string, AdapterFailureObservationDto[]>();
  for (const item of input.observatory.observations ?? []) observations.set(item.sourceFamily, [...(observations.get(item.sourceFamily) ?? []), item]);
  const readiness = configs(input).map((config) => readinessRow(config, input, observations.get(config.sourceFamily) ?? []));
  const blockers = uniq(readiness.flatMap((row) => row.blockers)), warnings = uniq(readiness.flatMap((row) => row.warnings)), canaries = input.canarySources.filter(approved), rollbackTriggers = uniq(readiness.flatMap((row) => row.rollbackTriggers));
  return { schemaVersion: "ti.adapter_runtime_enablement_packet.v1", generatedAt: input.generatedAt, readyForCanary: readiness.some((row) => ["enabled", "canary_only"].includes(row.readiness)) && blockers.length === 0, readyForDefaultEnablement: readiness.every((row) => row.readiness === "enabled") && blockers.length === 0, readiness, summary: { totalAdapters: readiness.length, enabled: count(readiness, "enabled"), canaryOnly: count(readiness, "canary_only"), disabled: count(readiness, "disabled"), blocked: count(readiness, "blocked"), blockers, warnings }, rolloutControls: { canarySourceIds: uniq(canaries.map((item) => item.source.id)), canaryUrlHashes: uniq(canaries.map((item) => hashUrl(item.canonicalUrl ?? item.source.url))), browserWorkersEnabled: false, dynamicRequiresExplicitAllocation: true, screenshotStorage: "hash_only", rollbackTriggers }, agentHandoffs: { agent01SourceRollout: ["approve canary source ids only when readiness is canary_only or enabled and blockers are empty"], agent02Scheduler: ["schedule canary cadence from pool caps; pause pools when readiness is blocked"], agent06EvidenceStorage: ["store screenshot hashes only; suppress raw screenshots and unsafe URLs"], agent07Quality: ["enforce parser confidence thresholds before extraction promotion"], agent09ApiContracts: ["expose readiness, rolloutControls, routeContract, and no-leak forbidden fields"], agent10Observability: ["gate release on blockers, rollbackTriggers, watch failure ratio, blocked failure ratio, and memory caps"] }, routeContract: { safeForPublicApi: true, stableFields: ["schemaVersion", "generatedAt", "readyForCanary", "readyForDefaultEnablement", "readiness", "summary", "rolloutControls", "agentHandoffs", "routeContract", "safety"], forbiddenFields: ["url", "canonicalUrl", "rawText", "html", "body", "payload", "credential", "password", "cookie", "token", "privateInvite", "onionUrl", "screenshotBytes"] }, safety: safetyDefaults() };
}

function readinessRow(config: RuntimeConfig, input: AdapterRuntimeEnablementInput, observations: AdapterFailureObservationDto[]): AdapterRuntimeReadinessDto {
  const canaries = input.canarySources.filter((item) => item.sourceFamily === config.sourceFamily), accepted = canaries.filter(approved), threshold = input.thresholds[config.threshold];
  const parserOk = accepted.every((item) => item.parserProfile.profile === config.parserProfile && item.parserProfile.extractionScore >= threshold), byteOk = accepted.every((item) => item.observedContentLengthBytes === undefined || item.observedContentLengthBytes <= Math.min(item.maxBytes, input.poolCaps.maxBytes));
  const failureRatio = observations.length ? observations.filter((item) => item.outcome !== "ok").length / observations.length : 0, blockedRatio = observations.length ? observations.filter((item) => item.outcome === "blocked").length / observations.length : 0;
  const healthy = failureRatio <= input.thresholds.maxWatchFailureRatio && blockedRatio <= input.thresholds.maxBlockedFailureRatio, yieldOk = accepted.every((item) => (item.expectedEvidenceYield ?? 1) >= input.thresholds.minEvidenceYield), memoryOk = config.memory <= input.poolCaps.memoryCapMb, timeoutOk = config.timeout <= input.poolCaps.timeoutMs;
  const blockers = [...(accepted.length ? [] : [`${config.adapter}_canary_allowlist_empty`]), ...(parserOk ? [] : [`${config.adapter}_parser_confidence_below_threshold`]), ...(byteOk ? [] : [`${config.adapter}_byte_cap_exceeded`]), ...(healthy ? [] : [`${config.adapter}_observatory_failure_ratio_high`]), ...(yieldOk ? [] : [`${config.adapter}_evidence_yield_low`]), ...(memoryOk ? [] : [`${config.adapter}_memory_cap_exceeded`]), ...(timeoutOk ? [] : [`${config.adapter}_timeout_cap_exceeded`]), ...(config.adapter === "dynamic_public_browser" && !input.browserPlan.policy.robotsAllowed ? ["dynamic_public_browser_robots_policy_hold"] : []), ...(config.adapter === "dynamic_public_browser" && !input.browserPlan.policy.legalNotesPresent ? ["dynamic_public_browser_legal_notes_missing"] : [])];
  const readiness: AdapterRuntimeReadinessState = blockers.length ? "blocked" : config.enabled ? "enabled" : config.canary ? "canary_only" : "disabled";
  const warnings = [...(observations.some((item) => item.outcome === "watch") ? [`${config.adapter}_watch_failures_present`] : []), ...(accepted.some((item) => (item.expectedEvidenceYield ?? 1) < input.thresholds.minEvidenceYield + 0.15) ? [`${config.adapter}_evidence_yield_near_floor`] : [])];
  return { schemaVersion: "ti.adapter_runtime_readiness.v1", generatedAt: input.generatedAt, adapter: config.adapter, sourceFamily: config.sourceFamily, parserProfile: config.parserProfile, readiness, enabledByDefault: config.enabled && readiness === "enabled", canaryOnly: readiness === "canary_only", canarySourceIds: uniq(accepted.map((item) => item.source.id)), canaryUrlHashes: uniq(accepted.map((item) => hashUrl(item.canonicalUrl ?? item.source.url))), workerPool: { maxWorkers: input.poolCaps[config.workers], memoryCapMb: Math.min(config.memory, input.poolCaps.memoryCapMb), timeoutMs: Math.min(config.timeout, input.poolCaps.timeoutMs), maxBytes: Math.min(config.bytes, input.poolCaps.maxBytes) }, gates: { canaryAllowlist: accepted.length > 0, robotsAllowed: accepted.every((item) => item.robotsAllowed), legalNotesPresent: accepted.every((item) => item.legalNotesPresent ?? Boolean(item.source.legalNotes.trim())), parserConfidenceMet: parserOk, byteCapMet: byteOk, observatoryHealthy: healthy, browserDisabledByDefault: true, screenshotHashOnly: true }, rollbackTriggers: rollbackTriggersFor(config.adapter), blockers, warnings, handoffs: handoffsFor(readiness, config.adapter), safety: safetyDefaults() };
}

function configs(input: AdapterRuntimeEnablementInput): RuntimeConfig[] { return [["static_html", "static_html", "static_html", true, "staticMaxWorkers", 256, 10_000, input.poolCaps.maxBytes, "staticMinParserConfidence"], ["rss_feed", "rss_feed", "rss_entry", true, "rssMaxWorkers", 192, 8_000, 1_000_000, "rssMinParserConfidence"], ["dynamic_public_browser", "dynamic_page", "dynamic_page", false, "dynamicMaxWorkers", input.browserPlan.resourceCaps.memoryCapMb, input.browserPlan.resourceCaps.timeoutMs, 5_000_000, "dynamicMinParserConfidence"], ["pdf_report", "pdf_report", "pdf_report", false, "pdfMaxWorkers", 768, 20_000, 10_000_000, "pdfMinParserConfidence"], ["public_channel_handoff", "public_channel", "public_channel_handoff", false, "publicChannelMaxWorkers", 256, 10_000, 500_000, "publicChannelMinParserConfidence"], ["advisory_signal", "advisory_signal", "static_html", true, "advisoryMaxWorkers", 256, 8_000, 1_000_000, "advisoryMinParserConfidence"]].map(([adapter, sourceFamily, parserProfile, enabled, workers, memory, timeout, bytes, threshold]) => ({ adapter, sourceFamily, parserProfile, enabled, canary: true, workers, memory, timeout, bytes, threshold } as RuntimeConfig)); }
function approved(item: AdapterRuntimeCanarySourceInput): boolean { return item.robotsAllowed && (item.legalNotesPresent ?? Boolean(item.source.legalNotes.trim())); }
function count(rows: AdapterRuntimeReadinessDto[], state: AdapterRuntimeReadinessState): number { return rows.filter((row) => row.readiness === state).length; }
function rollbackTriggersFor(adapter: AdapterRuntimePoolName): string[] { const common = ["parser_confidence_below_threshold", "blocked_failure_ratio_exceeded", "policy_hold_detected", "unsafe_serialization_detected"]; return adapter === "dynamic_public_browser" ? [...common, "browser_memory_cap_exceeded", "browser_timeout_spike", "raw_screenshot_storage_attempt"] : adapter === "pdf_report" ? [...common, "pdf_byte_cap_exceeded", "pdf_extraction_timeout_spike"] : common; }
function handoffsFor(readiness: AdapterRuntimeReadinessState, adapter: AdapterRuntimePoolName) { return readiness === "blocked" ? { agent01SourceRollout: "hold_source", agent02Scheduler: "pause_pool", agent06EvidenceStorage: "suppress_capture", agent07Quality: "block_extraction", agent09ApiContracts: "blocked", agent10Observability: "hold" } : readiness === "canary_only" || adapter === "dynamic_public_browser" || adapter === "pdf_report" ? { agent01SourceRollout: "approve_canary", agent02Scheduler: "canary_cadence", agent06EvidenceStorage: adapter === "dynamic_public_browser" ? "hash_only_screenshots" : "normal_capture", agent07Quality: "watch_confidence", agent09ApiContracts: "canary_only", agent10Observability: "watch" } : { agent01SourceRollout: "no_action", agent02Scheduler: "normal_cadence", agent06EvidenceStorage: "normal_capture", agent07Quality: "accept", agent09ApiContracts: "ready", agent10Observability: "green" }; }
function hashUrl(url: string): string { return `urlhash:${hashContent(url).slice(0, 16)}`; }
function safetyDefaults(): AdapterFailureObservationDto["safety"] { return { publicOnly: true, noAuthBypass: true, noCaptchaSolving: true, noPrivateCommunities: true, noExploitPayloadDownload: true, noRestrictedRawMaterial: true, unsafeUrlExposed: false }; }
function uniq(values: string[]): string[] { return [...new Set(values)].sort(); }
