// @ts-nocheck
import { processCollectedItem } from "../pipeline/pipeline.ts";
import type { ScraperStore } from "../storage/memoryStore.ts";
import type { CollectionTask, DiscoveryEvidence, SourceRecord } from "../types.ts";
import { hashContent, stableId } from "../utils.ts";
import { StaticWebAdapter, type StaticWebAdapterOptions } from "./staticWeb.ts";

export type PublicChannelMatchState = "matched" | "not_matched" | "not_configured" | "pending_review" | "blocked";
export type ClearWebPromotionStatus = "captured" | "blocked" | "duplicate";
export type ClearWebPromotionFailureCategory = "policy_blocked" | "robots_blocked" | "not_modified" | "rate_limited" | "not_found" | "http_error" | "too_large" | "unsupported_mime" | "duplicate_canonical";
export type SearchResultHandoff = any; export type ClearWebCollectedItemProof = any; export type ClearWebApiPromotionMetadata = any; export type ClearWebPromotionProof = any; export interface ClearWebPromotionOptions extends StaticWebAdapterOptions { maxBytes?: number; }

export async function promoteSearchResultToCanonicalCapture(store: ScraperStore, source: SourceRecord, handoff: SearchResultHandoff, options: ClearWebPromotionOptions = {}): Promise<ClearWebPromotionProof> {
  const normalizedQuery = normalizeQuery(handoff.query), resultId = handoff.resultId ?? stableId("result", `${handoff.provider}:${handoff.url}:${handoff.rank}`), discovery = store.saveDiscoveryEvidence(discoveryFor(source, handoff, normalizedQuery, resultId)), task = taskFor(source, handoff, discovery, options.maxBytes ?? 1_000_000), collected = await new StaticWebAdapter(options).collect(source, task), match = handoff.publicChannelMatchState ?? "not_configured", base = skeleton(source, handoff, normalizedQuery, discovery.id, task.id, match), item = collected.items[0];
  if (!item) { store.promoteDiscoveryEvidence({ discoveryEvidenceId: discovery.id, taskId: task.id, promotedAt: handoff.observedAt, promotedBy: "collector" }); return { ...base, evidenceStage: "blocked", status: "blocked", failureCategory: mstr(collected.metadata, "failureCategory"), responseStatus: mnum(collected.metadata, "responseStatus"), retryAfterSeconds: mnum(collected.metadata, "retryAfterSeconds"), apiPromotionMetadata: apiMeta({ proofBase: base, evidenceStage: "blocked", status: "blocked", failureCategory: mstr(collected.metadata, "failureCategory"), responseStatus: mnum(collected.metadata, "responseStatus"), retryAfterSeconds: mnum(collected.metadata, "retryAfterSeconds") }), warnings: collected.warnings }; }
  const parserProfile = parserFor(item.url, item.metadata), collectedItem = proofItem(item), pipeline = processCollectedItem({ ...item, metadata: { ...item.metadata, query: handoff.query, normalizedQuery, runId: handoff.runId, promotedFromDiscoveryId: discovery.id, searchProvider: handoff.provider, searchRank: handoff.rank, discoveryObservedAt: handoff.observedAt, evidenceStage: "captured_page", parserProfile, publicChannelMatchState: match, publicChannelEvidenceIds: handoff.publicChannelEvidenceIds ?? [], publicChannelMessageUrls: handoff.publicChannelMessageUrls ?? [] } });
  const duplicate = store.findDuplicateCapture(pipeline.capture), stored = store.savePipelineResult(pipeline), incidentId = stored.incident?.id;
  store.promoteDiscoveryEvidence({ discoveryEvidenceId: discovery.id, taskId: task.id, captureId: stored.capture.id, incidentId, promotedAt: item.collectedAt, promotedBy: "collector" });
  if (duplicate) return { ...base, captureId: duplicate.id, incidentId, canonicalUrl: duplicate.url, contentHash: duplicate.contentHash, parserProfile: String(duplicate.metadata.parserProfile ?? parserProfile), evidenceStage: "duplicate_canonical", status: "duplicate", failureCategory: "duplicate_canonical", responseStatus: mnum(item.metadata, "responseStatus"), collectedItem, apiPromotionMetadata: apiMeta({ proofBase: base, captureId: duplicate.id, incidentId, canonicalUrl: duplicate.url, contentHash: duplicate.contentHash, parserProfile: String(duplicate.metadata.parserProfile ?? parserProfile), evidenceStage: "duplicate_canonical", status: "duplicate", failureCategory: "duplicate_canonical", publicChannelMatchState: match }), warnings: [...collected.warnings, `duplicate canonical capture ${duplicate.id}`] };
  const status = "captured", evidenceStage = "captured_page";
  return { ...base, captureId: stored.capture.id, incidentId, canonicalUrl: stored.capture.url, contentHash: stored.capture.contentHash, parserProfile: String(stored.capture.metadata.parserProfile ?? "generic_static_web"), evidenceStage, status, failureCategory: undefined, responseStatus: mnum(stored.capture.metadata, "responseStatus"), collectedItem, apiPromotionMetadata: apiMeta({ proofBase: base, captureId: stored.capture.id, incidentId, canonicalUrl: stored.capture.url, contentHash: stored.capture.contentHash, parserProfile: String(stored.capture.metadata.parserProfile ?? "generic_static_web"), evidenceStage, status, failureCategory: undefined, responseStatus: mnum(stored.capture.metadata, "responseStatus"), publicChannelMatchState: match }), warnings: collected.warnings };
}

function discoveryFor(source: SourceRecord, handoff: SearchResultHandoff, normalizedQuery: string, resultId: string): DiscoveryEvidence { return { id: stableId("disc", `${handoff.provider}:${normalizedQuery}:${resultId}`), tenantId: handoff.tenantId, query: handoff.query, normalizedQuery, provider: "search_provider", evidenceType: "search_snippet", resultId, observedAt: handoff.observedAt, title: handoff.title, snippet: handoff.snippet, url: handoff.url, sourceId: source.id, rank: handoff.rank, confidence: handoff.confidence ?? 0.62, metadata: { searchProvider: handoff.provider, sourceType: source.type, targetUrl: handoff.url, snippetHash: hashContent(handoff.snippet), promotion: "canonical_capture_required", publicChannelMatchState: handoff.publicChannelMatchState ?? "not_configured", publicChannelEvidenceIds: handoff.publicChannelEvidenceIds ?? [], publicChannelMessageUrls: handoff.publicChannelMessageUrls ?? [] }, retentionClass: "discovery_snippet" }; }
function skeleton(source: SourceRecord, handoff: SearchResultHandoff, normalizedQuery: string, discoveryId: string, taskId: string, publicChannelMatchState: PublicChannelMatchState) { return { query: handoff.query, normalizedQuery, sourceId: source.id, discoveryId, taskId, publicChannelMatchState, publicChannelEvidenceIds: handoff.publicChannelEvidenceIds ?? [], publicChannelMessageUrls: handoff.publicChannelMessageUrls ?? [] }; }
function apiMeta(input): ClearWebApiPromotionMetadata { const match = input.publicChannelMatchState ?? input.proofBase.publicChannelMatchState; return { agent06: { taskId: input.proofBase.taskId, discoveryId: input.proofBase.discoveryId, captureId: input.captureId, contentHash: input.contentHash, canonicalUrl: input.canonicalUrl, evidenceStage: input.evidenceStage, persistenceReady: Boolean(input.captureId && input.contentHash) }, agent07: { query: input.proofBase.query, normalizedQuery: input.proofBase.normalizedQuery, incidentId: input.incidentId, parserProfile: input.parserProfile, publicChannelMatchState: match, answerState: answer(input.status, match, input.incidentId) }, agent09: { status: input.status, failureCategory: input.failureCategory, responseStatus: input.responseStatus, retryAfterSeconds: input.retryAfterSeconds, publicTiImpact: impact(input.status, match) } }; }
function answer(status: ClearWebPromotionStatus, match: PublicChannelMatchState, incidentId?: string) { return status === "blocked" ? "blocked" : match === "matched" && incidentId ? "partial_support" : "answerable"; }
function impact(status: ClearWebPromotionStatus, match: PublicChannelMatchState) { return status === "blocked" ? "blocked" : status === "captured" ? "promoted" : status === "duplicate" || match === "matched" ? "partial" : "searching"; }
function proofItem(item: { url: string; title?: string; contentHash: string; rawText: string; links: string[] }): ClearWebCollectedItemProof { return { url: item.url, title: item.title, contentHash: item.contentHash, rawTextLength: item.rawText.length, linkCount: item.links.length }; }
function mstr(metadata: Record<string, unknown> | undefined, key: string) { const value = metadata?.[key]; return typeof value === "string" ? value : undefined; }
function mnum(metadata: Record<string, unknown> | undefined, key: string) { const value = metadata?.[key]; return typeof value === "number" && Number.isFinite(value) ? value : undefined; }
function taskFor(source: SourceRecord, handoff: SearchResultHandoff, discovery: DiscoveryEvidence, maxBytes: number): CollectionTask { return { id: stableId("task", `${discovery.id}:${handoff.url}`), tenantId: handoff.tenantId, sourceId: source.id, targetUrl: handoff.url, sourceType: "static_web", queuedAt: handoff.observedAt, priority: Math.max(0.1, 1 - handoff.rank / 20), reason: `promote search result for ${handoff.query}`, parentUrl: discovery.url, retryCount: 0, intelRequestId: handoff.runId, runId: handoff.runId, maxBytes, maxRetries: 2, sourceConcurrencyKey: source.id, fairnessKey: `${handoff.tenantId ?? "global"}:${normalizeQuery(handoff.query)}:clear_web_capture`, planning: { budgetClass: "interactive_live_search", decision: "selected", reason: "search snippet requires canonical captured-page evidence", queryTerms: [handoff.query], freshness: 1, freshnessTargetSeconds: source.crawlFrequencySeconds, maxCost: { tasks: 1, bytes: maxBytes }, safetyEnvelope: { allowClearWeb: true, allowPublicChannel: false, allowRestrictedMetadata: false, metadataOnlyRestricted: false, forbiddenOperations: ["credential_bypass", "captcha_solving", "private_community_access"] }, sourceTrust: source.trustScore, selectedFor: "interactive" } }; }
function parserFor(url: string, metadata: Record<string, unknown>) { const value = String(metadata.parserProfile ?? ""); if (value) return value; const host = hostname(url); return host.includes("wikipedia.org") ? "public_encyclopedia" : host.includes("github.com") ? "github_advisory" : host.includes("cisa.gov") || host.includes("cert.") || host.endsWith(".gov") ? "government_advisory" : /blog|research|threat|security|report/i.test(url) ? "vendor_report" : "generic_static_web"; }
function hostname(url: string) { try { return new URL(url).hostname.toLowerCase(); } catch { return ""; } }
function normalizeQuery(query: string) { return query.trim().toLowerCase().replace(/\s+/g, " "); }
