// @ts-nocheck
import { citationSpansForText } from "./parserProfiles.ts";
import { hashContent } from "../utils.ts";

export type PublicReportLanguageCode = "en" | "nb" | "ru" | "zh" | "fa" | "es" | "mixed" | "unknown";
export type MultilingualPublicReportInput = any; export type TranslationHandoffPacketDto = any; export type MultilingualParserConfidenceBenchmarkInput = any; export type MultilingualParserConfidenceBenchmarkDto = any;
const FORBIDDEN = ["url", "canonicalUrl", "rawText", "translatedText", "html", "body", "payload", "credential", "password", "cookie", "token", "privateInvite", "onionUrl", "translationVendor", "apiKey"];

export function buildTranslationHandoffPacket(input: MultilingualPublicReportInput): TranslationHandoffPacketDto {
  const declared = normLang(input.declaredLanguage ?? input.item.language ?? input.source.language), detected = detectPublicReportLanguage(input.item.rawText, declared), original = declared && declared !== "unknown" ? declared : detected.language, target = input.targetLanguage ?? "en", translationNeeded = original !== "en" || detected.language === "mixed";
  const spans = (spanValue(input.item.metadata.citationSpans).length ? spanValue(input.item.metadata.citationSpans) : citationSpansForText(input.item.rawText)).map((s) => ({ start: s.start, end: s.end, label: s.label, sourceLanguage: original, targetLanguage: target }));
  const adjusted = round(Math.max(0, Math.min(1, input.parserProfile.extractionScore - (translationNeeded ? 0.08 : 0) - (detected.language === "mixed" ? 0.08 : 0) - (spans.length ? 0 : 0.12)))), impact = confidenceImpact(input.parserProfile.extractionScore, adjusted), requested = normLang(input.requestedLanguage);
  const requestedLanguageFit = requested ? fit(requested, original, detected.language) : 1, sourceLanguageFit = fit(original, detected.language, detected.language), priority = !translationNeeded ? "none" : impact === "major" || detected.language === "mixed" ? "high" : "normal", quality = adjusted < 0.45 ? "block_low_confidence" : translationNeeded ? "review_translation" : "accept";
  return { schemaVersion: "ti.translation_handoff.v1", generatedAt: input.generatedAt, sourceId: input.source.id, taskId: input.item.taskId, sourceFamily: input.sourceFamily, parserProfile: input.parserProfile.profile, parserVersion: input.parserProfile.parserVersion, contentHash: input.item.contentHash, canonicalUrlHash: `urlhash:${hashContent(input.item.url).slice(0, 16)}`, language: { ...(declared ? { declared } : {}), detected: detected.language, original, target, ...(requested ? { requested } : {}), confidence: detected.confidence, mixedLanguage: detected.language === "mixed", translationNeeded, detectionSignals: detected.signals }, citationSpans: spans, extraction: { originalParserConfidence: input.parserProfile.extractionScore, adjustedParserConfidence: adjusted, confidenceImpact: impact, fallbackOrder: input.parserProfile.fallbackOrder, parserWarnings: [...input.parserProfile.parserWarnings, ...(translationNeeded ? [`translation handoff required for ${original}->${target}`] : []), ...(detected.language === "mixed" ? ["mixed-language public report requires analyst review after translation"] : [])] }, sourceLanguageScoring: { sourceLanguageFit, requestedLanguageFit, translationPriority: priority, sourceScoringNotes: notes(original, requested, detected.language, translationNeeded) }, handoffs: { agent01SourceScoring: sourceLanguageFit >= 0.9 && !translationNeeded ? "language_boost" : translationNeeded ? "language_review" : "no_action", agent04CoverageGaps: detected.language === "mixed" ? "mixed_language_gap" : translationNeeded ? "translation_gap" : "covered", agent06EvidenceRetention: translationNeeded ? "retain_translation_metadata_only" : "retain_original_language_metadata", agent07Quality: quality, agent09ApiContracts: "stable_multilingual_fields", agent10Observability: translationNeeded || requestedLanguageFit < 0.7 ? "watch_language_gap" : "ok" }, routeContract: { safeForPublicApi: true, stableFields: ["schemaVersion", "generatedAt", "sourceId", "sourceFamily", "parserProfile", "contentHash", "canonicalUrlHash", "language", "citationSpans", "extraction", "sourceLanguageScoring", "handoffs", "routeContract", "safety"], forbiddenFields: FORBIDDEN }, safety: { publicOnly: true, noTranslationVendorCoupling: true, rawTextExposed: false, translatedTextExposed: false, unsafeUrlExposed: false } };
}
export function buildMultilingualParserConfidenceBenchmark(input: MultilingualParserConfidenceBenchmarkInput): MultilingualParserConfidenceBenchmarkDto {
  const thresholds = { minAdjustedParserConfidence: input.thresholds?.minAdjustedParserConfidence ?? 0.62, minCitationSpanCoverage: input.thresholds?.minCitationSpanCoverage ?? 0.8, maxHighPriorityTranslationRatio: input.thresholds?.maxHighPriorityTranslationRatio ?? 0.35, maxMixedLanguageRatio: input.thresholds?.maxMixedLanguageRatio ?? 0.2 }, rows = languageRows(input.packets, thresholds), status = worst(rows.map((r) => r.status)), count = (fn) => input.packets.filter(fn).length;
  return { schemaVersion: "ti.multilingual_parser_confidence_benchmark.v1", generatedAt: input.generatedAt, status, thresholds, summary: { packetCount: input.packets.length, languagesCovered: uniq(input.packets.map((p) => p.language.original)), translationNeededCount: count((p) => p.language.translationNeeded), mixedLanguageCount: count((p) => p.language.mixedLanguage), highPriorityTranslationCount: count((p) => p.sourceLanguageScoring.translationPriority === "high"), reviewTranslationCount: count((p) => p.handoffs.agent07Quality === "review_translation"), blockedLowConfidenceCount: count((p) => p.handoffs.agent07Quality === "block_low_confidence"), averageDetectionConfidence: avg(input.packets.map((p) => p.language.confidence)), averageAdjustedParserConfidence: avg(input.packets.map((p) => p.extraction.adjustedParserConfidence)), citationSpanCoverage: ratio(count((p) => p.citationSpans.length > 0), input.packets.length) }, rows, handoffs: { agent01SourceScoring: uniq(rows.flatMap((r) => r.status === "pass" ? [`language_benchmark_pass:${r.language}`] : [`language_benchmark_${r.status}:${r.language}`])), agent04CoverageGaps: uniq(rows.filter((r) => r.status !== "pass").map((r) => `translation_coverage_${r.status}:${r.language}`)), agent06EvidenceRetention: ["retain_original_language_metadata", "retain_translation_metadata_only"], agent07Quality: uniq(rows.map((r) => r.status === "hold" ? `hold_low_confidence_language:${r.language}` : r.status === "watch" ? `review_language_quality:${r.language}` : `accept_language_quality:${r.language}`)), agent09ApiContracts: "stable_multilingual_benchmark_fields", agent10Release: status === "pass" ? "green" : status }, routeContract: { safeForPublicApi: true, stableFields: ["schemaVersion", "generatedAt", "status", "thresholds", "summary", "rows", "handoffs", "routeContract", "safety"], forbiddenFields: FORBIDDEN }, safety: { publicOnly: true, rawTextExposed: false, translatedTextExposed: false, unsafeUrlExposed: false, vendorCoupling: false } };
}
export function detectPublicReportLanguage(text: string, declared?: PublicReportLanguageCode) { const signals = [], n = text.toLowerCase(); if (/[а-яё]/i.test(text)) signals.push(["ru", "cyrillic", 0.95]); if (/[\u4e00-\u9fff]/u.test(text)) signals.push(["zh", "han_script", 0.95]); if (/[\u0600-\u06ff]/u.test(text)) signals.push(["fa", "persian_arabic_script", 0.95]); if (/\b(?:trusselaktør|sårbarhet|angrep|etterretning|skadevare|løsepengevirus)\b/i.test(text)) signals.push(["nb", "norwegian_cti_terms", 0.78]); if (/\b(?:amenaza|vulnerabilidad|ataque|campaña|infraestructura|indicadores)\b/i.test(n)) signals.push(["es", "spanish_cti_terms", 0.78]); if (/\b(?:threat|vulnerability|attack|malware|campaign|infrastructure|indicators|advisory)\b/i.test(n)) signals.push(["en", "english_cti_terms", 0.74]); if (declared && declared !== "unknown") signals.push([declared, `declared:${declared}`, 0.65]); if (!signals.length) return { language: declared ?? "unknown", confidence: declared && declared !== "unknown" ? 0.58 : 0.2, signals: declared ? [`declared:${declared}`] : ["no_language_signal"] }; const scores = new Map(); for (const [lang, , weight] of signals) scores.set(lang, (scores.get(lang) ?? 0) + weight); const ranked = [...scores.entries()].sort((a, b) => b[1] - a[1]), strong = ranked.filter(([, score]) => score >= 0.7).map(([lang]) => lang).filter((lang) => lang !== "unknown"); return strong.length >= 2 ? { language: "mixed", confidence: 0.76, signals: signals.map((s) => s[1]) } : { language: ranked[0]?.[0] ?? "unknown", confidence: Math.min(0.98, Math.max(0.35, ranked[0]?.[1] ?? 0.2)), signals: signals.map((s) => s[1]) }; }
function normLang(value: string | undefined): PublicReportLanguageCode | undefined { if (!value) return undefined; const n = value.trim().toLowerCase(); return n === "no" || n === "nn" || n === "nb-nb" ? "nb" : n.startsWith("en") ? "en" : n.startsWith("nb") || n.startsWith("no") || n.startsWith("nn") ? "nb" : n.startsWith("ru") ? "ru" : n.startsWith("zh") || n.startsWith("cn") ? "zh" : n.startsWith("fa") || n.startsWith("per") ? "fa" : n.startsWith("es") ? "es" : n === "mixed" ? "mixed" : "unknown"; }
function confidenceImpact(original, adjusted) { const delta = original - adjusted; return delta <= 0.02 ? "none" : delta <= 0.08 ? "minor" : delta <= 0.16 ? "moderate" : "major"; }
function fit(requested, original, detected) { return requested === "unknown" || requested === "mixed" ? 0.5 : requested === original || requested === detected ? 1 : detected === "mixed" ? 0.65 : 0.35; }
function notes(original, requested, detected, needed) { return [`original_language:${original}`, `detected_language:${detected}`, ...(requested ? [`requested_language:${requested}`] : []), ...(needed ? ["translation_needed_without_vendor_coupling"] : ["source_language_matches_target"]), ...(detected === "mixed" ? ["mixed_language_requires_quality_review"] : [])]; }
function spanValue(value) { return Array.isArray(value) ? value.filter((i) => i && typeof i.start === "number" && typeof i.end === "number" && typeof i.label === "string") : []; }
function languageRows(packets, thresholds) { const groups = new Map(); for (const p of packets) groups.set(p.language.original, [...groups.get(p.language.original) ?? [], p]); return [...groups.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([language, rows]) => { const count = (fn) => rows.filter(fn).length, adjusted = rows.map((p) => p.extraction.adjustedParserConfidence), translationNeededCount = count((p) => p.language.translationNeeded), mixedLanguageCount = count((p) => p.language.mixedLanguage), highPriorityTranslationCount = count((p) => p.sourceLanguageScoring.translationPriority === "high"), reviewTranslationCount = count((p) => p.handoffs.agent07Quality === "review_translation"), blockedLowConfidenceCount = count((p) => p.handoffs.agent07Quality === "block_low_confidence"), averageAdjustedParserConfidence = avg(adjusted), minimumAdjustedParserConfidence = adjusted.length ? round(Math.min(...adjusted)) : 0, citationSpanCoverage = ratio(count((p) => p.citationSpans.length > 0), rows.length), blockers = uniq([...(blockedLowConfidenceCount ? ["low_confidence_translation_block"] : []), ...(minimumAdjustedParserConfidence < 0.45 ? ["minimum_adjusted_confidence_below_hold_threshold"] : []), ...(citationSpanCoverage < 0.5 ? ["citation_span_coverage_below_hold_threshold"] : [])]), warnings = uniq([...(averageAdjustedParserConfidence < thresholds.minAdjustedParserConfidence ? ["average_adjusted_confidence_below_target"] : []), ...(citationSpanCoverage < thresholds.minCitationSpanCoverage ? ["citation_span_coverage_below_target"] : []), ...(ratio(highPriorityTranslationCount, rows.length) > thresholds.maxHighPriorityTranslationRatio ? ["high_priority_translation_ratio_above_target"] : []), ...(ratio(mixedLanguageCount, rows.length) > thresholds.maxMixedLanguageRatio ? ["mixed_language_ratio_above_target"] : [])]), status = blockers.length ? "hold" : warnings.length ? "watch" : "pass"; return { language, packetCount: rows.length, packetRefs: rows.map(packetRef).sort(), translationNeededCount, mixedLanguageCount, highPriorityTranslationCount, reviewTranslationCount, blockedLowConfidenceCount, averageDetectionConfidence: avg(rows.map((p) => p.language.confidence)), averageAdjustedParserConfidence, minimumAdjustedParserConfidence, citationSpanCoverage, status, blockers, warnings }; }); }
function packetRef(packet) { return `translation_ref:${hashContent(`${packet.sourceId}:${packet.contentHash}:${packet.canonicalUrlHash}`).slice(0, 16)}`; }
function avg(values) { return values.length ? round(values.reduce((sum, v) => sum + v, 0) / values.length) : 0; }
function ratio(count, total) { return total ? round(count / total) : 0; }
function worst(statuses) { return statuses.includes("hold") ? "hold" : statuses.includes("watch") ? "watch" : "pass"; }
function uniq(values) { return [...new Set(values.filter(Boolean))].sort(); }
function round(value) { return Math.round(value * 1000) / 1000; }
