import type { AdapterRunResult, SourceRecord } from "../types.ts";

export type ParserProfileName = "static_html" | "dynamic_page" | "pdf_report" | "rss_entry" | "public_channel_handoff";
export type ParserFailureCategory = "timeout" | "robots_policy_hold" | "policy_hold" | "unsupported_media" | "content_too_large" | "parser_confidence_low" | "duplicate_canonical" | "rate_limited" | "unavailable" | "source_disabled";
export type ParserExtractionConfidenceBand = "high" | "medium" | "low" | "blocked";
export type ParserProfileDecision = any; export type ParserProfileInput = any; export type AdapterPromotionContractDto = any; export type Agent07ExtractionHandoffDto = any;

export function selectParserProfile(input: ParserProfileInput): ParserProfileDecision {
  const contentType = input.contentType?.split(";")[0]?.trim().toLowerCase() ?? "";
  const profile = input.publicChannelHandoff ? "public_channel_handoff" : input.requiresJavascript ? "dynamic_page" : contentType === "application/pdf" ? "pdf_report" : profileForSource(input.sourceType);
  const qualitySignals = quality(profile, input), extractionScore = score(qualitySignals, input);
  return { profile, fallbackOrder: fallback(profile), fallbackReasons: fallbackReasons(profile), reason: input.requiresJavascript ? "source or handoff requires rendered JavaScript capture" : contentType === "application/pdf" ? "response media type is PDF" : `selected ${profile} for ${input.sourceType}`, extractionScore, extractionConfidenceBand: band(extractionScore, input.failureCategory), languageHint: language(input.language, input.textSample), parserVersion: "parser-profile-matrix-v1", parserWarnings: input.parserWarnings ?? [], expectedMediaTypes: media(profile), qualitySignals };
}

export function adapterPromotionContract(input: { source: SourceRecord; result: AdapterRunResult; profile: ParserProfileDecision; adapter: SourceRecord["type"] | string; costClass: "low" | "medium" | "high" }): AdapterPromotionContractDto {
  const item = input.result.items[0], failureCategory = str(input.result.metadata?.failureCategory) as ParserFailureCategory | undefined, parserWarnings = warnings(input.result, input.profile, item), extractionStatus = status(item, input.profile, failureCategory);
  return { schemaVersion: "ti.adapter_capture_contract.v1", sourceId: input.source.id, taskId: item?.taskId, adapter: input.adapter, status: item ? "captured" : failureCategory ? "blocked" : "empty", canonicalUrl: item?.url, contentHash: item?.contentHash, parserProfile: input.profile.profile, parserVersion: input.profile.parserVersion, parserWarnings, sourceTrust: input.source.trustScore, extractionStatus, failureCategory, agent06: { captureReady: Boolean(item), canonicalUrl: item?.url, contentHash: item?.contentHash, provenanceRequired: true }, agent07: { parserProfile: input.profile.profile, extractionConfidenceBand: input.profile.extractionConfidenceBand, languageHint: input.profile.languageHint, citationSpansAvailable: Boolean(item?.metadata.citationSpans) }, agent09: { apiStatus: item ? "captured" : failureCategory ? "blocked" : "searching", failureCategory, retryable: ["timeout", "rate_limited", "unavailable"].includes(String(failureCategory)) }, agent10: { adapter: input.adapter, costClass: input.costClass, dashboardState: item ? "ok" : failureCategory ? "blocked" : "watch" } };
}

export function agent07ExtractionHandoff(input: { source: SourceRecord; result: AdapterRunResult; profile: ParserProfileDecision; failureCategory?: ParserFailureCategory }): Agent07ExtractionHandoffDto {
  const item = input.result.items[0], failureCategory = input.failureCategory ?? str(input.result.metadata?.failureCategory) as ParserFailureCategory | undefined, parserWarnings = warnings(input.result, input.profile, item);
  return { schemaVersion: "ti.agent07.extraction_handoff.v1", redactionSafe: true, sourceId: input.source.id, taskId: item?.taskId, canonicalUrl: item?.url, contentHash: item?.contentHash, publishedAt: item?.publishedAt, parserProfile: input.profile.profile, parserVersion: input.profile.parserVersion, extractionScore: input.profile.extractionScore, extractionConfidenceBand: failureCategory ? "blocked" : input.profile.extractionConfidenceBand, languageHint: input.profile.languageHint, citationSpans: spans(item?.metadata.citationSpans), parserWarnings, fallbackOrder: input.profile.fallbackOrder, fallbackReasons: input.profile.fallbackReasons, sourceTrust: input.source.trustScore, extractionStatus: status(item, input.profile, failureCategory), blockedReason: failureCategory, safeSummary: safeSummary(item?.rawText), forbiddenFields: ["rawText", "rawHtml", "html", "body", "payload", "credential", "password", "cookie", "session", "privateInvite"] };
}

export function citationSpansForText(text: string): Array<{ start: number; end: number; label: string }> { const match = text.match(/[^.!?]+[.!?]/); return match?.index === undefined ? [] : [{ start: match.index, end: match.index + match[0].length, label: "lead_sentence" }]; }
export function parserProfileMetadata(profile: ParserProfileDecision): Record<string, unknown> { return { parserProfile: profile.profile, parserFallbackOrder: profile.fallbackOrder, parserFallbackReasons: profile.fallbackReasons, parserVersion: profile.parserVersion, parserWarnings: profile.parserWarnings, extractionScore: profile.extractionScore, extractionConfidenceBand: profile.extractionConfidenceBand, languageHint: profile.languageHint, parserQualitySignals: profile.qualitySignals }; }
function profileForSource(sourceType: SourceRecord["type"]): ParserProfileName { return sourceType === "dynamic_web" ? "dynamic_page" : sourceType === "pdf" ? "pdf_report" : sourceType === "rss" ? "rss_entry" : sourceType === "telegram_public" ? "public_channel_handoff" : "static_html"; }
function fallback(profile: ParserProfileName): ParserProfileName[] { return profile === "dynamic_page" ? ["dynamic_page", "static_html"] : profile === "pdf_report" ? ["pdf_report", "static_html"] : profile === "rss_entry" ? ["rss_entry", "static_html"] : profile === "public_channel_handoff" ? ["public_channel_handoff", "static_html"] : ["static_html"]; }
function fallbackReasons(profile: ParserProfileName): string[] { return profile === "dynamic_page" ? ["rendered DOM first", "fall back to static HTML when rendered text is empty or renderer is unavailable"] : profile === "pdf_report" ? ["structured PDF/report extraction first", "fall back to static HTML for landing pages or converted report text"] : profile === "rss_entry" ? ["feed item metadata first", "fall back to linked static article for full body extraction"] : profile === "public_channel_handoff" ? ["public-channel normalized evidence first", "fall back to static linked references when citation URLs are available"] : ["static HTML readability extraction"]; }
function media(profile: ParserProfileName): string[] { return profile === "pdf_report" ? ["application/pdf"] : profile === "rss_entry" ? ["application/rss+xml", "application/atom+xml", "application/xml", "text/xml"] : profile === "public_channel_handoff" ? ["application/json", "text/plain"] : ["text/html", "application/xhtml+xml", "text/plain"]; }
function quality(profile: ParserProfileName, input: ParserProfileInput) { const type = input.contentType?.split(";")[0]?.trim().toLowerCase() ?? "", expected = media(profile), fit = !type || expected.includes(type) || (profile === "static_html" && type === "text/plain"), len = input.textSample?.trim().length ?? 0, tooLarge = input.maxBytes !== undefined && input.contentLengthBytes !== undefined && input.contentLengthBytes > input.maxBytes; return { parserSpecificity: profile === "static_html" ? 0.72 : profile === "public_channel_handoff" ? 0.78 : 0.9, contentFitness: tooLarge ? 0.1 : fit ? textFitness(len) : 0.35, policyFitness: ["policy_hold", "robots_policy_hold", "source_disabled"].includes(String(input.failureCategory)) ? 0 : 1 }; }
function score(signals, input: ParserProfileInput): number { if (input.failureCategory) return 0; return clamp((signals.parserSpecificity * 0.35) + (signals.contentFitness * 0.45) + (signals.policyFitness * 0.2) - Math.min((input.parserWarnings?.length ?? 0) * 0.06, 0.24)); }
function textFitness(len: number): number { return len === 0 ? 0.72 : len < 24 ? 0.35 : len < 120 ? 0.68 : 0.95; }
function band(score: number, failure?: ParserFailureCategory): ParserExtractionConfidenceBand { return failure ? "blocked" : score >= 0.82 ? "high" : score >= 0.58 ? "medium" : "low"; }
function language(language: string | undefined, sample: string | undefined): string | undefined { return language ?? (!sample ? undefined : /\b(der|die|das|und|nicht|bericht)\b/i.test(sample) ? "de" : /\b(le|la|les|rapport|attaque)\b/i.test(sample) ? "fr" : "en"); }
function status(item, profile: ParserProfileDecision, failure?: ParserFailureCategory): "ready_for_extraction" | "blocked" | "needs_review" { return failure ? "blocked" : item && profile.extractionConfidenceBand !== "low" ? "ready_for_extraction" : "needs_review"; }
function warnings(result: AdapterRunResult, profile: ParserProfileDecision, item): string[] { return [...profile.parserWarnings, ...result.warnings, ...arr(item?.metadata.parserWarnings)]; }
function str(value: unknown): string | undefined { return typeof value === "string" ? value : undefined; }
function arr(value: unknown): string[] { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : []; }
function spans(value: unknown): Array<{ start: number; end: number; label: string }> { return Array.isArray(value) ? value.filter((span): span is { start: number; end: number; label: string } => Boolean(span && typeof span === "object" && typeof span.start === "number" && typeof span.end === "number" && typeof span.label === "string")) : []; }
function safeSummary(text?: string): string | undefined { return text?.replace(/\s+/g, " ").trim().slice(0, 280); }
function clamp(value: number): number { return Math.max(0, Math.min(1, Number(value.toFixed(3)))); }
