// @ts-nocheck
import { hashContent } from "../utils.ts";
export type ProductionAdapterKind = any; export type ProductionAdapterRuntimeMode = any; export type ProductionParserCertificationState = any; export type ProductionAdapterImplementationState = any;
export type ProductionAdapterRuntimeInput = any; export type ProductionAdapterCapabilityDto = any; export type ProductionCaptureMetadataContractDto = any; export type ProductionAdapterRuntimeProgramDto = any;

const REQUIRED = ["success", "parser_drift", "stale_dates", "language_mismatch", "unsupported_mime", "timeout", "rate_limit", "duplicate_canonical", "truncated_capture", "empty_extraction"];
const CONFIGS = [
  ["rss_feed", "rss_feed", "rss_feed", "native_public_http", "rss_feed", "rss_entry", true, false, 2_000_000, 15_000, 24, true, true],
  ["static_html", "static_html", "static_html", "native_public_http", "static_html", "static_html", true, false, 5_000_000, 15_000, 32, true, true],
  ["pdf_report", "pdf_report", "pdf_report", "native_public_http", "pdf_report", "pdf_report", true, true, 10_000_000, 20_000, 4, true, false],
  ["dynamic_public_browser", "dynamic_public_browser", "dynamic_public_browser", "disabled_dynamic_isolation", "dynamic_page", "dynamic_page", false, true, 2_000_000, 15_000, 2, true, false],
  ["public_channel_handoff", "public_channel_handoff", "public_channel_handoff", "official_public_api", "public_channel", "public_channel_handoff", true, true, 1_000_000, 15_000, 4, true, false],
  ["advisory_signal", "advisory_signal", "advisory_signal", "native_public_http", "advisory_signal", "static_html", true, false, 2_000_000, 15_000, 8, true, true],
  ["github_security_feed", "advisory_signal", "advisory_signal", "official_public_api", "github_security_advisory", "advisory_signal", true, false, 1_000_000, 15_000, 4, true, true],
  ["multilingual_handoff", "static_html", "multilingual_handoff", "metadata_handoff", "multilingual_handoff", "translation_handoff", true, true, 0, 0, 0, false, false]
];
const FAILURES = {
  rss_feed: ["not_modified", "rate_limited", "unsupported_mime", "timeout", "malformed_feed"],
  static_html: ["robots_blocked", "not_modified", "rate_limited", "unsupported_mime", "too_large", "parser_confidence_low"],
  pdf_report: ["unsupported_media", "content_too_large", "parser_confidence_low", "truncated_capture"],
  dynamic_public_browser: ["js_render_timeout", "redirect_chain", "blank_page", "screenshot_hash_mismatch", "queue_pressure"],
  public_channel_handoff: ["rate_limited", "policy_disabled", "duplicate_message", "edited_or_deleted"],
  advisory_signal: ["rate_limited", "unavailable", "unsupported_mime", "stale_dates"],
  github_security_feed: ["rate_limited", "unavailable", "api_schema_drift"],
  multilingual_handoff: ["language_detection_drift", "mixed_language", "citation_span_missing"]
};

export function buildProductionAdapterRuntimeProgram(input: ProductionAdapterRuntimeInput): ProductionAdapterRuntimeProgramDto {
  const capabilities = CONFIGS.map((config) => capability(config, input));
  const ready = capabilities.every((c) => c.implementationState !== "blocked" && c.parserCertificationState !== "disabled") && capabilities.some((c) => c.implementationState === "implemented" && c.parserCertificationState === "certified");
  const captureMetadataContractDto = captureMetadataContract();
  return { schemaVersion: "ti.production_adapter_runtime_program.v1", generatedAt: input.generatedAt, readyForApprovedPublicCollection: ready, browserWorkersEnabled: false, capabilities, captureMetadataContract: captureMetadataContractDto, fixtureMatrix: { requiredFixtures: REQUIRED, adaptersCovered: capabilities.map((c) => c.adapter), missingByAdapter: capabilities.map((c) => ({ adapter: c.adapter, missingModes: c.fixtureReplay.missingModes })).filter((x) => x.missingModes.length) }, implementationSummary: summary(capabilities), agentHandoffs: handoffSummary(capabilities), routeContract: { safeForPublicApi: true, stableFields: ["schemaVersion", "generatedAt", "readyForApprovedPublicCollection", "browserWorkersEnabled", "capabilities", "captureMetadataContract", "fixtureMatrix", "implementationSummary", "agentHandoffs", "routeContract", "safety"], forbiddenFields: captureMetadataContractDto.forbiddenFields }, safety: { ...policy(), dryRunOnly: true, unsafeUrlExposed: false } };
}

function capability(config, input) {
  const [adapter, runtimeAdapter, certificationAdapter, runtimeMode, sourceFamily, parserProfile, implemented, canaryOnly, maxBytes, timeoutMs, maxWorkers, supportsRetryAfter, supportsConditionalRequests] = config;
  const runtime = input.runtimeEnablement.readiness.find((x) => x.adapter === runtimeAdapter);
  const gate = input.certification.adapterGates.find((x) => x.adapter === certificationAdapter);
  const contract = input.slaRepair.contracts.find((x) => x.adapter === certificationAdapter);
  const triage = input.repairTriage.recommendations.filter((x) => x.adapter === certificationAdapter);
  const missingModes = modes([...(gate?.missingModes ?? [])]);
  const parserCertificationState = certState(runtime?.readiness, gate?.status, contract?.status, missingModes, canaryOnly);
  const implementationState = implState(implemented, canaryOnly, runtime?.readiness, parserCertificationState);
  const blockers = uniq([...(runtime?.blockers ?? []), ...(gate?.holdReasons ?? []), ...triage.filter((x) => x.handoffs.agent10ReleaseGate === "hold").map((x) => x.action), ...(implementationState === "blocked" ? [`${adapter}_implementation_blocked`] : [])]);
  const warnings = uniq([...(runtime?.warnings ?? []), ...(contract?.breaches.map((x) => x.code) ?? []), ...triage.filter((x) => x.handoffs.agent10ReleaseGate === "watch").map((x) => x.action)]);
  return { schemaVersion: "ti.production_adapter_capability.v1", generatedAt: input.generatedAt, adapter, runtimeMode, implementationState, sourceFamily, parserProfile, parserCertificationState, limits: { maxBytes: runtime?.workerPool.maxBytes ?? maxBytes, timeoutMs: runtime?.workerPool.timeoutMs ?? timeoutMs, maxWorkers: runtime?.workerPool.maxWorkers ?? maxWorkers, languageSupport: adapter === "github_security_feed" || adapter === "advisory_signal" ? ["en"] : ["en", "nb", "es", "ru", "zh", "fa", ...(adapter === "multilingual_handoff" ? ["mixed"] : [])] }, policy: policy(), captureOutput: { requiredFields: [...captureMetadataContract().requiredFields], canonicalUrlHashOnly: true, contentHashRequired: true, provenanceRequired: true, evidenceReplayRefRequired: true, rawRestrictedFieldsForbidden: true }, dynamicIsolation: { browserWorkersEnabled: false, screenshotHashOnly: true, explicitApprovalRequired: adapter === "dynamic_public_browser", featureFlag: "disabled_by_default" }, retryBackoff: { supportsRetryAfter, supportsConditionalRequests, failureClasses: FAILURES[adapter] }, fixtureReplay: { requiredModes: REQUIRED, coveredModes: modes(REQUIRED.filter((m) => !missingModes.includes(m))), missingModes }, blockers, warnings, handoffs: handoffs(adapter, implementationState, parserCertificationState, blockers, warnings) };
}
function certState(readiness, gate, sla, missing, canaryOnly) { return readiness === "blocked" || gate === "hold" || sla === "hold" ? "disabled" : sla === "warn" || gate === "watch" ? "parser_degraded" : missing.length ? "needs_fixture" : canaryOnly || readiness === "canary_only" ? "canary_only" : "certified"; }
function implState(implemented, canaryOnly, readiness, cert) { return cert === "disabled" || readiness === "blocked" ? "blocked" : implemented && cert === "certified" ? "implemented" : implemented || canaryOnly || cert === "canary_only" ? "canary_contract" : "contract_ready"; }
function handoffs(adapter, implementationState, cert, blockers, warnings) { const blocked = blockers.length || implementationState === "blocked" || cert === "disabled"; return { agent01Activation: blocked ? "hold_or_disable_source_activation" : implementationState === "implemented" ? "allow_approved_public_activation" : "approve_canary_only", agent02Scheduler: blocked ? "pause_adapter_pool" : warnings.length ? "canary_or_backoff_cadence" : "normal_public_cadence", agent04Coverage: blocked ? "do_not_count_as_public_coverage" : cert === "certified" ? "count_certified_public_coverage" : "count_canary_coverage_with_caveat", agent06Evidence: adapter === "dynamic_public_browser" ? "hash_only_dynamic_evidence" : blocked ? "hold_evidence_replay" : "record_capture_metadata_and_replay_ref", agent07Quality: blocked ? "hold_extraction" : cert === "parser_degraded" || cert === "needs_fixture" ? "review_parser_quality" : "accept_certified_parser", agent09Api: blocked ? "show_adapter_hold_warning" : "expose_stable_capture_metadata", agent10Release: blocked ? "release_hold" : warnings.length ? "watch" : "green" }; }
function summary(capabilities) { return { implemented: count(capabilities, "implementationState", "implemented"), contractReady: count(capabilities, "implementationState", "contract_ready"), canaryContract: count(capabilities, "implementationState", "canary_contract"), blocked: count(capabilities, "implementationState", "blocked"), certified: count(capabilities, "parserCertificationState", "certified"), canaryOnly: count(capabilities, "parserCertificationState", "canary_only"), needsFixture: count(capabilities, "parserCertificationState", "needs_fixture"), parserDegraded: count(capabilities, "parserCertificationState", "parser_degraded"), disabled: count(capabilities, "parserCertificationState", "disabled") }; }
function handoffSummary(capabilities) { return { agent01Activation: uniq(capabilities.map((c) => c.handoffs.agent01Activation)), agent02Scheduler: uniq(capabilities.map((c) => c.handoffs.agent02Scheduler)), agent04Coverage: uniq(capabilities.map((c) => c.handoffs.agent04Coverage)), agent06Evidence: uniq(capabilities.map((c) => c.handoffs.agent06Evidence)), agent07Quality: uniq(capabilities.map((c) => c.handoffs.agent07Quality)), agent09Api: uniq(capabilities.map((c) => c.handoffs.agent09Api)), agent10Release: uniq(capabilities.map((c) => c.handoffs.agent10Release)) }; }
function captureMetadataContract(): ProductionCaptureMetadataContractDto { return { schemaVersion: "ti.production_capture_metadata_contract.v1", requiredFields: ["sourceId", "canonicalUrlHash", "contentHash", "fetchedAt", "language", "parserConfidence", "extractionWarnings", "provenance", "evidenceReplayRef"], optionalFields: ["etag", "lastModified", "responseStatus", "statusClass", "retryAfterSeconds", "redirectChainHash", "contentBytes", "citationSpanCount", "linkCount", "screenshotHash", "objectRefHash", "legalNotesHash", "robotsState"], forbiddenFields: ["url", "canonicalUrl", "requestedUrl", "finalUrl", "rawText", "translatedText", "html", "body", "payload", "credential", "password", "cookie", "token", "privateInvite", "onionUrl", "screenshotBytes", "downloadUrl", "objectRef", "objectKey"], replayRefFormat: "evidence_replay_ref:<hash>", noLeakProof: { noRawUrls: true, noRawText: true, noHtml: true, noScreenshots: true, noObjectKeys: true, noCredentials: true, noPrivateInvites: true, noOnionLinks: true, noRestrictedMaterial: true } }; }
export function productionEvidenceReplayRef(input: { sourceId: string; canonicalUrlHash: string; contentHash: string; fetchedAt: string }): string { return `evidence_replay_ref:${hashContent(`${input.sourceId}:${input.canonicalUrlHash}:${input.contentHash}:${input.fetchedAt}`).slice(0, 16)}`; }
function policy() { return { publicOnly: true, robotsLegalRequired: true, restrictedMetadataOnly: true, noAuthBypass: true, noCaptchaSolving: true, noPrivateChannelJoining: true, noCredentialCollection: true, noLeakedFileDownload: true, noThreatActorInteraction: true }; }
function modes(values) { return [...new Set(values)].sort((a, b) => REQUIRED.indexOf(a) - REQUIRED.indexOf(b)); }
function uniq(values) { return [...new Set(values.filter(Boolean))].sort((a, b) => String(a).localeCompare(String(b))); }
function count(items, key, value) { return items.filter((item) => item[key] === value).length; }
