// @ts-nocheck
import { agent07ExtractionHandoff, selectParserProfile } from "./parserProfiles.ts";
import type { AdapterRunResult, CollectedItem, SourceRecord } from "../types.ts";
import { hashContent, stableId } from "../utils.ts";

export type ReportCorpusFixture = any; export type ReportCorpusBenchmarkRow = any; export type ReportCorpusBenchmarkReport = any;
export type ReportCorpusFixtureClass = "vendor_report" | "advisory" | "multilingual_report" | "malformed_pdf" | "scanned_pdf" | "unsupported_mime" | "stale_report" | "duplicate_canonical" | "restricted_policy_hold" | "dynamic_snapshot" | "rss_item";
export type ReportCorpusQueryClass = "actor" | "campaign" | "malware_tool" | "cve" | "sector" | "country" | "victim_company" | "ransomware" | "infrastructure";
const CLASSES = ["vendor_report", "advisory", "multilingual_report", "malformed_pdf", "scanned_pdf", "unsupported_mime", "stale_report", "duplicate_canonical", "restricted_policy_hold", "dynamic_snapshot", "rss_item"];
const FORBIDDEN = ["url", "canonicalUrl", "rawUrl", "unsafeUrl", "rawText", "html", "body", "payload", "objectRef", "objectKey", "screenshotBytes", "ocrVendor", "apiKey", "credential", "cookie", "token", "privateInvite", "onionUrl"];

export function runReportCorpusBenchmark(fixtures: ReportCorpusFixture[], now: string): ReportCorpusBenchmarkReport {
  const rows = fixtures.map((fixture) => row(fixture, now)), total = rows.length, count = (fn) => rows.filter(fn).length, avg = total ? rows.reduce((sum, r) => sum + r.extractionScore, 0) / total : 0;
  return { schemaVersion: "ti.report_corpus_benchmark.v1", rows, summary: { total, pass: count((r) => r.handoffQuality === "pass"), warn: count((r) => r.handoffQuality === "warn"), fail: count((r) => r.handoffQuality === "fail"), averageScore: Number(avg.toFixed(3)), ocrReady: count((r) => ["ready", "not_required"].includes(r.ocrReadiness.status)), ocrNeedsReview: count((r) => r.ocrReadiness.status === "needs_ocr"), ocrBlocked: count((r) => r.ocrReadiness.status === "blocked"), citationSpanCoverage: Number((total ? count((r) => r.citationSpanCount > 0) / total : 0).toFixed(3)), extractionReady: count((r) => r.extractionReadiness.status === "pass"), extractionWatch: count((r) => r.extractionReadiness.status === "watch"), extractionHold: count((r) => r.extractionReadiness.status === "hold"), unsupportedMedia: count((r) => r.mediaReadiness.status === "unsupported"), staleReports: count((r) => r.stalePublication), duplicateCanonicalReports: count((r) => Boolean(r.provenanceContract.duplicateCanonicalKey)), languageReview: count((r) => ["review", "missing"].includes(r.languageReadiness.status)) }, fixtureCoverage: coverage(rows), routeContract: { safeForPublicApi: true, stableFields: ["schemaVersion", "rows", "summary", "fixtureCoverage", "routeContract", "safety"], forbiddenFields: FORBIDDEN }, safety: { publicOnly: true, rawTextExposed: false, unsafeUrlExposed: false, objectKeyExposed: false, ocrVendorCoupling: false } };
}
function row(fixture: ReportCorpusFixture, now: string): ReportCorpusBenchmarkRow {
  const profile = selectParserProfile({ ...fixture.profileInput, textSample: fixture.text, language: fixture.profileInput.language ?? fixture.expectedLanguage, parserWarnings: fixture.parserWarnings, failureCategory: fixture.failureCategory ?? fixture.profileInput.failureCategory, contentLengthBytes: fixture.contentLengthBytes ?? fixture.profileInput.contentLengthBytes, maxBytes: fixture.maxBytes ?? fixture.profileInput.maxBytes });
  const collected: CollectedItem = { sourceId: fixture.source.id, taskId: `benchmark_${fixture.id}`, url: fixture.source.url, collectedAt: now, publishedAt: fixture.publishedAt, title: fixture.title, rawText: fixture.text, contentHash: hashContent(fixture.text), language: profile.languageHint, links: [], sensitive: false, metadata: { citationSpans: citations(fixture.text), parserWarnings: fixture.parserWarnings ?? [] } };
  const result: AdapterRunResult = { items: [collected], discovered: [], warnings: [], metadata: {} }, handoff = agent07ExtractionHandoff({ source: fixture.source, result, profile, failureCategory: fixture.failureCategory });
  const safeHandoff = { ...handoff, canonicalUrl: undefined, safeSummary: undefined, forbiddenFields: [...handoff.forbiddenFields, "url", "canonicalUrl", "unsafeUrl", "objectKey", "ocrVendor", "apiKey"] };
  const stale = fixture.publishedAt ? Date.parse(now) - Date.parse(fixture.publishedAt) > 180 * 86400_000 : true, fixtureClass = fixture.fixtureClass ?? inferClass(fixture, now), citeCoverage = Math.min(1, safeHandoff.citationSpans.length / (fixture.expectedCitationSpanCount ?? 1));
  const languageReadiness = lang(fixture, profile.languageHint), mediaReadiness = media(fixture), ocrReadiness = ocr(fixture, safeHandoff), extractionReadiness = extraction({ fixture, handoff: safeHandoff, stale, ocrReadiness, citeCoverage, languageReadiness, mediaReadiness });
  return { fixtureId: fixture.id, fixtureClass, parserProfile: profile.profile, extractionScore: profile.extractionScore, confidenceBand: profile.extractionConfidenceBand, languageHint: profile.languageHint, languageReadiness, citationSpanCount: safeHandoff.citationSpans.length, citationSpanCoverage: citeCoverage, warningCount: safeHandoff.parserWarnings.length, stalePublication: stale, mediaReadiness, provenanceContract: provenance(fixture, collected, now), extractionReadiness, ocrReadiness, handoffQuality: quality(safeHandoff, stale, ocrReadiness), handoff: safeHandoff };
}
function coverage(rows) { const out = Object.fromEntries(CLASSES.map((c) => [c, 0])); for (const row of rows) out[row.fixtureClass] += 1; return out; }
function citations(text: string) { return text.trim() ? [{ start: 0, end: Math.min(140, text.length), label: "benchmark_excerpt" }] : []; }
function quality(handoff, stale, ocrReadiness) { return handoff.extractionConfidenceBand === "blocked" || handoff.extractionConfidenceBand === "low" || handoff.citationSpans.length === 0 || ocrReadiness.status === "blocked" ? "fail" : ocrReadiness.status === "needs_ocr" || handoff.parserWarnings.length > 1 || stale || handoff.extractionConfidenceBand === "medium" ? "warn" : "pass"; }
function inferClass(fixture, now) { const ct = contentType(fixture); return fixture.failureCategory === "policy_hold" || fixture.profileInput.failureCategory === "policy_hold" || fixture.robotsAllowed === false ? "restricted_policy_hold" : fixture.duplicateCanonicalKey ? "duplicate_canonical" : fixture.publishedAt && Date.parse(now) - Date.parse(fixture.publishedAt) > 180 * 86400_000 ? "stale_report" : ct && !supported().has(ct) ? "unsupported_mime" : fixture.profileInput.sourceType === "pdf" && (!fixture.text.trim() || fixture.parserWarnings?.some((w) => /malformed|xref|encrypted/i.test(w))) ? "malformed_pdf" : fixture.profileInput.sourceType === "pdf" && (fixture.scannedPageCount ?? 0) > 0 ? "scanned_pdf" : fixture.expectedLanguage && fixture.expectedLanguage !== "en" ? "multilingual_report" : fixture.profileInput.sourceType === "dynamic_web" || fixture.profileInput.requiresJavascript ? "dynamic_snapshot" : fixture.profileInput.sourceType === "rss" ? "rss_item" : /cve|advisory|cert/i.test(`${fixture.title} ${fixture.text}`) ? "advisory" : "vendor_report"; }
function lang(fixture, detected) { const expected = fixture.expectedLanguage ?? fixture.profileInput.language; return !expected ? { expected, detected, status: detected ? "pass" : "missing" } : !detected ? { expected, detected, status: "missing" } : { expected, detected, status: detected === expected ? "pass" : "review" }; }
function media(fixture) { const ct = contentType(fixture), blockers = [...(ct && !supported().has(ct) ? [`unsupported_media:${ct}`] : []), ...((fixture.parserWarnings ?? []).some((w) => /malformed|xref|encrypted/i.test(w)) ? ["malformed_report_parser_warning"] : []), ...(fixture.failureCategory === "policy_hold" || fixture.profileInput.failureCategory === "policy_hold" || fixture.robotsAllowed === false ? ["policy_or_robots_hold"] : [])], status = blockers.some((b) => b.startsWith("unsupported_media")) ? "unsupported" : blockers.includes("policy_or_robots_hold") ? "policy_hold" : blockers.includes("malformed_report_parser_warning") ? "malformed" : "supported"; return { contentType: ct, supported: status === "supported", status, blockers }; }
function provenance(fixture, collected, now) { return { sourceId: fixture.source.id, taskId: collected.taskId ?? stableId("report-corpus-task", `${fixture.id}:${fixture.source.id}`), canonicalUrlHash: fixture.canonicalUrlHash ?? hashContent(fixture.source.url), contentHash: collected.contentHash, fetchedAt: now, publishedAt: fixture.publishedAt, robotsAllowed: fixture.robotsAllowed ?? true, legalNotesPresent: Boolean(fixture.legalNotes ?? fixture.source.legalNotes), duplicateCanonicalKey: fixture.duplicateCanonicalKey, collectedItemCompatible: true, preservedFields: ["sourceId", "taskId", "canonicalUrlHash", "contentHash", "fetchedAt", "publishedAt", "language", "parserConfidence", "citationSpans", "robotsAllowed", "legalNotesPresent"] }; }
function extraction(input) { const blockers = [...(["blocked", "low"].includes(input.handoff.extractionConfidenceBand) ? ["parser_confidence_not_ready"] : []), ...(input.handoff.citationSpans.length === 0 ? ["missing_citation_spans"] : []), ...(input.ocrReadiness.status === "blocked" ? input.ocrReadiness.blockers : []), ...(["unsupported", "malformed", "policy_hold"].includes(input.mediaReadiness.status) ? input.mediaReadiness.blockers : []), ...(input.fixture.duplicateCanonicalKey ? ["duplicate_canonical_report"] : [])], warnings = [...(input.stale ? ["stale_publication"] : []), ...(input.ocrReadiness.status === "needs_ocr" ? input.ocrReadiness.warnings : []), ...(input.citeCoverage < 1 && input.handoff.citationSpans.length > 0 ? ["citation_span_coverage_below_expected"] : []), ...(input.languageReadiness.status === "review" ? ["language_detection_mismatch"] : []), ...(input.languageReadiness.status === "missing" ? ["language_detection_missing"] : []), ...(input.handoff.parserWarnings.length ? ["parser_warnings_present"] : [])], status = blockers.length ? "hold" : warnings.length || input.handoff.extractionConfidenceBand === "medium" ? "watch" : "pass"; return { status, queryClasses: input.fixture.expectedQueryClasses ?? queryClasses(input.fixture), blockers, warnings, handoffs: { agent03Adapter: status === "hold" ? "block_promotion" : status === "watch" ? "repair_parser" : "certify_fixture", agent06Evidence: status === "hold" ? "hold_capture_replay" : "capture_replay_ready", agent07Quality: status === "hold" ? "block" : status === "watch" ? "review" : "accept", agent09Api: status === "hold" ? "hold_route_output" : status === "watch" ? "surface_partial" : "safe_to_surface", agent10Release: status === "hold" ? "hold" : status === "watch" ? "watch" : "green" } }; }
function queryClasses(fixture): ReportCorpusQueryClass[] { const text = `${fixture.title} ${fixture.text}`.toLowerCase(), out = []; if (/apt|actor|lazarus|sandworm|volt typhoon/.test(text)) out.push("actor"); if (/campaign|operation/.test(text)) out.push("campaign"); if (/malware|tool|ransomware|akira|lockbit/.test(text)) out.push(/ransomware|akira|lockbit/.test(text) ? "ransomware" : "malware_tool"); if (/cve-\d{4}-\d+/i.test(text)) out.push("cve"); if (/sector|energy|finance|healthcare/.test(text)) out.push("sector"); if (/country|china|russia|iran|norway/.test(text)) out.push("country"); if (/victim|company|organization/.test(text)) out.push("victim_company"); if (/infrastructure|domain|ip address|server/.test(text)) out.push("infrastructure"); return out.length ? [...new Set(out)] : ["actor"]; }
function ocr(fixture, handoff) { const pageCount = fixture.pageCount, scannedPageCount = fixture.scannedPageCount ?? 0, textLayer = fixture.text.trim().length >= 120 ? "present" : fixture.text.trim().length ? "thin" : "missing", required = contentType(fixture) === "application/pdf" && (scannedPageCount > 0 || textLayer !== "present"), ocrAvailable = fixture.ocrAvailable ?? false, conf = fixture.ocrConfidence, blockers = [...(required && !ocrAvailable && textLayer === "missing" ? ["missing_text_layer_without_ocr"] : []), ...(required && ocrAvailable && typeof conf === "number" && conf < 0.5 ? ["ocr_confidence_below_hold_threshold"] : []), ...(required && handoff.citationSpans.length < (fixture.expectedCitationSpanCount ?? 1) && textLayer === "missing" ? ["citation_spans_unavailable_for_scanned_report"] : [])], warnings = [...(required && !ocrAvailable && textLayer === "thin" ? ["thin_text_layer_needs_ocr_fixture"] : []), ...(required && ocrAvailable && typeof conf === "number" && conf < 0.7 && conf >= 0.5 ? ["ocr_confidence_below_target"] : []), ...(required && handoff.citationSpans.length < (fixture.expectedCitationSpanCount ?? 1) && textLayer !== "missing" ? ["citation_span_count_below_expected"] : [])], status = !required ? "not_required" : blockers.length ? "blocked" : warnings.length || !ocrAvailable ? "needs_ocr" : "ready"; return { required, status, textLayer, pageCount, scannedPageCount, ocrAvailable, ocrConfidence: conf, blockers, warnings, handoffs: { agent03Adapter: status === "blocked" ? "block_pdf_promotion" : status === "needs_ocr" ? "add_ocr_fixture" : "no_action", agent06Evidence: status === "blocked" ? "hold_capture_replay" : required ? "retain_ocr_metadata_only" : "retain_text_layer_metadata", agent07Quality: status === "blocked" ? "block_low_ocr_confidence" : status === "needs_ocr" ? "review_ocr" : "accept", agent10Release: status === "blocked" ? "hold" : status === "needs_ocr" ? "watch" : "green" } }; }
function contentType(fixture) { return fixture.profileInput.contentType?.split(";")[0]?.trim().toLowerCase(); }
function supported() { return new Set(["application/pdf", "text/html", "application/xhtml+xml", "text/plain", "application/rss+xml", "application/atom+xml", "application/xml", "text/xml"]); }
