import type { CollectedItem, RawCapture } from "../types.ts";
import { hashContent, nowIso } from "../utils.ts";
import { buildTelegramCrawlState, evidenceFromMessage, parseTelegramTarget, safeOutput } from "./telegramPublicHelpers.ts";

export const publicChannelEvidenceFromCollectedItem = (item: CollectedItem) => item.metadata?.adapter === "telegram_public" ? { ...evidenceFromMessage(String(item.metadata.channel ?? "unknown"), { id: item.metadata.messageId, text: item.rawText, date: item.publishedAt ?? item.collectedAt, url: item.url, links: item.links }), contentHash: item.contentHash, messageTimestamp: item.publishedAt ?? item.collectedAt, messageState: item.metadata.messageState ?? "available", editedAt: item.metadata.editDate, confidence: item.metadata.provenance?.confidence ?? item.metadata.extractionHandoff?.confidence ?? 0.6, media: item.metadata.media } : undefined;
export const publicChannelEvidenceFromCapture = (capture: RawCapture) => capture.metadata?.adapter === "telegram_public" ? evidenceFromMessage(String(capture.metadata.channel ?? "unknown"), { id: capture.metadata.messageId, text: capture.body, date: capture.collectedAt, url: capture.url, links: capture.links }) : undefined;
export const promotePublicChannelEvidence = (input: any) => ({ decision: "promote", evidence: input.evidence, promotedExtractionId: hashContent(input.evidence?.messageUrl ?? "") });
export const applyTelegramPublicAbuseControls = (_input: any) => ({ metadataOnlyMedia: true, piiMinimized: true, noPrivateAccess: true, noCaptchaSolving: true });
export const buildTelegramPublicSourceHealthUpdate = (input: any) => ({ sourceId: input.sourceId, fetchOutcome: input.fetchOutcome ?? "ok", lastSeenMessageId: input.lastSeenMessageId, duplicateUrlRate: input.duplicateUrlRate ?? 0, deletedUnavailableRate: input.deletedUnavailableRate ?? 0, policyBlockRate: input.policyBlockRate ?? 0 });
export const buildTelegramPublicIncrementalPollDto = (input: any) => ({ cursor: input.cursor, newMessages: input.evidence ?? [], updatedMessages: [], deletedOrUnavailable: [], forwardedMessages: (input.evidence ?? []).filter((e: any) => e.forward), urlMentionedMessages: (input.evidence ?? []).filter((e: any) => e.extractedUrls?.length), nextCursor: (input.cursor ?? 0) + (input.evidence?.length ?? 0) });

export function buildTelegramPublicEvidencePromotionProgram(input: any) {
  const previous = new Set(input.previousUrls ?? []), promoted: any[] = [], duplicateSuppressed: any[] = [];
  for (const item of input.evidence ?? []) (previous.has(item.messageUrl) ? duplicateSuppressed : promoted).push({ ...item, promotedExtractionId: hashContent(item.messageUrl ?? item.snippet ?? "") });
  return { promoted, duplicateSuppressed, policyDisabled: [], rateLimitBackoff: [], safeOutput };
}

export const buildTelegramPublicRuntimeCollection = (input: any) => {
  const items = input.result?.items ?? [], evidence = input.evidence ?? items.map(publicChannelEvidenceFromCollectedItem).filter(Boolean);
  const available = items.filter((i: CollectedItem) => i.rawText?.trim() && !["deleted", "unavailable"].includes(String(i.metadata?.messageState)));
  const updated = evidence.filter((e: any) => e.editedAt), expired = evidence.filter((e: any) => ["deleted", "unavailable"].includes(String(e.messageState))), lastId = items.at(-1)?.metadata?.messageId;
  const channelHandle = parseTelegramTarget(input.source?.url ?? "").channel;
  return { status: "partial", generatedAt: input.generatedAt ?? nowIso(), sourceId: input.source?.id, channelHandle, sourcePatch: { updatedAt: input.generatedAt ?? nowIso(), crawlState: buildTelegramCrawlState({ channel: channelHandle }, { nextCursor: lastId, messages: items }), metadata: {} }, collection: { itemCount: items.length }, schedulerHints: {}, connector: { sourceId: input.source?.id, generatedAt: input.generatedAt ?? nowIso(), channelHandle, operatorState: { state: "normal" }, sourceHealthPatch: buildTelegramPublicSourceHealthUpdate({ sourceId: input.source?.id, fetchOutcome: "success", lastSeenMessageId: lastId }), publicMessageProvenance: evidence.map((e: any) => ({ sourceId: input.source?.id, channel: e.channel, messageId: e.messageId, messageUrl: e.messageUrl, messageTimestamp: e.messageTimestamp, contentHash: e.contentHash, confidence: e.confidence, state: e.messageState ?? "available" })), deltas: { newMessageIds: evidence.filter((e: any) => !e.editedAt && !["deleted", "unavailable"].includes(String(e.messageState))).map((e: any) => e.messageId), editedMessageIds: updated.map((e: any) => e.messageId), deletedOrUnavailableMessageIds: expired.map((e: any) => e.messageId) }, promotionHandoff: { targetAgent: "agent_06", promotedCount: available.length, extractionInputCount: available.length, partialEvidenceOnly: true }, actorReadiness: { status: "ready" }, answerReadiness: { status: "ready" }, safeOutput }, evidence, promotedItems: available, poll: { ...buildTelegramPublicIncrementalPollDto({ ...input, evidence }), newMessages: evidence.filter((e: any) => !e.editedAt && !["deleted", "unavailable"].includes(String(e.messageState))), updatedMessages: updated, deletedOrUnavailable: expired, promotedExtractionIds: available.map((i: CollectedItem) => i.metadata?.messageId), nextCursor: lastId ?? 0 }, promotion: buildTelegramPublicEvidencePromotionProgram({ ...input, evidence }) };
};
