import "./globals.css"
import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "agent-nextjs-docker-smoke",
  description: "Dockerized Next.js starter generated by Hanasand AI",
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
