import { mapAttackTechniqueCandidates } from "../export/attack.ts";
import type { AttackTechniqueCandidate } from "../types.ts";
import { clampScore, stableId } from "../utils.ts";
import { actorAliasesFor } from "./actorAliases.ts";
import { buildActorQueryExtractionProfile, type StagedEvidenceInput } from "./intelligenceProfiles.ts";

export type AttackMappingReviewState = "accepted" | "proposed" | "review_required" | "held";
export type AttackMappingStixImpact = "eligible" | "needs_review" | "blocked";
export type AttackMappingCitationDto = any; export type AttackTechniqueQualityDto = any; export type AttackMappingQualityDto = any;
const DEPRECATED = new Set(["T1066", "T1086", "T1111"]);

export function buildAttackMappingQualityDto(input: { query: string; evidence: StagedEvidenceInput[]; generatedAt?: string }): AttackMappingQualityDto {
  const generatedAt = input.generatedAt ?? new Date().toISOString(), techniques = mergeTechniques(input.evidence.flatMap((evidence) => mapAttackTechniqueCandidates(evidence.result).map((candidate) => quality(input.query, evidence, candidate)))).slice(0, 80), holds = techniques.some((item) => ["held", "review_required"].includes(item.reviewState));
  return { schemaVersion: "ti.attack_mapping_quality.v1", query: input.query, generatedAt, summary: { candidateCount: techniques.length, acceptedCount: count(techniques, "accepted"), reviewRequiredCount: count(techniques, "review_required"), heldCount: count(techniques, "held"), mappedAttackIdCount: techniques.filter((item) => Boolean(item.attackId)).length, stixEligibleCount: techniques.filter((item) => item.stixEligibility.impact === "eligible").length }, techniques, reviewQueues: { missingTechniqueId: queue(techniques, (item) => !item.attackId), deprecatedOrRevoked: queue(techniques, (item) => item.drift.deprecatedOrRevoked), weakActorRelevance: queue(techniques, (item) => item.actorRelevance.score < 0.55), missingTimeframe: queue(techniques, (item) => item.campaignTimeframe.confidence < 0.35), contradictions: queue(techniques, (item) => item.contradictionFlags.length > 0), stixBlocked: queue(techniques, (item) => item.stixEligibility.impact === "blocked") }, releaseImpact: { publicAnswerState: techniques.length === 0 || holds ? "review_required" : techniques.some((item) => item.reviewState === "proposed") ? "partial" : "ready", holdsReadyPromotion: holds, caveats: caveats(techniques) }, safety: { rawEvidenceExposed: false, sourceUrlsExposed: false, preservesUncertainty: true } };
}

function quality(query: string, evidence: StagedEvidenceInput, candidate: AttackTechniqueCandidate): AttackTechniqueQualityDto {
  const profile = buildActorQueryExtractionProfile(query, evidence.result), citations = candidate.provenance.slice(0, 8).map((item) => ({ evidenceId: evidence.id, sourceId: item.sourceId, captureId: item.captureId, evidenceStage: evidence.stage, collectedAt: item.collectedAt, extractorVersion: item.extractorVersion })), actorRelevance = actorRelevanceFor(query, evidence), campaignTimeframe = timeframe(profile), contradictionFlags = contradictions(evidence, candidate), drift = driftFor(evidence, candidate);
  const confidence = clampScore(candidate.confidence * 0.58 + actorRelevance.score * 0.24 + campaignTimeframe.confidence * 0.12 + (citations.length ? 0.06 : 0)), reviewState = state(candidate, confidence, actorRelevance.score, campaignTimeframe.confidence, contradictionFlags, drift), stixEligibility = stix(candidate, reviewState, drift, citations);
  return { id: stableId("attack-quality", `${candidate.attackId ?? candidate.name}:${evidence.id}`), attackId: candidate.attackId, name: candidate.name, tactic: candidate.tactic, confidence, reviewState, actorRelevance, campaignTimeframe, contradictionFlags, drift, stixEligibility, evidenceIds: [evidence.id], sourceIds: [evidence.result.capture.sourceId], citations };
}
function actorRelevanceFor(query: string, evidence: StagedEvidenceInput) { const aliases = merge([query, ...actorAliasesFor(query)]).map((item) => item.toLowerCase()), actors = evidence.result.entities.filter((entity) => entity.type === "actor").flatMap((entity) => [entity.value, entity.normalizedValue, entity.rawValue, ...(entity.aliases ?? [])]).filter(Boolean), matchedActorAliases = merge(actors.filter((value) => aliases.includes(value.toLowerCase()))), score = matchedActorAliases.length ? 0.92 : actors.length ? 0.55 : 0.28; return { score, matchedActorAliases, reasons: [matchedActorAliases.length ? "technique evidence co-occurs with the queried actor or known alias" : "queried actor was not directly matched in technique evidence", ...(actors.length > 1 ? ["multiple actor names require attribution review"] : [])] }; }
function timeframe(profile: ReturnType<typeof buildActorQueryExtractionProfile>) { const t = profile.temporal, dated = Boolean(t.firstSeenAt || t.lastSeenAt || t.reportPublishedAt || t.campaignWindow?.start || t.campaignWindow?.end); return { firstSeenAt: t.firstSeenAt, lastSeenAt: t.lastSeenAt, reportPublishedAt: t.reportPublishedAt, campaignStart: t.campaignWindow?.start, campaignEnd: t.campaignWindow?.end, confidence: dated ? clampScore(0.45 + t.freshnessScore * 0.5) : 0.18, reasons: dated ? ["dated evidence is available for campaign or report timeframe"] : ["no dated campaign or report timeframe extracted"] }; }
function contradictions(evidence: StagedEvidenceInput, candidate: AttackTechniqueCandidate): string[] { const text = `${title(evidence)} ${evidence.result.capture.body ?? ""}`; return [/\b(?:conflicting reports|vendor disagreement|disputed|contradict(?:ed|ory|ion))\b/i.test(text) ? "mapping appears in contradictory reporting" : "", /\b(?:not attributed to|not linked to|false positive|misattributed)\b/i.test(text) ? "negative attribution language near technique evidence" : "", candidate.reviewReasons.some((reason) => /review|confirm/i.test(reason)) ? "candidate mapper requires analyst confirmation" : ""].filter(Boolean); }
function driftFor(evidence: StagedEvidenceInput, candidate: AttackTechniqueCandidate) { const text = `${candidate.attackId ?? ""} ${candidate.name} ${title(evidence)} ${evidence.result.capture.body ?? ""}`, deprecatedOrRevoked = Boolean(candidate.attackId && DEPRECATED.has(candidate.attackId)) || /\b(?:deprecated|revoked)\s+(?:ATT&CK|attack|technique|id)\b/i.test(text); return { deprecatedOrRevoked, replacementRequired: deprecatedOrRevoked, reasons: [...(deprecatedOrRevoked ? ["ATT&CK mapping is marked deprecated/revoked or uses a held legacy technique id"] : []), ...candidate.reviewReasons] }; }
function state(candidate: AttackTechniqueCandidate, confidence: number, actor: number, time: number, flags: string[], drift: any): AttackMappingReviewState { return drift.deprecatedOrRevoked || flags.length ? "held" : !candidate.attackId || actor < 0.55 || time < 0.35 ? "review_required" : confidence >= 0.78 ? "accepted" : "proposed"; }
function stix(candidate: AttackTechniqueCandidate, reviewState: AttackMappingReviewState, drift: any, citations: AttackMappingCitationDto[]) { const reasons = [...(!candidate.attackId ? ["missing MITRE ATT&CK external id"] : []), ...(citations.length ? [] : ["missing compact evidence citation"]), ...(drift.deprecatedOrRevoked ? ["deprecated/revoked ATT&CK ids cannot export as facts"] : []), ...(reviewState === "held" ? ["technique is held for analyst review"] : []), ...(reviewState === "review_required" ? ["technique requires analyst confirmation before STIX fact export"] : [])]; return drift.deprecatedOrRevoked || reviewState === "held" ? { impact: "blocked", reasons } : !candidate.attackId || !citations.length || reviewState === "review_required" ? { impact: "needs_review", reasons } : { impact: "eligible", reasons: ["ATT&CK id, evidence citation, and review state allow STIX export"] }; }
function mergeTechniques(items: AttackTechniqueQualityDto[]): AttackTechniqueQualityDto[] { const byKey = new Map<string, AttackTechniqueQualityDto>(); for (const item of items) { const key = item.attackId ?? item.name.toLowerCase(), existing = byKey.get(key); if (!existing) { byKey.set(key, item); continue; } existing.confidence = clampScore(Math.max(existing.confidence, item.confidence) + 0.04); existing.reviewState = rank(existing.reviewState) <= rank(item.reviewState) ? existing.reviewState : item.reviewState; existing.actorRelevance.score = Math.max(existing.actorRelevance.score, item.actorRelevance.score); existing.actorRelevance.matchedActorAliases = merge([...existing.actorRelevance.matchedActorAliases, ...item.actorRelevance.matchedActorAliases]); existing.actorRelevance.reasons = merge([...existing.actorRelevance.reasons, ...item.actorRelevance.reasons]); existing.campaignTimeframe = mergeTimes(existing.campaignTimeframe, item.campaignTimeframe); existing.contradictionFlags = merge([...existing.contradictionFlags, ...item.contradictionFlags]); existing.drift = { deprecatedOrRevoked: existing.drift.deprecatedOrRevoked || item.drift.deprecatedOrRevoked, replacementRequired: existing.drift.replacementRequired || item.drift.replacementRequired, reasons: merge([...existing.drift.reasons, ...item.drift.reasons]) }; existing.evidenceIds = merge([...existing.evidenceIds, ...item.evidenceIds]).slice(0, 12); existing.sourceIds = merge([...existing.sourceIds, ...item.sourceIds]).slice(0, 12); existing.citations = mergeCitations([...existing.citations, ...item.citations]).slice(0, 12); existing.stixEligibility = stix(existing, existing.reviewState, existing.drift, existing.citations); } return [...byKey.values()].sort((a, b) => rank(a.reviewState) - rank(b.reviewState) || b.confidence - a.confidence || a.name.localeCompare(b.name)); }
function mergeTimes(a, b) { return { firstSeenAt: pick([a.firstSeenAt, b.firstSeenAt], 1), lastSeenAt: pick([a.lastSeenAt, b.lastSeenAt], -1), reportPublishedAt: pick([a.reportPublishedAt, b.reportPublishedAt], -1), campaignStart: pick([a.campaignStart, b.campaignStart], 1), campaignEnd: pick([a.campaignEnd, b.campaignEnd], -1), confidence: Math.max(a.confidence, b.confidence), reasons: merge([...a.reasons, ...b.reasons]) }; }
function caveats(items: AttackTechniqueQualityDto[]): string[] { return [...(items.length ? [] : ["no ATT&CK/TTP mapping candidates are available"]), ...items.flatMap((item) => [item.drift.deprecatedOrRevoked ? `${item.name} is held because the ATT&CK mapping may be deprecated or revoked` : "", item.contradictionFlags.length ? `${item.name} has contradiction flags` : "", item.stixEligibility.impact !== "eligible" ? `${item.name} is not STIX-fact eligible yet` : ""])].filter(Boolean).slice(0, 12); }
function queue(items: AttackTechniqueQualityDto[], predicate: (item: AttackTechniqueQualityDto) => boolean): string[] { return items.filter(predicate).map((item) => item.id); }
function mergeCitations(items: AttackMappingCitationDto[]): AttackMappingCitationDto[] { const seen = new Set<string>(); return items.filter((item) => { const key = `${item.evidenceId}:${item.sourceId}:${item.captureId}`; if (seen.has(key)) return false; seen.add(key); return true; }); }
function merge(values: string[]): string[] { const seen = new Set<string>(), out: string[] = []; for (const value of values.map((item) => item.trim()).filter(Boolean)) { const key = value.toLowerCase(); if (!seen.has(key)) { seen.add(key); out.push(value); } } return out; }
function pick(values: Array<string | undefined>, dir: 1 | -1): string | undefined { return values.filter(Boolean).sort((a, b) => dir * (Date.parse(a!) - Date.parse(b!)))[0]; }
function rank(state: AttackMappingReviewState): number { return { held: 0, review_required: 1, proposed: 2, accepted: 3 }[state]; }
function count(items: AttackTechniqueQualityDto[], state: AttackMappingReviewState): number { return items.filter((item) => item.reviewState === state).length; }
function title(evidence: StagedEvidenceInput): string { return typeof evidence.result.capture.metadata.title === "string" ? evidence.result.capture.metadata.title : ""; }
