import type { ExtractedEntity, Indicator } from "../types.ts";
import { clampScore, normalizeWhitespace, stableId } from "../utils.ts";
import { ACTOR_ALIAS_RECORDS, actorAliasesFor } from "./actorAliases.ts";
import type { EvidenceStage, StagedEvidenceInput } from "./intelligenceProfiles.ts";

export type EntityResolutionKind = "actor_alias" | "ransomware_rebrand" | "victim_company" | "country" | "sector" | "malware_tool" | "cve" | "infrastructure";
export type EntityResolutionReviewState = "accepted" | "proposed" | "review_required" | "held";
export type EntityResolutionCorrectionAction = "accept_merge" | "split_entity" | "set_canonical" | "suppress_alias" | "request_more_evidence" | "send_to_graph_review";
export type EntityResolutionProvenanceDto = { evidenceId: string; sourceId: string; captureId: string; collectedAt: string; evidenceStage: EvidenceStage; extractorVersion?: string; confidence: number };
export type EntityResolutionCandidateDto = any; export type EntityResolutionWorkbenchDto = any; type Draft = any;
const RANSOMWARE = new Set(["akira", "lockbit", "clop", "alphv", "blackcat", "black cat", "ransomhub", "black basta", "play", "bianlian"]);
const MALWARE: Record<string, string> = { "cobalt strike": "Cobalt Strike", emotet: "Emotet", trickbot: "TrickBot", qakbot: "QakBot", plugx: "PlugX", sliver: "Sliver", carbanak: "Carbanak", mimikatz: "Mimikatz", icedid: "IcedID", rclone: "Rclone", anydesk: "AnyDesk", snake: "Snake", powgoop: "POWGOOP", wellmess: "WellMess", ngrok: "Ngrok", cloudflared: "Cloudflared", meshagent: "MeshAgent", screenconnect: "ScreenConnect", "brute ratel": "Brute Ratel", systembc: "SystemBC", darkgate: "DarkGate", lumma: "Lumma", redline: "RedLine", stealc: "Stealc", akira: "Akira", lockbit: "LockBit", alphv: "ALPHV", blackcat: "BlackCat", "black cat": "BlackCat", clop: "Clop", ransomhub: "RansomHub", "black basta": "Black Basta", play: "Play", bianlian: "BianLian" };

export function buildEntityResolutionWorkbenchDto(input: { query: string; evidence: StagedEvidenceInput[]; generatedAt?: string }): EntityResolutionWorkbenchDto {
  const drafts = new Map<string, Draft>();
  for (const evidence of input.evidence) { for (const entity of evidence.result.entities) addEntity(drafts, evidence, entity); for (const indicator of evidence.result.indicators) addIndicator(drafts, evidence, indicator); }
  const candidates = [...drafts.values()].map(finalize).sort((a, b) => reviewRank(a.reviewState) - reviewRank(b.reviewState) || b.confidence - a.confidence || a.kind.localeCompare(b.kind)).slice(0, 80);
  return { schemaVersion: "ti.entity_resolution_workbench.v1", query: input.query, generatedAt: input.generatedAt ?? new Date().toISOString(), summary: { candidateCount: candidates.length, acceptedCount: count(candidates, "accepted"), proposedCount: count(candidates, "proposed"), reviewRequiredCount: count(candidates, "review_required"), heldCount: count(candidates, "held"), sourceFamilyCount: new Set(input.evidence.map((item) => item.result.capture.sourceId)).size }, candidates, reviewQueues: { aliasCollisions: queue(candidates, /alias collision|ambiguous alias/i), weakMerges: queue(candidates, /single-source|weak|low confidence|needs corroboration/i), victimClaims: candidates.filter((c) => c.kind === "victim_company" && c.reviewState !== "accepted").map((c) => c.id), cveMentions: candidates.filter((c) => c.kind === "cve" && c.reviewState !== "accepted").map((c) => c.id), infrastructure: candidates.filter((c) => c.kind === "infrastructure" && c.reviewState !== "accepted").map((c) => c.id), graphReview: candidates.filter((c) => c.correctionActions.includes("send_to_graph_review")).map((c) => c.id) }, safety: { rawEvidenceExposed: false, restrictedPayloadsExposed: false, preservesUncertainty: true } };
}

function addEntity(drafts: Map<string, Draft>, evidence: StagedEvidenceInput, entity: ExtractedEntity): void {
  const kind = kindFor(entity); if (!kind) return; const canonicalValue = canonical(entity, kind); if (!canonicalValue) return;
  const observedValues = [entity.rawValue, entity.value, entity.normalizedValue, ...(entity.aliases ?? [])].filter(Boolean);
  addDraft(drafts, { kind, canonicalValue, observedValues, confidence: entity.confidence, reviewReasons: entity.reviewReasons ?? [], provenance: provenance(evidence, entity.provenance, entity.confidence) });
  if (kind === "actor_alias" && isRansomware(canonicalValue)) addDraft(drafts, { kind: "ransomware_rebrand", canonicalValue, observedValues: merge([...observedValues, ...actorAliasesFor(canonicalValue)]), confidence: Math.min(entity.confidence, 0.78), reviewReasons: ["ransomware actor/rebrand requires alias review before merge"], provenance: provenance(evidence, entity.provenance, entity.confidence) });
}
function addIndicator(drafts: Map<string, Draft>, evidence: StagedEvidenceInput, indicator: Indicator): void { addDraft(drafts, { kind: indicator.type === "cve" ? "cve" : "infrastructure", canonicalValue: indicator.type === "cve" ? indicator.value.toUpperCase() : normalizeIndicator(indicator), observedValues: [indicator.rawValue, indicator.value, indicator.normalizedValue].filter(Boolean), confidence: indicator.confidence, reviewReasons: indicator.reviewReasons ?? [], provenance: provenance(evidence, indicator.provenance, indicator.confidence) }); }
function addDraft(drafts: Map<string, Draft>, input: Draft): void {
  const normalizedKey = `${input.kind}:${key(input.canonicalValue)}`, existing = drafts.get(normalizedKey);
  if (!existing) { drafts.set(normalizedKey, { kind: input.kind, canonicalValue: input.canonicalValue, observedValues: merge(input.observedValues), normalizedKey, confidence: input.confidence, confidences: [input.confidence], reviewReasons: input.reviewReasons, evidenceIds: merge(input.provenance.map((p) => p.evidenceId)), sourceIds: merge(input.provenance.map((p) => p.sourceId)), provenance: input.provenance.slice(0, 12) }); return; }
  existing.observedValues = merge([...existing.observedValues, ...input.observedValues]); existing.confidences.push(input.confidence); existing.confidence = clampScore(avg(existing.confidences)); existing.reviewReasons = merge([...existing.reviewReasons, ...input.reviewReasons]); existing.evidenceIds = merge([...existing.evidenceIds, ...input.provenance.map((p) => p.evidenceId)]); existing.sourceIds = merge([...existing.sourceIds, ...input.provenance.map((p) => p.sourceId)]); existing.provenance = mergeProv([...existing.provenance, ...input.provenance]).slice(0, 12);
}
function finalize(draft: Draft): EntityResolutionCandidateDto {
  const confidence = clampScore(Math.max(...draft.confidences) * 0.7 + (draft.sourceIds.length > 1 ? 0.18 : 0) + (draft.evidenceIds.length > 1 ? 0.08 : 0));
  const uncertaintyReasons = merge([...draft.reviewReasons, ...(draft.sourceIds.length < 2 && needsCorroboration(draft.kind) ? ["single-source merge needs corroboration"] : []), ...(confidence < 0.65 ? ["low confidence normalization"] : []), ...(collision(draft) ? ["alias collision with another entity family"] : []), ...(draft.provenance.some((p) => p.evidenceStage === "metadata_only_claim") ? ["metadata-only evidence requires human review"] : [])]);
  const reviewState = stateFor(draft.kind, confidence, uncertaintyReasons);
  return { id: stableId("entity-resolution", `${draft.normalizedKey}:${draft.evidenceIds.join(":")}`), kind: draft.kind, canonicalValue: draft.canonicalValue, observedValues: draft.observedValues, normalizedKey: draft.normalizedKey, confidence, reviewState, confidenceReasons: [`${draft.provenance.length} provenance reference(s)`, `${draft.sourceIds.length} source family/families`, `${draft.evidenceIds.length} evidence item(s)`, `max extractor confidence ${Math.round(Math.max(...draft.confidences) * 100)}%`, `resolved confidence ${Math.round(confidence * 100)}%`], uncertaintyReasons, correctionActions: actions(draft.kind, reviewState, uncertaintyReasons), evidenceIds: draft.evidenceIds, sourceIds: draft.sourceIds, provenance: draft.provenance };
}
function kindFor(entity: ExtractedEntity): EntityResolutionKind | undefined { return entity.type === "actor" ? "actor_alias" : entity.type === "victim" ? "victim_company" : entity.type === "country" ? "country" : entity.type === "sector" ? "sector" : entity.type === "malware" || entity.type === "ransomware_family" ? "malware_tool" : entity.type === "cve" ? "cve" : undefined; }
function canonical(entity: ExtractedEntity, kind: EntityResolutionKind): string { return kind === "victim_company" ? normalizeCompany(entity.value) : kind === "country" || kind === "sector" ? title(entity.value) : kind === "malware_tool" ? MALWARE[entity.value.toLowerCase()] ?? title(entity.value) : kind === "cve" ? entity.value.toUpperCase() : entity.value; }
function provenance(evidence: StagedEvidenceInput, provenances: any[] | undefined, confidence: number): EntityResolutionProvenanceDto[] { const capture = evidence.result.capture, fallback = { sourceId: capture.sourceId, captureId: capture.id, collectedAt: capture.collectedAt, extractorVersion: String(capture.metadata.extractorVersion ?? "unknown") }; return (provenances?.length ? provenances : [fallback]).map((p) => ({ evidenceId: evidence.id, sourceId: p.sourceId, captureId: p.captureId, collectedAt: p.collectedAt, evidenceStage: evidence.stage, extractorVersion: p.extractorVersion, confidence })); }
function normalizeCompany(value: string): string { return normalizeWhitespace(value).replace(/[.,;:]+$/g, "").replace(/\b(ltd|llc|plc|gmbh|asa|as|inc|corp|corporation)\b\.?$/i, (suffix) => suffix.toUpperCase()).trim(); }
function normalizeIndicator(indicator: Indicator): string { return ["domain", "url", "sha1", "sha256", "md5"].includes(indicator.type) ? indicator.value.toLowerCase() : indicator.value; }
function isRansomware(value: string): boolean { return RANSOMWARE.has(value.toLowerCase()) || actorAliasesFor(value).some((alias) => RANSOMWARE.has(alias)); }
function needsCorroboration(kind: EntityResolutionKind): boolean { return ["actor_alias", "ransomware_rebrand", "victim_company", "cve", "infrastructure"].includes(kind); }
function collision(draft: Draft): boolean { const aliases = new Set(draft.observedValues.map((value) => value.toLowerCase())); return draft.kind === "malware_tool" && draft.canonicalValue.toLowerCase() === "snake" || draft.kind === "actor_alias" && ACTOR_ALIAS_RECORDS.some((record) => record.canonical !== draft.canonicalValue && record.aliases.some((alias) => aliases.has(alias))); }
function stateFor(kind: EntityResolutionKind, confidence: number, reasons: string[]): EntityResolutionReviewState { return reasons.some((r) => /metadata-only|alias collision|private or reserved/i.test(r)) ? "review_required" : kind === "infrastructure" && reasons.some((r) => /private or reserved/i.test(r)) ? "held" : confidence >= 0.82 && reasons.length === 0 ? "accepted" : confidence >= 0.72 && !reasons.some((r) => /low confidence|weak/i.test(r)) ? "proposed" : "review_required"; }
function actions(kind: EntityResolutionKind, state: EntityResolutionReviewState, reasons: string[]): EntityResolutionCorrectionAction[] { return merge([state === "accepted" ? "accept_merge" : "request_more_evidence", ...(state !== "accepted" ? ["accept_merge", "set_canonical"] : []), ...(reasons.some((r) => /alias collision|ambiguous/i.test(r)) ? ["split_entity", "suppress_alias"] : []), ...(needsCorroboration(kind) && kind !== "infrastructure" ? ["send_to_graph_review"] : [])]) as EntityResolutionCorrectionAction[]; }
function mergeProv(items: EntityResolutionProvenanceDto[]): EntityResolutionProvenanceDto[] { const seen = new Set<string>(); return items.filter((item) => { const k = `${item.evidenceId}:${item.captureId}:${item.extractorVersion}:${item.evidenceStage}`; if (seen.has(k)) return false; seen.add(k); return true; }); }
function queue(candidates: EntityResolutionCandidateDto[], pattern: RegExp): string[] { return candidates.filter((c) => c.uncertaintyReasons.some((r) => pattern.test(r))).map((c) => c.id); }
function reviewRank(state: EntityResolutionReviewState): number { return state === "review_required" ? 0 : state === "held" ? 1 : state === "proposed" ? 2 : 3; }
function title(value: string): string { return normalizeWhitespace(value).split(" ").map((part) => part.slice(0, 1).toUpperCase() + part.slice(1).toLowerCase()).join(" "); }
function key(value: string): string { return normalizeWhitespace(value).toLowerCase(); }
function avg(values: number[]): number { return values.reduce((sum, value) => sum + value, 0) / values.length; }
function count(candidates: EntityResolutionCandidateDto[], state: EntityResolutionReviewState): number { return candidates.filter((c) => c.reviewState === state).length; }
function merge(values: string[]): string[] { const seen = new Set<string>(); return values.map(normalizeWhitespace).filter((value) => value && !seen.has(value.toLowerCase()) && seen.add(value.toLowerCase())); }
