// @ts-nocheck
import { clampScore } from "../utils.ts";
import { EXTRACTOR_VERSION } from "./extractors.ts";
import type { LiveActorIntelligenceDto, PublicIntelAnswerDto } from "./actorProfileFusionTypes.ts";
import { uniq } from "./actorProfileFusionUtils.ts";

export function buildPublicIntelAnswerDto(dto: LiveActorIntelligenceDto, quality: any = {}): PublicIntelAnswerDto {
  const warnings = uniq([...(quality.publicWarningText ?? []), ...dto.readiness.downgradeReasons, ...dto.falsePositiveControls]).slice(0, 12);
  const claims = claimsFor(dto, warnings);
  const status = quality.status === "ready" && dto.readiness.overall === "fact" ? "ready" : dto.readiness.overall === "needs_review" ? "review_required" : "partial";
  const policy = { state: status, canPromote: status === "ready", publicStatus: status === "ready" ? "ready" : "partial", rules: [], caveats: [], pollableDeltas: claims.map((c) => ({ kind: "new", claimKind: c.kind, value: c.value, status: c.status, evidenceIds: c.evidenceIds, ledgerIds: c.ledgerIds, reasons: ["current public intelligence row"], pollReason: "new_evidence", nextPollAfterSeconds: 60 })) };
  const analystFusion = { queryClass: queryClass(dto), answerState: policy.state, changed: [], firstSeen: dto.recentActivity.firstSeen, lastSeen: dto.recentActivity.lastSeen, recentAttacks: recentAttacks(dto), targetSectors: dto.targets.sectors, targetRegions: dto.targets.regions, ttps: dto.ttps, datasets: dto.datasets.coverage, caveatDigest: [], confidence: { score: dto.confidence, state: policy.state, sourceFamilyCount: dto.datasets.sourceCount, ledgerBackedClaimCount: claims.filter((c) => c.ledgerIds.length).length }, contradictionHandling: { contradicted: false, holdReadyPromotion: false, reasons: [], evidenceIds: [] }, sourceBias: { missingSourceFamily: dto.datasets.sourceCount < 2, sourceFamilyCount: dto.datasets.sourceCount, reasons: dto.datasets.sourceCount < 2 ? ["single source family"] : [] }, staleEvidence: { stale: dto.recentActivity.freshnessScore < 0.2, reasons: [], evidenceIds: [] }, liveCollectionWaitingFor: [], claims: claims.map((c) => ({ ...c, provenance: dto.provenance, graphExportState: "ready", graphExportReasons: [], caveats: [] })), pollableDeltas: policy.pollableDeltas };
  const publicContract = { schemaVersion: "ti.public_answer_contract.v1", query: dto.query, queryClass: analystFusion.queryClass, state: policy.state, status: policy.publicStatus, displayState: status, noResult: claims.length === 0, safeSummary: dto.summaryBullets, confidence: analystFusion.confidence, recentAttacks: analystFusion.recentAttacks, targets: dto.targets, ttps: dto.ttps, datasets: dto.datasets.coverage, sources: { sourceCount: dto.datasets.sourceCount, evidenceStageCounts: dto.datasets.evidenceStageCounts, evidenceIds: dto.provenance.map((p) => p.evidenceId), ledgerIds: uniq(dto.provenance.flatMap((p) => p.ledgerIds)) }, caveats: [], waitReasons: [], nextPoll: { pollable: true, nextPollAfterSeconds: policy.canPromote ? 300 : 15, cursorRequired: true, deltaCount: policy.pollableDeltas.length }, evidenceLedgerReferences: claims.map((c) => ({ claimKind: c.kind, value: c.value, ledgerIds: c.ledgerIds, evidenceIds: c.evidenceIds, provenance: dto.provenance })), graphStixReadiness: { state: "ready", reasons: [], readyForDefaultExport: policy.canPromote }, deltas: policy.pollableDeltas, safeWording: { overstatesLiveSnippets: false, rawEvidenceExposed: false, restrictedPayloadsExposed: false, guidance: ["Render only metadata and cited public intelligence claims."] } };
  return { query: dto.query, actor: dto.actor, status: dto.readiness.overall, confidence: clampScore((quality.score ?? dto.confidence) * 0.4 + dto.confidence * 0.6), summary: dto.summaryBullets.slice(0, 5), aliases: dto.aliases, recentActivity: dto.recentActivity, targets: dto.targets, campaigns: dto.campaigns, victims: dto.targets.victims, ttps: dto.ttps, malwareTools: dto.malwareTools, vulnerabilities: dto.vulnerabilities, datasets: dto.datasets, timeline: timelineFor(dto), warnings, warningCodes: uniq([...(quality.publicWarningCodes ?? []), ...dto.caveats.map((c) => c.code)]), claims, reviewGates: claims.filter((c) => c.status !== "fact").map((c) => ({ claimKind: c.kind, value: c.value, state: "recommended", requiredForReady: c.status === "needs_review", requiredReviews: ["source_diversity"], evidenceIds: c.evidenceIds, ledgerIds: c.ledgerIds, reasons: c.downgradeReasons })), deltas: policy.pollableDeltas, readinessSla: { status: policy.publicStatus, confidence: dto.confidence, freshness: dto.recentActivity, evidenceFamilySupport: { sourceFamilyCount: dto.datasets.sourceCount, ledgerIds: uniq(dto.provenance.flatMap((p) => p.ledgerIds)), evidenceIds: dto.provenance.map((p) => p.evidenceId), evidenceStageCounts: dto.datasets.evidenceStageCounts }, graphState: { status: "ready", reasons: [] }, sourceSla: { status: dto.datasets.sourceCount ? "met" : "unknown", reasons: [] }, schedulerState: { status: "normal", reasons: [] }, publicChannelSla: { status: "stable", reasons: [] }, restrictedMetadataSla: { status: "compliant", reasons: [] }, explanations: [] }, promotionPolicy: policy, analystFusion, publicContract, provenanceNotes: dto.provenance.map((p) => `${p.evidenceStage} evidence ${p.evidenceId} from ${p.sourceId}`).slice(0, 12), readiness: dto.readiness };
}

function claimsFor(dto: any, downgrades: string[]) {
  const evidenceIds = dto.provenance.map((p) => p.evidenceId), ledger = uniq(dto.provenance.flatMap((p) => p.ledgerIds));
  const claim = (kind: string, value: string, field = kind) => ({ kind, value, field, status: dto.readiness.fields[field]?.status ?? dto.readiness.overall, confidence: dto.confidence, evidenceIds, ledgerIds: ledger, sourceFamilySupport: uniq(dto.provenance.map((p) => p.sourceId)), extractionVersion: EXTRACTOR_VERSION, freshness: { score: dto.recentActivity.freshnessScore, firstSeen: dto.recentActivity.firstSeen, lastSeen: dto.recentActivity.lastSeen, reportPublishedAt: dto.recentActivity.reportPublishedAt }, caveatCodes: dto.caveats.map((c) => c.code), downgradeReasons: downgrades, analystReviewState: dto.needsAnalystReview ? "recommended" : "not_required" });
  return [claim("actor", dto.actor, "summary"), ...dto.campaigns.map((v) => claim("campaign", v, "summary")), ...dto.targets.victims.map((v) => claim("victim", v, "victims")), ...dto.targets.sectors.map((v) => claim("sector", v, "sectors")), ...dto.targets.regions.map((v) => claim("region", v, "regions")), ...dto.ttps.map((v) => claim("ttp", v, "ttps")), ...dto.malwareTools.map((v) => claim("malware_tool", v, "malware_tools")), ...dto.vulnerabilities.map((v) => claim("vulnerability", v, "vulnerabilities")), ...dto.infrastructure.map((v) => claim("infrastructure", v, "infrastructure")), ...dto.datasets.coverage.map((v) => claim("dataset", v, "datasets"))].slice(0, 80);
}

const timelineFor = (dto: any) => [["First seen", dto.recentActivity.firstSeen], ["Last seen", dto.recentActivity.lastSeen], ["Report published", dto.recentActivity.reportPublishedAt]].filter((x) => x[1]).map(([label, at]) => ({ label, at, readiness: dto.readiness.fields.recent_activity.status, evidenceIds: dto.provenance.map((p) => p.evidenceId) }));
const queryClass = (dto: any) => dto.actor.toLowerCase().includes("lockbit") || dto.datasets.coverage.some((d) => d.includes("ransom")) ? "ransomware" : dto.vulnerabilities.length ? "cve" : "actor";
const recentAttacks = (dto: any) => dto.targets.victims.map((victim) => ({ victim, at: dto.recentActivity.lastSeen, sectors: dto.targets.sectors, regions: dto.targets.regions, ttps: dto.ttps, malwareTools: dto.malwareTools, vulnerabilities: dto.vulnerabilities, confidence: dto.confidence, evidenceIds: dto.provenance.map((p) => p.evidenceId), ledgerIds: uniq(dto.provenance.flatMap((p) => p.ledgerIds)) })).slice(0, 20);
