// @ts-nocheck
import { actorAliasesFor } from "./actorAliases.ts";
import { buildActorQueryExtractionProfile } from "./intelligenceProfiles.ts";
import { stableId, uniqueStrings } from "../utils.ts";

export type TimelinessQueryClass = "high_activity_actor" | "actor" | "ransomware" | "cve" | "malware_tool" | "unknown";
export type TimelinessFieldName = "recent_activity" | "source_freshness" | "victim_claims" | "ttps" | "malware_tools" | "cves" | "infrastructure";
export type TimelinessStatus = "current" | "aging" | "stale" | "unknown";
export type TimelinessFieldScoreDto = any; export type TimelinessGroundTruthHarnessDto = any;
export type ActorFreshnessCadence = "daily" | "weekly"; export type ActorFreshnessState = "current" | "aging" | "stale" | "unknown";
export type HighPriorityActorFreshnessRowDto = any; export type HighPriorityActorFreshnessDashboardDto = any;

const HOT = new Set(["apt29", "apt42", "turla", "volt typhoon", "scattered spider", "akira", "lockbit"]);
const RANSOM = new Set(["akira", "lockbit", "clop", "alphv", "blackcat", "black cat"]);
const DEFAULT_ACTORS = [["APT29", "critical", "daily", 14], ["APT42", "critical", "daily", 14], ["Sandworm", "critical", "daily", 14], ["Volt Typhoon", "critical", "daily", 14], ["Lazarus", "high", "weekly", 21], ["Turla", "high", "weekly", 21], ["LockBit", "high", "daily", 7], ["Akira", "high", "daily", 7]];
const FIELDS = ["recent_activity", "source_freshness", "victim_claims", "ttps", "malware_tools", "cves", "infrastructure"];
export function buildTimelinessGroundTruthHarnessDto(input: { query: string; evidence: any[]; generatedAt?: string }): TimelinessGroundTruthHarnessDto {
  const generatedAt = input.generatedAt ?? new Date().toISOString(), queryClass = classify(input.query), maxAge = maxAge(queryClass);
  const profiles = input.evidence.map((item) => buildActorQueryExtractionProfile(input.query, item.result).temporal);
  const latestSourceAt = latest(input.evidence.map((item) => item.result.capture.publishedAt ?? item.result.capture.collectedAt));
  const latestClaimAt = latest(profiles.flatMap((t) => [t.lastSeenAt, t.reportPublishedAt, t.incidentDate, t.firstSeenAt]));
  const latestEvidenceStage = input.evidence.find((item) => (item.result.capture.publishedAt ?? item.result.capture.collectedAt) === latestSourceAt)?.stage;
  const fields = fieldScores(input.evidence, profiles, generatedAt, maxAge);
  const gaps = gapsFor(input.evidence, fields, queryClass);
  const holds = gaps.some((g) => ["no_evidence", "no_recent_activity", "stale_latest_source", "metadata_only_latest"].includes(g.code)) || fields.some((f) => f.status === "stale" && ["recent_activity", "source_freshness"].includes(f.field));
  return { schemaVersion: "ti.timeliness_ground_truth.v1", query: input.query, queryClass, generatedAt, expectations: { maxAgeDays: maxAge, highActivityActor: queryClass === "high_activity_actor", requiresFreshSource: ["high_activity_actor", "ransomware", "cve"].includes(queryClass), staleCannotBeLatest: queryClass === "high_activity_actor" }, latest: { latestSourceAt, latestClaimAt, latestEvidenceStage, freshnessScore: freshnessScore(latestSourceAt, generatedAt, maxAge) }, fields, gaps, releaseImpact: { publicAnswerState: holds ? "partial" : fields.some((f) => ["aging", "unknown"].includes(f.status)) ? "partial" : "ready", holdsReadyPromotion: holds, caveats: caveats(gaps, fields, queryClass) }, safety: { rawEvidenceExposed: false, sourceUrlsExposed: false, preservesUncertainty: true } };
}

export function buildHighPriorityActorFreshnessDashboardDto(input: { query: string; generatedAt?: string; timelinessGroundTruth?: any; monitoredActors?: any[] }): HighPriorityActorFreshnessDashboardDto {
  const generatedAt = input.generatedAt ?? input.timelinessGroundTruth?.generatedAt ?? new Date().toISOString();
  const actors = (input.monitoredActors ?? DEFAULT_ACTORS.map(([actor, priority, cadence, targetMaxAgeDays]) => ({ actor, priority, cadence, targetMaxAgeDays }))).map((cfg) => row({ actor: cfg.actor, priority: cfg.priority ?? (cfg.cadence === "daily" ? "critical" : "high"), cadence: cfg.cadence ?? (cfg.priority === "critical" ? "daily" : "weekly"), targetMaxAgeDays: cfg.targetMaxAgeDays ?? (cfg.cadence === "daily" ? 14 : 21), generatedAt, timeliness: matches(input.query, cfg.actor) ? input.timelinessGroundTruth : undefined }));
  return { schemaVersion: "ti.high_priority_actor_freshness_dashboard.v1", query: input.query, generatedAt, actors, summary: { actorCount: actors.length, currentCount: count(actors, "overall", "current"), agingCount: count(actors, "overall", "aging"), staleCount: count(actors, "overall", "stale"), unknownCount: count(actors, "overall", "unknown"), dailyDueCount: actors.filter((r) => r.cadence.expected === "daily" && r.states.overall !== "current").length, weeklyDueCount: actors.filter((r) => r.cadence.expected === "weekly" && r.states.overall !== "current").length, readyPromotionHoldCount: actors.filter((r) => r.states.blocksReadyPromotion).length }, queues: { dailyRefresh: ids(actors, (r) => r.cadence.expected === "daily" && r.states.overall !== "current"), weeklyRefresh: ids(actors, (r) => r.cadence.expected === "weekly" && r.states.overall !== "current"), staleAnswerHolds: ids(actors, (r) => r.states.blocksReadyPromotion), missingEvidence: ids(actors, (r) => r.states.overall === "unknown"), sourceGapReview: ids(actors, (r) => r.sourceIds.length < 2 || r.states.overall === "stale") }, routing: { agent01SourceReliability: routed(actors, "agent01SourceReliability"), agent02SchedulerCadence: routed(actors, "agent02SchedulerCadence"), agent04FreshnessSourceGaps: routed(actors, "agent04SourceGap"), agent06EvidenceReplay: routed(actors, "agent06EvidenceReplay"), agent09ApiFields: routed(actors, "agent09ApiField"), agent10ReleaseGates: routed(actors, "agent10ReleaseGate") }, policy: { preservesUncertainty: true, staleCannotBeLatest: true, unknownActorSearchingOnly: true, noAutomaticPromotion: true, noAutonomousScraping: true }, safety: { rawEvidenceExposed: false, sourceUrlsExposed: false, restrictedPayloadsExposed: false, objectKeysExposed: false } };
}

function fieldScores(evidence, profiles, at, maxAge) {
  const sourceLatest = latest(evidence.map((e) => e.result.capture.publishedAt ?? e.result.capture.collectedAt));
  const claimLatest = latest(profiles.flatMap((t) => [t.lastSeenAt, t.incidentDate, t.reportPublishedAt]));
  const latestFor = (predicate) => latest(evidence.filter(predicate).map((e) => e.result.capture.publishedAt ?? e.result.capture.collectedAt));
  const byField = { recent_activity: [claimLatest, evidence, maxAge], source_freshness: [sourceLatest, evidence, maxAge], victim_claims: [latestFor((e) => hasEntity(e, "victim")), evidence.filter((e) => hasEntity(e, "victim")), maxAge], ttps: [latestFor((e) => hasEntity(e, "ttp")), evidence.filter((e) => hasEntity(e, "ttp")), maxAge * 2], malware_tools: [latestFor((e) => hasEntity(e, "malware")), evidence.filter((e) => hasEntity(e, "malware")), maxAge * 2], cves: [latestFor((e) => hasIndicator(e, "cve") || hasEntity(e, "cve")), evidence.filter((e) => hasIndicator(e, "cve") || hasEntity(e, "cve")), maxAge * 2], infrastructure: [latestFor((e) => e.result.indicators.some((i) => i.type !== "cve")), evidence.filter((e) => e.result.indicators.some((i) => i.type !== "cve")), maxAge] };
  return FIELDS.map((field) => fieldScore(field, ...byField[field], at));
}
function fieldScore(field, observedAt, evidence, expectedMaxAgeDays, generatedAt) {
  const score = freshnessScore(observedAt, generatedAt, expectedMaxAgeDays), status = !observedAt ? "unknown" : score >= 0.9 ? "current" : score >= 0.55 ? "aging" : "stale";
  return { field, status, score, latestObservedAt: observedAt, expectedMaxAgeDays, evidenceIds: evidence.map((e) => e.id).slice(0, 12), sourceIds: uniqueStrings(evidence.map((e) => e.result.capture.sourceId)).slice(0, 12), reasons: [observedAt ? `latest ${field} observation is ${ageDays(observedAt, generatedAt)} day(s) old` : `no ${field} timestamp available`, status === "stale" ? `${field} exceeds ${expectedMaxAgeDays} day freshness expectation` : ""].filter(Boolean) };
}
function gapsFor(evidence, fields, queryClass) { const gaps = [], recent = fields.find((f) => f.field === "recent_activity"), source = fields.find((f) => f.field === "source_freshness"); if (!evidence.length) gaps.push(gap("no_evidence", "No evidence is available for timeliness evaluation.")); if (recent?.status === "unknown") gaps.push(gap("no_recent_activity", "No dated recent activity was extracted.", recent)); if (source?.status === "stale") gaps.push(gap("stale_latest_source", "Latest source material is stale for this query class.", source)); for (const field of fields.filter((f) => f.status === "stale" && f.field !== "source_freshness")) gaps.push(gap("stale_field", `${field.field} is stale for this query class.`, field)); if (["high_activity_actor", "cve"].includes(queryClass) && new Set(source?.sourceIds ?? []).size === 1 && evidence.length > 1) gaps.push(gap("single_source_latest", "Latest activity depends on one source family.", source)); if (evidence.length && evidence.every((e) => e.stage === "metadata_only_claim")) gaps.push({ code: "metadata_only_latest", message: "Latest evidence is metadata-only and requires review before public ready wording.", evidenceIds: evidence.map((e) => e.id) }); return gaps; }
function row(input) { const recent = input.timeliness?.fields.find((f) => f.field === "recent_activity"), source = input.timeliness?.fields.find((f) => f.field === "source_freshness"), sourceAge = input.timeliness?.latest.latestSourceAt ? ageDays(input.timeliness.latest.latestSourceAt, input.generatedAt) : Infinity; const overall = !input.timeliness ? "unknown" : source?.status === "stale" || recent?.status === "stale" || sourceAge > input.targetMaxAgeDays * 2 ? "stale" : source?.status === "aging" || recent?.status === "aging" || sourceAge > input.targetMaxAgeDays ? "aging" : "current"; const evidenceIds = uniqueStrings([...(recent?.evidenceIds ?? []), ...(source?.evidenceIds ?? []), ...(input.timeliness?.gaps.flatMap((g) => g.evidenceIds) ?? [])]).slice(0, 12), sourceIds = uniqueStrings([...(recent?.sourceIds ?? []), ...(source?.sourceIds ?? [])]).slice(0, 12), blocks = ["stale", "unknown"].includes(overall) || input.timeliness?.releaseImpact.holdsReadyPromotion === true; return { id: stableId("high-priority-actor-freshness", `${input.actor}:${input.generatedAt}`), actor: input.actor, aliases: actorAliasesFor(input.actor).slice(0, 8), priority: input.priority, cadence: { expected: input.cadence, targetMaxAgeDays: input.targetMaxAgeDays, nextReviewDueAt: new Date((Date.parse(input.timeliness?.latest.latestSourceAt ?? input.generatedAt)) + (input.cadence === "daily" ? 1 : 7) * 86_400_000).toISOString() }, latest: { ...input.timeliness?.latest, freshnessScore: input.timeliness?.latest.freshnessScore ?? 0 }, states: { overall, recentActivity: recent?.status ?? "unknown", sourceFreshness: source?.status ?? "unknown", publicAnswerState: input.timeliness ? input.timeliness.releaseImpact.publicAnswerState : "searching", blocksReadyPromotion: blocks }, evidenceIds, sourceIds, reasons: [`${input.actor} is tracked on a ${input.cadence} freshness cadence`, Number.isFinite(sourceAge) ? `latest source material is ${sourceAge} day(s) old against ${input.targetMaxAgeDays} day target` : "no current evidence is available for this actor in the dashboard context", ...(input.timeliness?.releaseImpact.caveats ?? [])].slice(0, 10), handoffs: { agent01SourceReliability: sourceIds.length < 2 ? "review source-family support before ready wording" : undefined, agent02SchedulerCadence: overall !== "current" ? `schedule ${input.cadence} refresh for high-priority actor` : undefined, agent04SourceGap: sourceIds.length < 2 || overall === "unknown" ? "fill public source gap with approved safe sources" : undefined, agent06EvidenceReplay: evidenceIds.length ? "replay latest evidence before freshness promotion" : undefined, agent09ApiField: "highPriorityActorFreshnessDashboard", agent10ReleaseGate: blocks ? "hold ready public answer until freshness gate passes" : undefined } }; }
function caveats(gaps, fields, queryClass) { return [...(queryClass === "high_activity_actor" ? ["high-activity actor requires fresh dated evidence before latest-activity wording"] : []), ...gaps.map((g) => g.message), ...fields.filter((f) => f.status === "aging").map((f) => `${f.field} is aging; keep public answer caveated`)].slice(0, 12); }
function classify(query) { const names = new Set([query.toLowerCase(), ...actorAliasesFor(query).map((a) => a.toLowerCase())]); return /\bCVE-\d{4}-\d{4,7}\b/i.test(query) ? "cve" : [...names].some((a) => HOT.has(a)) ? "high_activity_actor" : [...names].some((a) => RANSOM.has(a)) ? "ransomware" : /\b(?:malware|tool|cobalt strike|snake|plugx|sliver)\b/i.test(query) ? "malware_tool" : /[a-z]/i.test(query) ? "actor" : "unknown"; }
function maxAge(queryClass) { return queryClass === "high_activity_actor" ? 14 : queryClass === "ransomware" ? 7 : queryClass === "cve" ? 30 : queryClass === "malware_tool" ? 45 : queryClass === "actor" ? 60 : 90; }
function freshnessScore(value, at, maxAgeDays) { if (!value) return 0; const days = ageDays(value, at); return !Number.isFinite(days) || days < 0 ? 0.5 : days <= maxAgeDays ? 1 : days <= maxAgeDays * 2 ? 0.65 : days <= maxAgeDays * 4 ? 0.35 : 0.1; }
function ageDays(value, at) { const ms = Date.parse(at) - Date.parse(value); return Number.isFinite(ms) ? Math.max(0, Math.round(ms / 86_400_000)) : Infinity; }
function latest(values) { return values.filter(Boolean).sort((a, b) => Date.parse(b) - Date.parse(a))[0]; }
function hasEntity(e, type) { return e.result.entities.some((entity) => entity.type === type); }
function hasIndicator(e, type) { return e.result.indicators.some((indicator) => indicator.type === type); }
function matches(query, actor) { const names = new Set([actor.toLowerCase(), ...actorAliasesFor(actor).map((a) => a.toLowerCase())]); return [...names].some((name) => query.toLowerCase() === name || query.toLowerCase().includes(name)); }
function gap(code, message, field) { return { code, message, field: field?.field, evidenceIds: field?.evidenceIds ?? [] }; }
function ids(rows, predicate) { return rows.filter(predicate).map((row) => row.id); }
function routed(rows, field) { return rows.filter((row) => Boolean(row.handoffs[field])).map((row) => row.id); }
function count(rows, field, value) { return rows.filter((row) => row.states[field] === value).length; }
