// @ts-nocheck
import type { SourceRecord, SourceStatus } from "../types.ts";
import { nowIso, stableId } from "../utils.ts";

export type SourceApplyPlanAction = "approve" | "activate" | "quarantine" | "restore" | "retire" | "request_legal_notes" | "leave_unchanged";
export type SourceApplyPlanAutomation = "automation_safe" | "human_approval_required" | "blocked" | "rollback_only";
export type SourceApplyPlanPrerequisite = any; export type SourceApplyPlanExpectedDiff = any; export type SourceApplyPlanItem = any; export type SourceApplyPlanExecutionResult = any; export type SourceApplyPlan = any; export type SourceApplyPlanApiRequestDto = any; export type SourceApplyPlanApiItemDto = any; export type SourceApplyPlanApiResponseDto = any; export type SourceApplyPlanApiExample = any;
const ACTIONS: SourceApplyPlanAction[] = ["approve", "activate", "quarantine", "restore", "retire", "request_legal_notes", "leave_unchanged"], AUTOMATION: SourceApplyPlanAutomation[] = ["automation_safe", "human_approval_required", "blocked", "rollback_only"];

export function buildSourceApplyPlan(input: { rehearsal: any; sources: SourceRecord[]; generatedAt?: string }): SourceApplyPlan {
  const generatedAt = input.generatedAt ?? nowIso(), byId = new Map(input.sources.map((s) => [s.id, s]));
  const evidence = input.rehearsal.governanceEvidence.flatMap((e) => e.sourceIds.map((id) => item(byId.get(id), id, actionForEvidence(e.kind, e.rollbackState.quarantineRecommended), e.reason, generatedAt)));
  const reviews = input.rehearsal.reconciliation.reviewPlans.flatMap((p) => p.sourceIds.map((id) => item(byId.get(id), id, actionForReview(p.action), p.reason, generatedAt)));
  const untouched = input.sources.filter((s) => !input.rehearsal.governanceEvidence.some((e) => e.sourceIds.includes(s.id))).map((s) => item(s, s.id, "leave_unchanged", "No source apply action recommended.", generatedAt));
  const items = dedupe([...evidence, ...reviews, ...untouched]), summary = tally(ACTIONS, items, "action"), automationSummary = tally(AUTOMATION, items, "automation");
  return { id: stableId("source_apply_plan", `${input.rehearsal.tenantId ?? "global"}:${generatedAt}:${items.map((i) => i.id).join(",")}`), generatedAt, tenantId: input.rehearsal.tenantId, dryRun: true, willMutate: false, sourceCount: input.sources.length, items, summary, automationSummary, promotionGate: { gate: "source_apply_plan_ready", ready: automationSummary.blocked === 0, unappliedChangeCount: items.filter((i) => i.action !== "leave_unchanged").length, humanApprovalRequiredCount: automationSummary.human_approval_required, blockedCount: automationSummary.blocked, willStartCrawling: false } };
}
export const executeSourceApplyPlanDryRun = (plan: SourceApplyPlan): SourceApplyPlanExecutionResult => ({ dryRun: true, executed: false, itemResults: plan.items.map((i) => ({ itemId: i.id, sourceId: i.sourceId, action: i.action, wouldApply: i.action !== "leave_unchanged" && i.automation !== "blocked", blocked: i.automation === "blocked", reason: i.automation === "blocked" ? "Apply item is blocked by policy or prerequisites." : "Dry-run only; no registry mutation executed." })) });
export function buildSourceApplyPlanApiResponse(plan: SourceApplyPlan, request: SourceApplyPlanApiRequestDto): SourceApplyPlanApiResponseDto {
  const selected = new Set(request.selectedActions ?? ACTIONS), items = plan.items.filter((i) => selected.has(i.action)).map(apiItem);
  const response = { apiVersion: "v1", endpoint: "/v1/sources/apply-plan", applyPlanId: plan.id, generatedAt: plan.generatedAt, tenantId: plan.tenantId, dryRun: true, willMutate: false, willStartCrawling: false, request: { ...request, dryRun: true }, summary: plan.summary, automationSummary: plan.automationSummary, approvalSummary: approvals(items), items, executionPreview: request.includeExecutionPreview ? executeSourceApplyPlanDryRun({ ...plan, items: plan.items.filter((i) => selected.has(i.action)) }) : undefined, promotionPacketLink: { field: "sourceApplyPlanId", value: plan.id, gate: plan.promotionGate.gate, ready: plan.promotionGate.ready, unappliedChangeCount: items.filter((i) => i.action !== "leave_unchanged").length }, schemaExamples: [] };
  return { ...response, schemaExamples: buildSourceApplyPlanApiExamples(response) };
}
export function buildSourceApplyPlanApiExamples(base: SourceApplyPlanApiResponseDto): SourceApplyPlanApiExample[] { const fallback = base.items[0] ?? exampleItem("leave_unchanged", "automation_safe"), byAction = (a) => base.items.find((i) => i.action === a) ?? fallback, byAuto = (a) => base.items.find((i) => i.automation === a) ?? fallback; return [ex("happy_path", "Dry-run preview with no mutation and no crawling.", base, byAction("leave_unchanged")), ex("human_approval_required", "Safe-public source change that requires operator approval.", base, byAuto("human_approval_required")), ex("blocked_restricted_source", "Restricted source remains blocked from automatic activation.", base, byAuto("blocked")), ex("duplicate_source", "Duplicate source is represented as an explicit retire or review action.", base, byAction("retire")), ex("stale_legal_notes", "Legal notes refresh request is exposed without applying registry changes.", base, byAction("request_legal_notes")), ex("rollback_only_quarantine", "Degraded source quarantine is rollback-only and dry-run.", base, byAuto("rollback_only"))]; }

function item(source: SourceRecord | undefined, sourceId: string, action: SourceApplyPlanAction, reason: string, generatedAt: string): SourceApplyPlanItem { const restricted = source ? isRestricted(source) : false, automation = automationFor(source, action), nextStatus = expectedStatus(source?.status, action); return { id: stableId("source_apply_item", `${sourceId}:${action}:${generatedAt}`), sourceId, sourceName: source?.name, action, automation, dryRun: true, prerequisites: prereqs(source, action), expectedRegistryDiff: diff(source, nextStatus, action, generatedAt), rollbackState: { canRollback: action !== "leave_unchanged" && source !== undefined, rollbackToStatus: source?.status, quarantineState: action === "quarantine" ? "required" : automation === "rollback_only" ? "recommended" : "none", reason: action === "leave_unchanged" ? "No rollback needed for unchanged source." : `Rollback returns source to ${source?.status ?? "unknown"} if apply is later executed.` }, policyImpact: { riskChange: restricted ? "restricted_blocked" : action === "approve" || action === "activate" ? "low_to_public" : action === "request_legal_notes" ? "approval_refresh" : action === "quarantine" || action === "retire" ? "containment" : "none", requiresLegalReview: action === "request_legal_notes" || restricted, metadataOnlyRequired: restricted }, collectionImpact: { willStartCrawling: false, enablesCollection: action === "activate" && automation !== "blocked", disablesCollection: action === "quarantine" || action === "retire", remainsDisabled: restricted ? ["restricted raw payload collection", "automatic restricted-source activation", "credentialed collection"] : ["automatic crawling during apply-plan generation", "restricted raw payload collection"] }, reason }; }
function actionForEvidence(kind: string, quarantine: boolean): SourceApplyPlanAction { return quarantine ? "quarantine" : kind === "source_pack_install" ? "approve" : kind === "activation_recommendation" ? "activate" : kind === "reconciliation_drift" ? "request_legal_notes" : "leave_unchanged"; }
function actionForReview(action: string): SourceApplyPlanAction { return action === "approve_candidates" ? "approve" : action === "quarantine_degraded_sources" ? "quarantine" : action === "restore_recovered_sources" ? "restore" : action === "retire_dead_sources" ? "retire" : action === "request_legal_notes" ? "request_legal_notes" : "leave_unchanged"; }
function automationFor(source: SourceRecord | undefined, action: SourceApplyPlanAction): SourceApplyPlanAutomation { if (!source) return action === "approve" ? "human_approval_required" : "blocked"; if (isRestricted(source) && ["approve", "activate", "restore"].includes(action)) return "blocked"; if (action === "leave_unchanged") return "automation_safe"; if (["quarantine", "retire"].includes(action)) return "rollback_only"; if (["request_legal_notes", "approve", "activate"].includes(action)) return "human_approval_required"; return action === "restore" ? source.health?.status === "healthy" ? "human_approval_required" : "blocked" : "human_approval_required"; }
function prereqs(source: SourceRecord | undefined, action: SourceApplyPlanAction): SourceApplyPlanPrerequisite[] { const exists = Boolean(source), restricted = source ? isRestricted(source) : false; return [{ code: "source_exists", satisfied: exists || action === "approve", reason: exists ? "Source exists in registry." : "Source is missing and must be created through source-pack import before mutation." }, { code: "dry_run_only", satisfied: true, reason: "Plan generation is dry-run-only and does not mutate registry state." }, { code: "not_restricted_auto_activation", satisfied: !(restricted && ["approve", "activate", "restore"].includes(action)), reason: restricted ? "Restricted sources cannot be auto-approved, activated, or restored." : "Source is not a restricted auto-activation target." }, { code: "legal_notes_present", satisfied: Boolean(source?.legalNotes.trim()) || action === "request_legal_notes" || action === "approve", reason: source?.legalNotes.trim() ? "Legal notes are present." : "Legal notes must be supplied or refreshed." }]; }
function diff(source: SourceRecord | undefined, next: SourceStatus | undefined, action: SourceApplyPlanAction, at: string): SourceApplyPlanExpectedDiff[] { if (!source || action === "leave_unchanged") return []; return [[next && next !== source.status, { field: "status", before: source.status, after: next }], [action === "approve", { field: "governance.approvalState", before: source.governance?.approvalState, after: "approved" }], [action === "request_legal_notes", { field: "metadata.legalNotesRequestedAt", before: source.metadata?.legalNotesRequestedAt, after: at }], [action === "quarantine", { field: "catalog.rollback.lastQuarantineReason", before: source.catalog?.rollback?.lastQuarantineReason, after: "source apply plan quarantine" }]].filter(([ok]) => ok).map(([, d]) => d); }
function expectedStatus(status: SourceStatus | undefined, action: SourceApplyPlanAction): SourceStatus | undefined { return !status ? undefined : action === "approve" ? "approved" : action === "activate" ? "active" : action === "quarantine" ? "quarantined" : action === "restore" ? "probation" : action === "retire" ? "retired" : status; }
function dedupe(items: SourceApplyPlanItem[]) { const rank = { quarantine: 7, retire: 6, request_legal_notes: 5, approve: 4, activate: 3, restore: 2, leave_unchanged: 1 }, bySource = new Map(); for (const item of items) if (!bySource.get(item.sourceId) || rank[item.action] > rank[bySource.get(item.sourceId).action]) bySource.set(item.sourceId, item); return [...bySource.values()].sort((a, b) => a.sourceId.localeCompare(b.sourceId)); }
function isRestricted(source: SourceRecord) { return ["restricted", "high"].includes(source.risk) || ["tor_metadata", "i2p_metadata", "freenet_metadata"].includes(source.type) || source.catalog?.approvalScope === "restricted_protocol"; }
function apiItem(item: SourceApplyPlanItem): SourceApplyPlanApiItemDto { return { itemId: item.id, sourceId: item.sourceId, sourceName: item.sourceName, action: item.action, automation: item.automation, approvalRequired: item.automation === "human_approval_required" || item.policyImpact.requiresLegalReview, blocked: item.automation === "blocked", prerequisiteFailures: item.prerequisites.filter((p) => !p.satisfied).map((p) => p.code), expectedDiffCount: item.expectedRegistryDiff.length, policyImpact: item.policyImpact, collectionImpact: item.collectionImpact, rollback: item.rollbackState, reason: item.reason }; }
function approvals(items: SourceApplyPlanApiItemDto[]) { return { approvalsRequired: items.filter((i) => i.approvalRequired).length, legalReviewRequired: items.filter((i) => i.policyImpact.requiresLegalReview).length, blocked: items.filter((i) => i.blocked).length, rollbackOnly: items.filter((i) => i.automation === "rollback_only").length }; }
function ex(name, description, base, exampleItemValue) { return { name, description, request: base.request, response: { apiVersion: base.apiVersion, endpoint: base.endpoint, dryRun: true, willMutate: false, willStartCrawling: false, approvalSummary: base.approvalSummary, promotionPacketLink: base.promotionPacketLink, exampleItem: exampleItemValue } }; }
function exampleItem(action: SourceApplyPlanAction, automation: SourceApplyPlanAutomation): SourceApplyPlanApiItemDto { return { itemId: `example_${action}`, sourceId: `example_${action}`, action, automation, approvalRequired: automation === "human_approval_required", blocked: automation === "blocked", prerequisiteFailures: automation === "blocked" ? ["not_restricted_auto_activation"] : [], expectedDiffCount: action === "leave_unchanged" ? 0 : 1, policyImpact: { riskChange: automation === "blocked" ? "restricted_blocked" : "none", requiresLegalReview: automation === "blocked", metadataOnlyRequired: automation === "blocked" }, collectionImpact: { willStartCrawling: false, enablesCollection: false, disablesCollection: ["quarantine", "retire"].includes(action), remainsDisabled: ["automatic crawling during apply-plan generation", "restricted raw payload collection"] }, rollback: { canRollback: action !== "leave_unchanged", quarantineState: action === "quarantine" ? "required" : "none", reason: "Schema example only; no mutation." }, reason: "Schema example item." }; }
function tally(keys: string[], rows: any[], field: string) { return Object.fromEntries(keys.map((key) => [key, rows.filter((row) => row[field] === key).length])); }
