// @ts-nocheck
import type { SourceCrawlState, SourceGovernance, SourceHealth, SourceLifecycleEvent, SourceLifecycleReason, SourceRecord, SourceReviewDecision, SourceScoringInputs, SourceStatus } from "../types.ts";
import { clampScore, nowIso, stableId } from "../utils.ts";

const ACTIVE = new Set(["active", "probation", "degraded"]), TERMINAL = new Set(["retired", "rejected"]), REVIEWED = new Set(["approved", "active", "probation", "degraded"]);
const HIGH_RISK = new Set(["tor_metadata", "i2p_metadata", "freenet_metadata"]), HTTP = new Set(["rss", "static_web", "dynamic_web", "api", "pdf"]);
export interface SourceRegistry { list(): SourceRecord[]; get(id: string): SourceRecord | undefined; upsert(input: Omit<SourceRecord, "id" | "createdAt" | "updatedAt"> & { id?: string }): SourceRecord; ingestSeedSources(inputs: Array<Omit<SourceRecord, "id" | "createdAt" | "updatedAt"> & { id?: string }>): SourceRecord[]; setStatus(id: string, status: SourceStatus, options?: LifecycleTransitionOptions): SourceRecord; approve(id: string, actorId: string, options?: ApprovalOptions): SourceRecord; applyReviewDecision(decision: SourceReviewDecision): SourceRecord; recordHealth(id: string, health: Partial<SourceHealth>): SourceRecord; }
export interface LifecycleTransitionOptions { actorId?: string; reason?: SourceLifecycleReason; note?: string; }
export interface ApprovalOptions { approvedAt?: string; expiresAt?: string; reviewTicket?: string; riskJustification?: string; legalContact?: string; activate?: boolean; }

export class InMemorySourceRegistry implements SourceRegistry {
  private readonly sources = new Map<string, SourceRecord>();
  list() { return [...this.sources.values()].sort((a, b) => a.name.localeCompare(b.name)); }
  get(id: string) { return this.sources.get(id); }
  upsert(input: Omit<SourceRecord, "id" | "createdAt" | "updatedAt"> & { id?: string }) { const now = nowIso(), id = input.id ?? stableId("src", `${input.type}:${input.url}`), prev = this.sources.get(id); return this.put(id, norm({ ...input, id, trustScore: clampScore(input.trustScore), createdAt: prev?.createdAt ?? now, updatedAt: now } as SourceRecord, prev, now)); }
  ingestSeedSources(inputs: Array<Omit<SourceRecord, "id" | "createdAt" | "updatedAt"> & { id?: string }>) { const seen = new Set<string>(); return inputs.map((input) => { const key = `${input.tenantId ?? "global"}:${input.type}:${input.url}`; if (seen.has(key)) throw new Error(`Duplicate seed source: ${key}`); seen.add(key); return this.upsert({ ...input, status: input.status ?? "candidate" }); }); }
  setStatus(id: string, status: SourceStatus, options: LifecycleTransitionOptions = {}) { const source = need(this.sources, id), now = nowIso(), next = norm({ ...source, status, updatedAt: now, lifecycle: [...(source.lifecycle ?? []), event(source.status, status, now, options)] }, source, now); lifecycle(source, next); return this.put(id, next); }
  approve(id: string, actorId: string, options: ApprovalOptions = {}) { const source = need(this.sources, id), at = options.approvedAt ?? nowIso(), status = options.activate ? "active" : "approved", governance = { ...source.governance, approvalRequired: requiresApproval(source), approvalState: "approved", metadataOnly: requiresMetadataOnly(source), approvedAt: at, approvedBy: actorId, approvalExpiresAt: options.expiresAt ?? source.governance?.approvalExpiresAt, reviewTicket: options.reviewTicket ?? source.governance?.reviewTicket, policyVersion: source.governance?.policyVersion ?? "collection-policy:v1", riskJustification: options.riskJustification ?? source.governance?.riskJustification, legalContact: options.legalContact ?? source.governance?.legalContact }; return this.put(id, norm({ ...source, governance, approvalRequired: governance.approvalRequired, approvedAt: at, approvedBy: actorId, status, updatedAt: at, lifecycle: [...(source.lifecycle ?? []), event(source.status, status, at, { actorId, reason: "policy_review", note: options.reviewTicket })] }, source, at)); }
  applyReviewDecision(decision: SourceReviewDecision) { const source = need(this.sources, decision.sourceId), next = applySourceReviewDecision(source, decision); lifecycle(source, next); return this.put(next.id, next); }
  recordHealth(id: string, health: Partial<SourceHealth>) { const source = need(this.sources, id), now = nowIso(), nextHealth = { ...defaultHealth(), ...source.health, ...health, checkedAt: health.checkedAt ?? now, errorRate: clampScore(health.errorRate ?? source.health?.errorRate ?? 0), consecutiveFailures: Math.max(0, health.consecutiveFailures ?? source.health?.consecutiveFailures ?? 0) }, change = statusFromHealth(source, nextHealth), next = norm({ ...source, status: change.status, health: nextHealth, updatedAt: now, lifecycle: change.status === source.status ? source.lifecycle : [...(source.lifecycle ?? []), event(source.status, change.status, now, { reason: "health_check", note: change.note })] }, source, now); lifecycle(source, next); return this.put(id, next); }
  private put(id: string, source: SourceRecord) { validateSource(source); this.sources.set(id, source); return source; }
}

export function validateSource(source: SourceRecord) { if (!source.name.trim()) throw new Error("Source name is required"); if (!source.url.trim()) throw new Error("Source URL is required"); validateUrl(source); if (!source.legalNotes.trim() || source.legalNotes.trim().length < 12) throw new Error(source.legalNotes.trim() ? "Source legal notes must describe collection basis" : "Source legal notes are required"); if (source.crawlFrequencySeconds < 60) throw new Error("Source crawl frequency must be at least 60 seconds"); if (source.trustScore < 0 || source.trustScore > 1) throw new Error("Source trust score must be between 0 and 1"); if (source.accessMethod === "disabled" && ACTIVE.has(source.status)) throw new Error("Disabled access method cannot be active"); if (source.risk === "low" && source.accessMethod === "approved_proxy") throw new Error("Approved proxy access cannot be low risk"); if (HIGH_RISK.has(source.type) && source.accessMethod !== "approved_proxy" && source.accessMethod !== "disabled") throw new Error("Darknet metadata sources require approved proxy or disabled access"); if (HIGH_RISK.has(source.type) && !source.governance?.metadataOnly) throw new Error("Darknet metadata sources must be metadata-only"); if (source.risk === "restricted" && source.status === "active") throw new Error("Restricted sources cannot become active through registry automation"); if (requiresApproval(source) && REVIEWED.has(source.status)) approval(source); scoring(source.scoring); health(source.health); crawl(source.crawlState); }
export const sourceLifecycleEvent = (to: SourceStatus, options: LifecycleTransitionOptions = {}, from?: SourceStatus): SourceLifecycleEvent => event(from, to, nowIso(), options);
export const requiresApproval = (source: Pick<SourceRecord, "risk" | "type">) => source.risk !== "low" || HIGH_RISK.has(source.type);
export const requiresMetadataOnly = (source: Pick<SourceRecord, "type">) => HIGH_RISK.has(source.type);
export const effectiveSourceScore = (source: SourceRecord) => !source.scoring ? clampScore(source.trustScore) : clampScore(0.35 * source.scoring.reliability + 0.2 * source.scoring.freshness + 0.2 * source.scoring.relevance + 0.15 * source.scoring.uniqueness + 0.1 * source.scoring.parseability + source.scoring.operatorBoost - source.scoring.policyRiskPenalty - (source.health?.status === "failing" ? 0.25 : source.health?.status === "degraded" ? 0.1 : 0));
export function applySourceReviewDecision(source: SourceRecord, decision: SourceReviewDecision) { if (decision.sourceId !== source.id) throw new Error("Review decision source id mismatch"); if (!decision.decidedBy.trim()) throw new Error("Review decision requires decidedBy"); if (!decision.reason.trim()) throw new Error("Review decision requires reason"); const gov = { ...governance(source, requiresApproval(source)), approvalRequired: requiresApproval(source), metadataOnly: decision.metadataOnly ?? governance(source, requiresApproval(source)).metadataOnly, reviewTicket: decision.reviewTicket ?? governance(source, requiresApproval(source)).reviewTicket, policyVersion: decision.policyVersion ?? governance(source, requiresApproval(source)).policyVersion ?? "collection-policy:v1", riskJustification: decision.riskJustification ?? governance(source, requiresApproval(source)).riskJustification, legalContact: decision.legalContact ?? governance(source, requiresApproval(source)).legalContact }; let status = source.status; if (decision.action === "approve") Object.assign(gov, { approvalState: "approved", approvedAt: decision.decidedAt, approvedBy: decision.decidedBy, approvalExpiresAt: decision.approvalExpiresAt }), status = "approved"; else if (decision.action === "reject") gov.approvalState = "rejected", status = "rejected"; else if (decision.action === "expire") gov.approvalState = "expired", gov.approvalExpiresAt = decision.approvalExpiresAt ?? decision.decidedAt, status = ACTIVE.has(source.status) ? "needs_review" : source.status; else if (decision.action === "quarantine") status = "quarantined"; else if (decision.action === "restore") { if (source.health && !["healthy", "unknown"].includes(source.health.status)) throw new Error("Source health must recover before restore"); status = decision.restoreStatus ?? (requiresApproval(source) ? "needs_review" : "active"); } const next = norm({ ...source, status, governance: gov, approvalRequired: gov.approvalRequired, approvedAt: gov.approvedAt, approvedBy: gov.approvedBy, updatedAt: decision.decidedAt, lifecycle: [...(source.lifecycle ?? []), event(source.status, status, decision.decidedAt, { actorId: decision.decidedBy, reason: decision.action === "quarantine" ? "health_check" : "policy_review", note: `${decision.action}: ${decision.reason}` })] }, source, decision.decidedAt); return decision.action === "approve" && decision.restoreStatus === "active" ? { ...next, status: "active" } : next; }

function norm(source: SourceRecord, prev: SourceRecord | undefined, now: string): SourceRecord { const approvalRequired = source.approvalRequired ?? source.governance?.approvalRequired ?? requiresApproval(source), gov = governance(source, approvalRequired); return { ...source, approvalRequired, approvedAt: source.approvedAt ?? gov.approvedAt, approvedBy: source.approvedBy ?? gov.approvedBy, governance: gov, health: source.health ? normHealth(source.health) : prev?.health, scoring: source.scoring ? normScoring(source.scoring) : prev?.scoring ?? defaultScoring(source.trustScore, approvalRequired), crawlState: source.crawlState ? { ...source.crawlState, retryCount: Math.max(0, source.crawlState.retryCount) } : prev?.crawlState ?? { retryCount: 0 }, lifecycle: source.lifecycle?.length ? source.lifecycle : prev?.lifecycle ?? [event(undefined, source.status, now, { reason: "seeded" })], tags: source.tags?.map((tag) => tag.trim()).filter(Boolean) }; }
function governance(source: SourceRecord, approvalRequired: boolean): SourceGovernance { return { approvalRequired, approvalState: source.governance?.approvalState ?? (approvalRequired ? "pending" : "not_required"), metadataOnly: source.governance?.metadataOnly ?? requiresMetadataOnly(source), approvedAt: source.governance?.approvedAt ?? source.approvedAt, approvedBy: source.governance?.approvedBy ?? source.approvedBy, approvalExpiresAt: source.governance?.approvalExpiresAt, reviewTicket: source.governance?.reviewTicket, policyVersion: source.governance?.policyVersion ?? "collection-policy:v1", riskJustification: source.governance?.riskJustification, legalContact: source.governance?.legalContact }; }
function normHealth(h: SourceHealth) { return { ...h, consecutiveFailures: Math.max(0, h.consecutiveFailures), errorRate: clampScore(h.errorRate) }; }
function normScoring(s: SourceScoringInputs) { return { reliability: clampScore(s.reliability), freshness: clampScore(s.freshness), relevance: clampScore(s.relevance), uniqueness: clampScore(s.uniqueness), parseability: clampScore(s.parseability), policyRiskPenalty: clampScore(s.policyRiskPenalty), operatorBoost: clampScore(s.operatorBoost) }; }
function defaultHealth(): SourceHealth { return { status: "unknown", consecutiveFailures: 0, errorRate: 0 }; }
function defaultScoring(trustScore: number, approvalRequired: boolean): SourceScoringInputs { return { reliability: clampScore(trustScore), freshness: 0.5, relevance: 0.5, uniqueness: 0.5, parseability: 0.5, policyRiskPenalty: approvalRequired ? 0.15 : 0, operatorBoost: 0 }; }
function event(from: SourceStatus | undefined, to: SourceStatus, at: string, options: LifecycleTransitionOptions): SourceLifecycleEvent { return { at, from, to, reason: options.reason ?? "operator_request", actorId: options.actorId, note: options.note }; }
function lifecycle(previous: SourceRecord, next: SourceRecord) { if (previous.status === next.status) return; if (TERMINAL.has(previous.status)) throw new Error(`Cannot transition source from terminal status ${previous.status}`); if (next.status === "active" && requiresApproval(next) && next.governance?.approvalState !== "approved") throw new Error("Source approval is required before activation"); if (next.status === "approved" && next.governance?.approvalState !== "approved") throw new Error("Source must have approved governance before approved status"); }
function approval(source: SourceRecord) { const gov = source.governance; if (!gov) throw new Error("Source governance is required"); if (gov.approvalState !== "approved") throw new Error("Source approval is required"); if (!gov.approvedAt || !gov.approvedBy) throw new Error("Source approval must include approver and timestamp"); if ((source.risk === "high" || source.risk === "restricted") && !gov.riskJustification?.trim()) throw new Error("High-risk source approval requires risk justification"); if (gov.approvalExpiresAt && Date.parse(gov.approvalExpiresAt) <= Date.now()) throw new Error("Source approval has expired"); }
function validateUrl(source: SourceRecord) { if (source.accessMethod === "manual_seed") return; if (source.type === "telegram_public") { if (!source.url.startsWith("https://t.me/") && !source.url.startsWith("tg://")) throw new Error("Telegram sources must use https://t.me/ or tg:// URLs"); return; } if (source.accessMethod === "approved_proxy" && HIGH_RISK.has(source.type)) return; if (HTTP.has(source.type) || source.accessMethod === "public_http" || source.accessMethod === "official_api") { try { const url = new URL(source.url); if (!["http:", "https:"].includes(url.protocol)) throw new Error("Source URL must be HTTP(S)"); } catch { throw new Error("Source URL must be a valid URL"); } } }
function scoring(s: SourceScoringInputs | undefined) { if (!s) return; for (const [key, value] of Object.entries(s)) if (value < 0 || value > 1) throw new Error(`Source scoring ${key} must be between 0 and 1`); }
function health(h: SourceHealth | undefined) { if (!h) return; if (h.consecutiveFailures < 0) throw new Error("Source health failures cannot be negative"); if (h.errorRate < 0 || h.errorRate > 1) throw new Error("Source health error rate must be between 0 and 1"); }
function crawl(c: SourceCrawlState | undefined) { if (c && c.retryCount < 0) throw new Error("Source crawl retry count cannot be negative"); }
function statusFromHealth(source: SourceRecord, h: SourceHealth) { if (h.status === "failing" && h.consecutiveFailures >= 5) return { status: "quarantined", note: `quarantined after ${h.consecutiveFailures} consecutive failures` }; if (source.status === "quarantined" && h.status === "healthy" && h.consecutiveFailures === 0) return { status: "probation", note: "restored to probation after health recovered" }; if (source.status === "active" && h.status === "degraded") return { status: "degraded", note: "source health degraded" }; if (source.status === "degraded" && h.status === "healthy" && h.consecutiveFailures === 0) return { status: "active", note: "source health recovered" }; return { status: source.status }; }
function need(sources: Map<string, SourceRecord>, id: string) { const source = sources.get(id); if (!source) throw new Error(`Unknown source: ${id}`); return source; }
