export type EvidenceSearchReadModelBackend = "embedded_memory" | "postgres_read_model" | "opensearch_pgvector";
export type EvidenceSearchReadModelConfig = any; export type EvidenceSearchReadModelRecord = any; export type EvidenceSearchReadModelQuery = any;
export type EvidenceSearchReadModelSearchResult = any; export type EvidenceSearchReadModelWriteResult = any; export type EvidenceSearchReadModelDeleteResult = any;
export type EvidenceSearchReadModelStats = any; export type EvidenceSearchReadModelReadiness = any; export type EvidenceSearchReadModelSafety = any;
export type EvidenceSearchReadModelPostgresDocumentRow = any; export type EvidenceSearchReadModelTombstoneRow = any; export type EvidenceSearchOpenSearchDocument = any;
export type EvidenceSearchPgvectorCandidateRow = any; export type EvidenceSearchReadModelBackendWriteSet = any; export type EvidenceSearchableSourceMetadataCatalog = any;
export type EvidenceSearchableSourceMetadataCatalogRow = any; export type EvidenceSearchableSourceMetadataPublicSupportQueue = any; export type EvidenceSearchableSourceMetadataPublicSupportCandidate = any;
export type EvidenceSearchableSourceMetadataPublicSupportPostgresRows = any; export type EvidenceSearchableSourceMetadataPublicSupportQueueRunRow = any; export type EvidenceSearchableSourceMetadataPublicSupportCandidateRow = any;
export type EvidenceSearchableSourceMetadataPublicSupportRepositoryStatus = any; export type EvidenceSearchableSourceMetadataPublicSupportRepository = any;
export type EvidenceSearchableSourceMetadataPromotionGate = any; export type EvidenceSearchableSourceMetadataPromotionGateRow = any; export type EvidenceSearchableSourceMetadataPromotionGatePostgresRows = any;
export type EvidenceSearchableSourceMetadataPromotionGateRunRow = any; export type EvidenceSearchableSourceMetadataPromotionGateDecisionRow = any; export type EvidenceSearchableSourceMetadataPromotionGateRepositoryStatus = any;
export type EvidenceSearchableSourceMetadataPromotionGateRepository = any; export type EvidenceSearchableSourceMetadataPromotionConsumerReplay = any;
export type EvidenceSearchableSourceMetadataPromotionConsumerReplayReceipt = any; export type EvidenceSearchableSourceMetadataPublicSupportReplayReceiptLedger = any;
export type EvidenceSearchableSourceMetadataPublicSupportReplayReceipt = any; export type EvidenceSearchableSourceMetadataPublicSupportReplayReceiptPostgresRows = any;
export type EvidenceSearchableSourceMetadataPublicSupportReplayRunRow = any; export type EvidenceSearchableSourceMetadataPublicSupportReplayReceiptRow = any;
export type EvidenceSearchableSourceMetadataPublicSupportReplayReceiptRepositoryStatus = any; export type EvidenceSearchableSourceMetadataPublicSupportReplayReceiptRepository = any;
export type EvidenceSearchReadModelPromotionReplay = any; export type EvidencePromotionTransactionPlan = any; export type EvidencePromotionConsumerPlan = any;
export type EvidencePromotionTransactionExecutionConfig = any; export type EvidencePromotionTransactionExecutionReceipt = any; export type EvidencePromotionTransactionExecutionPostgresRows = any;
export type EvidencePromotionExecutionReceiptRow = any; export type EvidencePromotionExecutionStepRow = any; export type EvidencePromotionExecutionHeldStepRow = any;
export type EvidencePromotionExecutionRollbackRow = any; export type EvidencePromotionTransactionAuditReplay = any; export type EvidenceActorProductImpactReplay = any;
export type EvidenceActorProductImpactRow = any; export type EvidenceActorDatasetPromotionPreview = any; export type EvidenceActorDatasetSourceGapSuppressionFeedback = any;
export type EvidenceActorDatasetSourceGapConsumerQueue = any; export type EvidenceActorDatasetSourceGapConsumerQueueRow = any; export type EvidenceActorDatasetSourceGapConsumerQueuePostgresRows = any;
export type EvidenceActorDatasetSourceGapConsumerQueueRunRow = any; export type EvidenceActorDatasetSourceGapConsumerQueueItemRow = any; export type EvidenceActorDatasetSourceGapConsumerQueueAuditRepositoryStatus = any;
export type EvidenceActorDatasetSourceGapConsumerQueueAuditRepository = any; export type EvidenceActorDatasetSourceGapRepairHandoff = any; export type EvidenceActorDatasetSourceGapRepairPacket = any;
export type EvidenceActorDatasetSourceGapRepairReplayLedger = any; export type EvidenceActorDatasetSourceGapRepairReplayCheckpoint = any; export type EvidenceActorDatasetSourceGapRepairReplayPostgresRows = any;
export type EvidenceActorDatasetSourceGapRepairReplayLedgerRunRow = any; export type EvidenceActorDatasetSourceGapRepairReplayCheckpointRow = any; export type EvidenceActorDatasetSourceGapRepairReplayRepositoryStatus = any;
export type EvidenceActorDatasetSourceGapRepairReplayRepository = any; export type EvidenceActorDatasetPromotionRow = any; export type EvidenceActorDatasetConsumerHandoff = any;
export type EvidenceActorDatasetConsumerExecutionReceipt = any; export type EvidenceActorDatasetConsumerExecutionPostgresRows = any; export type EvidenceActorDatasetConsumerExecutionReceiptRow = any;
export type EvidenceActorDatasetConsumerActorDatasetReceiptRow = any; export type EvidenceActorDatasetConsumerPublicAnswerCacheReceiptRow = any; export type EvidenceActorDatasetConsumerAuditReplay = any;
export type EvidenceActorDatasetConsumerAuditRepositoryStatus = any; export type EvidenceActorDatasetConsumerAuditRepository = any; export type EvidenceActorDatasetConsumerRow = any;
export type EvidenceActorPublicAnswerCacheWrite = any; export type EvidenceSearchReadModelRepository = any;
