import type { CaptureReplayJob, DiscoveryEvidence, EvidenceCaptureCounts, EvidenceDelta, EvidenceDedupeGroup, EvidenceExtractorVersionSummary, EvidenceProvenanceChain, EvidenceQueryHelpers, EvidenceQueryScope, EvidenceRedactionSummary, IncidentCandidate, LiveSearchEvidenceView, LiveSearchSnapshot, RawCapture, SourceFreshnessSummary } from "../types.ts";

export interface EvidenceQueryData { captures: RawCapture[]; incidents: IncidentCandidate[]; replayJobs: CaptureReplayJob[]; discoveryEvidence: DiscoveryEvidence[]; liveSearchSnapshots: LiveSearchSnapshot[]; evidenceDeltas: EvidenceDelta[]; }

export class InMemoryEvidenceQueries implements EvidenceQueryHelpers {
  constructor(private readonly data: () => EvidenceQueryData) {}
  latestCaptures(scope: EvidenceQueryScope): RawCapture[] { return limit(this.captures(scope), scope.limit).sort(desc("collectedAt")); }
  provenanceForClaim(scope: EvidenceQueryScope): EvidenceProvenanceChain[] { const captures = new Map(this.captures(scope).map((c) => [c.id, c])); const chains = this.incidents(scope).filter((i) => (!scope.captureId || i.captureId === scope.captureId) && (!scope.claimId || i.id === scope.claimId) && matchesActor(i, scope.actor)).flatMap((i) => chainFor(i, captures.get(i.captureId ?? ""))); return limit(chains.sort(desc("collectedAt")), scope.limit); }
  provenanceChainByResultId(resultId: string, scope: EvidenceQueryScope = {}): EvidenceProvenanceChain[] { const d = this.discovery(scope).find((item) => item.resultId === resultId || item.id === resultId); if (d?.promotedToIncidentId) return this.provenanceForClaim({ ...scope, claimId: d.promotedToIncidentId }); if (d?.promotedToCaptureId) return this.provenanceForClaim({ ...scope, captureId: d.promotedToCaptureId }); return d ? [discoveryChain(d)] : this.provenanceForClaim({ ...scope, claimId: resultId }); }
  dedupeGroups(scope: EvidenceQueryScope = {}): EvidenceDedupeGroup[] { const groups = groupBy(this.captures(scope), dedupeKey); return [...groups.entries()].filter(([, c]) => c.length > 1).map(([key, c]) => ({ key, captureIds: c.map((x) => x.id), sourceIds: uniq(c.map((x) => x.sourceId)), canonicalUrls: uniq(c.map((x) => x.canonicalUrl ?? x.url)), contentHashes: uniq(c.map((x) => x.contentHash)), normalizedTextHash: c.find((x) => x.normalizedTextHash)?.normalizedTextHash, tenantId: c.find((x) => x.tenantId)?.tenantId })); }
  replayStatus(scope: EvidenceQueryScope = {}): CaptureReplayJob[] { const ids = new Set(this.captures(scope).map((c) => c.id)); return limit(this.data().replayJobs.filter((j) => (!scope.tenantId || j.tenantId === scope.tenantId) && (!scope.captureId || j.captureId === scope.captureId) && (!ids.size || ids.has(j.captureId))).sort(desc("requestedAt")), scope.limit); }
  sourceFreshness(scope: EvidenceQueryScope = {}): SourceFreshnessSummary[] { return [...groupBy(this.captures(scope), (c) => c.sourceId).entries()].map(([sourceId, rows]) => { const sorted = rows.sort(desc("collectedAt")); return { sourceId, tenantId: sorted.find((c) => c.tenantId)?.tenantId, latestCollectedAt: sorted[0]?.collectedAt, captureCount: sorted.length, latestCaptureId: sorted[0]?.id }; }); }
  redactionSummaries(scope: EvidenceQueryScope = {}): EvidenceRedactionSummary[] { return limit(this.captures(scope).map((c) => ({ captureId: c.id, tenantId: c.tenantId, sourceId: c.sourceId, sensitive: c.sensitive, storageKind: c.storageKind, retentionClass: c.retentionClass ?? (c.sensitive ? "restricted_metadata" : "standard"), legalHold: Boolean(c.legalHold || c.retentionClass === "legal_hold"), bodyAvailableToApi: Boolean(c.body && !c.sensitive && c.storageKind !== "metadata_only"), redactionPolicy: c.redaction?.policy, reason: c.redaction?.reason })), scope.limit); }
  captureCounts(scope: EvidenceQueryScope = {}): EvidenceCaptureCounts { const captures = this.captures(scope); return { total: captures.length, byRetentionClass: countBy(captures, (c) => c.retentionClass ?? (c.sensitive ? "restricted_metadata" : "standard")), sensitive: captures.filter((c) => c.sensitive).length, legalHold: captures.filter((c) => c.legalHold || c.retentionClass === "legal_hold").length }; }
  extractionVersions(scope: EvidenceQueryScope = {}): EvidenceExtractorVersionSummary[] { const captures = new Map(this.captures(scope).map((c) => [c.id, c])); const versions = new Map<string, any>(); for (const i of this.incidents(scope)) addVersion(versions, captures.get(i.captureId ?? ""), i.extractorVersion); for (const c of captures.values()) addVersion(versions, c); return [...versions.values()].map(({ captureIds: _ids, ...summary }) => summary); }
  liveSnapshotsByQuery(query: string, scope: EvidenceQueryScope = {}): LiveSearchSnapshot[] { return limit(this.snapshots(scope).filter((s) => s.normalizedQuery === normalize(query)).sort(desc("capturedAt")), scope.limit); }
  getSearchDeltas(query: string, sinceCursor?: string, scope: EvidenceQueryScope = {}): EvidenceDelta[] { return limit(this.deltas(scope).filter((d) => d.normalizedQuery === normalize(query) && after(d, sinceCursor)).sort(byCursor), scope.limit); }
  activeRunEvidence(runId: string, scope: EvidenceQueryScope = {}): LiveSearchEvidenceView { return this.getActiveRunEvidence(runId, undefined, scope); }
  getActiveRunEvidence(runId: string, sinceCursor?: string, scope: EvidenceQueryScope = {}): LiveSearchEvidenceView { return this.view(this.snapshots(scope).filter((s) => s.runId === runId), scope, this.deltas(scope).filter((d) => d.runId === runId && after(d, sinceCursor)).sort(byCursor)); }
  newlyAvailableEvidenceSince(since: string, scope: EvidenceQueryScope = {}): LiveSearchEvidenceView { const captures = this.captures(scope).filter((c) => c.collectedAt > since), ids = new Set(captures.map((c) => c.id)), deltas = this.deltas(scope).filter((d) => d.observedAt > since).sort(byCursor); return { discoveryEvidence: this.discovery(scope).filter((d) => d.observedAt > since), captures, incidents: this.incidents(scope).filter((i) => i.firstSeenAt > since || Boolean(i.captureId && ids.has(i.captureId))), snapshots: this.snapshots(scope).filter((s) => s.capturedAt > since), deltas, nextCursor: latest(deltas) }; }
  getEvidenceTimeline(query: string, scope: EvidenceQueryScope = {}): EvidenceDelta[] { return limit(this.deltas(scope).filter((d) => d.normalizedQuery === normalize(query)).sort(byCursor), scope.limit); }
  pruneStaleSnapshots(now: string, scope: EvidenceQueryScope = {}): LiveSearchSnapshot[] { return this.snapshots(scope).filter((s) => Boolean(s.staleAt && s.staleAt <= now)); }
  private captures(s: EvidenceQueryScope = {}) { return this.data().captures.filter((c) => (!s.tenantId || c.tenantId === s.tenantId) && (!s.sourceId || c.sourceId === s.sourceId) && (!s.captureId || c.id === s.captureId)); }
  private incidents(s: EvidenceQueryScope = {}) { const ids = new Set(this.captures(s).map((c) => c.id)); return this.data().incidents.filter((i) => (!s.sourceId || i.sourceId === s.sourceId) && (!s.claimId || i.id === s.claimId) && (!i.captureId || ids.has(i.captureId))); }
  private discovery(s: EvidenceQueryScope = {}) { return this.data().discoveryEvidence.filter((d) => (!s.tenantId || d.tenantId === s.tenantId) && (!s.sourceId || d.sourceId === s.sourceId) && (!s.actor || d.normalizedQuery === normalize(s.actor) || d.snippet.toLowerCase().includes(s.actor.toLowerCase()))); }
  private snapshots(s: EvidenceQueryScope = {}) { return this.data().liveSearchSnapshots.filter((x) => (!s.tenantId || x.tenantId === s.tenantId) && (!s.actor || x.normalizedQuery === normalize(s.actor))); }
  private deltas(s: EvidenceQueryScope = {}) { return this.data().evidenceDeltas.filter((d) => (!s.tenantId || d.tenantId === s.tenantId) && (!s.sourceId || d.sourceId === s.sourceId) && (!s.captureId || d.captureIds.includes(s.captureId) || (d.subjectType === "capture" && d.subjectId === s.captureId)) && (!s.claimId || d.incidentIds.includes(s.claimId) || (d.subjectType === "extraction" && d.subjectId === s.claimId))); }
  private view(snapshots: LiveSearchSnapshot[], scope: EvidenceQueryScope, deltas: EvidenceDelta[] = []): LiveSearchEvidenceView { const ids = (field: "discoveryEvidenceIds" | "captureIds" | "incidentIds") => new Set([...snapshots.flatMap((s) => s[field]), ...deltas.flatMap((d) => d[field])]); return { discoveryEvidence: this.discovery(scope).filter((d) => ids("discoveryEvidenceIds").has(d.id)), captures: this.captures(scope).filter((c) => ids("captureIds").has(c.id)), incidents: this.incidents(scope).filter((i) => ids("incidentIds").has(i.id)), snapshots, deltas, nextCursor: latest(deltas) }; }
}

const desc = <T>(field: keyof T) => (left: T, right: T) => String(right[field]).localeCompare(String(left[field]));
const byCursor = (left: EvidenceDelta, right: EvidenceDelta) => left.cursor.localeCompare(right.cursor);
const normalize = (query: string) => query.trim().toLowerCase().replace(/\s+/g, " ");
const latest = (deltas: EvidenceDelta[]) => deltas.at(-1)?.cursor;
const after = (delta: EvidenceDelta, cursor?: string) => !cursor || delta.cursor > cursor;
const limit = <T>(items: T[], n?: number) => n === undefined ? items : items.slice(0, Math.max(0, n));
const uniq = (values: string[]) => [...new Set(values.filter(Boolean))];
const dedupeKey = (c: RawCapture) => `${c.tenantId ?? "global"}:${c.sourceId}:${c.normalizedTextHash ?? c.canonicalUrl ?? c.url}:${c.publishedAt ?? ""}`;
const chainFor = (i: IncidentCandidate, c?: RawCapture): EvidenceProvenanceChain[] => c ? [{ tenantId: c.tenantId, sourceId: c.sourceId, taskId: c.taskId, captureId: c.id, incidentId: i.id, extractorVersion: i.extractorVersion ?? c.provenance?.extractorVersion, collectedAt: c.collectedAt, contentHash: c.contentHash, url: c.url, confidence: i.confidence, claimValues: [i.title, ...i.entities.map((e) => e.value), ...i.indicators.map((x) => x.value)] }] : [];
const discoveryChain = (d: DiscoveryEvidence): EvidenceProvenanceChain => ({ tenantId: d.tenantId, sourceId: d.sourceId ?? d.provider, captureId: d.promotedToCaptureId ?? d.id, incidentId: d.promotedToIncidentId, extractorVersion: "discovery-evidence:v1", collectedAt: d.observedAt, contentHash: d.id, url: d.url ?? "", confidence: d.confidence, claimValues: [d.title, d.snippet].filter(Boolean) as string[] });
const matchesActor = (i: IncidentCandidate, actor?: string) => !actor || i.entities.some((e) => (e.type === "actor" || e.type === "ransomware_family") && [e.value, e.normalizedValue, ...(e.aliases ?? [])].some((v) => v?.toLowerCase() === actor.toLowerCase()));
function groupBy<T>(items: T[], key: (item: T) => string): Map<string, T[]> { const out = new Map<string, T[]>(); for (const item of items) out.set(key(item), [...(out.get(key(item)) ?? []), item]); return out; }
function countBy<T>(items: T[], key: (item: T) => string): Record<string, number> { const out: Record<string, number> = {}; for (const item of items) out[key(item)] = (out[key(item)] ?? 0) + 1; return out; }
function addVersion(versions: Map<string, any>, capture?: RawCapture, incidentVersion?: string) { if (!capture) return; const name = incidentVersion ?? capture.provenance?.extractorVersion ?? "unknown"; const item = versions.get(name) ?? { extractorVersion: name, captureCount: 0, incidentCount: 0, captureIds: new Set<string>() }; item.incidentCount += incidentVersion ? 1 : 0; item.captureIds.add(capture.id); item.captureCount = item.captureIds.size; item.latestCollectedAt = !item.latestCollectedAt || capture.collectedAt > item.latestCollectedAt ? capture.collectedAt : item.latestCollectedAt; versions.set(name, item); }
