// @ts-nocheck
import type { TelegramPublicRuntimeCollectionDto } from "../adapters/telegramPublic.ts";
import { processCollectedItem } from "../pipeline/pipeline.ts";
import type { CollectedItem, DiscoveryEvidence, EvidenceDelta, IncidentCandidate, LiveSearchSnapshot, RawCapture, SourceRecord } from "../types.ts";
import { stableId } from "../utils.ts";
import type { ScraperStore } from "./memoryStore.ts";

export type RuntimeEvidencePersistenceResult = any;
const SAFE = { sensitiveBodiesExposed: false, objectKeysExposed: false, rawMediaPayloadsExposed: false, privateDataExposed: false };

export function persistTelegramPublicRuntimeEvidence(store: ScraperStore, runtime: TelegramPublicRuntimeCollectionDto, options: { tenantId?: string; runId?: string; query: string; generatedAt?: string }): RuntimeEvidencePersistenceResult {
  const generatedAt = options.generatedAt ?? runtime.generatedAt, normalizedQuery = norm(options.query), source = patchSource(store, runtime), tenantId = options.tenantId ?? source?.tenantId, base = { tenantId, runId: options.runId, query: options.query, normalizedQuery, generatedAt };
  const byUrl = new Map<string, DiscoveryEvidence>(), discoveryEvidence = runtime.evidence.map((item) => { const disc = store.getDiscoveryEvidence(discovery(runtime, item, base).id) ?? store.saveDiscoveryEvidence(discovery(runtime, item, base)); byUrl.set(item.messageUrl, disc); return disc; });
  const persisted = runtime.promotedItems.map((item) => persistItem(store, item, base)), captures = persisted.map((p) => p.capture), incidents = persisted.map((p) => p.incident).filter(Boolean);
  for (const p of persisted) { const disc = byUrl.get(p.promotedItem.url); if (disc && (disc.promotedToCaptureId !== p.capture.id || disc.promotedToIncidentId !== p.incident?.id)) store.promoteDiscoveryEvidence({ discoveryEvidenceId: disc.id, taskId: p.promotedItem.taskId, captureId: p.capture.id, incidentId: p.incident?.id, promotedAt: generatedAt, promotedBy: "collector" }); }
  const deltas = [...newMessageDeltas(runtime, byUrl, base), ...runtime.poll.updatedMessages.map((item) => delta(runtime, item, { ...base, kind: "updated", subjectId: byUrl.get(item.messageUrl)?.id })), ...runtime.poll.deletedOrUnavailable.map((item) => delta(runtime, item, { ...base, kind: "expired", subjectId: byUrl.get(item.messageUrl)?.id })), ...persisted.flatMap((p) => p.incident ? [relationshipDelta({ capture: p.capture, incident: p.incident }, base)] : [])].map((d) => store.saveEvidenceDelta(d));
  const snapshot = store.saveLiveSearchSnapshot({ id: stableId("snapshot", `telegram-runtime:${runtime.sourceId}:${normalizedQuery}:${options.runId ?? ""}:${generatedAt}`), tenantId, query: options.query, normalizedQuery, runId: options.runId, status: snapshotStatus(runtime.status), capturedAt: generatedAt, discoveryEvidenceIds: discoveryEvidence.map((d) => d.id), captureIds: captures.map((c) => c.id), incidentIds: incidents.map((i) => i.id), newEvidenceIds: [...discoveryEvidence.map((d) => d.id), ...captures.map((c) => c.id), ...incidents.map((i) => i.id), ...deltas.map((d) => d.id)], deltaCursors: deltas.map((d) => d.cursor), metadata: { adapter: "telegram_public", runtimeStatus: runtime.status, channelHandle: runtime.channelHandle, sourceId: runtime.sourceId, collection: runtime.collection, schedulerHints: runtime.schedulerHints, poll: { cursor: runtime.poll.cursor, nextCursor: runtime.poll.nextCursor, newMessages: runtime.poll.newMessages.length, updatedMessages: runtime.poll.updatedMessages.length, deletedOrUnavailable: runtime.poll.deletedOrUnavailable.length, promotedExtractionIds: runtime.poll.promotedExtractionIds }, connector: connector(runtime), media: runtime.poll.media }, retentionClass: "live_search_snapshot" });
  return { source, discoveryEvidence: discoveryEvidence.map((d) => store.getDiscoveryEvidence(d.id) ?? d), captures, incidents, deltas: store.listEvidenceDeltas().filter((d) => snapshot.deltaCursors?.includes(d.cursor)), snapshot, nextCursor: snapshot.deltaCursors?.at(-1) ?? deltas.at(-1)?.cursor, safeOutput: SAFE };
}
function persistItem(store: ScraperStore, item: CollectedItem, options) { const promotedItem = { ...item, metadata: { ...item.metadata, query: options.query, normalizedQuery: options.normalizedQuery, runId: options.runId, runtimePersistedAt: options.generatedAt } }, result = processCollectedItem(promotedItem), saved = store.savePipelineResult({ ...result, capture: { ...result.capture, tenantId: options.tenantId, retentionClass: "public_chat_text", metadata: { ...result.capture.metadata, query: options.query, normalizedQuery: options.normalizedQuery, runId: options.runId, runtimePersistedAt: options.generatedAt }, provenance: { ...result.capture.provenance, sourceId: result.capture.provenance?.sourceId ?? result.capture.sourceId, captureId: result.capture.provenance?.captureId ?? result.capture.id, url: result.capture.provenance?.url ?? result.capture.url, collectedAt: result.capture.provenance?.collectedAt ?? result.capture.collectedAt, contentHash: result.capture.provenance?.contentHash ?? result.capture.contentHash, extractorVersion: result.capture.provenance?.extractorVersion ?? "telegram_public_runtime:v1", tenantId: options.tenantId, adapterVersion: "telegram_public_runtime:v1" } } }); return { promotedItem, result: saved, capture: saved.capture, incident: saved.incident }; }
function patchSource(store: ScraperStore, runtime: TelegramPublicRuntimeCollectionDto): SourceRecord | undefined { const existing = store.getSource(runtime.sourceId); return existing ? store.saveSource({ ...existing, updatedAt: runtime.sourcePatch.updatedAt, crawlState: { ...(existing.crawlState ?? { retryCount: 0 }), ...runtime.sourcePatch.crawlState }, metadata: { ...(existing.metadata ?? {}), ...(runtime.sourcePatch.metadata ?? {}), telegramPublicConnector: connector(runtime) } }) : undefined; }
function connector(runtime: TelegramPublicRuntimeCollectionDto) { return { generatedAt: runtime.connector.generatedAt, sourceId: runtime.connector.sourceId, channelHandle: runtime.connector.channelHandle, sourceHealthPatch: runtime.connector.sourceHealthPatch, publicMessageProvenance: runtime.connector.publicMessageProvenance.map((p) => ({ sourceId: p.sourceId, channel: p.channel, messageId: p.messageId, messageUrl: p.messageUrl, messageTimestamp: p.messageTimestamp, contentHash: p.contentHash, confidence: p.confidence, state: p.state })), deltas: { newMessageIds: runtime.connector.deltas.newMessageIds, editedMessageIds: runtime.connector.deltas.editedMessageIds, deletedOrUnavailableMessageIds: runtime.connector.deltas.deletedOrUnavailableMessageIds }, promotionHandoff: runtime.connector.promotionHandoff, actorReadiness: runtime.connector.actorReadiness, safeOutput: runtime.connector.safeOutput }; }
function newMessageDeltas(runtime: TelegramPublicRuntimeCollectionDto, byUrl: Map<string, DiscoveryEvidence>, options): EvidenceDelta[] { const changed = new Set([...runtime.connector.deltas.editedMessageIds, ...runtime.connector.deltas.deletedOrUnavailableMessageIds]); return runtime.connector.deltas.newMessageIds.filter((id) => !changed.has(id)).map((messageId) => { const p = runtime.connector.publicMessageProvenance.find((item) => item.messageId === messageId), subjectId = p ? byUrl.get(p.messageUrl)?.id ?? stableId("disc", `telegram-runtime:${runtime.sourceId}:${p.messageUrl}:${p.contentHash ?? messageId}`) : stableId("disc", `telegram-runtime:${runtime.sourceId}:${messageId}`); return { id: stableId("delta", `telegram-runtime:connector-new:${runtime.sourceId}:${messageId}:${options.generatedAt}`), tenantId: options.tenantId, query: options.query, normalizedQuery: options.normalizedQuery, runId: options.runId, cursor: "", kind: "added", subjectType: "discovery_evidence", subjectId, observedAt: p?.messageTimestamp ?? options.generatedAt, sourceId: runtime.sourceId, discoveryEvidenceIds: [subjectId], captureIds: [], incidentIds: [], relationshipIds: [], policyEventIds: [], retentionClass: "evidence_delta", metadata: { adapter: "telegram_public", connectorDelta: true, deltaType: "new_message", channel: p?.channel ?? runtime.channelHandle, messageId, messageUrl: p?.messageUrl, messageState: p?.state ?? "available", contentHash: p?.contentHash, confidence: p?.confidence, mediaRetention: "metadata_only", rawMediaPayloadsExposed: false, privateDataExposed: false } }; }); }
function discovery(runtime: TelegramPublicRuntimeCollectionDto, item: TelegramPublicRuntimeCollectionDto["evidence"][number], options): DiscoveryEvidence { const key = `${runtime.sourceId}:${item.messageUrl}:${item.contentHash ?? item.messageId ?? item.messageTimestamp ?? options.generatedAt}`; return { id: stableId("disc", `telegram-runtime:${key}`), tenantId: options.tenantId, query: options.query, normalizedQuery: options.normalizedQuery, provider: "public_channel", evidenceType: "public_channel_snippet", resultId: item.promotedExtractionId ?? stableId("telegram-result", key), observedAt: item.messageTimestamp ?? options.generatedAt, title: `${item.channel} #${item.messageId ?? "unknown"}`, snippet: item.snippet, url: item.messageUrl, sourceId: runtime.sourceId, confidence: item.confidence, retentionClass: "public_chat_text", metadata: { adapter: "telegram_public", channel: item.channel, messageId: item.messageId, messageState: item.messageState ?? "available", editedAt: item.editedAt, contentHash: item.contentHash, media: item.media ? { retention: "metadata_only", rawFetchAllowed: false, count: item.media.items.length } : undefined, safeOutput: { rawMediaPayloadsExposed: false, privateDataExposed: false } } }; }
function delta(runtime: TelegramPublicRuntimeCollectionDto, item: TelegramPublicRuntimeCollectionDto["evidence"][number], options): EvidenceDelta { const subjectId = options.subjectId ?? stableId("disc", `telegram-runtime:${runtime.sourceId}:${item.messageUrl}:${item.contentHash ?? item.messageId ?? options.generatedAt}`); return { id: stableId("delta", `telegram-runtime:${options.kind}:${subjectId}:${options.generatedAt}`), tenantId: options.tenantId, query: options.query, normalizedQuery: options.normalizedQuery, runId: options.runId, cursor: "", kind: options.kind, subjectType: "discovery_evidence", subjectId, observedAt: options.kind === "expired" ? options.generatedAt : item.editedAt ?? item.messageTimestamp ?? options.generatedAt, sourceId: runtime.sourceId, discoveryEvidenceIds: [subjectId], captureIds: [], incidentIds: [], relationshipIds: [], policyEventIds: [], retentionClass: "evidence_delta", metadata: { adapter: "telegram_public", channel: item.channel, messageId: item.messageId, messageState: item.messageState ?? (options.kind === "expired" ? "unavailable" : "available"), contentHash: item.contentHash, connectorDelta: true, mediaRetention: "metadata_only", rawMediaPayloadsExposed: false, privateDataExposed: false } }; }
function relationshipDelta(item: { capture: RawCapture; incident: IncidentCandidate }, options): EvidenceDelta { const relationshipId = stableId("rel", `runtime:${item.incident.id}:${item.capture.id}`); return { id: stableId("delta", `telegram-runtime:relationship:${relationshipId}:${options.generatedAt}`), tenantId: options.tenantId, query: options.query, normalizedQuery: options.normalizedQuery, runId: options.runId, cursor: "", kind: "promoted", subjectType: "relationship", subjectId: relationshipId, observedAt: options.generatedAt, sourceId: item.capture.sourceId, discoveryEvidenceIds: arr(item.capture.metadata.discoveryEvidenceId), captureIds: [item.capture.id], incidentIds: [item.incident.id], relationshipIds: [relationshipId], policyEventIds: [], retentionClass: "evidence_delta", metadata: { adapter: "telegram_public", promotion: "runtime_public_channel_relationship", captureId: item.capture.id, incidentId: item.incident.id, contentHash: item.capture.contentHash } }; }
function snapshotStatus(status: TelegramPublicRuntimeCollectionDto["status"]): LiveSearchSnapshot["status"] { return status === "ready" ? "ready" : status === "blocked" || status === "policy_disabled" ? "blocked" : status === "unavailable" || status === "rate_limited" ? "degraded" : "partial"; }
function arr(value: unknown) { return Array.isArray(value) ? value.filter((item) => typeof item === "string") : []; }
function norm(query: string) { return query.trim().toLowerCase().replace(/\s+/g, " "); }
