// @ts-nocheck
import type { SourceRecord } from "../types.ts";

export type SourceRegistrySourceRow = any;
export type SourceRegistryGovernanceRow = any;
export type SourceRegistryLegalNoteRow = any;
export type SourceRegistryHealthRow = any;
export type SourceRegistryScoringInputsRow = any;
export type SourceRegistryCrawlStateRow = any;
export type SourceRegistryLifecycleEventRow = any;
export type SourceAtlasRecordRow = any;
export type SourceAtlasReviewQueuePostgresRow = any;
export type SourceAtlasExportManifestPostgresRow = any;
export type SourceAtlasActivationPacketAuditRow = any;
export type SourceAtlasSourcePackCandidateReviewRow = any;
export type SourceRegistryPostgresRows = any;
export type SourceAtlasPostgresRows = any;

export function sourceRecordToPostgresRows(source: SourceRecord): SourceRegistryPostgresRows {
  const updated = source.updatedAt, governance = source.governance ?? {};
  return { sources: [{ id: source.id, tenant_id: source.tenantId, name: source.name, type: source.type, url: source.url, access_method: source.accessMethod, status: source.status, risk: source.risk, trust_score: clamp(source.trustScore), language: source.language, crawl_frequency_seconds: source.crawlFrequencySeconds, last_seen_at: source.lastSeenAt, created_at: source.createdAt, updated_at: updated, tags: [...(source.tags ?? [])], metadata: source.catalog ? { ...(source.metadata ?? {}), catalog: source.catalog } : (source.metadata ?? {}) }], source_governance: [{ source_id: source.id, approval_required: governance.approvalRequired ?? source.approvalRequired ?? source.risk !== "low", approval_state: governance.approvalState ?? ((source.approvalRequired ?? source.risk !== "low") ? "pending" : "not_required"), metadata_only: governance.metadataOnly ?? ["tor_metadata", "i2p_metadata", "freenet_metadata", "restricted"].includes(String(source.type)) || source.risk === "restricted", approved_at: governance.approvedAt ?? source.approvedAt, approved_by: governance.approvedBy ?? source.approvedBy, approval_expires_at: governance.approvalExpiresAt, review_ticket: governance.reviewTicket, policy_version: governance.policyVersion ?? "collection-policy:v1", risk_justification: governance.riskJustification, legal_contact: governance.legalContact, created_at: source.createdAt, updated_at: updated }], source_legal_notes: [{ id: `legal-note:${source.id}:${source.createdAt}`, source_id: source.id, note: source.legalNotes, note_kind: "collection_basis", created_at: source.createdAt, created_by: source.approvedBy }], source_health: source.health ? [{ source_id: source.id, ...snake(source.health), error_rate: clamp(source.health.errorRate), updated_at: updated }] : [], source_scoring_inputs: source.scoring ? [{ source_id: source.id, reliability: clamp(source.scoring.reliability), freshness: clamp(source.scoring.freshness), relevance: clamp(source.scoring.relevance), uniqueness: clamp(source.scoring.uniqueness), parseability: clamp(source.scoring.parseability), policy_risk_penalty: clamp(source.scoring.policyRiskPenalty), operator_boost: clamp(source.scoring.operatorBoost), updated_at: updated }] : [], source_crawl_state: source.crawlState ? [{ source_id: source.id, last_scheduled_at: source.crawlState.lastScheduledAt, next_eligible_at: source.crawlState.nextEligibleAt, last_collected_at: source.crawlState.lastCollectedAt, etag: source.crawlState.etag, last_modified: source.crawlState.lastModified, cursor_value: source.crawlState.cursor, backoff_until: source.crawlState.backoffUntil, retry_count: source.crawlState.retryCount, updated_at: updated }] : [], source_lifecycle_events: (source.lifecycle ?? []).map((event) => ({ source_id: source.id, occurred_at: event.at, from_status: event.from, to_status: event.to, reason: event.reason, actor_id: event.actorId, note: event.note })) };
}

export function sourceRecordFromPostgresRows(input: any): SourceRecord {
  const row = input.source, gov = input.governance ?? {}, meta = { ...(row.metadata ?? {}) }, catalog = meta.catalog;
  delete meta.catalog;
  return { id: row.id, tenantId: row.tenant_id, name: row.name, type: row.type, url: row.url, accessMethod: row.access_method, status: row.status, risk: row.risk, trustScore: clamp(row.trust_score), language: row.language, crawlFrequencySeconds: row.crawl_frequency_seconds, legalNotes: latest(input.legalNotes)?.note ?? "", createdAt: row.created_at, updatedAt: row.updated_at, lastSeenAt: row.last_seen_at, approvalRequired: gov.approval_required, approvedAt: gov.approved_at, approvedBy: gov.approved_by, governance: gov.source_id ? { approvalRequired: gov.approval_required, approvalState: gov.approval_state, metadataOnly: gov.metadata_only, approvedAt: gov.approved_at, approvedBy: gov.approved_by, approvalExpiresAt: gov.approval_expires_at, reviewTicket: gov.review_ticket, policyVersion: gov.policy_version, riskJustification: gov.risk_justification, legalContact: gov.legal_contact } : undefined, health: input.health ? camel(input.health) : undefined, scoring: input.scoring ? { reliability: input.scoring.reliability, freshness: input.scoring.freshness, relevance: input.scoring.relevance, uniqueness: input.scoring.uniqueness, parseability: input.scoring.parseability, policyRiskPenalty: input.scoring.policy_risk_penalty, operatorBoost: input.scoring.operator_boost } : undefined, crawlState: input.crawlState ? { lastScheduledAt: input.crawlState.last_scheduled_at, nextEligibleAt: input.crawlState.next_eligible_at, lastCollectedAt: input.crawlState.last_collected_at, etag: input.crawlState.etag, lastModified: input.crawlState.last_modified, cursor: input.crawlState.cursor_value, backoffUntil: input.crawlState.backoff_until, retryCount: input.crawlState.retry_count } : undefined, lifecycle: (input.lifecycle ?? []).map((e: any) => ({ at: e.occurred_at, from: e.from_status, to: e.to_status, reason: e.reason, actorId: e.actor_id, note: e.note })).sort((a: any, b: any) => a.at.localeCompare(b.at)), tags: row.tags, metadata: meta, catalog };
}

export function buildSourceRegistryPersistenceReadinessPacket(generatedAt: string) {
  const tables = ["sources", "source_governance", "source_legal_notes", "source_health", "source_scoring_inputs", "source_crawl_state", "source_lifecycle_events", "source_atlas_records", "source_atlas_review_queue", "source_atlas_export_manifest", "source_atlas_activation_packet_audit", "source_atlas_source_pack_candidate_review"];
  return { schemaVersion: "ti.source_registry_persistence_readiness.v1", generatedAt, migration: "migrations/001_source_registry.sql", dryRun: true, willMutate: false, willConnectToDatabase: false, workflowTables: tables.map((table) => ({ table, mapper: table, requiredForCutover: !table.startsWith("source_atlas_") })), replayOrder: tables, guardrails: ["source registry persistence does not lease work or start crawling", "source atlas rows stay staged until explicit activation"] };
}

export function tiSourceAtlasRecordToPostgresRow(record: any, input: { tenantId?: string; generatedAt: string }): SourceAtlasRecordRow {
  return { atlas_source_id: record.id, tenant_id: input.tenantId, url: record.url, domain: record.domain, feed_url: record.feedUrl, source_name: record.sourceName, family: record.family, discovery_method: record.discoveryMethod, query_class_coverage: [...record.queryClassCoverage], language: record.language, regions: [...record.region], sectors: [...record.sector], reliability: clamp(record.reliability), freshness: clamp(record.freshness), evidence_yield: clamp(record.evidenceYield), uniqueness: clamp(record.uniqueness), downstream_public_answer_impact: clamp(record.downstreamPublicAnswerImpact), source_value_score: clamp(record.sourceValueScore), parser_profile: record.parserCapability.profile, parser_certified: record.parserCapability.certified, parser_certification_required: record.parserCapability.certificationRequired, legal_review: record.legalRobotsState.legalReview, robots_review: record.legalRobotsState.robotsReview, legal_robots_notes: [...record.legalRobotsState.notes], duplicate_of: record.duplicate.duplicateOf, mirror_of: record.duplicate.mirrorOf, content_similarity: clamp(record.duplicate.contentSimilarity), duplicate_suppressed: record.duplicate.suppressed, scheduler_budget_class: record.schedulerEstimate.budgetClass, cadence_seconds: record.schedulerEstimate.cadenceSeconds, estimated_daily_tasks: record.schedulerEstimate.estimatedDailyTasks, expected_items_per_day: record.evidenceEstimate.expectedItemsPerDay, storage_mb_per_day: record.evidenceEstimate.storageMbPerDay, retention_class: record.evidenceEstimate.retentionClass, activation_state: record.activationReadiness.state, activation_reasons: [...record.activationReadiness.reasons], approval_required: true, auto_activation_allowed: false, public_only: true, private_invite_auth_captcha: false, raw_payload_target: false, auto_activate: false, generated_at: input.generatedAt };
}

export function tiSourceAtlasRecordFromPostgresRow(row: any): any {
  return { id: row.atlas_source_id, url: row.url, domain: row.domain, feedUrl: row.feed_url, sourceName: row.source_name, family: row.family, discoveryMethod: row.discovery_method, queryClassCoverage: [...row.query_class_coverage], language: row.language, region: [...row.regions], sector: [...row.sectors], reliability: clamp(row.reliability), freshness: clamp(row.freshness), evidenceYield: clamp(row.evidence_yield), uniqueness: clamp(row.uniqueness), downstreamPublicAnswerImpact: clamp(row.downstream_public_answer_impact), sourceValueScore: clamp(row.source_value_score), parserCapability: { profile: row.parser_profile, owner: "agent_03", certified: row.parser_certified, certificationRequired: row.parser_certification_required }, legalRobotsState: { legalReview: row.legal_review, robotsReview: row.robots_review, notes: [...row.legal_robots_notes] }, duplicate: { duplicateOf: row.duplicate_of, mirrorOf: row.mirror_of, contentSimilarity: clamp(row.content_similarity), suppressed: row.duplicate_suppressed }, schedulerEstimate: { budgetClass: row.scheduler_budget_class, cadenceSeconds: row.cadence_seconds, estimatedDailyTasks: row.estimated_daily_tasks }, evidenceEstimate: { expectedItemsPerDay: row.expected_items_per_day, storageMbPerDay: row.storage_mb_per_day, retentionClass: row.retention_class }, activationReadiness: { state: row.activation_state, approvalRequired: true, autoActivationAllowed: false, reasons: [...row.activation_reasons] }, safety: { publicOnly: true, privateInviteAuthCaptcha: false, rawPayloadTarget: false, autoActivate: false } };
}

export const tiSourceAtlasExportManifestToPostgresRows = (packet: any): SourceAtlasPostgresRows => ({ source_atlas_records: [], source_atlas_review_queue: packet.reviewQueue.map((row: any) => tiSourceAtlasReviewQueueRowToPostgresRow(row, packet)), source_atlas_export_manifest: packet.exportManifest.rows.map((row: any) => tiSourceAtlasExportManifestRowToPostgresRow(row, packet)), source_atlas_activation_packet_audit: [], source_atlas_source_pack_candidate_review: [] });
export const tiSourceAtlasRepairActivationPacketInputsToPostgresRows = (packetInputs: any, input: any): SourceAtlasActivationPacketAuditRow[] => packetInputs.packets.map((p: any) => ({ packet_id: p.packetId, tenant_id: input.tenantId, priority: p.priority, approval_mode: p.approvalMode, action: p.action, repair_decision: p.repairDecision, blocker: p.blocker, atlas_source_ids: [...p.atlasSourceIds], replacement_candidate_ids: [...p.replacementCandidateIds], source_families: [...p.sourceFamilies], expected_payworthy_lift: p.expectedPayworthyLift, expected_fresh_rows_per_day: p.expectedFreshRowsPerDay, expected_row_lift: p.expectedRowLift, buyer_visible_reason: p.buyerVisibleReason, prerequisites: [...p.prerequisites], route_hints: [...p.routeHints], forbidden_actions: [...p.forbiddenActions], dry_run: true, will_mutate: false, will_start_crawling: false, raw_url_exposed: false, raw_payload_exposed: false, private_auth_captcha_required: false, crawl_started: false, source_activation_applied: false, generated_at: input.generatedAt }));
export const tiSourceAtlasSourcePackCandidatesToPostgresRows = (packet: any, input: any): SourceAtlasSourcePackCandidateReviewRow[] => packet.packs.map((p: any) => ({ pack_id: p.packId, tenant_id: input.tenantId, rank: p.rank, pack_label: p.packLabel, family: p.family, acquisition_mode: p.acquisitionMode, source_ids: [...p.sourceIds], safe_source_hashes: [...p.safeSourceHashes], expected_payworthy_lift: p.expectedPayworthyLift, expected_fresh_rows_per_day: p.expectedFreshRowsPerDay, expected_useful_evidence_items_per_day: p.expectedUsefulEvidenceItemsPerDay, expected_scheduler_tasks_per_day: p.expectedSchedulerTasksPerDay, estimated_cost_units_per_useful_evidence: p.estimatedCostUnitsPerUsefulEvidence, buyer_visible_use_case: p.buyerVisibleUseCase, required_proof: [...p.requiredProof], agent01_source_registry_handoff: p.ownerHandoffs.agent01SourceRegistry, agent03_parser_handoff: p.ownerHandoffs.agent03Parser, agent07_quality_handoff: p.ownerHandoffs.agent07Quality, agent09_marketplace_handoff: p.ownerHandoffs.agent09Marketplace, agent10_slo_handoff: p.ownerHandoffs.agent10Slo, dry_run: true, will_mutate: false, will_import_source_packs: false, will_start_crawling: false, source_pack_imported: false, source_activation_applied: false, registry_mutation_planned: false, crawl_enqueued: false, raw_urls_exposed: false, raw_payloads_exposed: false, generated_at: input.generatedAt }));
export const tiSourceAtlasReviewQueueRowToPostgresRow = (row: any, packet: any): SourceAtlasReviewQueuePostgresRow => ({ review_id: row.reviewId, atlas_source_id: row.atlasSourceId, tenant_id: packet.tenantId, source_name: row.sourceName, family: row.family, domain: row.domain, source_hash: row.sourceHash, decision: row.decision, reasons: [...row.reasons], approval_route: row.approvalRoute, parser_owner: row.parserOwner, scheduler_owner: row.schedulerOwner, quality_owner: row.qualityOwner, release_owner: row.releaseOwner, dry_run: true, will_mutate: false, will_start_crawling: false, generated_at: packet.generatedAt });
export const tiSourceAtlasExportManifestRowToPostgresRow = (row: any, packet: any): SourceAtlasExportManifestPostgresRow => ({ atlas_source_id: row.atlasSourceId, tenant_id: packet.tenantId, source_hash: row.sourceHash, source_name: row.sourceName, url: row.url, domain: row.domain, family: row.family, query_class_coverage: [...row.queryClassCoverage], source_value_score: clamp(row.sourceValueScore), parser_profile: row.parserProfile, scheduler_cadence_seconds: row.schedulerCadenceSeconds, expected_items_per_day: row.expectedItemsPerDay, legal_review: row.legalReview, robots_review: row.robotsReview, approval_required: true, auto_activation_allowed: false, manifest_schema_version: "ti.source_atlas_export.v1", requested_plan: packet.requestedPlan, generated_at: packet.generatedAt });

function latest(rows: any[] | undefined) { return [...(rows ?? [])].sort((a, b) => b.created_at.localeCompare(a.created_at))[0]; }
function clamp(value: number) { return Number.isFinite(value) ? Math.max(0, Math.min(1, value)) : 0; }
function snake(input: Record<string, any>) { return Object.fromEntries(Object.entries(input).map(([k, v]) => [k.replace(/[A-Z]/g, (m) => `_${m.toLowerCase()}`), v])); }
function camel(input: Record<string, any>) { return Object.fromEntries(Object.entries(input).map(([k, v]) => [k.replace(/_([a-z])/g, (_, c) => c.toUpperCase()), v])); }
