#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"

export HANASAND_MODEL_PROFILE="${HANASAND_MODEL_PROFILE:-inspur-gpu}"
export HANASAND_REQUIRE_CUDA="${HANASAND_REQUIRE_CUDA:-1}"
export HANASAND_EXPECTED_NVIDIA_GPUS="${HANASAND_EXPECTED_NVIDIA_GPUS:-8}"
export GPT_REQUIRE_SELECTED_MODEL="${GPT_REQUIRE_SELECTED_MODEL:-1}"
export LLAMA_CTX_SIZE="${LLAMA_CTX_SIZE:-32768}"
export LLAMA_BATCH_SIZE="${LLAMA_BATCH_SIZE:-4096}"
export LLAMA_UBATCH_SIZE="${LLAMA_UBATCH_SIZE:-1024}"
export LLAMA_THREADS="${LLAMA_THREADS:-64}"
export LLAMA_THREADS_BATCH="${LLAMA_THREADS_BATCH:-64}"
export LLAMA_PROCESS_PRIORITY="${LLAMA_PROCESS_PRIORITY:--1}"
export LLAMA_POLL_LEVEL="${LLAMA_POLL_LEVEL:-0}"
export HANASAND_LLAMA_CPP_DIR="${HANASAND_LLAMA_CPP_DIR:-$SCRIPT_DIR/.llama.cpp-src}"

exec "$SCRIPT_DIR/run_model_common.sh" generic
