import type { ExtractedEntity, ExtractionProvenance, GraphRelationshipReviewState, Indicator, IntelligenceGraphNode, IntelligenceRelationship, IntelligenceRelationshipType, PipelineResult, ProgressiveEvidenceStage, RelationshipGraph } from "../types.ts";
import { clampScore, stableId } from "../utils.ts";

export type RelationshipConfidenceRule = "incident-mentions-entity" | "indicator-indicates-incident" | "incident-attributed-to-actor" | "actor-targets-victim" | "actor-uses-ttp" | "actor-uses-malware" | "actor-exploits-cve";
export const RELATIONSHIP_CONFIDENCE_RULES: Record<RelationshipConfidenceRule, { weight: number; description: string }> = {
  "incident-mentions-entity": { weight: 0.72, description: "Mention edges are supporting context and inherit reduced incident/entity confidence." },
  "indicator-indicates-incident": { weight: 0.9, description: "Indicator-to-incident edges combine indicator confidence with incident confidence." },
  "incident-attributed-to-actor": { weight: 0.86, description: "Attribution stays below direct evidence confidence until corroborated." },
  "actor-targets-victim": { weight: 0.82, description: "Targeting requires both grounded actor and victim evidence." },
  "actor-uses-ttp": { weight: 0.78, description: "TTP use is conservative because ATT&CK extraction is often ambiguous." },
  "actor-uses-malware": { weight: 0.88, description: "Malware use is stronger than broad TTP use when malware evidence is explicit." },
  "actor-exploits-cve": { weight: 0.84, description: "Exploit edges require actor and CVE evidence and stay below raw CVE confidence." }
};

export function buildRelationshipGraph(result: PipelineResult): RelationshipGraph {
  const nodes = new Map<string, IntelligenceGraphNode>(), rels = new Map<string, IntelligenceRelationship>(), incident = result.incident;
  if (!incident) return { nodes: [], relationships: [] };
  const incidentNode = addNode(nodes, { id: incident.id, type: "incident", value: incident.title, confidence: incident.confidence, provenance: result.capture.provenance ? [{ ...result.capture.provenance, extractorVersion: result.capture.provenance.extractorVersion ?? String(result.capture.metadata.extractorVersion ?? "unknown") }] : [], properties: { sourceId: incident.sourceId, captureId: incident.captureId, summary: incident.summary } });
  const groups = Object.fromEntries(["actor", "victim", "sector", "country", "ttp", "cve"].map((type) => [type, result.entities.filter((e) => e.type === type)]));
  const malware = result.entities.filter((e) => e.type === "malware" || e.type === "ransomware_family");
  for (const entity of result.entities) { const node = entityNode(entity); addNode(nodes, node); addRel(rels, edge(incidentNode.id, node.id, "mentions", conf("incident-mentions-entity", incident.confidence, entity.confidence), incident.firstSeenAt, node.provenance, "incident-mentions-entity")); }
  for (const indicator of result.indicators) { const node = indicatorNode(indicator); addNode(nodes, node); addRel(rels, edge(node.id, incidentNode.id, "indicates", conf("indicator-indicates-incident", indicator.confidence, incident.confidence), incident.firstSeenAt, node.provenance, "indicator-indicates-incident")); }
  for (const actor of groups.actor) {
    const actorNode = entityNode(actor); addRel(rels, edge(incidentNode.id, actorNode.id, "attributed-to", conf("incident-attributed-to-actor", incident.confidence, actor.confidence), incident.firstSeenAt, actor.provenance ?? [], "incident-attributed-to-actor"));
    for (const victim of groups.victim) { const victimNode = entityNode(victim); addRel(rels, edge(actorNode.id, victimNode.id, "targets", conf("actor-targets-victim", actor.confidence, victim.confidence), incident.firstSeenAt, merged(actor, victim), "actor-targets-victim")); for (const sector of groups.sector) addRel(rels, edge(victimNode.id, entityNode(sector).id, "related-to", conf("incident-mentions-entity", victim.confidence, sector.confidence), incident.firstSeenAt, merged(victim, sector), "incident-mentions-entity")); for (const country of groups.country) addRel(rels, edge(victimNode.id, entityNode(country).id, "located-in", conf("incident-mentions-entity", victim.confidence, country.confidence), incident.firstSeenAt, merged(victim, country), "incident-mentions-entity")); }
    for (const ttp of groups.ttp) addRel(rels, edge(actorNode.id, entityNode(ttp).id, "uses", conf("actor-uses-ttp", actor.confidence, ttp.confidence), incident.firstSeenAt, merged(actor, ttp), "actor-uses-ttp"));
    for (const used of malware) addRel(rels, edge(actorNode.id, entityNode(used).id, "uses", conf("actor-uses-malware", actor.confidence, used.confidence), incident.firstSeenAt, merged(actor, used), "actor-uses-malware"));
    for (const cve of groups.cve) addRel(rels, edge(actorNode.id, entityNode(cve).id, "exploits", conf("actor-exploits-cve", actor.confidence, cve.confidence), incident.firstSeenAt, merged(actor, cve), "actor-exploits-cve"));
  }
  return { nodes: [...nodes.values()], relationships: [...rels.values()].map((rel) => review(rel, result)) };
}

function entityNode(e: ExtractedEntity): IntelligenceGraphNode { const value = e.normalizedValue ?? e.value, type = e.type === "ttp" ? "attack-pattern" : e.type === "cve" ? "vulnerability" : e.type === "ransomware_family" ? "malware" : e.type; return { id: stableId("node", `${type}:${value.toLowerCase()}`), type, value, confidence: e.confidence, provenance: e.provenance ?? [], properties: { rawValue: e.rawValue, aliases: e.aliases, reviewReasons: e.reviewReasons } }; }
function indicatorNode(i: Indicator): IntelligenceGraphNode { const value = i.normalizedValue ?? i.value; return { id: stableId("node", `indicator:${i.type}:${value}`), type: i.type === "cve" ? "vulnerability" : "indicator", value, confidence: i.confidence, provenance: i.provenance ?? [], properties: { indicatorType: i.type, rawValue: i.rawValue, reviewReasons: i.reviewReasons } }; }
function addNode(nodes: Map<string, IntelligenceGraphNode>, node: IntelligenceGraphNode) { if (!nodes.has(node.id)) nodes.set(node.id, node); return nodes.get(node.id) ?? node; }
function addRel(rels: Map<string, IntelligenceRelationship>, rel: IntelligenceRelationship) { if (rel.provenance.length) rels.set(rel.id, rel); }
function edge(sourceRef: string, targetRef: string, type: IntelligenceRelationshipType, confidence: number, seenAt: string, provenance: ExtractionProvenance[], rule: RelationshipConfidenceRule): IntelligenceRelationship { return { id: stableId("rel", `${sourceRef}:${type}:${targetRef}`), sourceRef, targetRef, type, confidence: clampScore(confidence), firstSeenAt: seenAt, lastSeenAt: seenAt, provenance, properties: { grounded: true, confidenceRule: rule, confidenceRuleDescription: RELATIONSHIP_CONFIDENCE_RULES[rule].description } }; }
export function relationshipConfidence(rule: RelationshipConfidenceRule, left: number, right: number): number { return conf(rule, left, right); }
const conf = (rule: RelationshipConfidenceRule, left: number, right: number) => clampScore(((clampScore(left) + clampScore(right)) / 2) * RELATIONSHIP_CONFIDENCE_RULES[rule].weight);
function merged(left: ExtractedEntity, right: ExtractedEntity): ExtractionProvenance[] { if (!left.provenance?.length || !right.provenance?.length) return []; const seen = new Set<string>(); return [...left.provenance, ...right.provenance].filter((p) => { const key = `${p.captureId}:${p.startOffset}:${p.endOffset}:${p.evidenceText}`; if (seen.has(key)) return false; seen.add(key); return true; }); }
function review(rel: IntelligenceRelationship, result: PipelineResult): IntelligenceRelationship { const state = reviewState(result.capture.metadata.graphReviewState); return { ...rel, properties: { ...rel.properties, stage: stage(result), liveEvidenceStage: result.capture.metadata.evidenceStage, sourceFamily: family(result), publicChannelOnly: result.capture.metadata.adapter === "telegram_public" || result.capture.metadata.evidenceStage === "public_channel_message", restrictedHeld: result.capture.storageKind === "metadata_only" || result.capture.metadata.evidenceStage === "metadata_only_claim", reviewState: state ?? rel.properties?.reviewState, reviewReason: typeof result.capture.metadata.graphReviewReason === "string" ? result.capture.metadata.graphReviewReason : undefined, promoted: rel.properties?.promoted === true || state === "accepted", contradicted: rel.properties?.contradicted === true || state === "contradicted" } }; }
function reviewState(value: unknown): GraphRelationshipReviewState | undefined { return ["unreviewed", "needs_review", "accepted", "rejected", "superseded", "contradicted", "expired"].includes(value as string) ? value as GraphRelationshipReviewState : undefined; }
function stage(result: PipelineResult): ProgressiveEvidenceStage { const s = result.capture.metadata.evidenceStage; return result.capture.metadata.graphReviewState === "accepted" ? "reviewed" : s === "reviewed_promoted" ? "promoted" : s === "extracted_relationship" ? "extracted" : s === "captured_page" ? "captured" : s === "public_channel_message" || s === "metadata_only_claim" || s === "live_discovery" || s === "seeded" || result.capture.metadata.adapter === "telegram_public" ? "discovery" : "captured"; }
function family(result: PipelineResult): "clear_web" | "public_channel" | "restricted_metadata" | "seeded" { return result.capture.metadata.adapter === "telegram_public" || result.capture.metadata.evidenceStage === "public_channel_message" ? "public_channel" : result.capture.storageKind === "metadata_only" || result.capture.metadata.evidenceStage === "metadata_only_claim" ? "restricted_metadata" : result.capture.metadata.evidenceStage === "seeded" ? "seeded" : "clear_web"; }
