FROM alpine:3.22

ARG HANASAND_RELEASE_COMMIT=unknown
LABEL org.opencontainers.image.revision=$HANASAND_RELEASE_COMMIT

RUN apk add --no-cache openssh-client procps
COPY tunnel-entrypoint.sh /usr/local/bin/hanasand-tunnel
RUN chmod 0755 /usr/local/bin/hanasand-tunnel

ENTRYPOINT ["/usr/local/bin/hanasand-tunnel"]
