import { test, expect } from '@playwright/test'

test.use({ baseURL: 'http://127.0.0.1:3265' })
test.skip(process.env.THESIS_CODE_TEST !== '1', 'Requires the isolated code-review fixture.')
test('settings persist per sheet; source reviews and map work; readers cannot access source', async({ page, context, request }) => {
    test.setTimeout(180000)
    await context.addCookies([{ name: 'id', value: 'eirikhanasand', url: 'http://127.0.0.1:3265' }, { name: 'access_token', value: 'synthetic-owner', url: 'http://127.0.0.1:3265' }])
    await page.routeWebSocket('**/api/ws/thesis', socket => socket.close())
    const document = await (await request.get('http://127.0.0.1:3262/api/thesis')).json()
    const sheets = [{ id: 'Overview', name: 'Overview', title: '# Overview', body: 'Hello' }, { id: 'Code', name: 'Code', title: '# Code', body: 'Review workspace' }]
    const body = '<!-- thesis-workspace:2 ' + encodeURIComponent(JSON.stringify(sheets.map(({ body: content, ...sheet }) => ({ ...sheet, length: content.length })))).replace(/-/g, '%2D') + ' -->\n' + sheets.map(sheet => sheet.body).join('\n\n')
    const seed = await request.put('http://127.0.0.1:3262/api/thesis', { headers: { id: 'eirikhanasand', Authorization: 'Bearer synthetic-owner' }, data: { ...document, body } })
    expect(seed.ok()).toBe(true)
    await page.goto('/thesis?sheet=Code')
    await page.getByRole('tab', { name: 'Code', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Code review workspace', exact: true })).toBeVisible()
    await expect(page.getByRole('combobox', { name: 'Repository scope' })).toBeVisible({ timeout: 60000 })
    const inventoryResponse = await page.request.get('/api/thesis/code')
    expect(inventoryResponse.ok()).toBe(true)
    const inventory = await inventoryResponse.json()
    expect(inventory.nodes.length).toBeGreaterThan(1000)
    expect(inventory.nodes.every((item: { content?: string }) => item.content === undefined)).toBe(true)
    const source = inventory.nodes.find((item: { id: string }) => item.id === 'source:frontend/src/utils/codeReviewTypes.ts')
    expect(source).toBeTruthy()
    await page.getByLabel('Sheet settings').click()
    await page.getByRole('checkbox', { name: 'Insert table', exact: true }).uncheck()
    await page.getByRole('checkbox', { name: 'History', exact: true }).uncheck()
    await expect(page.getByRole('button', { name: 'Insert table', exact: true })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'History', exact: true })).toHaveCount(0)
    await page.getByLabel('Sheet settings').press('Escape')
    await expect.poll(async() => (await (await request.get('http://127.0.0.1:3262/api/thesis')).json()).body.includes('insertTable'), { timeout: 20000 }).toBe(true)
    await page.reload()
    await expect(page.getByRole('button', { name: 'Insert table', exact: true })).toHaveCount(0)
    await page.getByRole('tab', { name: 'Overview', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Insert table', exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'History', exact: true })).toBeVisible()
    await page.getByRole('tab', { name: 'Code', exact: true }).click()
    await page.getByRole('combobox', { name: 'Repository scope' }).selectOption('repository')
    await page.getByRole('textbox', { name: 'Search code inventory' }).fill('frontend/src/utils/codeReviewTypes.ts')
    await page.getByRole('complementary', { name: 'Alphabetical code inventory' }).getByRole('button').filter({ hasText: 'frontend/src/utils/codeReviewTypes.ts' }).click()
    const detail = page.getByRole('article', { name: 'Selected code item' })
    await expect(detail.locator('pre')).toContainText('reviewStatus')
    await detail.getByRole('button', { name: 'Review status: Not reviewed', exact: true }).click()
    await detail.getByRole('button', { name: 'Approve this version', exact: true }).click()
    await expect(detail.getByRole('button', { name: 'Review status: Approved', exact: true })).toBeVisible()
    await expect(detail.getByRole('region', { name: 'Review history' })).toContainText('eirikhanasand')
    const stale = await page.request.post('/api/thesis/code', { headers: { Origin: 'http://127.0.0.1:3265' }, data: { id: source.id, sha256: source.sha256, reviewHash: '0'.repeat(64), approved: true, eventId: '00000000-0000-4000-8000-000000000001' } })
    expect(stale.status()).toBe(409)
    await detail.getByRole('button', { name: 'Mark as needing review' }).click()
    await expect(detail.getByRole('button', { name: 'Review status: Not reviewed', exact: true })).toBeVisible()
    await expect(detail.getByRole('region', { name: 'Review history' })).toContainText('Marked for review')
    await detail.getByRole('button', { name: 'Approve this version', exact: true }).click()
    await page.getByRole('button', { name: 'Focus selected', exact: true }).click()
    await expect(page.getByRole('group', { name: 'Dependencies of frontend/src/utils/codeReviewTypes.ts' })).toBeVisible()
    await page.getByRole('button', { name: 'Zoom out', exact: true }).click()
    await expect(page.getByLabel('Map zoom')).toContainText('85%')
    await page.setViewportSize({ width: 390, height: 844 })
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await expect.poll(() => page.locator('.code-detail pre').evaluate(element => { const bounds = element.getBoundingClientRect(); return bounds.x >= 0 && bounds.right <= window.innerWidth })).toBe(true)
    await page.screenshot({ path: '/tmp/thesis-code-mobile.png', fullPage: true })
    await page.reload()
    const saved = await (await page.request.get('/api/thesis/code')).json()
    expect(saved.nodes.find((item: { id: string }) => item.id === source.id).review.approved).toBe(true)
    await context.clearCookies()
    expect((await page.request.get('/api/thesis/code')).status()).toBe(403)
    expect((await page.request.get('/api/thesis/code?id=' + encodeURIComponent(source.id))).status()).toBe(403)
    expect((await request.get('http://127.0.0.1:3262/api/thesis/code-reviews')).status()).toBe(403)
    expect((await page.request.post('/api/thesis/code', { data: {} })).status()).toBe(403)
    await page.reload()
    await expect(page.getByRole('region', { name: 'Code review workspace', exact: true })).toHaveCount(0)
    await expect(page.getByLabel('Sheet settings')).toHaveCount(0)
})
