import { test, expect } from '@playwright/test'

test.use({ baseURL: 'http://127.0.0.1:3265' })
test.skip(process.env.THESIS_CODE_TEST !== '1', 'Requires the isolated code-review fixture.')
test('map zoom, manual collapse, expanded search and Escape stay independent', async({ page, context, request }) => {
    test.setTimeout(120000)
    await context.addCookies([{ name: 'id', value: 'eirikhanasand', url: 'http://127.0.0.1:3265' }, { name: 'access_token', value: 'synthetic-owner', url: 'http://127.0.0.1:3265' }])
    await page.routeWebSocket('**/api/ws/thesis', socket => socket.close())
    const document = await (await request.get('http://127.0.0.1:3262/api/thesis')).json()
    const body = '<!-- thesis-workspace:2 ' + encodeURIComponent(JSON.stringify([{ id: 'Code', name: 'Code', title: '# Code', length: 0 }])) + ' -->\n'
    expect((await request.put('http://127.0.0.1:3262/api/thesis', { headers: { id: 'eirikhanasand', Authorization: 'Bearer synthetic-owner' }, data: { ...document, body } })).ok()).toBe(true)
    await page.goto('/thesis?sheet=Code')
    const map = page.getByRole('region', { name: 'Dependency map', exact: true })
    await expect(map).toBeVisible({ timeout: 60000 })
    const zoom = () => map.getByLabel('Map zoom').textContent().then(value => parseFloat(value || '0'))
    const nodes = map.locator('svg[role=group] [role=button]')
    const count = await nodes.count()
    expect(count).toBeGreaterThan(0)
    for (let i = 0; i < 30; i++) await map.getByRole('button', { name: 'Zoom out', exact: true }).click()
    expect(await zoom()).toBeLessThan(1)
    await expect(nodes).toHaveCount(count)
    await map.getByRole('button', { name: 'Collapse connections', exact: true }).click()
    await expect(map.locator('.code-map-summary')).toBeVisible()
    const collapsedZoom = await zoom()
    await map.getByRole('button', { name: 'Expand connections', exact: true }).click()
    expect(await zoom()).toBe(collapsedZoom)
    await expect(nodes).toHaveCount(count)
    await map.getByRole('button', { name: 'Focus selected', exact: true }).click()
    const viewport = map.getByLabel('Scrollable dependency map')
    expect(await viewport.evaluate(element => !element.dispatchEvent(new WheelEvent('wheel', { ctrlKey: true, deltaY: -50, clientX: element.getBoundingClientRect().x + 100, clientY: element.getBoundingClientRect().y + 100, bubbles: true, cancelable: true })))).toBe(true)
    await expect.poll(zoom).toBeGreaterThan(100)
    await map.getByRole('button', { name: 'Enlarge dependency map', exact: true }).click()
    await expect(map).toHaveAttribute('data-expanded', 'true')
    expect(await map.evaluate(element => Math.abs(element.getBoundingClientRect().width / innerWidth - 0.8))).toBeLessThan(0.01)
    await page.keyboard.press('Meta+j')
    const search = map.getByRole('textbox', { name: 'Find in dependency map' })
    await expect(search).toBeFocused()
    await search.fill('frontend/src/utils/codeReviewTypes.ts')
    await map.getByRole('search').getByRole('button', { name: 'frontend/src/utils/codeReviewTypes.ts', exact: true }).click()
    await expect(map.getByRole('group', { name: 'Dependencies of frontend/src/utils/codeReviewTypes.ts', exact: true })).toBeVisible()
    await expect(search).toHaveCount(0)
    await page.evaluate(() => {
        window.addEventListener('keydown', event => {
            if (event.key === 'Escape') setTimeout(() => { document.body.dataset.escapePrevented = String(event.defaultPrevented) }, 0)
        }, true)
    })
    await page.keyboard.press('Meta+j')
    await expect(search).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(search).toHaveCount(0)
    await expect(page.locator('body')).toHaveAttribute('data-escape-prevented', 'true')
    await expect(map).toHaveAttribute('data-expanded', 'true')
    await page.keyboard.press('Meta+k')
    await expect(page.getByRole('dialog', { name: 'Site search' })).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(page.getByRole('dialog', { name: 'Site search' })).toHaveCount(0)
    await expect(page.locator('body')).toHaveAttribute('data-escape-prevented', 'true')
    await expect(map).toHaveAttribute('data-expanded', 'true')
    await map.getByRole('button', { name: 'Focus selected', exact: true }).click()
    const bounds = (await viewport.boundingBox())!
    const x = Math.round(bounds.x + bounds.width / 2), y = Math.round(bounds.y + bounds.height / 2)
    const cdp = await context.newCDPSession(page)
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: x - 40, y, id: 1 }, { x: x + 40, y, id: 2 }] })
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x - 90, y, id: 1 }, { x: x + 90, y, id: 2 }] })
    await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await expect.poll(zoom).toBeGreaterThan(200)
    await page.screenshot({ path: '/tmp/dependency-map-expanded.png' })
    await map.getByRole('button', { name: 'Minimize dependency map', exact: true }).click()
    await expect(map).toHaveAttribute('data-expanded', 'false')
    await expect.poll(zoom).toBeGreaterThan(200)
    await page.setViewportSize({ width: 390, height: 844 })
    await map.getByRole('button', { name: 'Enlarge dependency map', exact: true }).click()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
