import { strict as assert } from 'node:assert'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const source = readFileSync(new URL('../src/app/dashboard/dwm/cases/[id]/case-detail-client.tsx', import.meta.url), 'utf8')
const pageSource = readFileSync(new URL('../src/app/dashboard/dwm/cases/[id]/page.tsx', import.meta.url), 'utf8')
const deliveryRouteSource = readFileSync(new URL('../src/app/api/dwm/webhooks/deliver/route.ts', import.meta.url), 'utf8')

test('DWM case detail exposes webhook delivery traceability', () => {
    assert.match(source, /<CollapsiblePanel title='Evidence rows' action=\{`\$\{evidence\.length\} rows`\}/)
    assert.match(source, /data-dwm-case-evidence-mobile-list='true'/)
    assert.match(source, /data-dwm-case-evidence-mobile-row='true'/)
    assert.match(source, /data-dwm-case-evidence-desktop-table='true'/)
    assert.match(source, /function EvidenceMobileRow/)
    assert.match(source, /import \{ safeEvidenceExcerpt \} from '@\/utils\/dwm\/display'/)
    assert.match(source, /function safeCaseEvidenceExcerpt\(row: EvidenceRow\)/)
    assert.match(source, /safeEvidenceExcerpt\(row\.safeExcerpt \|\| row\.excerpt/)
    assert.doesNotMatch(source, /\{row\.safeExcerpt \|\| row\.excerpt \|\| 'No safe excerpt available\.'\}/)
    assert.match(source, /<CollapsiblePanel title='Audit timeline' action=\{`\$\{timeline\.length\} events`\}/)
    assert.match(source, /function CollapsiblePanel/)
    assert.match(source, /sendWebhook/)
    assert.match(source, /data-third-party-report-contract='true'/)
    assert.match(source, /reportFormat: 'stix'/)
    assert.match(source, /evidenceIds: selectedEvidenceIds/)
    assert.match(source, /destinationId: selectedDestinationId/)
    assert.doesNotMatch(source, /limit: 1/)
    assert.match(source, /Select one configured receiver/)
    assert.match(source, /fetch\(`\/api\/organizations\/\$\{encodeURIComponent\(scopedOrganizationId\)\}\/webhooks`/)
    assert.match(source, /setSelectedDestinationId\(previous => destinations\.some\(destination => destination\.id === previous\) \? previous : ''\)/)
    assert.match(source, /setSelectedEvidenceIds\(previous => previous\.filter\(id => availableIds\.includes\(id\)\)\)/)
    assert.doesNotMatch(source, /previous\.length \? previous\.filter\(id => availableIds\.includes\(id\)\) : availableIds/)
    assert.match(source, /deliveryId: retryDeliveryId/)
    assert.match(source, /latestDelivery\?\.status === 'failed' && latestDelivery\.retryable === true/)
    assert.match(source, /Retry exact report/)
    assert.match(source, /delivery\.status === 'failed' \|\| delivery\.status === 'skipped'/)
    assert.match(source, /Export JSON report/)
    assert.match(source, /Export STIX 2\.1/)
    assert.match(source, /DWM_CASE_REPORT_MAX_EVIDENCE = 25/)
    assert.match(source, /data-dwm-case-action-blockers='true'/)
    assert.match(source, /function actionUnavailableReasons/)
    assert.match(source, /data-dwm-webhook-action-blocker='true'/)
    assert.match(source, /Webhook delivery needs a linked alert before it can be tested or sent\./)
    assert.match(source, /Manage destination/)
    assert.match(source, /Delivery history/)
    assert.match(source, /focus: 'destinations'/)
    assert.match(source, /fetch\(`\/api\/dwm\/webhooks\/deliveries\$\{queryString\(\{ organizationId: scopedOrganizationId, alertId: scopedAlertId, reportCaseId: caseId \}\)\}`/)
    assert.match(source, /deliveries = deliveryRowsFromApi\(deliveryPayload\)/)
    assert.match(source, /\.filter\(delivery => delivery\.thirdPartyReport === true && delivery\.reportCaseId === caseId\)/)
    assert.match(source, /reportExportChecksum: stringValue\(row\.reportExportChecksum\)/)
    assert.match(source, /deliveryContext: deliveryContextFromApi\(orderedDeliveries\)/)
    assert.match(source, /const deliveries = orderCaseDeliveries\(state\.detail\.deliveries \|\| state\.exportPayload\?\.deliveryEvidence \|\| \[\]\)/)
    assert.match(source, /const latestDelivery = deliveries\[0\]/)
    assert.doesNotMatch(source, /state\.detail\.deliveryContext\?\.latestDelivery \|\| deliveries\[0\]/)
    assert.match(source, /function orderCaseDeliveries\(rows: DeliveryRow\[\]\)/)
    assert.match(source, /latestDelivery\.nextRetryAt/)
    assert.match(source, /function deliveryRetryBlockedReason/)
    assert.match(source, /Exact report retry is available at/)
    assert.match(source, /latestDelivery\.requestId \|\| latestDelivery\.auditEventId/)
    assert.match(source, /\/dashboard\/dwm\$\{queryString\(\{ tenantId, organizationId, alert: alertId \}\)\}/)
    assert.match(source, /Selected alert/)
    assert.match(source, /const caseMeta = \[/)
    assert.match(source, /compactCaseReference\(caseRecord\.id, 'Case'\)/)
    assert.match(source, /compactCaseReference\(scopedOrganizationId, 'Org'\)/)
    assert.match(source, /compactCaseReference\(scopedAlertId, 'Alert'\)/)
    assert.match(source, /compactCaseReference\(detail\.alert\?\.id \|\| detail\.case\?\.alertId, 'Alert'\)/)
    assert.match(source, /compactCaseReference\(organizationId, 'Org'\)/)
    assert.doesNotMatch(source, /\{caseRecord\.id\} · \{caseRecord\.organizationId \|\| organizationId \|\| 'organization pending'\}/)
    assert.doesNotMatch(source, /value=\{organizationId \|\| tenantId\}/)
    assert.doesNotMatch(source, /\/api\/dwm\/alerts/)
    assert.doesNotMatch(source, /What returned/)
})

test('DWM case detail loads through the authenticated tenant proxy', () => {
    assert.doesNotMatch(pageSource, /loadCaseDetail/)
    assert.doesNotMatch(pageSource, /loadCaseExport/)
    assert.match(pageSource, /cookieStore\.get\('id'\)/)
    assert.match(pageSource, /cookieStore\.get\('access_token'\)/)
    assert.match(source, /fetch\(`\/api\/cases\/\$\{encodeURIComponent\(caseId\)\}\$\{query\}`/)
    assert.match(source, /initialDetail\?: CaseDetail/)
    assert.match(source, /loading: !initialDetail/)
    assert.match(source, /detail: initialDetail/)
})

test('report delivery resolves the selected case export server-side before forwarding', () => {
    assert.match(deliveryRouteSource, /reportUrl\.searchParams\.set\('report', 'true'\)/)
    assert.match(deliveryRouteSource, /if \(deliveryId && organizationId\)/)
    assert.match(deliveryRouteSource, /body: JSON\.stringify\(\{ organizationId, orgId: organizationId, tenantId: organizationId, deliveryId \}\)/)
    assert.match(deliveryRouteSource, /`\/v1\/cases\/\$\{encodeURIComponent\(reportRequest\.value\.caseId\)\}\/export`/)
    assert.match(deliveryRouteSource, /dedupeKey: checksum/)
    assert.match(deliveryRouteSource, /reportAlertId !== fetchedAlertId/)
    assert.match(deliveryRouteSource, /fetchedAlertId !== alertId/)
    assert.match(deliveryRouteSource, /unsupported_report_format/)
    assert.match(deliveryRouteSource, /report,/)
    assert.match(deliveryRouteSource, /evidenceIds\.length > 25/)
    assert.match(deliveryRouteSource, /new Set\(requested\)\.size !== requested\.length/)
    assert.match(deliveryRouteSource, /report_duplicate_evidence_selection/)
    assert.match(deliveryRouteSource, /report_destination_required/)
    assert.match(deliveryRouteSource, /destinationId: reportRequest\.value\?\.destinationId/)
    assert.match(deliveryRouteSource, /const evidenceIds = requested\.sort\(\)/)
    assert.doesNotMatch(deliveryRouteSource, /report:\s*body\.report/)
})
