import { strict as assert } from 'node:assert'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const source = readFileSync(new URL('../src/app/dashboard/dwm/cases/[id]/case-detail-client.tsx', import.meta.url), 'utf8')
const pageSource = readFileSync(new URL('../src/app/dashboard/dwm/cases/[id]/page.tsx', import.meta.url), 'utf8')

test('DWM case detail exposes webhook delivery traceability', () => {
    assert.match(source, /<CollapsiblePanel title='Evidence rows' action=\{`\$\{evidence\.length\} rows`\}/)
    assert.match(source, /data-dwm-case-evidence-mobile-list='true'/)
    assert.match(source, /data-dwm-case-evidence-mobile-row='true'/)
    assert.match(source, /data-dwm-case-evidence-desktop-table='true'/)
    assert.match(source, /function EvidenceMobileRow/)
    assert.match(source, /import \{ safeEvidenceExcerpt \} from '@\/utils\/dwm\/display'/)
    assert.match(source, /function safeCaseEvidenceExcerpt\(row: EvidenceRow\)/)
    assert.match(source, /safeEvidenceExcerpt\(row\.safeExcerpt \|\| row\.excerpt/)
    assert.doesNotMatch(source, /\{row\.safeExcerpt \|\| row\.excerpt \|\| 'No safe excerpt available\.'\}/)
    assert.match(source, /<CollapsiblePanel title='Audit timeline' action=\{`\$\{timeline\.length\} events`\}/)
    assert.match(source, /function CollapsiblePanel/)
    assert.match(source, /sendWebhook/)
    assert.match(source, /data-dwm-case-action-blockers='true'/)
    assert.match(source, /function actionUnavailableReasons/)
    assert.match(source, /data-dwm-webhook-action-blocker='true'/)
    assert.match(source, /Webhook delivery needs a linked alert before it can be tested or sent\./)
    assert.match(source, /Manage destination/)
    assert.match(source, /Delivery history/)
    assert.match(source, /focus: 'destinations'/)
    assert.match(source, /const deliveries = orderCaseDeliveries\(state\.detail\.deliveries \|\| state\.exportPayload\?\.deliveryEvidence \|\| \[\]\)/)
    assert.match(source, /function orderCaseDeliveries\(rows: DeliveryRow\[\]\)/)
    assert.match(source, /latestDelivery\.nextRetryAt/)
    assert.match(source, /latestDelivery\.requestId \|\| latestDelivery\.auditEventId/)
    assert.match(source, /\/dashboard\/dwm\$\{queryString\(\{ tenantId, organizationId, alert: alertId \}\)\}/)
    assert.match(source, /Selected alert/)
    assert.match(source, /const caseMeta = \[/)
    assert.match(source, /compactCaseReference\(caseRecord\.id, 'Case'\)/)
    assert.match(source, /compactCaseReference\(scopedOrganizationId, 'Org'\)/)
    assert.match(source, /compactCaseReference\(scopedAlertId, 'Alert'\)/)
    assert.match(source, /compactCaseReference\(detail\.alert\?\.id \|\| detail\.case\?\.alertId, 'Alert'\)/)
    assert.match(source, /compactCaseReference\(organizationId, 'Org'\)/)
    assert.doesNotMatch(source, /\{caseRecord\.id\} · \{caseRecord\.organizationId \|\| organizationId \|\| 'organization pending'\}/)
    assert.doesNotMatch(source, /value=\{organizationId \|\| tenantId\}/)
    assert.doesNotMatch(source, /\/api\/dwm\/alerts/)
    assert.doesNotMatch(source, /What returned/)
})

test('DWM case detail loads through the authenticated tenant proxy', () => {
    assert.doesNotMatch(pageSource, /loadCaseDetail/)
    assert.doesNotMatch(pageSource, /loadCaseExport/)
    assert.match(pageSource, /cookieStore\.get\('id'\)/)
    assert.match(pageSource, /cookieStore\.get\('access_token'\)/)
    assert.match(source, /fetch\(`\/api\/cases\/\$\{encodeURIComponent\(caseId\)\}\$\{query\}`/)
    assert.match(source, /initialDetail\?: CaseDetail/)
    assert.match(source, /loading: !initialDetail/)
    assert.match(source, /detail: initialDetail/)
})
