import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import path from 'node:path'

const root = process.cwd()

test('dashboard DWM keeps scoped workflow and durable delivery wording', async () => {
    const dwmPage = await readFile(path.join(root, 'src/app/dashboard/dwm/page.tsx'), 'utf8')
    const dwmPortal = await readFile(path.join(root, 'src/app/dashboard/dwm/dwm-analyst-portal.tsx'), 'utf8')
    const dashboardPage = await readFile(path.join(root, 'src/app/dashboard/page.tsx'), 'utf8')
    const workflowActions = await readFile(path.join(root, 'src/app/dashboard/dwm/dwm-workflow-actions.tsx'), 'utf8')
    const workbench = await readFile(path.join(root, 'src/app/dashboard/ti/workbench/workbenchClient.tsx'), 'utf8')
    const caseDetail = await readFile(path.join(root, 'src/app/dashboard/dwm/cases/[id]/case-detail-client.tsx'), 'utf8')

    expect(dwmPage).toContain('<DwmAnalystPortal')
    expect(dwmPage).toContain('snapshot={loadingSnapshot(tenantId)}')
    expect(dwmPage).toContain('dataHealth={loadingDataHealth()}')
    expect(dwmPage).toContain('view={normalizeDwmView(firstParam(params?.panel))}')
    expect(dwmPage).not.toContain('mergeDwmAlerts')
    expect(dwmPortal).not.toContain('fallbackAlerts')
    expect(dashboardPage).toContain('redirect(\'/dashboard/overview\')')
    expect(workflowActions).toContain('<RouteRunSummary route={lastRoute} organizationId={organizationId} />')
    expect(workflowActions).toContain('function organizationDestinationPath(organizationId: string, alertId?: string, caseId?: string)')
    expect(workflowActions).toContain('focus: \'destinations\'')
    expect(workflowActions).toContain('#delivery-history')
    expect(workflowActions).toContain('Open delivery log')
    expect(workflowActions).toContain('data-dwm-workflow-result-action=\'true\'')
    expect(workflowActions).toContain('deliverySetupHref(organizationId, alert.id, caseId || undefined)')
    expect(workflowActions).toContain('No destination yet. Add or test an HTTPS Discord/webhook endpoint before sending.')
    expect(workflowActions).toContain('Test saves a delivery attempt without sending externally.')
    expect(workflowActions).toContain('webhookUrl: webhookConfigured ? webhookUrl.trim() : undefined')
    expect(workflowActions).toContain('Enter an HTTPS webhook URL or open an organization with a saved delivery destination before sending queued alerts.')
    expect(workflowActions).toContain('alert linked')
    expect(workflowActions).toContain('data-dwm-command-disabled-reason=\'true\'')
    expect(workflowActions).toContain('{action.disabledReason}')
    expect(workflowActions).toContain('function rebuiltAlertSummary(alert: Record<string, unknown>)')
    expect(workflowActions).toContain('formatClaimSummary(readString(alert.claimSummary)')
    expect(workflowActions).not.toContain('{route.alertId}</span>')
    expect(workflowActions).not.toContain('const summary = readString(alert.claimSummary).toLowerCase()')
    expect(dwmPortal).toContain('no durable delivery result was returned')
    expect(workflowActions).toContain('No durable delivery result was returned.')
    expect(workflowActions).toContain('const deliveredCount = deliveryRows.filter(row => row.status === \'delivered\' && row.dryRun !== true).length')
    expect(workflowActions).toContain('Webhook delivery recorded a dry-run; no customer notification was sent.')
    expect(workflowActions).toContain('Webhook delivery recorded a failed attempt.')
    expect(workflowActions).not.toContain('Webhook delivery attempted for ${attemptedCount} alert(s).')
    expect(workflowActions).toContain('Webhook test recorded a dry-run delivery.')
    expect(workflowActions).toContain('Webhook test recorded a failed delivery attempt.')
    expect(workbench).toContain('return \'No durable delivery result was returned.\'')
    expect(workbench).not.toContain('Webhook delivery attempted for ${payload.attemptedCount} alert')
    expect(caseDetail).toContain('Webhook delivery stores the exact report and receipt.')

    expect(dashboardPage).not.toContain('DWM alerts returned HTTP')
    expect(dashboardPage).not.toContain('What returned')
    expect(workflowActions).not.toContain('No delivery was ready')
    expect(workflowActions).not.toContain('Delivery was not ready')
    expect(workflowActions).not.toContain('Stage a webhook when the case needs customer notification.')
    expect(workflowActions).not.toContain('Every command calls the DWM API')
    expect(workflowActions).not.toContain('Dry-run uses this endpoint and records the delivery result without external send by default.')
    expect(workflowActions).not.toContain('Paste an HTTPS Discord or webhook endpoint before testing customer delivery.')
})

test('product progress uses persisted evidence instead of synthetic readiness rows', async () => {
    const route = await readFile(path.join(root, 'src/app/api/product-progress/route.ts'), 'utf8')

    expect(route).not.toMatch(/synthetic(?:Organization|Webhook|Deliveries|Cases|Analyst|Support)/)
    expect(route).not.toContain('sourceCount < 1000')
    expect(route).toContain('const organizationProof = organizationReadinessProof(organizationReadiness)')
    expect(route).toContain('const selectedCaseProof = analystCaseDetailProof(selectedCaseDetail')
})
