import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import path from 'node:path'

const root = process.cwd()

test('organization workspace keeps launch workflow primary and admin controls disclosed', async () => {
    const page = await readFile(path.join(root, 'src/app/organizations/organizationWorkspaceClient.tsx'), 'utf8')

    expect(page).toContain('data-org-setup-progress')
    expect(page).toContain('data-org-watchlist-starter')
    expect(page).toContain('data-org-watchlist-suggestion=\'true\'')
    expect(page).toContain('starterWatchlistSuggestions(selectedOrganization, bundle.watchlists)')
    expect(page).toContain('setDraft({ kind: suggestion.kind, value: suggestion.value, notes: suggestion.notes })')
    expect(page).toContain('firstDomainCandidate')
    expect(page).toContain('data-org-health-strip')
    expect(page).toContain('Workspace health')
    expect(page).toContain('Notification setup')
    expect(page).toContain('Shared watchlists')
    expect(page).toContain('Test destination')
    expect(page).toContain('/api/organizations/${encodeURIComponent(selectedOrganization.id)}/watchlists')
    expect(page).toContain('/api/dwm/webhooks/deliver')

    expect(page).toContain('data-org-settings-disclosure')
    expect(page).toContain('Advanced organization settings')
    expect(page).toContain('data-org-members-disclosure')
    expect(page).toContain('data-org-destinations-disclosure')
    expect(page).toContain('Saved destinations')

    expect(page.indexOf('<WatchlistPanel')).toBeLessThan(page.indexOf('<SettingsPanel'))
    expect(page.indexOf('data-org-settings-disclosure')).toBeLessThan(page.indexOf('Save settings'))
    expect(page.indexOf('data-org-members-disclosure')).toBeLessThan(page.indexOf('Remove member'))
    expect(page.indexOf('data-org-destinations-disclosure')).toBeLessThan(page.indexOf('Remove destination'))

    expect(page).toContain('onRoleChange={(member, role) => void changeMemberRole(member, role)}')
    expect(page).toContain('onTest={destination => void testSavedDestination(destination)}')
    expect(page).toContain('onDelete={destination => void deleteSavedDestination(destination)}')
    expect(page).toContain('admin controls enabled')
    expect(page).toContain('read-only access')
    expect(page).toContain('return <span className={classes} aria-disabled=\'true\'>{icon}{label}</span>')
    expect(page).toContain('? <span key={row.id} className={rowClass} aria-disabled=\'true\'>{content}</span>')
    expect(page).toContain('role={tone === \'error\' ? \'alert\' : \'status\'}')
    expect(page).toContain('role={message.ok ? \'status\' : \'alert\'}')
    expect(page).toContain('role=\'status\' aria-live=\'polite\'')
    expect(page).toContain('aria-pressed={confirming}')
    expect(page).toContain('data-org-confirm-action={confirming ? \'confirming\' : \'idle\'}')
    expect(page).toContain('if (event.key === \'Escape\')')
    expect(page).toContain('aria-pressed={selected}')
    expect(page).toContain('role=\'button\'')
    expect(page).toContain('tabIndex={0}')
    expect(page).toContain('event.preventDefault()')
    expect(page).toContain('onSelectSubject({ type: \'watchlist\', id: item.id })')
    expect(page).toContain('function stopRowSelectionKeys')
    expect(page).toContain('onKeyDown={stopRowSelectionKeys}')
    expect(page).toContain('event.stopPropagation()')
    expect(page).toContain('onSelectSubject={selectActivitySubject}')
    expect(page).toContain('replaceOrganizationWorkspaceSelectionUrl')
    expect(page).toContain('requestedInviteId')
    expect(page).toContain('requestedMemberId')
    expect(page).toContain('input.focus === \'invites\'')
    expect(page).toContain('input.focus === \'members\'')
    expect(page).toContain('data-org-activity-row=\'true\'')
    expect(page).toContain('activitySubjectFromItem(item, organization.id)')
    expect(page).toContain('onClick={() => itemSubject && onSelectSubject(itemSubject)}')
    expect(page).toContain('data-org-activity-context-action=\'true\'')
    expect(page).toContain('selectedSubjectActions(selectedSubject, organization)')
    expect(page).toContain('Audit trail')
    expect(page).toContain('Delivery activity')
    expect(page).toContain('href: \'#delivery-history\'')
    expect(page).toContain('/dashboard/ti/workbench?organizationId=${organizationId}&watchlistId=${watchlistId}')
    expect(page).toContain('/dashboard/dwm/cases/${caseId}?organizationId=${organizationId}')
    expect(page).not.toContain('Org API')
    expect(page).not.toContain('Invite API')
    expect(page).not.toContain('Member API')
    expect(page).not.toContain('Cases API')
    expect(page).toContain('Open delivery log')
    expect(page).not.toContain('Open API')
    expect(page).not.toContain('/api/organizations/${organizationId}/watchlists/alert-terms?watchlistId=${watchlistId}')
    expect(page).not.toContain('/api/dwm/webhooks/deliveries?organizationId=${organizationId}&destinationId=${destinationId}')

    expect(page).toContain('bg-ui-text px-4 text-sm font-semibold text-ui-canvas')
    expect(page).not.toContain('dark:text-white')
    expect(page).not.toContain('text-white transition')
})
