import { expect, test } from '@playwright/test'

test('role controls create, edit and remove roles without a Shift shortcut', async ({ browser, baseURL }) => {
    test.skip(process.env.ROLE_MANAGEMENT_TEST !== '1', 'Requires the isolated role management fixture.')
    test.setTimeout(90000)
    expect(baseURL).toBe('http://127.0.0.1:3230')
    const context = await browser.newContext()
    await context.addCookies(['id', 'name', 'access_token'].map(name => ({ name, value: 'role-fixture-admin', url: baseURL! })))
    await context.route(/\/api\/role(?:\/|$)/, async route => {
        const request = route.request()
        const response = await context.request.fetch('http://127.0.0.1:3231' + new URL(request.url()).pathname, { method: request.method(), data: request.postData(), headers: { 'Content-Type': 'application/json' } })
        await route.fulfill({ response })
    })
    const page = await context.newPage()
    await page.goto('/management')
    await page.getByRole('button', { name: 'Add role', exact: true }).click()
    const form = page.getByRole('form', { name: 'Add role', exact: true })
    await form.getByLabel('Name', { exact: true }).fill('Review team')
    await form.getByLabel('Description').fill('Reviews reports.')
    await form.getByRole('button', { name: 'Create role' }).click()
    await expect(page.getByText('Review team', { exact: true })).toBeVisible()
    await page.reload({ waitUntil: 'domcontentloaded' })
    await expect(page.getByText('Review team', { exact: true })).toBeVisible()
    await page.keyboard.down('Shift')
    await page.getByText('Review team', { exact: true }).click()
    await page.keyboard.up('Shift')
    await expect(page.getByText('Review team', { exact: true })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Delete Review team', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Edit roles', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Delete Administrator', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Edit Review team', exact: true }).click()
    const edit = page.getByRole('form', { name: 'Edit role', exact: true })
    await edit.getByLabel('Name', { exact: true }).fill('Reviewers')
    await edit.getByRole('button', { name: 'Save', exact: true }).click()
    await expect(page.getByText('Reviewers', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Delete Reviewers', exact: true }).click()
    await page.getByRole('alertdialog').getByRole('button', { name: 'Cancel' }).click()
    await expect(page.getByText('Reviewers', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Delete Reviewers', exact: true }).click()
    await page.getByRole('alertdialog').getByRole('button', { name: 'Delete role', exact: true }).click()
    await expect(page.getByText('Reviewers', { exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Add role', exact: true }).click()
    await form.getByLabel('Name', { exact: true }).fill('User Administrator')
    await form.getByRole('button', { name: 'Create role' }).click()
    await expect(page.getByText('Role already exists', { exact: true })).toBeVisible()
    await expect(form.getByLabel('Name', { exact: true })).toHaveValue('User Administrator')
    await form.getByRole('button', { name: 'Cancel' }).click()
    for (const width of [390, 768, 1440]) {
        await page.setViewportSize({ width, height: 900 })
        const add = await page.getByRole('button', { name: 'Add role', exact: true }).boundingBox()
        expect(add!.x).toBeGreaterThanOrEqual(0)
        expect(add!.x + add!.width).toBeLessThanOrEqual(width)
    }
    await page.screenshot({ path: '/tmp/roles-management.png' })
    await context.close()
    const reader = await browser.newContext()
    await reader.addCookies(['id', 'name', 'access_token'].map(name => ({ name, value: 'role-fixture-reader', url: baseURL! })))
    const readerPage = await reader.newPage()
    await readerPage.goto('/management')
    await expect(readerPage.getByRole('heading', { name: 'Roles', exact: true })).toBeVisible()
    await expect(readerPage.getByRole('button', { name: 'Add role', exact: true })).toHaveCount(0)
    await expect(readerPage.getByRole('button', { name: 'Edit roles', exact: true })).toHaveCount(0)
    await reader.close()
})
