import { expect, test } from '@playwright/test'
import assert from 'node:assert/strict'
test('service account creation and mandatory deletion confirmation', async ({ browser, baseURL }) => {
    assert(baseURL)
    const context = await browser.newContext({viewport:{width:1280,height:1000}, extraHTTPHeaders:{'x-hanasand-render-proof-auth':'local-dashboard-render-proof'}})
    await context.addCookies([{name:'id',value:'dashboard-render-proof-user',url:baseURL},{name:'access_token',value:'local-dashboard-render-proof-token',url:baseURL},{name:'roles',value:JSON.stringify([{id:'system_admin',name:'System administrator',priority:0}]),url:baseURL}])
    let accounts=[{id:'svc_fixture',name:'Existing monitor',active:true,created_at:'2026-09-01T12:00:00Z',keys:[{lastUsedAt:'2026-09-12T12:00:00Z',scopes:[{method:'GET',route:'/api/service-accounts/self'}]}]}]
    let deletes=0, creates=0
    const endpoints=[{method:'GET',route:'/api/service-accounts/self',label:'Check authentication'},{method:'GET',route:'/api/db',label:'Read database overview'}]
    await context.route(url=>url.pathname.startsWith('/api/service-accounts'),async route=>{
        const req=route.request()
        if(req.method()==='POST'){creates++; const body=req.postDataJSON(); assert.deepEqual(body.scopes,[{method:'GET',route:'/api/db'}]);accounts.push({id:'svc_new',name:body.name,active:true,created_at:'2026-09-12T12:00:00Z',keys:[]});await route.fulfill({json:{secret:'fixture-shown-once'}})}
        else if(req.method()==='DELETE'){deletes++;accounts=accounts.filter(a=>!req.url().endsWith(a.id));await route.fulfill({json:{message:'revoked'}})}
        else await route.fulfill({json:{accounts,endpoints}})
    })
    const page=await context.newPage()
    const errors: string[]=[];page.on('pageerror',e=>errors.push(e.message))
    await page.goto(`${baseURL}/management/service-accounts`)
    await page.getByText('Existing monitor',{exact:true}).waitFor()
    await page.evaluate(() => sessionStorage.setItem('account-delete-confirmation:dashboard-render-proof-user', 'skip'))
    await expect(page.getByLabel('Name',{exact:true})).toBeHidden()
    await page.getByRole('button',{name:'Add service account',exact:true}).click()
    await expect(page.getByLabel('Name',{exact:true})).toBeFocused()
    await page.getByLabel('Name',{exact:true}).fill('Database check')
    await page.getByLabel(/Read database overview/).check()
    await page.getByRole('button',{name:'Create service account',exact:true}).click()
    await page.getByText('fixture-shown-once',{exact:true}).waitFor()
    assert.equal(creates,1)
    await page.getByRole('button',{name:'Dismiss key'}).click()
    await page.getByRole('button',{name:'Delete Existing monitor',exact:true}).click()
    assert.equal(deletes,0)
    await page.getByRole('dialog').waitFor()
    await page.keyboard.press('Escape')
    assert.equal(await page.getByRole('dialog').count(),0)
    await page.getByRole('button',{name:'Delete Existing monitor',exact:true}).click()
    await expect(page.getByRole('dialog').getByLabel('Don’t ask again for this session')).toHaveCount(0)
    await page.getByRole('dialog').getByRole('button',{name:'Delete',exact:true}).click()
    await page.getByText('Existing monitor',{exact:true}).waitFor({state:'hidden'})
    assert.equal(deletes,1)
    await page.reload()
    await page.getByRole('button',{name:'Delete Database check',exact:true}).click()
    await expect(page.getByRole('dialog',{name:'Delete Database check?'})).toBeVisible()
    assert.equal(deletes,1)
    await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click()
    assert.equal(deletes,1)
    await page.getByRole('button',{name:'Delete Database check',exact:true}).click()
    await page.getByRole('dialog').getByRole('button',{name:'Delete',exact:true}).click()
    await page.getByText('Database check',{exact:true}).waitFor({state:'hidden'})
    assert.equal(deletes,2)
    assert.deepEqual(errors,[])
    console.log('UI passed: creation, scopes, one-time secret, cancellation/Escape, mandatory deletion confirmation despite saved skip preference and reload. No browser errors.')
    await context.close()
})

test('service account search, sorting, dialog keyboard controls and failed creation', async ({ browser, baseURL }) => {
    assert(baseURL)
    const context = await browser.newContext({viewport:{width:1280,height:900},extraHTTPHeaders:{'x-hanasand-render-proof-auth':'local-dashboard-render-proof'}})
    await context.addCookies([{name:'id',value:'dashboard-render-proof-user',url:baseURL},{name:'access_token',value:'local-dashboard-render-proof-token',url:baseURL},{name:'roles',value:JSON.stringify([{id:'system_admin',name:'System administrator',priority:0}]),url:baseURL}])
    const endpoints = [{method:'GET',route:'/api/db',label:'Read database'},{method:'POST',route:'/api/db',label:'Write database'}]
    const accounts = [
        {id:'svc_zulu',name:'Zulu monitor',active:true,created_at:null,keys:[]},
        {id:'svc_alpha',name:'alpha database',active:true,created_at:null,keys:[{lastUsedAt:null,scopes:[endpoints[0]]}]},
        {id:'svc_beta',name:'Beta monitor',active:true,created_at:null,keys:[]},
        {id:'svc_revoked',name:'Revoked monitor',active:false,created_at:null,keys:[]},
    ]
    await context.route(url=>url.pathname.startsWith('/api/service-accounts'),async route=>{
        if(route.request().method()==='POST') {
            assert.deepEqual(route.request().postDataJSON(), {name:'New monitor',description:'',scopes:[{method:'GET',route:'/api/db'}]})
            await route.fulfill({status:400,json:{error:'Creation failed; try again.'}})
        } else await route.fulfill({json:{accounts,endpoints}})
    })
    const page = await context.newPage()
    await page.goto(`${baseURL}/management/service-accounts`)
    const names = page.locator('tbody tr > td:first-child')
    await expect(names).toHaveText(['alpha database','Beta monitor','Zulu monitor'])
    await page.getByLabel('Sort service accounts').selectOption('desc')
    await expect(names).toHaveText(['Zulu monitor','Beta monitor','alpha database'])
    const search = page.getByRole('searchbox',{name:'Search service accounts'})
    await page.keyboard.press('Meta+j')
    await expect(search).toBeFocused()
    await search.fill('  ALPHA  ')
    await expect(names).toHaveText(['alpha database'])
    await search.fill('/api/db')
    await expect(names).toHaveText(['alpha database'])
    await search.fill('svc_beta')
    await expect(names).toHaveText(['Beta monitor'])
    await search.fill('no match')
    await expect(page.getByText('No service accounts match your search.')).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(names).toHaveCount(3)
    await search.blur()
    await page.keyboard.press('Control+j')
    await expect(search).toBeFocused()
    const add = page.getByRole('button',{name:'Add service account',exact:true})
    await add.click()
    const dialog = page.getByRole('dialog',{name:'Add service account'})
    await expect(dialog).toBeVisible()
    await expect(dialog.getByLabel('Name',{exact:true})).toBeFocused()
    await page.keyboard.press('Shift+Tab')
    await expect(dialog.getByRole('button',{name:'Close create service account'})).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(dialog.getByLabel('Name',{exact:true})).toBeFocused()
    await page.keyboard.press('Meta+j')
    await expect(dialog.getByLabel('Name',{exact:true})).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(dialog).toBeHidden()
    await expect(add).toBeFocused()
    await add.click()
    await dialog.getByLabel('Name',{exact:true}).fill('New monitor')
    await dialog.getByLabel(/Read database/).check()
    await expect(dialog.getByLabel(/Write database/)).not.toBeChecked()
    await dialog.getByRole('button',{name:'Create service account',exact:true}).click()
    await expect(dialog.getByRole('alert')).toHaveText('Creation failed; try again.')
    await expect(dialog.getByLabel('Name',{exact:true})).toHaveValue('New monitor')
    await dialog.getByRole('button',{name:'Cancel',exact:true}).click()
    await page.screenshot({path:'/tmp/service-accounts-desktop.png',fullPage:true})
    await page.setViewportSize({width:390,height:844})
    await add.click()
    await expect(dialog).toBeVisible()
    const box = await dialog.boundingBox()
    assert(box && box.x >= 0 && box.x + box.width <= 390 && box.height <= 844)
    await page.screenshot({path:'/tmp/service-accounts-mobile-dialog.png',fullPage:true})
    await context.close()
})

test('descriptions persist, can be edited and searched, and long text opens in an accessible popup', async ({ browser, baseURL }) => {
    assert(baseURL)
    const context = await browser.newContext({viewport:{width:1280,height:900},extraHTTPHeaders:{'x-hanasand-render-proof-auth':'local-dashboard-render-proof'}})
    await context.addCookies([{name:'id',value:'dashboard-render-proof-user',url:baseURL},{name:'access_token',value:'local-dashboard-render-proof-token',url:baseURL},{name:'roles',value:JSON.stringify([{id:'system_admin',name:'System administrator',priority:0}]),url:baseURL}])
    const endpoints = [{method:'GET',route:'/api/db',label:'Read database'}]
    const accounts = [{id:'svc_existing',name:'Existing monitor',description:'Checks authentication',active:true,created_at:null,keys:[]}]
    const longDescription = 'Checks production database health and correlates backup results.\nAlerts the infrastructure team when replication or scheduled verification fails. <script>plain text only</script>'
    let failSave = true
    await context.route(url=>url.pathname.startsWith('/api/service-accounts'),async route=>{
        const req = route.request()
        if (req.method()==='POST') {
            const body = req.postDataJSON()
            assert.equal(body.description, longDescription)
            accounts.push({id:'svc_new',name:body.name,description:body.description,active:true,created_at:null,keys:[]})
            await route.fulfill({json:{secret:'fixture-secret'}})
        } else if (req.method()==='PATCH') {
            if (failSave) { failSave = false; await route.fulfill({status:500,json:{error:'Unable to save; try again.'}}); return }
            const account = accounts.find(account=>req.url().endsWith(account.id))!
            account.description = req.postDataJSON().description
            await route.fulfill({json:{id:account.id,description:account.description}})
        } else await route.fulfill({json:{accounts,endpoints}})
    })
    const page = await context.newPage()
    const errors: string[] = []; page.on('pageerror', error=>errors.push(error.message))
    await page.goto(`${baseURL}/management/service-accounts`)
    await expect(page.locator('span').filter({hasText:/^Checks authentication$/})).toBeVisible()
    await page.getByRole('button',{name:'Add service account',exact:true}).click()
    await page.getByLabel('Name',{exact:true}).fill('Database monitor')
    await page.getByLabel('Description (optional)',{exact:true}).fill(longDescription)
    await page.getByLabel(/Read database/).check()
    await page.getByRole('button',{name:'Create service account',exact:true}).click()
    await page.getByRole('button',{name:'Dismiss key'}).click()
    await page.reload()
    const info = page.getByRole('button',{name:'Description for Database monitor',exact:true})
    const popup = page.getByRole('tooltip')
    await expect(page.getByRole('tooltip',{includeHidden:true})).toBeHidden()
    await info.hover()
    await expect(popup).toHaveText(longDescription)
    await popup.hover()
    await expect(popup).toBeVisible()
    await page.screenshot({path:'/tmp/service-account-description-desktop.png',fullPage:true})
    await page.mouse.move(0,0)
    await expect(popup).toBeHidden()
    await info.focus()
    await expect(popup).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(popup).toBeHidden()
    const search = page.getByRole('searchbox',{name:'Search service accounts'})
    await search.fill('replication')
    await expect(page.locator('tbody tr > td:first-child')).toHaveText(['Database monitor'])
    await search.fill('')
    await page.getByRole('button',{name:'Edit description for Existing monitor',exact:true}).click()
    const dialog = page.getByRole('dialog',{name:'Edit description for Existing monitor'})
    await expect(dialog.getByLabel('Description',{exact:true})).toHaveValue('Checks authentication')
    await dialog.getByLabel('Description',{exact:true}).fill('Updated checks')
    await dialog.getByRole('button',{name:'Save description'}).click()
    await expect(dialog.getByRole('alert')).toHaveText('Unable to save; try again.')
    await expect(dialog.getByLabel('Description',{exact:true})).toHaveValue('Updated checks')
    await dialog.getByRole('button',{name:'Save description'}).click()
    await expect(dialog).toBeHidden()
    await page.reload()
    await expect(page.locator('span').filter({hasText:/^Updated checks$/})).toBeVisible()
    await page.getByRole('button',{name:'Edit description for Existing monitor',exact:true}).click()
    await dialog.getByLabel('Description',{exact:true}).fill('')
    await dialog.getByRole('button',{name:'Save description'}).click()
    await expect(dialog).toBeHidden()
    await page.reload()
    await expect(page.getByText('Updated checks',{exact:true})).toHaveCount(0)
    await page.setViewportSize({width:390,height:844})
    await info.click()
    await expect(popup).toHaveText(longDescription)
    const box = await popup.boundingBox()
    assert(box && box.x >= 0 && box.x + box.width <= 390 && box.y >= 0 && box.y + box.height <= 844)
    await page.screenshot({path:'/tmp/service-account-description-mobile.png',fullPage:true})
    await search.click()
    await expect(popup).toBeHidden()
    assert.deepEqual(errors,[])
    await context.close()
})
