import { expect, test } from '@playwright/test'

async function edgeDistances(locator: import('@playwright/test').Locator, width: number, height: number) {
    const box = (await locator.boundingBox())!
    return [box.x, width - box.x - box.width, box.y, height - box.y - box.height]
}

test('slow drops snap to an edge, corners are preferred, and reset restores the default', async ({ page }) => {
    await page.route('**/api/support/chat', route => route.fulfill({ json: { channel: 'ai', status: 'open', pending: false, messages: [] } }))
    await page.setViewportSize({ width: 1000, height: 800 })
    await page.goto('/contact')
    const bubble = page.getByLabel('Open support assistant', { exact: true })
    await bubble.click()
    await expect(page.getByLabel('Reset support position')).toHaveCount(0)
    await page.getByLabel('Close support assistant').click()
    let box = (await bubble.boundingBox())!
    await page.mouse.move(box.x + 32, box.y + 32)
    await page.mouse.down()
    await page.mouse.move(550, 420, { steps: 8 })
    // A paused release should not retain the earlier throwing velocity.
    await page.waitForTimeout(160)
    await page.mouse.up()
    await expect(page.getByRole('dialog', { name: 'Support assistant' })).toBeHidden()
    await expect.poll(async () => (await edgeDistances(bubble, 1000, 800))[3]).toBeCloseTo(16, 0)
    expect((await bubble.boundingBox())!.x).toBeGreaterThan(200)
    box = (await bubble.boundingBox())!
    await page.mouse.move(box.x + 32, box.y + 32)
    await page.mouse.down()
    await page.mouse.move(100, 110, { steps: 8 })
    await page.waitForTimeout(160)
    await page.mouse.up()
    await expect.poll(async () => (await bubble.boundingBox())!.x).toBeCloseTo(16, 0)
    await expect.poll(async () => (await bubble.boundingBox())!.y).toBeCloseTo(16, 0)
    await page.reload()
    await expect.poll(async () => (await bubble.boundingBox())!.x).toBeCloseTo(16, 0)
    await bubble.click()
    const dialog = page.getByRole('dialog', { name: 'Support assistant' })
    await expect.poll(async () => (await dialog.boundingBox())!.x).toBeCloseTo(16, 0)
    await expect.poll(async () => (await dialog.boundingBox())!.y).toBeCloseTo(16, 0)
    const reset = page.getByRole('button', { name: 'Reset support position' })
    await expect(reset).toBeVisible()
    await expect(reset.locator('svg circle')).toHaveAttribute('class', 'fill-blue-600')
    await page.screenshot({ path: '/tmp/support-reset-control.png' })
    await page.setViewportSize({ width: 390, height: 650 })
    await expect.poll(async () => Math.min(...await edgeDistances(dialog, 390, 650))).toBeCloseTo(16, 0)
    await expect(dialog.getByLabel('Message', { exact: true })).toBeVisible()
    await reset.click()
    await expect(reset).toHaveCount(0)
    await expect.poll(async () => (await edgeDistances(dialog, 390, 650))[3]).toBeCloseTo(16, 0)
    await page.getByLabel('Close support assistant').click()
    await page.reload()
    await expect.poll(async () => (await edgeDistances(bubble, 390, 650))[1]).toBeCloseTo(16, 0)
    await expect.poll(async () => (await edgeDistances(bubble, 390, 650))[3]).toBeCloseTo(16, 0)
})

test('a fast throw carries the bubble to the far corner and keyboard docking works', async ({ page }) => {
    await page.setViewportSize({ width: 1000, height: 800 })
    await page.route('**/api/support/chat', route => route.fulfill({ json: { channel: 'ai', status: 'open', pending: false, messages: [] } }))
    await page.goto('/contact')
    const bubble = page.getByLabel('Open support assistant', { exact: true })
    const box = (await bubble.boundingBox())!
    await page.mouse.move(box.x + 32, box.y + 32)
    await page.mouse.down()
    await page.mouse.move(550, 420, { steps: 3 })
    await page.mouse.up()
    await expect(page.getByRole('dialog', { name: 'Support assistant' })).toBeHidden()
    await expect.poll(async () => (await bubble.boundingBox())!.x).toBeCloseTo(16, 0)
    await expect.poll(async () => (await bubble.boundingBox())!.y).toBeCloseTo(16, 0)
    await bubble.click()
    const handle = page.getByRole('button', { name: 'Move support window' })
    await handle.focus()
    await page.keyboard.press('ArrowRight')
    await page.keyboard.press('ArrowDown')
    await expect(page.getByLabel('Reset support position')).toHaveCount(0)
    const dialog = page.getByRole('dialog', { name: 'Support assistant' })
    await expect.poll(async () => (await edgeDistances(dialog, 1000, 800))[1]).toBeCloseTo(16, 0)
    await expect.poll(async () => (await edgeDistances(dialog, 1000, 800))[3]).toBeCloseTo(16, 0)
    const grip = (await handle.boundingBox())!
    await page.mouse.move(grip.x + 20, grip.y + 20)
    await page.mouse.down()
    await page.mouse.move(grip.x - 260, grip.y - 100, { steps: 3 })
    await page.mouse.up()
    await expect.poll(async () => (await dialog.boundingBox())!.x).toBeCloseTo(16, 0)
    await expect.poll(async () => (await dialog.boundingBox())!.y).toBeCloseTo(16, 0)
    await expect(page.getByLabel('Reset support position')).toBeVisible()
})

test('touch throwing docks without opening and reduced motion still snaps', async ({ page, context }) => {
    await page.emulateMedia({ reducedMotion: 'reduce' })
    await page.setViewportSize({ width: 390, height: 844 })
    await page.route('**/api/support/chat', route => route.fulfill({ json: { channel: 'ai', status: 'open', pending: false, messages: [] } }))
    await page.goto('/contact')
    const bubble = page.getByLabel('Open support assistant', { exact: true })
    const start = (await bubble.boundingBox())!
    const client = await context.newCDPSession(page)
    await client.send('Emulation.setTouchEmulationEnabled', { enabled: true })
    await client.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: start.x + 32, y: start.y + 32 }] })
    await client.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 60, y: 250 }] })
    await client.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
    await expect(page.getByRole('dialog', { name: 'Support assistant' })).toBeHidden()
    await expect.poll(async () => (await bubble.boundingBox())!.x).toBeCloseTo(16, 0)
    await expect.poll(async () => (await bubble.boundingBox())!.y).toBeCloseTo(16, 0)
    await bubble.click()
    await expect(page.getByRole('dialog', { name: 'Support assistant' })).toBeVisible()
})

test('closed chat notifies for new replies, persists unread state, and clears when read', async ({ page }) => {
    await page.clock.install()
    const messages = [{ id: 'first', sender_kind: 'assistant', sender_name: 'Hanasand AI', body: 'How can I help?' }]
    await page.route('**/api/support/chat', route => route.fulfill({ json: { channel: 'human', status: 'open', pending: false, messages } }))
    await page.goto('/contact')
    await expect(page.getByRole('status', { name: '1 unread support reply' })).toBeVisible()
    await page.getByLabel('Open support assistant', { exact: true }).click()
    await expect(page.getByRole('log')).toContainText('How can I help?')
    await page.getByRole('dialog', { name: 'Support assistant' }).getByLabel('Message', { exact: true }).fill('Keep my draft')
    await page.getByLabel('Close support assistant').click()
    await expect(page.getByRole('status', { name: /unread support/ })).toHaveCount(0)
    messages.push({ id: 'user', sender_kind: 'user', sender_name: 'You', body: 'My question' }, { id: 'system', sender_kind: 'system', sender_name: 'Support', body: 'In queue' })
    await page.clock.fastForward(16000)
    await expect(page.getByRole('status', { name: /unread support/ })).toHaveCount(0)
    messages.push({ id: 'agent', sender_kind: 'support', sender_name: 'Alex', body: 'I can help you.' })
    await page.clock.fastForward(16000)
    await expect(page.getByRole('status', { name: '1 unread support reply' })).toBeVisible()
    await page.screenshot({ path: '/tmp/support-unread-badge.png' })
    await page.reload()
    await expect(page.getByRole('status', { name: '1 unread support reply' })).toBeVisible()
    await page.getByLabel('Open support assistant', { exact: true }).click()
    await expect(page.getByRole('log')).toContainText('I can help you.')
    await page.getByRole('dialog', { name: 'Support assistant' }).getByLabel('Message', { exact: true }).fill('Draft survives closing')
    await page.getByLabel('Close support assistant').click()
    await page.getByLabel('Open support assistant', { exact: true }).click()
    await expect(page.getByRole('dialog', { name: 'Support assistant' }).getByLabel('Message', { exact: true })).toHaveValue('Draft survives closing')
    await page.getByLabel('Close support assistant').click()
    await page.reload()
    await expect(page.getByRole('status', { name: /unread support/ })).toHaveCount(0)
})

test('an AI reply arriving after closing the window raises the badge', async ({ page }) => {
    const messages: { id: string; request_id?: string; sender_kind: string; sender_name: string; body: string }[] = []
    let finishReply: (() => void) | undefined
    await page.route('**/api/support/chat', async route => {
        if (route.request().method() === 'POST') {
            const body = route.request().postDataJSON()
            messages.push({ id: body.requestId, request_id: body.requestId, sender_kind: 'user', sender_name: 'You', body: body.message })
            await new Promise<void>(resolve => { finishReply = resolve })
            messages.push({ id: 'late-answer', sender_kind: 'assistant', sender_name: 'Hanasand AI', body: 'Here is your answer.' })
        }
        await route.fulfill({ json: { channel: 'ai', status: 'open', pending: false, accepted: true, messages } })
    })
    await page.goto('/contact')
    await page.getByLabel('Open support assistant', { exact: true }).click()
    const dialog = page.getByRole('dialog', { name: 'Support assistant' })
    await dialog.getByLabel('Message', { exact: true }).fill('A question')
    await dialog.getByLabel('Send message', { exact: true }).click()
    await expect.poll(() => Boolean(finishReply)).toBe(true)
    await page.getByLabel('Close support assistant').click()
    finishReply!()
    await expect(page.getByRole('status', { name: '1 unread support reply' })).toBeVisible()
    await page.getByLabel('Open support assistant', { exact: true }).click()
    await expect(dialog.getByRole('log')).toContainText('Here is your answer.')
    await expect(dialog.getByLabel('Message', { exact: true })).toHaveValue('')
})
