import { expect, test } from '@playwright/test'

test('document controls align with the title and preserve insertion, history and read-only access', async({ browser, baseURL }) => {
    test.skip(process.env.THESIS_HEADER_TEST !== '1', 'Requires the isolated thesis header fixture.')
    test.setTimeout(60000)
    expect(baseURL).toBe('http://127.0.0.1:3230')
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 } })
    await context.routeWebSocket('**/api/ws/thesis', socket => socket.close())
    await context.addCookies([{ name: 'id', value: 'eirikhanasand', url: baseURL! }, { name: 'access_token', value: 'isolated-header-owner', url: baseURL! }])
    const page = await context.newPage()
    await page.goto('/thesis')
    const region = page.getByRole('region', { name: 'Thesis document' })
    const insert = region.getByRole('button', { name: 'Insert table', exact: true })
    const history = region.getByRole('button', { name: 'History', exact: true })
    await expect(insert).toBeVisible()
    const titleBox = (await region.getByRole('heading', { name: 'Thesis header check' }).boundingBox())!
    const historyBox = (await history.boundingBox())!
    const insertBox = (await insert.boundingBox())!
    expect(Math.abs(titleBox.y - historyBox.y)).toBeLessThan(8)
    expect(insertBox.x).toBeGreaterThan(titleBox.x + titleBox.width)
    const rightInset = await region.evaluate(element => {
        const box = element.getBoundingClientRect()
        return box.right - parseFloat(getComputedStyle(element).paddingRight)
    })
    const actions = region.locator('[aria-label="Document actions"]')
    const actionBox = (await actions.boundingBox())!
    expect(Math.abs(actionBox.x + actionBox.width - rightInset)).toBeLessThan(2)
    await region.getByText('Before cursor', { exact: true }).click()
    await region.getByRole('textbox', { name: 'Description Markdown', exact: true }).press('End')
    await insert.click()
    await expect(region.getByRole('region', { name: 'Inline table' })).toHaveCount(1)
    await expect.poll(async() => (await (await context.request.get(baseURL + '/api/thesis')).json()).body, { timeout: 12000 }).toMatch(/Before cursor[\s\S]*\| Task[\s\S]*After cursor/)
    await history.click()
    await expect(region.getByRole('region', { name: 'Version history' })).toBeVisible()
    await region.getByRole('button', { name: 'Close history', exact: true }).click()
    await expect(region.getByRole('region', { name: 'Version history' })).toHaveCount(0)
    await page.reload()
    await expect(region.getByRole('region', { name: 'Inline table' })).toHaveCount(1)
    await page.screenshot({ path: '/tmp/thesis-header-desktop.png' })
    for (const [width, height] of [[320, 568], [390, 844], [767, 1024], [768, 1024], [820, 1180], [1024, 768], [1180, 820]]) {
        await page.setViewportSize({ width, height })
        const insertBounds = (await insert.boundingBox())!
        const historyBounds = (await history.boundingBox())!
        const titleBounds = (await region.getByRole('heading', { name: 'Thesis header check' }).boundingBox())!
        expect(insertBounds.height).toBeGreaterThanOrEqual(44)
        expect(historyBounds.height).toBeGreaterThanOrEqual(44)
        const actionBounds = (await actions.boundingBox())!
        expect(actionBounds.x + actionBounds.width).toBeLessThanOrEqual(width - 16)
        expect(actionBounds.x).toBeGreaterThanOrEqual(titleBounds.x + titleBounds.width)
        expect(Math.abs(actionBounds.y - titleBounds.y)).toBeLessThan(8)
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    }
    await page.setViewportSize({ width: 390, height: 844 })
    await expect(insert).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: '/tmp/thesis-header-mobile.png' })
    const viewer = await browser.newContext()
    await viewer.routeWebSocket('**/api/ws/thesis', socket => socket.close())
    const publicPage = await viewer.newPage()
    await publicPage.goto('/thesis')
    await expect(publicPage.getByRole('heading', { name: 'Thesis header check' })).toBeVisible()
    await expect(publicPage.getByRole('button', { name: /^(Insert table|History)$/ })).toHaveCount(0)
    await viewer.close()
    await context.close()
})


test('formula completion is inline, accepts Tab, and preserves normal cell navigation', async({ browser, baseURL }) => {
    test.skip(process.env.THESIS_HEADER_TEST !== '1', 'Requires the isolated thesis header fixture.')
    test.setTimeout(60000)
    expect(baseURL).toBe('http://127.0.0.1:3230')
    const context = await browser.newContext()
    await context.routeWebSocket('**/api/ws/thesis', socket => socket.close())
    await context.addCookies([{ name: 'id', value: 'eirikhanasand', url: baseURL! }, { name: 'access_token', value: 'isolated-header-owner', url: baseURL! }])
    const current = await (await context.request.get(baseURL + '/api/thesis')).json()
    await context.request.put(baseURL + '/api/thesis', { headers: { Origin: baseURL! }, data: { ...current, title: '# A long thesis title that wraps while its controls stay beside the first line', body: '| Task | Hours | Total |\n| --- | --- | --- |\n| First | 1 | |\n| Second | 2 | |\n' } })
    const page = await context.newPage()
    await page.goto('/thesis')
    const cell = page.getByRole('textbox', { name: 'Cell C2', exact: true })
    const ghost = page.locator('.thesis-formula-suggestion')
    await cell.fill('=')
    await expect(ghost).toHaveText('=SUMMARIZE()')
    await expect(page.getByRole('heading', { name: 'Working with tables' })).toHaveCount(0)
    await cell.press('Tab')
    await expect(cell).toBeFocused()
    await expect(cell).toHaveValue('=SUMMARIZE()')
    await cell.pressSequentially('B2:B3')
    await expect(cell).toHaveValue('=SUMMARIZE(B2:B3)')
    await cell.press('Tab')
    await expect(page.getByRole('textbox', { name: 'Cell A3', exact: true })).toBeFocused()
    await expect(cell).toHaveValue('3')
    await cell.focus()
    await expect(cell).toHaveValue('=SUMMARIZE(B2:B3)')
    await cell.fill('=su')
    await expect(ghost).toHaveText('=suMMARIZE()')
    await cell.press('Tab')
    await expect(cell).toHaveValue('=SUMMARIZE()')
    await cell.fill('=')
    await cell.press('Escape')
    await expect(ghost).toHaveCount(0)
    await cell.press('Tab')
    await expect(page.getByRole('textbox', { name: 'Cell A3', exact: true })).toBeFocused()
    await cell.fill('=OTHER')
    await expect(ghost).toHaveCount(0)
    await cell.press('Shift+Tab')
    await expect(page.getByRole('textbox', { name: 'Cell B2', exact: true })).toBeFocused()
    for (const width of [320, 390, 820, 1440]) {
        await page.setViewportSize({ width, height: 900 })
        const title = (await page.getByRole('heading', { level: 1 }).boundingBox())!
        const controls = (await page.locator('[aria-label="Document actions"]').boundingBox())!
        expect(Math.abs(title.y - controls.y)).toBeLessThan(8)
        expect(controls.x).toBeGreaterThanOrEqual(title.x + title.width)
        expect(controls.x + controls.width).toBeLessThanOrEqual(width - 16)
        expect(title.height).toBeGreaterThan(44)
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    }
    await cell.fill('=')
    await page.screenshot({ path: '/tmp/thesis-formula-inline.png' })
    await context.close()
})

test('sheet settings and weekly table controls remain usable above overflowing content', async({ browser, baseURL }) => {
    test.skip(process.env.THESIS_HEADER_TEST !== '1', 'Requires the isolated thesis header fixture.')
    test.setTimeout(90000)
    expect(baseURL).toBe('http://127.0.0.1:3230')
    const context = await browser.newContext({ viewport: { width: 1440, height: 900 } })
    await context.routeWebSocket('**/api/ws/thesis', socket => socket.close())
    await context.addCookies([{ name: 'id', value: 'eirikhanasand', url: baseURL! }, { name: 'access_token', value: 'isolated-header-owner', url: baseURL! }])
    const body = '| Week | Research | Total |\n| --- | --- | --- |\n| 2026-W30 | 2 | 2 |\n| 2026-W31 | | |\n\nKeep these notes.\n\n| Task | Hours |\n| --- | --- |\n| Kept task | 3 |\n'
    const metadata = [{ id: 'Timetable', name: 'Timetable', title: '# Timetable controls', length: body.length, activityLog: { startYear: 2026, activities: [{ id: 'kept-log', date: '2026-07-27', hours: 3, category: 'Research', description: 'Keep this logged work.' }] } }]
    const current = await (await context.request.get(baseURL + '/api/thesis')).json()
    expect((await context.request.put(baseURL + '/api/thesis', { headers: { Origin: baseURL! }, data: { ...current, body: '<!-- thesis-workspace:2 ' + encodeURIComponent(JSON.stringify(metadata)) + ' -->\n' + body } })).ok()).toBe(true)
    const page = await context.newPage()
    await page.goto('/thesis?sheet=Timetable')
    const settings = page.getByRole('button', { name: 'Sheet settings', exact: true })
    const panel = page.getByRole('group', { name: 'Features on this sheet' })
    const actions = page.getByLabel('Document actions', { exact: true })
    const style = (element: HTMLElement) => {
        const css = getComputedStyle(element)
        return [css.height, css.borderRadius, css.borderWidth, css.borderColor, css.fontSize]
    }
    await expect(page.getByRole('button', { name: 'Insert table', exact: true })).toBeVisible()
    await expect(settings).toBeVisible()
    expect(await settings.evaluate(style)).toEqual(await page.getByRole('button', { name: 'History', exact: true }).evaluate(style))
    for (const width of [320, 768, 1440]) {
        await page.setViewportSize({ width, height: 900 })
        await settings.click()
        await expect(panel).toBeVisible()
        const bounds = (await panel.boundingBox())!
        expect(bounds.x).toBeGreaterThanOrEqual(16)
        expect(bounds.x + bounds.width).toBeLessThanOrEqual(width - 16)
        expect(await panel.getByLabel('Code review', { exact: true }).evaluate(element => {
            const box = element.getBoundingClientRect()
            return document.elementFromPoint(box.x + box.width / 2, box.y + box.height / 2) === element
        })).toBe(true)
        if (width === 320) {
            await actions.evaluate(element => { element.scrollLeft = 0 })
            await page.waitForTimeout(50)
            await expect(panel).toBeVisible()
        }
        await page.keyboard.press('Escape')
        await expect(panel).toBeHidden()
        expect(await actions.evaluate(element => getComputedStyle(element).scrollbarWidth)).toBe('none')
    }
    await settings.click()
    await panel.getByLabel('History', { exact: true }).uncheck()
    await expect(page.getByRole('button', { name: 'History', exact: true })).toHaveCount(0)
    if (!await panel.isVisible()) await settings.click()
    await panel.getByLabel('History', { exact: true }).check()
    await page.keyboard.press('Escape')
    const cell = (row: number, col: number) => page.locator(`[data-table-cell="0:${row}:${col}"]`)
    await page.getByRole('button', { name: 'Week 30, 2026', exact: true }).focus()
    await page.keyboard.press('ArrowRight')
    await expect(cell(1, 1)).toBeFocused()
    await cell(1, 1).press('ArrowDown')
    await expect(cell(2, 1)).toBeFocused()
    await cell(2, 1).press('ArrowDown')
    await expect(cell(3, 1)).toBeFocused()
    await expect(page.getByRole('button', { name: 'Week 32, 2026', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Add row below 4', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Week 33, 2026', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Remove row 5', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Week 33, 2026', exact: true })).toHaveCount(0)
    await page.keyboard.press('ControlOrMeta+z')
    await expect(page.getByRole('button', { name: 'Week 33, 2026', exact: true })).toBeVisible()
    await page.keyboard.press('ControlOrMeta+Shift+z')
    await expect(page.getByRole('button', { name: 'Week 33, 2026', exact: true })).toHaveCount(0)
    await cell(2, 1).click()
    await page.getByRole('button', { name: 'Remove row 3', exact: true }).click()
    await expect(page.getByRole('button', { name: 'Week 31, 2026', exact: true })).toBeVisible()
    await expect(cell(2, 1)).toHaveText('3')
    await expect(page.getByRole('button', { name: 'Remove row 3', exact: true })).toBeDisabled()
    await page.getByRole('button', { name: 'Undo', exact: true }).click()
    await cell(1, 1).click()
    await page.getByRole('button', { name: 'Select table 1', exact: true }).click()
    await expect(page.locator('[data-sheet-table="0"]')).toHaveClass('thesis-selected-table')
    await expect(page.locator('[data-sheet-table="0"]')).toBeFocused()
    const copy = await page.locator('[data-sheet-table="0"]').evaluate(element => {
        const clipboardData = new DataTransfer()
        element.dispatchEvent(new ClipboardEvent('copy', { clipboardData, bubbles: true, cancelable: true }))
        return clipboardData.getData('text/plain')
    })
    expect(copy).toContain('Week\tResearch\tTotal')
    expect(copy).toMatch(/weeks\t5\t5$/)
    await page.keyboard.press('Delete')
    await expect(page.getByRole('region', { name: 'Weekly activity timetable' })).toHaveCount(0)
    await expect(page.getByText('Keep these notes.', { exact: true })).toBeVisible()
    await expect(page.getByRole('textbox', { name: 'Cell A2', exact: true })).toHaveValue('Kept task')
    await page.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Weekly activity timetable' })).toBeVisible()
    await cell(1, 1).click()
    await page.getByRole('button', { name: 'Delete table 1', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Weekly activity timetable' })).toHaveCount(0)
    await page.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Weekly activity timetable' })).toBeVisible()
    await settings.click()
    await page.screenshot({ path: '/tmp/thesis-controls-desktop.png' })
    await context.close()
})
