import { expect, test } from '@playwright/test'

test('only the active line shows source, with direct typing, line breaks, undo and autosave', async({ browser, baseURL }) => {
    test.skip(process.env.THESIS_WORKSPACE_TEST !== '1', 'Requires the disposable thesis API.')
    expect(baseURL).toBe('http://127.0.0.1:3205')
    const context = await browser.newContext()
    await context.addCookies([{ name: 'id', value: 'eirikhanasand', url: baseURL! }, { name: 'access_token', value: 'synthetic-owner', url: baseURL! }])
    await context.addInitScript(() => {
        const Socket = window.WebSocket
        window.WebSocket = class extends Socket {
            constructor(url: string | URL, protocols?: string | string[]) { super(String(url).endsWith('/api/ws/thesis') ? 'ws://127.0.0.1:3202/api/ws/thesis' : url, protocols) }
        }
    })
    const saved = await (await context.request.get(baseURL + '/api/thesis')).json()
    const body = 'Text\n\n# more text\n\nhere I wrote something\n\nhere is footer\n\n```js\nconst x = 1\nconst y = 2\n```'
    expect((await context.request.put(baseURL + '/api/thesis', { headers: { Origin: baseURL! }, data: { ...saved, title: '# Inline thesis', body } })).ok()).toBe(true)
    const page = await context.newPage()
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto(baseURL + '/thesis')
    const region = page.getByRole('region', { name: 'Thesis document' })
    await expect(region.getByRole('button', { name: /^(Edit markdown|Done editing markdown)$/ })).toHaveCount(0)
    await region.getByRole('group', { name: 'Description Markdown, click a line to edit', exact: true }).waitFor()
    await region.getByRole('heading', { name: 'more text', exact: true }).click()
    const line = region.getByRole('textbox', { name: 'Description Markdown', exact: true })
    await expect(line).toHaveValue('# more text')
    await expect(region.getByText('Text', { exact: true })).toBeVisible()
    await expect(region.getByText('here I wrote something', { exact: true })).toBeVisible()
    await expect(region.getByText('here is footer', { exact: true })).toBeVisible()
    await line.fill('# changed **heading**')
    await line.press('End')
    await line.press('Enter')
    await expect(line).toHaveValue('')
    await line.pressSequentially('An inserted line')
    await region.getByText('Text', { exact: true }).click()
    await expect(line).toHaveValue('Text')
    await expect(region.getByRole('heading', { name: 'changed heading' })).toBeVisible()
    await expect(region.getByText('An inserted line', { exact: true })).toBeVisible()
    await line.fill('Revised introduction')
    await line.press('ControlOrMeta+z')
    await expect(line).toHaveValue('Text')
    await region.locator('pre').click({ position: { x: 24, y: 22 } })
    await expect(line).toHaveValue('const x = 1')
    await line.fill('const x = 3')
    await expect(region.locator('pre').filter({ hasText: 'const y = 2' })).toBeVisible()
    await region.getByRole('heading', { name: 'Inline thesis', exact: true }).click()
    const title = region.getByRole('textbox', { name: 'Title Markdown', exact: true })
    await expect(title).toHaveValue('# Inline thesis')
    await title.fill('# **Live** thesis')
    await title.press('Enter')
    await expect(region.getByRole('heading', { name: 'Live thesis', exact: true })).toBeVisible()
    await expect.poll(async() => (await (await context.request.get(baseURL + '/api/thesis')).json()).body, { timeout: 12000 }).toContain('const x = 3')
    await page.reload()
    await expect(region.getByRole('heading', { name: 'changed heading' })).toBeVisible()
    await expect(region.getByText('An inserted line', { exact: true })).toBeVisible()
    await expect(region.locator('pre')).toContainText('const x = 3\nconst y = 2')
    await page.setViewportSize({ width: 390, height: 844 })
    await region.getByRole('group', { name: 'Description Markdown, click a line to edit', exact: true }).waitFor()
    await region.getByText('here is footer', { exact: true }).click()
    await expect(line).toHaveValue('here is footer')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: '/tmp/thesis-inline-mobile.png', fullPage: true })
    expect(errors).toEqual([])
    await context.close()
})
