import { expect, test } from '@playwright/test'
import { identifiedSheets, writeSheets } from '../src/app/thesis/workspace'

test('sheet URLs survive refresh, history, reordering and add/remove actions', async({ browser, baseURL }) => {
    test.skip(process.env.THESIS_SHEET_URL_TEST !== '1', 'Requires the isolated thesis URL fixture.')
    test.setTimeout(90000)
    expect(baseURL).toBe('http://127.0.0.1:3240')
    const context = await browser.newContext()
    await context.routeWebSocket('**/api/ws/thesis', socket => socket.close())
    const page = await context.newPage()
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('/thesis?source=shared#document')
    const tab = (name: string) => page.getByRole('tab', { name, exact: true })
    await tab('Plan').click()
    await expect(tab('Plan')).toHaveAttribute('aria-selected', 'true')
    expect(new URL(page.url()).searchParams.get('sheet')).toBe('Plan')
    expect(new URL(page.url()).searchParams.get('source')).toBe('shared')
    expect(new URL(page.url()).hash).toBe('#document')
    await page.reload()
    await expect(tab('Plan')).toHaveAttribute('aria-selected', 'true')
    await tab('Research').click()
    await page.goBack()
    await expect(tab('Plan')).toHaveAttribute('aria-selected', 'true')
    await page.goForward()
    await expect(tab('Research')).toHaveAttribute('aria-selected', 'true')
    await tab('Research').press('ArrowLeft')
    await expect(tab('Plan')).toHaveAttribute('aria-selected', 'true')
    expect(new URL(page.url()).searchParams.get('sheet')).toBe('Plan')
    await tab('Plan').press('End')
    expect(new URL(page.url()).searchParams.get('sheet')).toBe('notes & sources/1')
    await page.reload()
    await expect(tab('Notes')).toHaveAttribute('aria-selected', 'true')
    await page.goto('/thesis?sheet=Plan')
    await expect(tab('Plan')).toHaveAttribute('aria-selected', 'true')
    const noJS = await browser.newContext({ javaScriptEnabled: false })
    const initialPage = await noJS.newPage()
    await initialPage.goto('/thesis?sheet=Plan')
    await expect(initialPage.getByRole('tab', { name: 'Plan', exact: true, includeHidden: true })).toHaveAttribute('aria-selected', 'true')
    await noJS.close()
    const fixture = process.env.THESIS_FIXTURE_API!
    const savedSheetIds = async() => {
        const document = await (await context.request.get(fixture + '/thesis')).json()
        return identifiedSheets(document.title, document.body).map(sheet => sheet.id)
    }
    const saved = await (await context.request.get(fixture + '/thesis')).json()
    const sheets = identifiedSheets(saved.title, saved.body)
    await context.request.put(fixture + '/thesis', { data: { ...saved, body: writeSheets([...sheets].reverse()) } })
    await page.reload()
    await expect(tab('Plan')).toHaveAttribute('aria-selected', 'true')
    await context.request.put(fixture + '/thesis', { data: saved })
    await page.goto('/thesis?sheet=missing&source=shared')
    await expect(tab('Timetable')).toHaveAttribute('aria-selected', 'true')
    await expect.poll(() => new URL(page.url()).searchParams.get('sheet')).toBe('Timetable')
    expect(new URL(page.url()).searchParams.get('source')).toBe('shared')
    await context.addCookies([{ name: 'id', value: 'eirikhanasand', url: baseURL! }, { name: 'access_token', value: 'sheet-url-owner', url: baseURL! }])
    await page.goto('/thesis?sheet=Plan')
    await page.getByRole('button', { name: 'Add sheet', exact: true }).click()
    await page.getByRole('dialog').getByRole('textbox').fill('New notes')
    await page.getByRole('button', { name: 'Create sheet', exact: true }).click()
    await expect(tab('New notes')).toHaveAttribute('aria-selected', 'true')
    const newId = new URL(page.url()).searchParams.get('sheet')!
    expect(newId).not.toBe('Plan')
    await expect.poll(savedSheetIds).toContain(newId)
    await page.reload()
    await expect(tab('New notes')).toHaveAttribute('aria-selected', 'true')
    await page.getByRole('button', { name: 'Remove New notes sheet', exact: true }).click()
    await page.getByRole('dialog').getByRole('textbox').fill('New notes')
    await page.getByRole('button', { name: 'Delete', exact: true }).click()
    await expect(tab('Notes')).toHaveAttribute('aria-selected', 'true')
    expect(new URL(page.url()).searchParams.get('sheet')).toBe('notes & sources/1')
    await expect.poll(savedSheetIds).not.toContain(newId)
    await page.reload()
    await expect(tab('Notes')).toHaveAttribute('aria-selected', 'true')
    expect(errors).toEqual([])
    await context.close()
})
