import { expect, test } from '@playwright/test'

test('owners add/remove persisted tabs and compare sheets in shared history; viewers cannot edit', async({ browser, baseURL }) => {
    test.skip(process.env.THESIS_WORKSPACE_TEST !== '1', 'Requires disposable thesis API.')
    test.setTimeout(60000)
    expect(baseURL).toBe('http://127.0.0.1:3205')
    const context = await browser.newContext()
    await context.addCookies([{ name: 'id', value: 'eirikhanasand', url: baseURL! }, { name: 'access_token', value: 'synthetic-owner', url: baseURL! }])
    const socketFixture = () => {
        const Socket = window.WebSocket
        window.WebSocket = class extends Socket {
            constructor(url: string | URL, protocols?: string | string[]) { super(String(url).endsWith('/api/ws/thesis') ? 'ws://127.0.0.1:3202/api/ws/thesis' : url, protocols) }
        }
    }
    await context.addInitScript(socketFixture)
    const saved = await (await context.request.get(baseURL + '/api/thesis')).json()
    await context.request.put(baseURL + '/api/thesis', { headers: { Origin: baseURL! }, data: { ...saved, title: '# Thesis', body: 'Original overview' } })
    const page = await context.newPage()
    await page.goto(baseURL + '/thesis')
    await expect(page.getByRole('tab')).toHaveCount(4)
    await page.getByRole('button', { name: 'Add sheet', exact: true }).click()
    const createDialog = page.getByRole('dialog', { name: 'Create a new sheet' })
    await expect(createDialog.getByRole('textbox', { name: 'Sheet name', exact: true })).toBeFocused()
    await expect(createDialog.getByRole('button', { name: 'Create sheet', exact: true })).toBeDisabled()
    await createDialog.getByRole('textbox').fill('Notes')
    await createDialog.getByRole('textbox').press('Tab')
    await expect(createDialog.getByRole('button', { name: 'Cancel', exact: true })).toBeFocused()
    await createDialog.getByRole('button', { name: 'Cancel', exact: true }).press('Tab')
    await expect(createDialog.getByRole('button', { name: 'Create sheet', exact: true })).toBeFocused()
    await createDialog.getByRole('button', { name: 'Create sheet', exact: true }).click()
    await expect(createDialog).toHaveCount(0)
    await expect(page.getByRole('tab', { name: 'Notes', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect(page.getByRole('button', { name: /^Remove .* sheet$/ })).toHaveCount(1)
    await expect(page.getByRole('button', { name: 'Remove sheet', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Add sheet', exact: true }).click()
    await createDialog.getByRole('textbox').press('Escape')
    await expect(createDialog).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Add sheet', exact: true })).toBeFocused()
    const current = async() => { const doc = await (await context.request.get(baseURL + '/api/thesis')).json(); const header = /^<!-- thesis-workspace:2 (.*?) -->/.exec(doc.body); return header ? JSON.parse(decodeURIComponent(header[1])) as { name: string }[] : [] }
    await expect.poll(async() => (await current()).length, { timeout: 12000 }).toBe(5)
    const plan = page.getByRole('tab', { name: 'Plan', exact: true })
    const inactivePadding = await plan.evaluate(element => parseFloat(getComputedStyle(element).paddingRight))
    await plan.click()
    const minus = page.getByRole('button', { name: 'Remove Plan sheet', exact: true })
    expect((await minus.boundingBox())!.width).toBe(24)
    expect(await plan.evaluate(element => parseFloat(getComputedStyle(element).paddingRight)) - inactivePadding).toBe(12)
    await page.setViewportSize({ width: 390, height: 844 })
    await page.screenshot({ path: '/tmp/thesis-compact-minus.png' })
    await minus.click()
    await page.getByRole('dialog').getByRole('button', { name: 'Cancel', exact: true }).click()
    await page.setViewportSize({ width: 1280, height: 720 })
    await page.getByRole('tab', { name: 'Overview', exact: true }).click()
    await page.getByRole('button', { name: 'Remove Overview sheet', exact: true }).click()
    const deletion = page.getByRole('dialog', { name: 'Are you sure you want to delete?' })
    await expect(deletion.getByRole('button', { name: 'Delete', exact: true })).toBeDisabled()
    await deletion.getByRole('textbox').fill('Wrong name')
    await expect(deletion.getByRole('button', { name: 'Delete', exact: true })).toBeDisabled()
    await deletion.getByRole('button', { name: 'Cancel', exact: true }).click()
    await expect(page.getByRole('tab')).toHaveCount(5)
    await page.getByRole('button', { name: 'Remove Overview sheet', exact: true }).click()
    await context.grantPermissions(['clipboard-read', 'clipboard-write'])
    await deletion.getByRole('button', { name: 'Copy sheet name', exact: true }).click()
    await expect(deletion.getByRole('status')).toHaveText('Sheet name copied.')
    expect(await page.evaluate(() => navigator.clipboard.readText())).toBe('Overview')
    await deletion.getByRole('textbox').fill('Overview')
    await expect(deletion.getByRole('button', { name: 'Delete', exact: true })).toBeEnabled()
    const cancelBox = (await deletion.getByRole('button', { name: 'Cancel', exact: true }).boundingBox())!
    const deleteBox = (await deletion.getByRole('button', { name: 'Delete', exact: true }).boundingBox())!
    expect(cancelBox.x).toBeLessThan(deleteBox.x)
    await page.screenshot({ path: '/tmp/thesis-delete-dialog.png' })
    await deletion.getByRole('button', { name: 'Delete', exact: true }).click()
    await expect(page.getByRole('tab', { selected: true })).toBeFocused()
    await expect.poll(async() => (await current()).map(sheet => sheet.name), { timeout: 12000 }).toEqual(['Timetable', 'Plan', 'Research', 'Notes'])
    await page.reload()
    await expect(page.getByRole('tab')).toHaveCount(4)
    await expect(page.getByRole('tab', { name: 'Overview', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'History', exact: true }).click()
    await page.getByRole('button', { name: /^Previous version/ }).click()
    await expect(page.getByRole('heading', { name: 'Overview — Removed', exact: true })).toBeVisible()
    await expect(page.getByRole('region', { name: 'Version preview' })).toContainText('Original overview')
    const viewer = await browser.newContext()
    await viewer.addInitScript(socketFixture)
    const publicPage = await viewer.newPage()
    await publicPage.goto(baseURL + '/thesis')
    await expect(publicPage.getByRole('tab', { name: 'Notes', exact: true })).toBeVisible()
    await expect(publicPage.getByRole('button', { name: /Add sheet|Remove .* sheet|^History$/ })).toHaveCount(0)
    const doc = await (await viewer.request.get(baseURL + '/api/thesis')).json()
    expect((await viewer.request.put(baseURL + '/api/thesis', { headers: { Origin: baseURL! }, data: doc })).status()).toBe(403)
    await page.setViewportSize({ width: 390, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.getByRole('region', { name: 'Version history' }).getByRole('button', { name: /^Restore version/ }).first().click()
    await expect(page.getByRole('tab', { name: 'Overview', exact: true })).toBeVisible()
    await expect(page.getByRole('tab')).toHaveCount(5)
    while (await page.getByRole('tab').count() > 1) {
        const name = await page.getByRole('tab', { selected: true }).innerText()
        await page.getByRole('button', { name: /^Remove .* sheet$/ }).click()
        await deletion.getByRole('textbox').fill(name)
        await page.screenshot({ path: '/tmp/thesis-delete-dialog-mobile.png' })
        await deletion.getByRole('button', { name: 'Delete', exact: true }).click()
    }
    await page.locator('.enterprise-theme').evaluate(element => element.scrollTo({ top: 0 }))
    await expect(page.getByRole('button', { name: /^Remove .* sheet$/ })).toBeDisabled()
    await expect.poll(async() => (await current()).length, { timeout: 12000 }).toBe(1)
    await page.reload()
    await expect(page.getByRole('tab')).toHaveCount(1)
    await viewer.close()
    await context.close()
})
