import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import path from 'node:path'

const root = process.cwd()

test.describe('public threat actor profile', () => {
    test('APT29 renders country-level map and concrete victim context', async ({ page }, testInfo) => {
        await page.goto('/ti/apt29')

        await expect(page.getByRole('heading', { name: 'APT29', exact: true })).toBeVisible()
        await expect(page.locator('[data-ti-actor-info="true"]')).toBeVisible()
        await expect(page.locator('[data-ti-map="true"]')).toBeVisible()
        await expect(page.locator('[data-ti-map="true"]')).toContainText('Actor country map')
        await expect(page.locator('[data-ti-activity="true"]')).toBeVisible()
        await expect(page.locator('[data-ti-sources="true"]')).toBeVisible()

        const body = page.locator('body')
        await expect(body).toContainText('Russia')
        await expect(body).toContainText('United States')
        await expect(body).toContainText('United Kingdom')
        await expect(body).toContainText('Germany')
        await expect(body).toContainText('Democratic National Committee')
        await expect(body).toContainText('SolarWinds Orion customers and U.S. federal agencies')
        await expect(body).toContainText('Microsoft corporate email accounts')
        await expect(body).toContainText('Government and policy organizations')
        await expect(body).toContainText('Russia-linked SVR/APT29 activity in public government, vendor, and incident reporting')
        await expect(body).toContainText('Recent activity')
        await expect(body).toContainText('Summary')
        await expect(body).toContainText('Sources')
        await expect(body).toContainText('Malpedia\'s actor summary for APT29.')

        const actorBox = await page.locator('[data-ti-actor-info="true"]').boundingBox()
        const geoBox = await page.locator('[data-ti-map="true"]').boundingBox()
        const activityBox = await page.locator('#ti-activity').boundingBox()
        const sourcesBox = await page.locator('[data-ti-sources="true"]').boundingBox()
        expect(actorBox?.y ?? 0).toBeLessThan(activityBox?.y ?? Number.POSITIVE_INFINITY)
        expect(geoBox?.y ?? 0).toBeLessThan(activityBox?.y ?? Number.POSITIVE_INFINITY)
        expect(activityBox?.y ?? 0).toBeLessThan(sourcesBox?.y ?? Number.POSITIVE_INFINITY)

        const bodyText = await body.innerText()
        expect(bodyText).not.toMatch(/\bblocked\b/i)
        expect(bodyText).not.toMatch(/\baction required\b/i)
        expect(bodyText).not.toMatch(/NATO-aligned states/i)
        expect(bodyText).not.toMatch(/From live source conte(?:nt|xt)/i)
        expect(bodyText).not.toMatch(/What\s+returned/i)
        expect(bodyText).not.toMatch(/Actor workbenches/i)
        expect(bodyText).not.toMatch(/Source basis/i)
        expect(bodyText).not.toMatch(/Collection gaps/i)
        expect(bodyText).not.toMatch(/\bNorth America\b/)
        expect(bodyText).not.toMatch(/4 mapped/i)
        expect(bodyText).not.toMatch(/Current profile/i)
        expect(bodyText).not.toMatch(/capture needed/i)
        expect(bodyText).not.toMatch(/Missing links/i)
        expect(bodyText).not.toMatch(/Source context/i)
        expect(bodyText).not.toMatch(/Why it matters/i)
        expect(bodyText).not.toMatch(/Next action/i)
        expect(bodyText).not.toMatch(/Selected evidence/i)
        expect(bodyText).not.toMatch(/Action rail/i)
        expect(bodyText).not.toMatch(/Source reference attached/i)

        await testInfo.attach('apt29-country-map', {
            body: await page.screenshot({ fullPage: false }),
            contentType: 'image/png',
        })
    })

    test('keeps the actor page focused on four sections', async () => {
        const source = await readFile(path.join(root, 'src/app/ti/pageClient.tsx'), 'utf8')
        const workspaceIndex = source.indexOf('data-ti-workspace=\'true\'')

        expect(workspaceIndex).toBeGreaterThan(-1)
        expect(source).toContain('data-ti-actor-info')
        expect(source).toContain('data-ti-map')
        expect(source).toContain('const actorQuery = result.queryKind === \'actor\'')
        expect(source).toContain('{actorQuery ? <section data-ti-map=\'true\'')
        expect(source).not.toContain('defaultSourceLinks')
        expect(source).toContain('data-ti-activity')
        expect(source).toContain('data-ti-sources')
        expect(source).toContain('data-ti-evidence-boundary')
        expect(source).toContain('Captured matches are observed evidence. Source statements remain claims.')
        expect(source).toContain('return \'Inferred candidate\'')
        expect(source).not.toContain('data-ti-hero-map')
        expect(source).not.toContain('data-ti-hero-evidence')
        expect(source).not.toContain('data-ti-actor-workspace-rail')
        expect(source).not.toContain('data-ti-selected-action-rail')
        expect(source).not.toContain('data-ti-geo-subordinate')
        expect(source).not.toContain('<SelectedEvidenceRail')
        expect(source).toContain('BriefStep title=\'Summary\'')
        expect(source).not.toContain('BriefStep title=\'Why it matters\'')
        expect(source).not.toContain('BriefStep title=\'Next action\'')
        expect(source).not.toContain('Current profile')
        expect(source).not.toContain('capture needed')
        expect(source).not.toContain('Missing links')
        expect(source).not.toContain('Source context')
        expect(source).toContain('political|election')
        expect(source).toContain('{sourceBasisLabel(source.confidence)}</span>')
        expect(source).not.toContain('{Math.round(source.confidence * 100)}%</span>')
        expect(source).toContain('No intelligence is available for that search yet.')
        expect(source).toContain('summary: \'Checking sources\'')
        expect(source).not.toContain('The TI service did not return results.')
        expect(source).not.toContain('summary: \'Searching\'')
        expect(source).toContain('No reviewable activity is ready for this query.')
        expect(source).not.toContain("source: 'TI search service'")
    })
})
