import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import path from 'node:path'

const root = process.cwd()

test('TI workbench keeps selected-case actions primary and collapses secondary rail context', async () => {
    const page = await readFile(path.join(root, 'src/app/dashboard/ti/workbench/workbenchClient.tsx'), 'utf8')
    const route = await readFile(path.join(root, 'src/app/dashboard/ti/workbench/page.tsx'), 'utf8')
    const attacksRoute = await readFile(path.join(root, 'src/app/dashboard/ti/attacks/page.tsx'), 'utf8')
    const sidebar = await readFile(path.join(root, 'src/components/dashboard/dashboardSidebar.tsx'), 'utf8')
    const loading = await readFile(path.join(root, 'src/app/dashboard/ti/loading.tsx'), 'utf8')
    const proxy = await readFile(path.join(root, 'src/proxy.ts'), 'utf8')

    expect(page).toContain('<OperatorActionRail')
    expect(page).toContain('data-workbench-stats-disclosure')
    expect(page).toContain('data-workbench-stats')
    expect(page).toContain('data-workbench-org-disclosure')
    expect(page).toContain('data-workbench-case-groups-disclosure')
    expect(page.indexOf('data-workbench-stats-disclosure')).toBeLessThan(page.indexOf('Attack summary'))
    expect(page.indexOf('Attack summary')).toBeLessThan(page.indexOf('{workbenchStatsGrid}'))
    expect(page.indexOf('<OperatorActionRail')).toBeLessThan(page.indexOf('data-workbench-org-disclosure'))
    expect(page.indexOf('data-workbench-org-disclosure')).toBeLessThan(page.indexOf('data-workbench-case-groups-disclosure'))

    expect(page).toContain('embedded')
    expect(page).toContain('Attack summary')
    expect(page).not.toContain('<SelectedWorkflowHandoff')
    expect(page).not.toContain('<CaseRouteStrip')
    expect(page).toContain('.filter(row => !row.disabledReason && row.tone === \'ready\')')
    expect(route).toContain('title=\'Attacks\'')
    expect(attacksRoute).toContain('export { default, dynamic } from \'../workbench/page\'')
    expect(sidebar).toContain('{ href: \'/dashboard/ti/attacks\', label: \'Attacks\'')
    expect(sidebar).toContain('{ href: \'/dashboard/ti/timeliness\', label: \'Timeliness\'')
    expect(page).toContain('const workbenchStatsGrid')
    expect(page).toContain('Org and shared watchlist')
    expect(page).toContain('Case groups and links')
    expect(page).toContain('Members, terms, visibility')
    expect(page).toContain('Delivery rows')
    expect(page).toContain('onRunAction={(action) => selected && runWorkbenchAction')
    expect(page).toContain('onCustomerNotification={() => selected && recordCustomerNotification')
    expect(page).toContain('onCreateSharedWatchlistTerm={() => selected && createSharedWatchlistTerm(selected)}')
    expect(route).toContain('const initialSelectedId = selectedWorkbenchCaseId(cases, params) || publicTiCases[0]?.id')
    expect(route).toContain('function selectedWorkbenchCaseId')
    expect(route).toContain('function workbenchCaseMatchesScope')
    expect(route).toContain('function workbenchCaseReferenceRows')
    expect(route).toContain('function scopeRefsFromHref')
    expect(route).toContain('const WORKBENCH_FETCH_TIMEOUT_MS = 800')
    expect(route).toContain('AbortSignal.timeout(WORKBENCH_FETCH_TIMEOUT_MS)')
    expect(loading).toContain('Loading collection, recent attacks, actor profiles, sources, and review state.')
    expect(loading).toContain('animate-pulse')
    expect(proxy).toContain('recentlyValidatedSession(sessionExpiresAt, authCheckedAt)')
    expect(proxy).toContain('const AUTH_CHECK_CACHE_MS = 5 * 60 * 1000')
    expect(proxy).toContain('session_expires_at')
    expect(proxy).toContain('auth_checked_at')
    expect(route).toContain('[\'alertId\', \'alert\']')
    expect(route).toContain('[\'watchlistId\', \'watchlist\']')
    expect(route).toContain('[\'organizationId\', \'organization\']')
    expect(route).toContain('/dashboard/dwm/cases/')
    expect(page).toContain('safeEvidenceExcerpt } from \'@/utils/dwm/display\'')
    expect(page).toContain('function safeWorkbenchDetail(value: string | undefined)')
    expect(page).toContain('safeEvidenceExcerpt(value || \'Safe excerpt is being prepared from this evidence.\')')
    expect(page).toContain('safeWorkbenchDetail(delivery.error)')
    expect(page).toContain('safeWorkbenchDetail(item.excerpt)')
    expect(page).not.toContain('What returned')
})
