import { test, expect } from '@playwright/test'
const writeTable = ({ cells }: { cells: string[][], widths: number[], heights: number[] }) => [cells[0], cells[0].map(() => '---'), ...cells.slice(1)].map(row => '| ' + row.join(' | ') + ' |').join('\n') + '\n'
const writeSheets = (sheets: { id: string, name: string, title: string, body: string }[]) => '<!-- thesis-workspace:2 ' + encodeURIComponent(JSON.stringify(sheets.map(({ body, ...sheet }) => ({ ...sheet, length: body.length })))).replace(/-/g, '%2D') + ' -->\n' + sheets.map(sheet => sheet.body).join('\n\n')

test.use({ baseURL: 'http://127.0.0.1:3265' })
test.skip(process.env.THESIS_TIMETABLE_TEST !== '1', 'Requires isolated timetable services.')
test('weekly logs, targets, vacation rows, PDF, persistence and reader permissions', async({ page, context, request }) => {
    test.setTimeout(180000)
    page.setDefaultTimeout(15000)
    page.on('pageerror', error => console.log('Browser error:', error.message))
    await context.addCookies([{ name: 'id', value: 'eirikhanasand', url: 'http://127.0.0.1:3265' }, { name: 'access_token', value: 'synthetic-owner', url: 'http://127.0.0.1:3265' }])
    await page.routeWebSocket('**/api/ws/thesis', socket => socket.close())
    const original = await (await request.get('http://127.0.0.1:3262/api/thesis')).json()
    const weeks = [...Array.from({ length: 25 }, (_, index) => index + 28), ...Array.from({ length: 22 }, (_, index) => index + 1)]
    const cells = [['Week', 'Setup', 'Debugging', 'Development', 'Meetings', 'Research', 'Report', 'Total'], ...weeks.map(week => [String(week), '', '', '', '', '', '', '']), ['Total', '', '', '', '', '', '', '']]
    const body = writeSheets([{ id: 'Overview', name: 'Overview', title: '# Thesis', body: 'Preserve this.' }, { id: 'Timetable', name: 'Timetable', title: '# Timetable', body: 'Before the timetable\n\n' + writeTable({ cells, widths: [], heights: [] }) + '\nAfter the timetable' }])
    expect((await request.put('http://127.0.0.1:3262/api/thesis', { headers: { id: 'eirikhanasand', Authorization: 'Bearer synthetic-owner' }, data: { ...original, body } })).ok()).toBe(true)
    await page.goto('/thesis?sheet=Timetable', { waitUntil: 'domcontentloaded' })
    await expect(page.getByLabel('Hours spent and expected')).toContainText('0 / 1063.5 h')
    await expect(page.getByRole('button', { name: 'Log activity', exact: true })).toBeVisible({ timeout: 30000 })
    const table = page.getByRole('region', { name: 'Weekly activity timetable' })
    await expect(table.locator('textarea')).toHaveCount(0)
    await expect(table.locator('tfoot')).toContainText('47 weeks')
    await table.locator('[data-week="2026-W28"] td').nth(2).click()
    const week28 = page.getByRole('region', { name: 'Activities for week 28, 2026' })
    await expect(week28).toBeVisible()
    expect(await table.locator('[data-week="2026-W28"]').evaluate(row => row.nextElementSibling?.classList.contains('thesis-week-expanded') && row.nextElementSibling?.nextElementSibling?.getAttribute('data-week') === '2026-W29')).toBe(true)
    async function fillLog(date: string, hours: string, category: string, description: string) {
        const form = page.getByRole('form', { name: 'Log activity', exact: true })
        await form.getByLabel('Date', { exact: true }).fill(date)
        await form.getByLabel('Hours', { exact: true }).fill(hours)
        await form.getByRole('combobox', { name: 'Category', exact: true }).selectOption(category)
        await form.getByLabel('Description', { exact: true }).fill(description)
        await form.getByRole('button', { name: 'Add activity', exact: true }).click()
    }
    await week28.getByRole('button', { name: 'Add activity', exact: true }).click()
    await fillLog('2026-07-06', '1.5', 'Research', 'Literature review æøå\nCompared two approaches.')
    await expect(page.getByLabel('Hours spent and expected')).toContainText('1.5 / 1063.5 h')
    await page.getByRole('button', { name: 'Log activity', exact: true }).click()
    await fillLog('2026-07-07', '0.75', 'Development', 'Built a prototype')
    await expect(page.getByLabel('Hours spent and expected')).toContainText('2.25 / 1063.5 h')
    await week28.getByRole('button', { name: /Edit activity 2026-07-06/ }).click()
    await page.getByRole('form', { name: 'Edit activity' }).getByLabel('Hours', { exact: true }).fill('2')
    await page.getByRole('button', { name: 'Update activity', exact: true }).click()
    await expect(page.getByLabel('Hours spent and expected')).toContainText('2.75 / 1063.5 h')
    await week28.getByRole('button', { name: 'Remove week from plan' }).click()
    await expect(page.getByLabel('Hours spent and expected')).toContainText('2.75 / 1051.5 h')
    await expect(table.locator('tfoot')).toContainText('46 weeks')
    await expect(week28).toContainText('Outside the planned rows')
    await week28.getByRole('button', { name: 'Include week in plan' }).click()
    await expect(page.getByLabel('Hours spent and expected')).toContainText('2.75 / 1063.5 h')
    await week28.getByRole('button', { name: /Remove activity 2026-07-07/ }).click()
    await expect(page.getByLabel('Hours spent and expected')).toContainText('2 / 1063.5 h')
    await page.getByRole('button', { name: 'Undo', exact: true }).click()
    await expect(page.getByLabel('Hours spent and expected')).toContainText('2.75 / 1063.5 h')
    await page.getByRole('button', { name: 'Log activity', exact: true }).click()
    await fillLog('2026-12-14', '3', 'Report', 'Worked during Christmas break')
    await page.getByRole('button', { name: 'Week 51, 2026', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Activities for week 51, 2026' })).toContainText('0 expected hours')
    await page.getByRole('button', { name: 'Log activity', exact: true }).click()
    await fillLog('2027-01-01', '2', 'Research', 'New year reading')
    await expect(page.getByLabel('Hours spent and expected')).toContainText('7.75 / 1063.5 h')
    await expect(table.locator('tfoot')).toContainText('47 weeks')
    await expect(page.getByRole('button', { name: 'Week 53, 2026', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Week 12, 2027', exact: true }).click()
    await expect(page.getByRole('region', { name: 'Activities for week 12, 2027' })).toContainText('22.5 expected hours')
    await expect.poll(async() => (await (await request.get('http://127.0.0.1:3262/api/thesis')).json()).body.includes('New%20year%20reading'), { timeout: 20000 }).toBe(true)
    await page.reload({ waitUntil: 'domcontentloaded' })
    await expect(page.getByRole('tab', { name: 'Timetable', exact: true })).toBeEnabled({ timeout: 30000 })
    await expect(page.getByLabel('Hours spent and expected')).toContainText('7.75 / 1063.5 h')
    await page.getByRole('button', { name: 'Week 28, 2026', exact: true }).click()
    await expect(week28).toContainText('Literature review æøå')
    // Export with a week open: only the complete summary and day-by-day records belong in the file.
    const downloaded = page.waitForEvent('download')
    await page.getByRole('button', { name: 'Export timetable as PDF' }).click()
    const pdf = await downloaded
    await pdf.saveAs('/tmp/thesis-timetable-report.pdf')
    expect(pdf.suggestedFilename()).toMatch(/^thesis-timetable-.*\.pdf$/)
    await page.setViewportSize({ width: 390, height: 844 })
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await week28.getByRole('button', { name: 'Add activity', exact: true }).click()
    await expect(page.getByRole('form', { name: 'Log activity', exact: true })).toBeVisible()
    await page.screenshot({ path: '/tmp/thesis-timetable-mobile.png', fullPage: true })
    await context.clearCookies()
    expect((await page.request.put('/api/thesis', { data: { ...original, body } })).status()).toBe(403)
    await page.reload({ waitUntil: 'domcontentloaded' })
    await expect(page.getByRole('tab', { name: 'Timetable', exact: true })).toBeEnabled({ timeout: 30000 })
    await expect(page.getByLabel('Hours spent and expected')).toContainText('7.75 / 1063.5 h')
    await expect(page.getByRole('button', { name: 'Log activity', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: 'Week 28, 2026', exact: true }).click()
    await expect(week28).toContainText('Literature review æøå')
    await expect(week28.getByRole('button', { name: 'Add activity', exact: true })).toHaveCount(0)
    await expect(week28.getByRole('button', { name: /Remove activity/ })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Export timetable as PDF' })).toBeVisible()
})
