import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import path from 'node:path'

const root = process.cwd()

test('public workflow reliability contracts are not demo-only', async () => {
    const pwnedClient = await readFile(path.join(root, 'src/utils/pwned/checkHash.ts'), 'utf8')
    const pwnedRoute = await readFile(path.join(root, 'src/app/api/pwned/route.ts'), 'utf8')
    const pwnedPage = await readFile(path.join(root, 'src/app/pwned/pageClient.tsx'), 'utf8')
    const registerPage = await readFile(path.join(root, 'src/app/register/page.tsx'), 'utf8')
    const contact = await readFile(path.join(root, 'src/components/contact/contact.tsx'), 'utf8')
    const contactClient = await readFile(path.join(root, 'src/utils/contact/submitContactRequest.ts'), 'utf8')
    const contactHandler = await readFile(path.join(root, '../api/src/handlers/commercialContactRequests.ts'), 'utf8')
    const apiPwnedHandler = await readFile(path.join(root, '../api/src/handlers/pwned/post.ts'), 'utf8')
    const apiPwnedUtility = await readFile(path.join(root, '../api/src/utils/pwned/checkPwned.ts'), 'utf8')

    expect(pwnedClient).toContain('normalizeSha1Hash')
    expect(pwnedClient).toContain('body: JSON.stringify({ prefix })')
    expect(pwnedClient).not.toContain('body: JSON.stringify({ password })')
    expect(pwnedClient).not.toContain('window.crypto.subtle.digest')
    expect(pwnedRoute).toContain('A valid SHA-1 hash prefix is required.')
    expect(pwnedRoute).not.toContain('password =')
    expect(pwnedPage).toContain('setHashInput(\'\')')
    expect(pwnedPage).toContain('pattern=\'[A-Fa-f0-9]{40}\'')
    expect(apiPwnedHandler).toContain('normalizeSha1Prefix')
    expect(apiPwnedHandler).toContain('fetchPwnedRange')
    expect(apiPwnedHandler).toContain('Do not send raw secrets to this endpoint.')
    expect(apiPwnedHandler).not.toContain('password')
    expect(apiPwnedHandler).not.toContain('checkPwned(')
    expect(apiPwnedUtility).toContain('sha1SecretHash')
    expect(apiPwnedUtility).toContain('checkHibpRangeForHash')
    expect(apiPwnedUtility).toContain('User-Agent\': \'hanasand-bloom-hash-lookup')
    expect(apiPwnedUtility).not.toContain('body: JSON.stringify({ password })')
    expect(apiPwnedUtility).not.toContain('internal-pwned')

    expect(registerPage).toContain('mode: \'signup\'')
    expect(registerPage).toContain('redirect(`/login?${query}`)')

    expect(contact).toContain('submitContactRequest({')
    expect(contact).toContain('Ticket <span')
    expect(contact).toContain('data-contact-intake-routing')
    expect(contact).toContain('data-contact-security-review')
    expect(contact).toContain('deliveryPreference: values.deliveryPreference')
    expect(contact).toContain('securityReview: values.securityReview')
    expect(contact).toContain('Company is required for security review requests')
    expect(contact).toContain('required={formik.values.securityReview}')
    expect(contact).not.toContain('window.location.href = mailtoLink')
    expect(contactClient).toContain('/commercial/contact-requests')
    expect(contactClient).toContain('Idempotency-Key')
    expect(contactHandler).toContain('commercial_contact_requests')
    expect(contactHandler).toContain('deliveryPreference')
    expect(contactHandler).toContain('securityReview')
    expect(contactHandler).toContain('Company is required for security review requests.')
    expect(contactHandler).toContain('security review material')

})
