import { expect, test } from '@playwright/test'

test('sheet markdown, inline tables, persistence and inherited reader permissions', async({ browser, baseURL }) => {
    test.skip(process.env.THESIS_WORKSPACE_TEST !== '1', 'Requires the disposable thesis API on port 3202.')
    test.setTimeout(120000)
    expect(baseURL).toBe('http://127.0.0.1:3205')
    const socketFixture = () => {
        const NativeSocket = window.WebSocket
        window.WebSocket = class extends NativeSocket {
            constructor(url: string | URL, protocols?: string | string[]) {
                super(String(url).endsWith('/api/ws/thesis') ? 'ws://127.0.0.1:3202/api/ws/thesis' : url, protocols)
            }
        }
    }
    const owner = await browser.newContext()
    await owner.addInitScript(socketFixture)
    await owner.addCookies([{ name: 'id', value: 'eirikhanasand', url: baseURL! }, { name: 'access_token', value: 'synthetic-owner', url: baseURL! }])
    const initial = await (await owner.request.get(baseURL + '/api/thesis')).json()
    expect((await owner.request.put(baseURL + '/api/thesis', { headers: { Origin: baseURL! }, data: { ...initial, title: '# Thesis', body: '' } })).ok()).toBe(true)
    const page = await owner.newPage()
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto(baseURL + '/thesis')
    const workspace = page.getByRole('region', { name: 'Thesis document' })
    await expect(workspace.getByRole('tab')).toHaveCount(4)
    await page.getByRole('tab', { name: 'Timetable', exact: true }).click()
    await page.getByRole('button', { name: 'Add text to Description Markdown', exact: true }).last().click()
    await workspace.getByRole('heading', { name: 'Timetable', exact: true }).click()
    await page.getByRole('textbox', { name: 'Title Markdown', exact: true }).fill('# **Time** plan')
    await page.getByRole('textbox', { name: 'Title Markdown', exact: true }).press('Enter')
    await page.getByRole('button', { name: 'Add text to Description Markdown', exact: true }).last().click()
    const body = page.getByRole('textbox', { name: 'Description Markdown', exact: true })
    await body.fill('## Before\n\nWork **hours**.\n\n## After')
    await page.getByRole('tab', { name: 'Timetable', exact: true }).click()
    await workspace.getByText('Work hours.', { exact: true }).click()
    await body.press('End')
    await page.getByRole('button', { name: 'Insert table', exact: true }).click()
    await expect(workspace.getByRole('heading', { name: 'Before', exact: true })).toBeVisible()
    await expect(workspace.getByRole('heading', { name: 'After', exact: true })).toBeVisible()
    await page.getByRole('tab', { name: 'Timetable', exact: true }).click()
    const cell = (address: string) => workspace.getByRole('textbox', { name: `Cell ${address}`, exact: true })
    await cell('A2').fill('2')
    await cell('B2').fill('3')
    await cell('C2').fill('=SUMMARIZE(A2:B2)')
    await cell('A3').fill('4')
    await expect(cell('C2')).toHaveValue('5')
    await cell('B3').fill('First line\nSecond line | literal')
    await cell('C3').fill('=SUMMARIZE(A2:A3)')
    await workspace.getByRole('heading', { name: 'Time plan' }).click()
    await expect(cell('C3')).toHaveValue('6')
    const width = workspace.getByRole('separator', { name: 'Resize column A', exact: true })
    await width.focus(); await width.press('ArrowRight')
    await expect(width).toHaveAttribute('aria-valuenow', '190')
    expect((await workspace.locator('th').first().boundingBox())!.width).toBeCloseTo(190, 0)
    const height = workspace.getByRole('separator', { name: 'Resize row 2', exact: true })
    const box = (await height.boundingBox())!
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
    await page.mouse.down(); await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2 + 30); await page.mouse.up()
    await expect(height).toHaveAttribute('aria-valuenow', '78')
    await cell('A3').focus()
    await page.getByRole('button', { name: 'Add row below 3', exact: true }).click()
    await expect(cell('A4')).toBeVisible()
    await cell('A4').focus()
    await page.getByRole('button', { name: 'Remove row 4', exact: true }).click()
    await expect(cell('A4')).toHaveCount(0)
    await cell('C2').focus()
    await page.getByRole('button', { name: 'Add column after C', exact: true }).click()
    await cell('D2').focus()
    await page.getByRole('button', { name: 'Remove column D', exact: true }).click()
    await expect(cell('D2')).toHaveCount(0)
    await cell('B2').focus()
    await cell('B2').press('ArrowDown')
    await expect(cell('B3')).toBeFocused()
    await cell('B3').press('Tab')
    await expect(cell('C3')).toBeFocused()
    await expect(cell('C2')).toHaveValue('5')
    await expect.poll(async() => {
        const saved = await (await owner.request.get(baseURL + '/api/thesis')).json()
        return saved.body
    }, { timeout: 12000 }).toContain('First line<br>Second line &#124; literal')
    await page.getByRole('tab', { name: 'Plan', exact: true }).click()
    await page.getByRole('button', { name: 'Add text to Description Markdown', exact: true }).last().click()
    await body.fill('## Milestones\n\n- **Write** the thesis.')
    await page.locator('.enterprise-theme').evaluate(element => element.scrollTo({ top: 0 }))
    await page.getByRole('tab', { name: 'Research', exact: true }).click()
    await page.getByRole('button', { name: 'Add text to Description Markdown', exact: true }).last().click()
    await body.fill('## Sources\n\n<script>window.unsafeThesis = true</script>\n\n[Unsafe](javascript:alert(1))')
    await expect.poll(async() => (await (await owner.request.get(baseURL + '/api/thesis')).json()).body, { timeout: 12000 }).toContain('## Sources')
    await page.reload()
    await page.getByRole('tab', { name: 'Timetable', exact: true }).click()
    await expect(cell('C2')).toHaveValue('5')
    await expect(cell('C3')).toHaveValue('6')
    await expect(cell('B3')).toHaveValue('First line\nSecond line | literal')
    await expect(width).toHaveAttribute('aria-valuenow', '190')
    expect((await workspace.locator('th').first().boundingBox())!.width).toBeCloseTo(190, 0)
    await expect(height).toHaveAttribute('aria-valuenow', '78')
    const reader = await browser.newContext()
    await reader.addInitScript(socketFixture)
    const publicPage = await reader.newPage()
    await publicPage.goto(baseURL + '/thesis')
    const publicWorkspace = publicPage.getByRole('region', { name: 'Thesis document' })
    for (const name of ['Overview', 'Timetable', 'Plan', 'Research']) {
        await publicPage.getByRole('tab', { name, exact: true }).click()
        await expect(publicWorkspace.getByRole('textbox')).toHaveCount(0)
        await expect(publicWorkspace.getByRole('button', { name: 'Insert table' })).toHaveCount(0)
        await expect(publicWorkspace.getByRole('separator')).toHaveCount(0)
    }
    expect(await publicPage.evaluate(() => Boolean((window as unknown as { unsafeThesis?: boolean }).unsafeThesis))).toBe(false)
    await publicPage.getByRole('tab', { name: 'Timetable', exact: true }).click()
    await expect(publicWorkspace.getByRole('cell', { name: '6', exact: true })).toBeVisible()
    await publicPage.setViewportSize({ width: 390, height: 844 })
    expect(await publicPage.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.setViewportSize({ width: 390, height: 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    const saved = await (await reader.request.get(baseURL + '/api/thesis')).json()
    for (const method of ['PUT', 'POST']) {
        const denied = await reader.request.fetch(baseURL + '/api/thesis', { method, headers: { Origin: baseURL! }, data: saved })
        expect(denied.status()).toBe(403)
    }
    await reader.addCookies([{ name: 'id', value: 'another-user', url: baseURL! }, { name: 'access_token', value: 'synthetic-owner', url: baseURL! }])
    expect((await reader.request.put(baseURL + '/api/thesis', { headers: { Origin: baseURL! }, data: saved })).status()).toBe(403)
    await page.screenshot({ path: '/tmp/thesis-workspace-owner-mobile.png', fullPage: true })
    await publicPage.setViewportSize({ width: 1440, height: 1000 })
    await publicPage.screenshot({ path: '/tmp/thesis-workspace-reader.png', fullPage: true })
    expect(errors).toEqual([])
    await owner.close(); await reader.close()
})
