import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import path from 'node:path'

const root = process.cwd()

test('public workflow reliability contracts are not demo-only', async () => {
    const pwnedClient = await readFile(path.join(root, 'src/utils/pwned/checkHash.ts'), 'utf8')
    const pwnedRoute = await readFile(path.join(root, 'src/app/api/pwned/route.ts'), 'utf8')
    const pwnedPage = await readFile(path.join(root, 'src/app/pwned/pageClient.tsx'), 'utf8')
    const registerPage = await readFile(path.join(root, 'src/app/register/pageClient.tsx'), 'utf8')
    const contact = await readFile(path.join(root, 'src/components/contact/contact.tsx'), 'utf8')
    const contactRoute = await readFile(path.join(root, 'src/app/api/contact/route.ts'), 'utf8')
    const dwmPage = await readFile(path.join(root, 'src/app/solutions/dwm/pageClient.tsx'), 'utf8')
    const apiPwnedHandler = await readFile(path.join(root, '../api/src/handlers/pwned/post.ts'), 'utf8')
    const apiPwnedUtility = await readFile(path.join(root, '../api/src/utils/pwned/checkPwned.ts'), 'utf8')

    expect(pwnedClient).toContain('normalizeSha1Hash')
    expect(pwnedClient).toContain('body: JSON.stringify({ prefix })')
    expect(pwnedClient).not.toContain('body: JSON.stringify({ password })')
    expect(pwnedClient).not.toContain('window.crypto.subtle.digest')
    expect(pwnedRoute).toContain('A valid SHA-1 hash prefix is required.')
    expect(pwnedRoute).not.toContain('password =')
    expect(pwnedPage).toContain('setHashInput(\'\')')
    expect(pwnedPage).toContain('data-bloom-hash-safety-boundary')
    expect(pwnedPage).toContain('This lookup does not ask for, derive, or transmit the underlying secret.')
    expect(apiPwnedHandler).toContain('normalizeSha1Prefix')
    expect(apiPwnedHandler).toContain('fetchPwnedRange')
    expect(apiPwnedHandler).toContain('Do not send raw secrets to this endpoint.')
    expect(apiPwnedHandler).not.toContain('password')
    expect(apiPwnedHandler).not.toContain('checkPwned(')
    expect(apiPwnedUtility).toContain('sha1SecretHash')
    expect(apiPwnedUtility).toContain('checkHibpRangeForHash')
    expect(apiPwnedUtility).toContain('User-Agent\': \'hanasand-bloom-hash-lookup')
    expect(apiPwnedUtility).not.toContain('body: JSON.stringify({ password })')
    expect(apiPwnedUtility).not.toContain('internal-pwned')

    expect(registerPage).toContain('data-managed-onboarding-intake')
    expect(registerPage).toContain('fetch(\'/api/contact\'')
    expect(registerPage).toContain('plan: \'managed-onboarding\'')
    expect(registerPage).toContain('securityReview: true')
    expect(registerPage).toContain('data-managed-onboarding-result')
    expect(registerPage).not.toContain('name=\'businessEmail\'')
    expect(registerPage).not.toContain('name=\'company\'')

    expect(contact).toContain('fetch(\'/api/contact\'')
    expect(contact).toContain('Ticket <span')
    expect(contact).toContain('data-contact-intake-routing')
    expect(contact).toContain('data-contact-security-review')
    expect(contact).toContain('deliveryPreference: values.deliveryPreference')
    expect(contact).toContain('securityReview: values.securityReview')
    expect(contact).not.toContain('window.location.href = mailtoLink')
    expect(contactRoute).toContain('ticketId')
    expect(contactRoute).toContain('CONTACT_FORWARD_URL')
    expect(contactRoute).toContain('deliveryPreference')
    expect(contactRoute).toContain('securityReview')
    expect(contactRoute).toContain('security review material')

    expect(dwmPage).toContain('fetch(\'/api/dwm/webhook-sink\'')
    expect(dwmPage).toContain('Validate sample payload')
    expect(dwmPage).toContain('Save local preview')
    expect(dwmPage).toContain('data-dwm-public-webhook-boundary')
    expect(dwmPage).toContain('Your endpoint was not contacted.')
    expect(dwmPage).not.toContain('window.location.assign(\'/dashboard/automations?setup=dwm\')')
})
