export const HIGH_YIELD_RANSOMWARE_QUERIES = [
  "LockBit3", "Qilin", "Akira", "Play", "Clop",
  "LockBit2", "RansomHub", "INC Ransom", "ALPHV", "DragonForce",
  "BianLian", "Black Basta", "Medusa", "TheGentlemen", "SafePay",
  "8Base", "Lynx", "Everest", "Conti", "Dispossessor",
  "LockBit5", "Pysa", "Hunters", "NightSpire", "KillSec",
  "Sinobi", "Rhysida", "Cactus", "Royal", "Hive",
  "RansomHouse", "Fog", "Vice Society", "BlackSuit", "DevMan",
  "Babuk2", "Stormous", "Coinbase Cartel", "Handala", "FunkSec",
  "Malas", "WorldLeaks", "Cloak", "APT73", "BlackByte",
  "Nova", "Avaddon", "Meow", "Snatch", "Sarcoma",
  "Space Bears", "Ragnar Locker", "ShinyHunters", "NoEscape", "RAWorld",
  "SilentRansomGroup", "Toufan", "ElDorado", "Interlock", "Monti",
  "Cuba", "PayoutsKing", "Arcus Media", "Pear", "REvil",
  "Abyss", "Genesis", "Kairos", "RansomEXX", "Anubis",
  "3AM", "Lorenz", "Warlock", "Cicada3301", "DireWolf",
  "Karakurt", "AvosLocker", "Beast", "Quantum", "Ransomed",
  "MedusaLocker", "BlackLock", "LV", "BrainCipher", "Flocker",
  "Maze", "Chaos", "DarkVault", "Krybit", "LostTrust",
  "Mallox", "Tengu", "Trigona", "Knight", "Nitrogen",
  "Crypto24", "Termite", "Midas", "BlackShrantac", "DonutLeaks",
  "Gunra", "AILock", "DarkLeakMarket", "Dragon Ransomware", "Embargo",
  "Securotrop", "CiphBit", "HellDown", "Insomnia", "Nokoyawa",
  "ArvinClub", "Spook", "Lamashtu", "Dan0n", "Obscura",
  "WannaCry", "BlackMatter", "Marketo", "SunCrypt", "AlphaLocker",
  "BlackNevas", "MetaEncryptor", "Frag", "Money Message", "PayloadBin",
  "Onyx", "KelvinSecurity", "M3RX", "NetWalker", "WereWolves",
  "DoppelPaymer", "FulcrumSec", "Kraken", "Vect", "Lapsus$",
  "Radar"
];
