export const DEFAULT_API_BASE = "https://api.hanasand.com/api/ti/search";
export const ACTOR_START_EVENT = "apify-actor-start";
export const DATASET_ITEM_EVENT = "apify-default-dataset-item";
export const MAX_QUERIES_PER_RUN = 260;

export const DEFAULT_QUERIES = [
  "APT29", "APT28", "APT42", "Lazarus Group", "Volt Typhoon",
  "Salt Typhoon", "Turla", "Sandworm", "Kimsuky", "MuddyWater",
  "Charming Kitten", "Scattered Spider", "LockBit", "Clop", "Akira",
  "Black Basta", "Play", "RansomHub", "ALPHV", "Hunters International",
  "Qilin", "Medusa", "BianLian", "DragonForce", "INC Ransom",
  "8Base", "Royal", "BlackSuit", "Rhysida", "Everest",
  "KillSec", "Cactus", "Lynx", "SafePay", "FunkSec",
  "BlackByte", "Snatch", "Stormous", "REvil", "Conti",
  "Maze", "DarkSide", "Babuk", "Hive", "DoppelPaymer",
  "Cuba", "Ragnar Locker", "NoEscape", "Dark Angels", "Lorenz",
  "FIN7", "FIN8", "FIN11", "Evil Corp", "TA505",
  "APT41", "APT40", "APT31", "APT27", "APT10",
  "Mustang Panda", "Earth Estries", "UNC3886", "Flax Typhoon", "Bronze Starlight",
  "APT37", "APT43", "APT33", "APT34", "APT35",
  "APT36", "APT38", "APT39", "Transparent Tribe", "SideWinder",
  "Bitter", "Confucius", "Patchwork", "DoNot Team", "Gamaredon",
  "OilRig", "BlueNoroff", "Andariel", "TA410",
  "TA416", "TA428", "TA459", "TA551", "TA558",
  "TA577", "TA570", "TA866", "TA2541", "Carbanak",
  "Cobalt Group", "Lapsus$", "Storm-0501", "Storm-0978", "Storm-1811",
  "Raspberry Robin", "Interlock", "Fog", "HellCat", "Luna Moth",
  "Karakurt", "RansomHouse", "Vice Society", "Monti", "Money Message",
  "Mallox", "RansomEXX", "Abyss", "3AM", "Knight",
  "NoName057(16)", "Killnet", "Anonymous Sudan", "SiegedSec", "GhostSec",
  "Dark Pink", "Winter Vivern", "TA473", "FIN6", "FIN12",
  "UNC3944", "UNC4841", "UNC5221", "UNC5174", "UNC5537",
  "Storm-0558", "Storm-1152", "Storm-1283", "Storm-1567", "Embargo",
  "LockBitSupp", "BlackMatter", "Cloak", "AvosLocker", "Mespinoza",
  "Pysa", "Nefilim", "NetWalker", "Egregor", "Dharma",
  "LockFile", "Maui", "Yanluowang", "Cicada3301", "Arcus Media",
  "Space Bears", "WereWolves", "Meow", "Dragonfly", "Energetic Bear",
  "Berserk Bear", "Cozy Bear", "Fancy Bear", "Equation Group", "Duqu",
  "DarkHotel", "Sofacy", "Sednit", "Hafnium", "Nobelium",
  "Midnight Blizzard", "CozyDuke", "UAC-0056", "UAC-0099", "Void Blizzard",
  "Forest Blizzard", "Secret Blizzard", "Seashell Blizzard", "Cadet Blizzard", "Emerald Sleet",
  "Diamond Sleet", "Sapphire Sleet", "Ruby Sleet", "Crimson Sandstorm", "Mint Sandstorm",
  "Peach Sandstorm", "Pioneer Kitten", "Fox Kitten", "Moses Staff", "Agrius",
  "Molerats", "Gaza Cybergang", "Tropic Trooper", "Lotus Blossom", "Naikon",
  "Higaisa", "TA445", "TA456", "TA427", "TA450",
  "TA471", "TA569", "TA578", "TA585", "TA596",
  "Lumma Stealer", "RedLine Stealer", "Raccoon Stealer", "Vidar", "FormBook",
  "Agent Tesla", "AsyncRAT", "Remcos", "DarkGate", "SocGholish",
  "IcedID", "Bumblebee", "QakBot", "Emotet", "TrickBot",
  "Dridex", "SmokeLoader", "Amadey", "DanaBot", "Zloader",
  "XWorm", "NetSupport RAT", "DarkComet", "Cobalt Strike", "Sliver",
  "Brute Ratel", "PlugX", "ShadowPad", "Covenant", "Mythic",
  "Storm-1175", "Winnti", "Black Basta ransomware", "Akira ransomware", "Play ransomware",
  "Remcos RAT", "Hunters International ransomware", "Qilin ransomware", "GuLoader", "Medusa ransomware",
  "Rhysida ransomware", "SideCopy", "ScarCruft", "Grandoreiro", "OceanLotus",
  "APT32", "Earth Lusca", "StealC", "Atomic Stealer"
];
