import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildShareProjectResponse } from '../src/handlers/tools/ai.ts'

type ToolFile = { action: string; path: string; content: string }
type Kind = 'website' | 'api' | 'bot' | 'worker'
type Story = { id: number; title: string; prompt: string; kind: Kind; mustMention: RegExp[] }

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(scriptDir, '..', '..')
const outRoot = path.join(repoRoot, 'sandbox', 'share-chat-operational-assurance-stories')

const stories: Story[] = [
    { id: 361, title: 'Alerting SIEM API', kind: 'api', prompt: 'Create alerting SIEM API with alert rules SIEM events request IDs metrics audit hash vulnerability findings.', mustMention: [/\/alerts/i, /alertRules/i, /\/siem-events/i, /siemEvents/i, /x-request-id/i, /\/metrics/i, /auditHash/i, /\/vulnerability-findings/i] },
    { id: 362, title: 'Access Review SSO API', kind: 'api', prompt: 'Build access review SSO API with accessReviews sso config JWKS admin role gates RLS policies request IDs security review.', mustMention: [/\/access-reviews/i, /accessReviews/i, /\/sso-config/i, /jwksUri/i, /ADMIN_ROLE/i, /requireRole/i, /rlsPolicies/i, /docs\/security-review\.md/i] },
    { id: 363, title: 'Data Classification API', kind: 'api', prompt: 'Create data classification API with dataClassification DPIA data residency retention holds PII redaction audit hash backup verification.', mustMention: [/\/data-classification/i, /dataClassification/i, /\/dpia/i, /\/data-residency/i, /retentionHolds/i, /redact/i, /auditHash/i, /\/backup\/verify/i] },
    { id: 364, title: 'Backup Verification API', kind: 'api', prompt: 'Build backup verification API with backupVerification restore evidence audit release evidence schema rollback synthetic checks metrics.', mustMention: [/\/backup\/verify/i, /backupVerification/i, /\/restore/i, /appendAudit/i, /\/release-evidence/i, /\/schema-rollback/i, /\/synthetic-checks/i, /\/metrics/i] },
    { id: 365, title: 'Release Evidence Site', kind: 'website', prompt: 'Create release evidence launch site with release evidence runbook SLO observability access review chaos drill rollback plan verification CI Docker.', mustMention: [/docs\/release-evidence\.md/i, /docs\/runbook\.md/i, /docs\/slo\.md/i, /docs\/observability\.md/i, /docs\/access-review\.md/i, /docs\/chaos-drill\.md/i, /Rollback plan/i, /Verification/i, /\.github\/workflows\/ci\.yml/i, /Docker/i] },
    { id: 366, title: 'Chaos Experiment API', kind: 'api', prompt: 'Create chaos experiment API with chaosExperiments circuitBreaker incident drills synthetic checks metrics rollback approvals failure owner.', mustMention: [/\/chaos-experiments/i, /chaosExperiments/i, /circuitBreaker/i, /\/incident-drills/i, /\/synthetic-checks/i, /\/metrics/i, /\/rollback-approvals/i, /failureOwner/i] },
    { id: 367, title: 'Change Request API', kind: 'api', prompt: 'Build change request API with changeRequests rollback approvals release evidence API version history schema drift contract tests OpenAPI.', mustMention: [/\/change-requests/i, /changeRequests/i, /\/rollback-approvals/i, /\/release-evidence/i, /\/api-version-history/i, /\/schema-drift/i, /\/contract-tests/i, /\/openapi\.json/i] },
    { id: 368, title: 'Egress Encryption API', kind: 'api', prompt: 'Create egress encryption API with deny-by-default egress policy encryption plan CSP security headers SSO config dependency review threat model.', mustMention: [/\/egress-policy/i, /egressPolicy/i, /\/encryption-plan/i, /encryptionPlan/i, /content-security-policy/i, /\/sso-config/i, /\/dependency-review/i, /docs\/threat-model\.md/i] },
    { id: 369, title: 'API Version Drift API', kind: 'api', prompt: 'Create API version drift API with apiVersionHistory schemaDrift contract tests OpenAPI request IDs synthetic checks release evidence.', mustMention: [/\/api-version-history/i, /apiVersionHistory/i, /\/schema-drift/i, /schemaDrift/i, /\/contract-tests/i, /\/openapi\.json/i, /x-request-id/i, /\/synthetic-checks/i, /\/release-evidence/i] },
    { id: 370, title: 'Tenant Quota API', kind: 'api', prompt: 'Build tenant quota API with usageQuotas rate limits request IDs metrics owner scoping RLS policies shaped errors.', mustMention: [/\/usage-quotas/i, /usageQuotas/i, /rateLimit/i, /x-request-id/i, /\/metrics/i, /ownerId/i, /rlsPolicies/i, /request_error/i] },
    { id: 371, title: 'Replay Governance Worker', kind: 'worker', prompt: 'Create replay governance worker with replayPolicy retryBudget replayRequests stuckJobDetector workerAlerts DLQ replay endpoint replay requests stuck jobs.', mustMention: [/replayPolicy/i, /retryBudget/i, /replayRequests/i, /stuckJobDetector/i, /workerAlerts/i, /\/api\/jobs\/:id\/replay/i, /\/api\/replay-requests/i, /\/api\/stuck-jobs/i] },
    { id: 372, title: 'Poison Queue Alert Worker', kind: 'worker', prompt: 'Build poison queue alert worker with workerAlerts poisonJobs circuitBreaker retryBudget leases heartbeats backoff replay endpoint worker status.', mustMention: [/workerAlerts/i, /poisonJobs/i, /circuitBreaker/i, /retryBudget/i, /leaseUntil/i, /heartbeatAt/i, /BACKOFF_MS/i, /\/api\/jobs\/:id\/replay/i, /worker-status/i] },
    { id: 373, title: 'Access Review Portal Site', kind: 'website', prompt: 'Create access review portal site with access review security review threat model data classification no lock-in backend contract CI Docker.', mustMention: [/docs\/access-review\.md/i, /docs\/security-review\.md/i, /docs\/threat-model\.md/i, /docs\/data-classification\.md/i, /No platform lock-in/i, /Backend contract/i, /\.github\/workflows\/ci\.yml/i, /Docker/i] },
    { id: 374, title: 'Observability Evidence Site', kind: 'website', prompt: 'Build observability evidence incident status site with observability docs SLO docs runbook release evidence incident timeline SLO evidence postmortems CI Docker.', mustMention: [/docs\/observability\.md/i, /docs\/slo\.md/i, /docs\/runbook\.md/i, /docs\/release-evidence\.md/i, /Incident timeline/i, /SLO evidence/i, /Postmortems/i, /\.github\/workflows\/ci\.yml/i, /Docker/i] },
    { id: 375, title: 'Encryption Procurement Site', kind: 'website', prompt: 'Build encryption procurement site with encryption plan egress policy procurement review SBOM threat model security review source export rollback path.', mustMention: [/docs\/procurement-review\.md/i, /docs\/sbom/i, /docs\/threat-model/i, /docs\/security-review/i, /Source export/i, /Rollback path/i, /Docker/i] },
    { id: 376, title: 'SIEM Audit Export API', kind: 'api', prompt: 'Create SIEM audit export API with SIEM events audit events immutable audit hash request IDs vulnerability findings alerts metrics.', mustMention: [/\/siem-events/i, /siemEvents/i, /auditEvents/i, /auditHash/i, /x-request-id/i, /\/vulnerability-findings/i, /\/alerts/i, /\/metrics/i] },
    { id: 377, title: 'Release Rollback API', kind: 'api', prompt: 'Build release rollback API with rollback approvals release evidence change requests backup verification schema rollback audit evidence.', mustMention: [/\/rollback-approvals/i, /rollbackApprovals/i, /\/release-evidence/i, /\/change-requests/i, /\/backup\/verify/i, /\/schema-rollback/i, /appendAudit/i] },
    { id: 378, title: 'Data Export Governance API', kind: 'api', prompt: 'Create data export governance API with data classification data residency access reviews RLS policies retention holds egress policy encryption plan.', mustMention: [/\/data-classification/i, /\/data-residency/i, /\/access-reviews/i, /rlsPolicies/i, /retentionHolds/i, /\/egress-policy/i, /\/encryption-plan/i] },
    { id: 379, title: 'Worker Assurance Runbook', kind: 'worker', prompt: 'Create worker assurance runbook with observability runbook SLO chaos drill retry budget replay policy stuck job detector worker alerts.', mustMention: [/docs\/observability\.md/i, /docs\/runbook\.md/i, /docs\/slo\.md/i, /docs\/chaos-drill\.md/i, /retryBudget/i, /replayPolicy/i, /stuckJobDetector/i, /workerAlerts/i] },
    { id: 380, title: 'Production Assurance API', kind: 'api', prompt: 'Create production assurance API with alerting SIEM access reviews data classification backup verification release evidence chaos experiments rollback approvals change requests egress policy encryption plan API version history schema drift usage quotas SSO JWKS SBOM threat model DPIA SLO runbooks incident drills synthetic checks vulnerability findings payload limits security headers request IDs metrics RLS retention holds audit hash secrets rotation outbox circuit breaker contract tests OpenAPI transactions RBAC backup restore migrations feature flags PII redaction idempotency webhook signatures pagination schemaVersion failureOwner rate limiting token gate health readiness CI Docker.', mustMention: [/\/alerts/i, /\/siem-events/i, /\/access-reviews/i, /\/data-classification/i, /\/backup\/verify/i, /\/release-evidence/i, /\/chaos-experiments/i, /\/rollback-approvals/i, /\/change-requests/i, /\/egress-policy/i, /\/encryption-plan/i, /\/api-version-history/i, /\/schema-drift/i, /\/usage-quotas/i, /\/sso-config/i, /jwksUri/i, /docs\/sbom\.json/i, /docs\/threat-model\.md/i, /\/dpia/i, /\/slo/i, /docs\/runbook\.md/i, /\/incident-drills/i, /\/synthetic-checks/i, /\/vulnerability-findings/i, /MAX_BODY_BYTES/i, /content-security-policy/i, /x-request-id/i, /\/metrics/i, /rlsPolicies/i, /retentionHolds/i, /auditHash/i, /\/security\/secrets\/rotate/i, /outboxEvents/i, /circuitBreaker/i, /\/contract-tests/i, /\/openapi\.json/i, /withTransaction/i, /requireRole/i, /\/backup/i, /\/restore/i, /migrations/i, /featureFlags/i, /redact/i, /idempotency/i, /verifyWebhookSignature/i, /nextCursor/i, /schemaVersion/i, /failureOwner/i, /rateLimit/i, /API_TOKEN/i] },
]

function parseToolFiles(message: string) { return [...message.matchAll(/<hanasand-tool>([\s\S]*?)<\/hanasand-tool>/g)].map((match) => JSON.parse(match[1]) as ToolFile) }
async function exists(filePath: string) { try { await fs.access(filePath); return true } catch { return false } }
async function read(filePath: string) { return await fs.readFile(filePath, 'utf8').catch(() => '') }
async function writeFiles(story: Story, files: ToolFile[]) {
    const target = path.join(outRoot, `${story.id}-${slugify(story.title)}`)
    await fs.rm(target, { recursive: true, force: true })
    for (const file of files) { const filePath = path.join(target, file.path); await fs.mkdir(path.dirname(filePath), { recursive: true }); await fs.writeFile(filePath, file.content) }
    return target
}
async function verify(story: Story, target: string, files: ToolFile[]) {
    const allContent = files.map((file) => `${file.path}\n${file.content}`).join('\n---\n')
    const checks: Record<string, boolean> = {
        enoughFiles: files.length >= (story.kind === 'website' ? 22 : story.kind === 'worker' ? 22 : 20), packageJson: await exists(path.join(target, 'package.json')), readme: await exists(path.join(target, 'README.md')), envExample: await exists(path.join(target, '.env.example')), dockerfile: await exists(path.join(target, 'Dockerfile')), compose: await exists(path.join(target, 'docker-compose.yml')), ci: await exists(path.join(target, '.github/workflows/ci.yml')), observability: await exists(path.join(target, 'docs/observability.md')), releaseEvidence: await exists(path.join(target, 'docs/release-evidence.md')), dataClassification: await exists(path.join(target, 'docs/data-classification.md')), accessReview: await exists(path.join(target, 'docs/access-review.md')), chaosDrill: await exists(path.join(target, 'docs/chaos-drill.md')), noHardcodedSecrets: !/(sk-[a-z0-9]|xox[baprs]-|DISCORD_TOKEN\s*=\s*[^\n]*[A-Za-z0-9]{20,})/i.test(allContent), noLorem: !/lorem ipsum|placeholder text|todo: write copy/i.test(allContent), handoff: /handoff|verification|docker compose|failure owner|rollback|restore|CI|security review|runbook|observability/i.test(await read(path.join(target, 'README.md'))), mentions: story.mustMention.every((pattern) => pattern.test(allContent)),
    }
    if (story.kind === 'website') { checks.page = await exists(path.join(target, 'src/app/page.tsx')); checks.layout = await exists(path.join(target, 'src/app/layout.tsx')); checks.accessible = /aria-label|<label|Skip to content/i.test(allContent); checks.responsive = /clamp\(|auto-fit|flexWrap|mobile/i.test(allContent); checks.exportable = /output:\s*'standalone'|docker compose/i.test(allContent); checks.trust = /No platform lock-in|Privacy and data seams documented|Backend contract|Rollback path|Source export/i.test(allContent) }
    if (story.kind === 'api') { checks.apiSource = await exists(path.join(target, 'src/index.ts')); checks.healthReady = /\/health|\/ready/.test(allContent); checks.assurance = /\/alerts|\/siem-events|\/access-reviews|\/data-classification|\/backup\/verify|\/release-evidence|\/chaos-experiments|\/rollback-approvals|\/change-requests|\/egress-policy|\/encryption-plan|\/api-version-history|\/schema-drift|\/usage-quotas|\/sso-config/i.test(allContent); checks.trustArchitecture = /auditHash|appendAudit|\/data-residency|retentionHolds|outboxEvents|circuitBreaker|\/security\/secrets\/rotate|\/contract-tests/i.test(allContent); checks.operability = /x-request-id|\/openapi\.json|\/metrics|CACHE_TTL_SECONDS|withTransaction|ALLOWED_ORIGINS/i.test(allContent) }
    if (story.kind === 'worker') { checks.workerSource = await exists(path.join(target, 'src/worker.ts')); checks.queueSource = await exists(path.join(target, 'src/queue.ts')); checks.replay = /replayDeadLetter|replayRequests|\/api\/jobs\/:id\/replay/i.test(allContent); checks.assurance = /retryBudget|stuckJobDetector|replayPolicy|workerAlerts|\/api\/replay-requests|\/api\/stuck-jobs/i.test(allContent); checks.leaseOutbox = /leaseUntil|heartbeatAt|outboxEvents|circuitBreaker/i.test(allContent); checks.failureOwner = /FAILURE_OWNER|failure owner/i.test(allContent) }
    if (story.kind === 'bot') { checks.botSource = await exists(path.join(target, 'src/index.ts')); checks.audit = /auditLog|audit/i.test(allContent); checks.safeStubs = /restartRequests|Restart request logged|maintenance|stub|Destructive actions require explicit review/i.test(allContent) }
    return checks
}
function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') }
await fs.rm(outRoot, { recursive: true, force: true }); await fs.mkdir(outRoot, { recursive: true })
const results = []
for (const story of stories) {
    const response = buildShareProjectResponse(story.prompt)
    if (!response) { results.push({ id: story.id, title: story.title, ok: false, reason: 'No builder response', checks: {} }); continue }
    const files = parseToolFiles(response.message); const target = await writeFiles(story, files); const checks = await verify(story, target, files); const ok = Object.values(checks).every(Boolean)
    results.push({ id: story.id, title: story.title, ok, target, fileCount: files.length, checks }); console.log(`${ok ? 'PASS' : 'FAIL'} ${story.id} ${story.title} (${files.length} files)`); if (!ok) console.log(Object.entries(checks).filter(([, value]) => !value).map(([key]) => `  - ${key}`).join('\n'))
}
const failed = results.filter((result) => !result.ok); await fs.writeFile(path.join(outRoot, 'results.json'), JSON.stringify({ generatedAt: new Date().toISOString(), results }, null, 2)); if (failed.length) throw new Error(`${failed.length} operational assurance stories failed.`); console.log(`All ${results.length} operational assurance stories passed.`)
