import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildShareProjectResponse } from '../src/handlers/tools/ai.ts'

type ToolFile = { action: string; path: string; content: string }
type Kind = 'website' | 'api' | 'bot' | 'worker'
type Story = { id: number; title: string; prompt: string; kind: Kind; mustMention: RegExp[] }

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(scriptDir, '..', '..')
const outRoot = path.join(repoRoot, 'sandbox', 'share-chat-enterprise-recovery-stories')

const stories: Story[] = [
    { id: 281, title: 'RBAC Admin Restore API', kind: 'api', prompt: 'Create admin restore API with RBAC requireRole rolesFor backup restore audit events owner scoping token gate health readiness no hardcoded secrets Docker.', mustMention: [/requireRole/i, /rolesFor/i, /\/backup/i, /\/restore/i, /auditEvents/i, /ownerId/i, /API_TOKEN/i] },
    { id: 282, title: 'Migration Escape Hatch Site', kind: 'website', prompt: 'Build escape hatch migration site for founder leaving locked-in AI builder with source export clean schema parallel run cutover plan rollback plan DNS SSL checklist verification Docker.', mustMention: [/Source export/i, /Clean schema/i, /Parallel run/i, /Cutover plan/i, /Rollback plan/i, /DNS checklist/i, /SSL checklist/i] },
    { id: 283, title: 'OAuth Permission Boundary API', kind: 'api', prompt: 'Create OAuth permission boundary API with RBAC role checks scoped records token gates rate limits audit events security headers pagination readiness Docker.', mustMention: [/requireRole/i, /ownerId/i, /API_TOKEN/i, /rateLimit/i, /auditEvents/i, /x-content-type-options/i, /nextCursor/i] },
    { id: 284, title: 'Checkout Tax Invoice Site', kind: 'website', prompt: 'Build checkout tax invoice site with plans checkout states failed payments cancellation invoice notes security review handoff Docker.', mustMention: [/Plans/i, /Checkout states/i, /Failed payments/i, /Cancellation/i, /Invoice notes/i, /Security review/i] },
    { id: 285, title: 'Import Worker Backpressure Recovery', kind: 'worker', prompt: 'Build import worker backpressure recovery with idempotency retrying dead-letter poison quarantine event logs Redis worker status visible failure owner.', mustMention: [/idempotency/i, /events/i, /retrying/i, /dead/i, /poisonJobs/i, /worker-status/i, /Redis/i] },
    { id: 286, title: 'Analytics Consent Landing Page', kind: 'website', prompt: 'Create analytics consent marketing landing page with proof pricing FAQ lead capture privacy data seams analytics handoff Docker export.', mustMention: [/Proof/i, /Pricing/i, /FAQ/i, /lead capture/i, /Privacy and data seams documented/i, /Docker/i] },
    { id: 287, title: 'Feature Flag Rollout API', kind: 'api', prompt: 'Build feature flag rollout API with featureFlags role checks audit events rate limits schemaVersion failureOwner scoped records pagination health readiness backup restore.', mustMention: [/featureFlags/i, /requireRole/i, /auditEvents/i, /rateLimit/i, /schemaVersion/i, /failureOwner/i, /nextCursor/i, /\/backup/i, /\/restore/i] },
    { id: 288, title: 'Disaster Restore Runbook Site', kind: 'website', prompt: 'Build disaster restore runbook site with environment map DNS checklist SSL checklist rollback plan verification failure owner source export Docker responsive.', mustMention: [/Environment map/i, /DNS checklist/i, /SSL checklist/i, /Rollback plan/i, /Verification/i, /Failure owner/i] },
    { id: 289, title: 'Moderation Appeal Evidence Bot', kind: 'bot', prompt: 'Create Discord moderation appeal evidence bot with auditLog role stubs maintenance notices restart requests evidence safe env no destructive automatic actions Docker.', mustMention: [/auditLog/i, /restartRequests/i, /maintenance/i, /stub/i, /DISCORD_TOKEN/i, /Destructive actions require explicit review/i] },
    { id: 290, title: 'Customer Data Export Delete API', kind: 'api', prompt: 'Create customer data export delete API with PII redaction audit events scoped records pagination role-gated backup restore schemaVersion failureOwner.', mustMention: [/redact/i, /auditEvents/i, /ownerId/i, /nextCursor/i, /requireRole/i, /\/backup/i, /\/restore/i, /schemaVersion/i, /failureOwner/i] },
    { id: 291, title: 'Multi-Region Status Handoff Site', kind: 'website', prompt: 'Build multi-region incident observability status page with service health incident timeline subscriber notice SLO evidence postmortems escalation failure owner Docker.', mustMention: [/Service health/i, /Incident timeline/i, /Subscriber notice/i, /SLO evidence/i, /Postmortems/i, /Failure owner/i] },
    { id: 292, title: 'Webhook Replay Restore API', kind: 'api', prompt: 'Build webhook replay restore API with WEBHOOK_SIGNING_SECRET verifyWebhookSignature idempotency replay audit events backup restore owner scoping rate limits shaped errors readiness.', mustMention: [/WEBHOOK_SIGNING_SECRET/i, /verifyWebhookSignature/i, /idempotency/i, /auditEvents/i, /\/backup/i, /\/restore/i, /ownerId/i, /rateLimit/i] },
    { id: 293, title: 'CSV Reconciliation Worker Audit', kind: 'worker', prompt: 'Create CSV reconciliation worker audit with idempotency event logs retrying dead poison states worker status Redis no silent drops Docker.', mustMention: [/idempotency/i, /events/i, /retrying/i, /dead/i, /poisonJobs/i, /worker-status/i, /Redis/i] },
    { id: 294, title: 'Database Migration Review API', kind: 'api', prompt: 'Create database migration review API with migrations readiness checks role-gated restore backup export audit events owner scoping pagination token gates.', mustMention: [/migrations/i, /ready/i, /requireRole/i, /\/backup/i, /\/restore/i, /auditEvents/i, /ownerId/i, /nextCursor/i, /API_TOKEN/i] },
    { id: 295, title: 'Accessibility Lawsuit Landing Site', kind: 'website', prompt: 'Build accessibility lawsuit landing site with skip links keyboard flow contrast accessible forms reduced motion privacy seams Docker export.', mustMention: [/Skip links/i, /Keyboard flow/i, /Contrast/i, /Forms/i, /Reduced motion/i, /Accessible controls/i] },
    { id: 296, title: 'Support SLA Evidence API', kind: 'api', prompt: 'Create support SLA evidence API with audited support evidence PII redaction scoped records role checks backup restore rate limits shaped request_error.', mustMention: [/auditEvents/i, /redact/i, /ownerId/i, /requireRole/i, /\/backup/i, /\/restore/i, /rateLimit/i, /request_error/i] },
    { id: 297, title: 'Report Worker Cancellation Story', kind: 'worker', prompt: 'Build report worker cancellation story with idempotency event logs retrying dead poison states worker status Redis seam clear failure owner.', mustMention: [/idempotency/i, /events/i, /retrying/i, /dead/i, /poisonJobs/i, /worker-status/i, /Redis/i, /FAILURE_OWNER/i] },
    { id: 298, title: 'Source Ownership Marketing Site', kind: 'website', prompt: 'Create source ownership marketing site with no lock-in readable source export mobile layout accessible controls backend contract rollback path real handoff tasks.', mustMention: [/No platform lock-in/i, /Readable source export/i, /Mobile-first layout/i, /Accessible controls/i, /Backend contract/i, /Rollback path/i] },
    { id: 299, title: 'Tenant Audit Restore API', kind: 'api', prompt: 'Create tenant audit restore API with owner scoping role gates backup restore audit events PII redaction pagination schemaVersion failureOwner health readiness.', mustMention: [/ownerId/i, /requireRole/i, /\/backup/i, /\/restore/i, /auditEvents/i, /redact/i, /nextCursor/i, /schemaVersion/i, /failureOwner/i] },
    { id: 300, title: 'Production Recovery API', kind: 'api', prompt: 'Create production recovery API with RBAC backup restore migrations feature flags security headers PII redaction audit events idempotency webhook signatures pagination schemaVersion failureOwner rate limiting token gate health readiness.', mustMention: [/requireRole/i, /\/backup/i, /\/restore/i, /migrations/i, /featureFlags/i, /x-content-type-options/i, /redact/i, /auditEvents/i, /idempotency/i, /verifyWebhookSignature/i, /nextCursor/i, /schemaVersion/i, /failureOwner/i, /rateLimit/i, /API_TOKEN/i] },
]

function parseToolFiles(message: string) { return [...message.matchAll(/<hanasand-tool>([\s\S]*?)<\/hanasand-tool>/g)].map((match) => JSON.parse(match[1]) as ToolFile) }
async function exists(filePath: string) { try { await fs.access(filePath); return true } catch { return false } }
async function read(filePath: string) { return await fs.readFile(filePath, 'utf8').catch(() => '') }
async function writeFiles(story: Story, files: ToolFile[]) {
    const target = path.join(outRoot, `${story.id}-${slugify(story.title)}`)
    await fs.rm(target, { recursive: true, force: true })
    for (const file of files) { const filePath = path.join(target, file.path); await fs.mkdir(path.dirname(filePath), { recursive: true }); await fs.writeFile(filePath, file.content) }
    return target
}
async function verify(story: Story, target: string, files: ToolFile[]) {
    const allContent = files.map((file) => `${file.path}\n${file.content}`).join('\n---\n')
    const checks: Record<string, boolean> = {
        enoughFiles: files.length >= (story.kind === 'website' ? 8 : 7), packageJson: await exists(path.join(target, 'package.json')), readme: await exists(path.join(target, 'README.md')), envExample: await exists(path.join(target, '.env.example')), dockerfile: await exists(path.join(target, 'Dockerfile')), compose: await exists(path.join(target, 'docker-compose.yml')), noHardcodedSecrets: !/(sk-[a-z0-9]|xox[baprs]-|DISCORD_TOKEN\s*=\s*[^\n]*[A-Za-z0-9]{20,})/i.test(allContent), noLorem: !/lorem ipsum|placeholder text|todo: write copy/i.test(allContent), handoff: /handoff|verification|docker compose|failure owner|rollback|restore/i.test(await read(path.join(target, 'README.md'))), mentions: story.mustMention.every((pattern) => pattern.test(allContent)),
    }
    if (story.kind === 'website') { checks.page = await exists(path.join(target, 'src/app/page.tsx')); checks.layout = await exists(path.join(target, 'src/app/layout.tsx')); checks.accessible = /aria-label|<label|Skip to content/i.test(allContent); checks.responsive = /clamp\(|auto-fit|flexWrap|mobile/i.test(allContent); checks.exportable = /output:\s*'standalone'|docker compose/i.test(allContent); checks.trust = /No platform lock-in|Privacy and data seams documented|Backend contract|Rollback path/i.test(allContent) }
    if (story.kind === 'api') { checks.apiSource = await exists(path.join(target, 'src/index.ts')); checks.healthReady = /\/health|\/ready/.test(allContent); checks.validation = /title_required|Forbidden|setErrorHandler|request_error/i.test(allContent); checks.rateLimit = /rateBuckets|rateLimit|429|Limit reached/i.test(allContent); checks.scoped = /ownerId|x-account-id/i.test(allContent); checks.pagination = /nextCursor|limit = Math\.min|cursor/i.test(allContent); checks.schemaOwner = /schemaVersion|failureOwner/i.test(allContent); checks.auditPrivacy = /auditEvents|redact|WEBHOOK_SIGNING_SECRET|verifyWebhookSignature/i.test(allContent); checks.recovery = /requireRole|rolesFor|\/backup|\/restore|migrations|featureFlags|x-content-type-options/i.test(allContent) }
    if (story.kind === 'bot') { checks.botSource = await exists(path.join(target, 'src/index.ts')); checks.audit = /auditLog|audit/i.test(allContent); checks.safeStubs = /restartRequests|Restart request logged|maintenance|stub|Destructive actions require explicit review/i.test(allContent) }
    if (story.kind === 'worker') { checks.workerSource = await exists(path.join(target, 'src/worker.ts')); checks.queueSource = await exists(path.join(target, 'src/queue.ts')); checks.idempotent = /idempotency|idempotencyKey/i.test(allContent); checks.workerStatus = /worker-status|dead|failed|retrying|retry|poison/i.test(allContent); checks.eventLog = /events|event log|queue snapshot/i.test(allContent); checks.poison = /poisonJobs|poison/i.test(allContent); checks.failureOwner = /FAILURE_OWNER|failure owner/i.test(allContent) }
    return checks
}
function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') }
await fs.rm(outRoot, { recursive: true, force: true }); await fs.mkdir(outRoot, { recursive: true })
const results = []
for (const story of stories) {
    const response = buildShareProjectResponse(story.prompt)
    if (!response) { results.push({ id: story.id, title: story.title, ok: false, reason: 'No builder response', checks: {} }); continue }
    const files = parseToolFiles(response.message); const target = await writeFiles(story, files); const checks = await verify(story, target, files); const ok = Object.values(checks).every(Boolean)
    results.push({ id: story.id, title: story.title, ok, target, fileCount: files.length, checks }); console.log(`${ok ? 'PASS' : 'FAIL'} ${story.id} ${story.title} (${files.length} files)`); if (!ok) console.log(Object.entries(checks).filter(([, value]) => !value).map(([key]) => `  - ${key}`).join('\n'))
}
const failed = results.filter((result) => !result.ok); await fs.writeFile(path.join(outRoot, 'results.json'), JSON.stringify({ generatedAt: new Date().toISOString(), results }, null, 2)); if (failed.length) throw new Error(`${failed.length} enterprise recovery stories failed.`); console.log(`All ${results.length} enterprise recovery stories passed.`)
