import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildShareProjectResponse } from '../src/handlers/tools/ai.ts'

type ToolFile = { action: string; path: string; content: string }
type Kind = 'website' | 'api' | 'bot' | 'worker'
type Story = { id: number; title: string; prompt: string; kind: Kind; mustMention: RegExp[] }

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(scriptDir, '..', '..')
const outRoot = path.join(repoRoot, 'sandbox', 'share-chat-hardening-cliff-stories')

const stories: Story[] = [
    { id: 301, title: 'Transactional Billing Recovery API', kind: 'api', prompt: 'Create transactional billing recovery API with transaction rollback idempotency cache invalidation audit events request IDs OpenAPI metrics RBAC backup restore webhook signatures CI Docker.', mustMention: [/withTransaction/i, /metrics/i, /cache\.clear/i, /x-request-id/i, /\/openapi\.json/i, /requireRole/i, /\/backup/i, /\/restore/i, /verifyWebhookSignature/i, /\.github\/workflows\/ci\.yml/i] },
    { id: 302, title: 'CORS Debuggable Customer API', kind: 'api', prompt: 'Build CORS debuggable customer API with allowed origins CORS headers request IDs shaped errors owner scoping pagination rate limits readiness Docker.', mustMention: [/ALLOWED_ORIGINS/i, /allowedOrigin/i, /access-control-allow-origin/i, /x-request-id/i, /request_error/i, /ownerId/i, /nextCursor/i, /rateLimit/i] },
    { id: 303, title: 'Worker Cancellation Backoff Queue', kind: 'worker', prompt: 'Create worker cancellation backoff queue with cancelJob cancel endpoint BACKOFF_MS nextRunAt poison quarantine event logs Redis worker status.', mustMention: [/cancelJob/i, /\/api\/jobs\/:id\/cancel/i, /BACKOFF_MS/i, /nextRunAt/i, /poisonJobs/i, /events/i, /worker-status/i] },
    { id: 304, title: 'CI Export Ownership Marketing Site', kind: 'website', prompt: 'Build CI export ownership marketing site with source export Docker GitHub Actions CI no lock-in backend contract rollback path accessible controls.', mustMention: [/\.github\/workflows\/ci\.yml/i, /No platform lock-in/i, /Readable source export/i, /Docker/i, /Backend contract/i, /Rollback path/i, /Accessible controls/i] },
    { id: 305, title: 'OpenAPI Partner Integration API', kind: 'api', prompt: 'Create OpenAPI partner integration API with OpenAPI security headers request IDs idempotency webhook signature metrics backup restore readiness.', mustMention: [/\/openapi\.json/i, /x-content-type-options/i, /x-request-id/i, /idempotency/i, /verifyWebhookSignature/i, /\/metrics/i, /\/backup/i, /\/restore/i] },
    { id: 306, title: 'Cache TTL Product Catalog API', kind: 'api', prompt: 'Build cache TTL product catalog API with CACHE_TTL_SECONDS readCache writeCache cache hit miss metrics cache invalidation pagination owner scoping rate limits request IDs.', mustMention: [/CACHE_TTL_SECONDS/i, /readCache/i, /writeCache/i, /cacheHits/i, /cacheMisses/i, /cache\.clear/i, /nextCursor/i, /ownerId/i, /x-request-id/i] },
    { id: 307, title: 'Refund Dispute Transaction API', kind: 'api', prompt: 'Create refund dispute transaction API with withTransaction rollback metrics audit events PII redaction RBAC backup restore shaped errors.', mustMention: [/withTransaction/i, /rollbacks/i, /auditEvents/i, /redact/i, /requireRole/i, /\/backup/i, /\/restore/i, /request_error/i] },
    { id: 308, title: 'Disaster Cutover CI Site', kind: 'website', prompt: 'Build disaster cutover CI site with DNS SSL checklist rollback plan verification failure owner source export Docker GitHub Actions CI.', mustMention: [/DNS checklist/i, /SSL checklist/i, /Rollback plan/i, /Verification/i, /Failure owner/i, /Source export/i, /\.github\/workflows\/ci\.yml/i] },
    { id: 309, title: 'Moderator Evidence Bot With CI', kind: 'bot', prompt: 'Create Discord moderator evidence bot with audit logs safe stubs restart requests maintenance notices no destructive defaults env handling Docker CI.', mustMention: [/auditLog/i, /restartRequests/i, /maintenance/i, /stub/i, /DISCORD_TOKEN/i, /Destructive actions require explicit review/i, /\.github\/workflows\/ci\.yml/i] },
    { id: 310, title: 'Tenant Metrics API', kind: 'api', prompt: 'Create tenant metrics API with metrics request tracing scoped records rate limits cache hits writes rollbacks audit events pagination readiness.', mustMention: [/\/metrics/i, /metrics/i, /x-request-id/i, /ownerId/i, /rateLimit/i, /cacheHits/i, /writes/i, /rollbacks/i, /auditEvents/i, /nextCursor/i] },
    { id: 311, title: 'Report Worker Customer Cancel', kind: 'worker', prompt: 'Build report worker customer cancel with cancel endpoint event logs backoff retry dead poison states worker status Redis seam failure owner.', mustMention: [/cancelJob/i, /\/api\/jobs\/:id\/cancel/i, /BACKOFF_MS/i, /events/i, /retrying/i, /dead/i, /poisonJobs/i, /worker-status/i, /FAILURE_OWNER/i] },
    { id: 312, title: 'Security Headers API', kind: 'api', prompt: 'Create security headers API with CORS allowlist request IDs RBAC audit events PII redaction webhook signatures OpenAPI.', mustMention: [/x-content-type-options/i, /x-frame-options/i, /ALLOWED_ORIGINS/i, /x-request-id/i, /requireRole/i, /auditEvents/i, /redact/i, /verifyWebhookSignature/i, /\/openapi\.json/i] },
    { id: 313, title: 'Accessible Analytics Site', kind: 'website', prompt: 'Create accessible analytics consent marketing site with proof pricing FAQ lead capture privacy seams accessible controls CI Docker handoff tasks.', mustMention: [/Proof/i, /Pricing/i, /FAQ/i, /lead capture/i, /Privacy and data seams/i, /Accessible controls/i, /\.github\/workflows\/ci\.yml/i, /Docker/i] },
    { id: 314, title: 'Replay-Safe Webhook API', kind: 'api', prompt: 'Build replay safe webhook API with signature seam idempotency transaction rollback audit events metrics request IDs OpenAPI backup restore.', mustMention: [/verifyWebhookSignature/i, /idempotency/i, /withTransaction/i, /auditEvents/i, /\/metrics/i, /x-request-id/i, /\/openapi\.json/i, /\/backup/i, /\/restore/i] },
    { id: 315, title: 'Backpressure Import Worker', kind: 'worker', prompt: 'Create backpressure import worker with BACKOFF_MS cancellation idempotency poison quarantine event logs retry dead states Redis status counts.', mustMention: [/BACKOFF_MS/i, /cancelJob/i, /idempotency/i, /poisonJobs/i, /events/i, /retrying/i, /dead/i, /Redis/i, /worker-status/i] },
    { id: 316, title: 'Enterprise Status With CI Site', kind: 'website', prompt: 'Build enterprise incident observability status page with service health incident timeline subscriber notice SLO evidence postmortems failure owner Docker CI.', mustMention: [/Service health/i, /Incident timeline/i, /Subscriber notice/i, /SLO evidence/i, /Postmortems/i, /Failure owner/i, /\.github\/workflows\/ci\.yml/i] },
    { id: 317, title: 'Custom Rules Admin API', kind: 'api', prompt: 'Create custom rules admin API with feature flags migrations RBAC request IDs metrics backup restore OpenAPI transaction rollback.', mustMention: [/featureFlags/i, /migrations/i, /requireRole/i, /x-request-id/i, /\/metrics/i, /\/backup/i, /\/restore/i, /\/openapi\.json/i, /withTransaction/i] },
    { id: 318, title: 'Rate Limit UX API', kind: 'api', prompt: 'Build rate limit UX API with shaped Limit reached request_error request IDs CORS metrics owner scoping pagination readiness.', mustMention: [/Limit reached/i, /request_error/i, /x-request-id/i, /access-control-allow-origin/i, /\/metrics/i, /ownerId/i, /nextCursor/i, /\/ready/i] },
    { id: 319, title: 'Source Review Portfolio Site', kind: 'website', prompt: 'Create source review portfolio site with readable source export Docker CI accessible controls mobile layout backend contract rollback path no lock-in.', mustMention: [/Readable source export/i, /Docker/i, /\.github\/workflows\/ci\.yml/i, /Accessible controls/i, /Mobile-first layout/i, /Backend contract/i, /Rollback path/i, /No platform lock-in/i] },
    { id: 320, title: 'Production Operations API', kind: 'api', prompt: 'Create production operations API with CORS allowlist request IDs OpenAPI metrics cache TTL transaction rollback RBAC backup restore migrations feature flags security headers PII redaction audit events idempotency webhook signatures pagination schemaVersion failureOwner rate limiting token gate health readiness Docker CI.', mustMention: [/ALLOWED_ORIGINS/i, /x-request-id/i, /\/openapi\.json/i, /\/metrics/i, /CACHE_TTL_SECONDS/i, /withTransaction/i, /requireRole/i, /\/backup/i, /\/restore/i, /migrations/i, /featureFlags/i, /x-content-type-options/i, /redact/i, /auditEvents/i, /idempotency/i, /verifyWebhookSignature/i, /nextCursor/i, /schemaVersion/i, /failureOwner/i, /rateLimit/i, /API_TOKEN/i, /\.github\/workflows\/ci\.yml/i] },
]

function parseToolFiles(message: string) { return [...message.matchAll(/<hanasand-tool>([\s\S]*?)<\/hanasand-tool>/g)].map((match) => JSON.parse(match[1]) as ToolFile) }
async function exists(filePath: string) { try { await fs.access(filePath); return true } catch { return false } }
async function read(filePath: string) { return await fs.readFile(filePath, 'utf8').catch(() => '') }
async function writeFiles(story: Story, files: ToolFile[]) {
    const target = path.join(outRoot, `${story.id}-${slugify(story.title)}`)
    await fs.rm(target, { recursive: true, force: true })
    for (const file of files) { const filePath = path.join(target, file.path); await fs.mkdir(path.dirname(filePath), { recursive: true }); await fs.writeFile(filePath, file.content) }
    return target
}
async function verify(story: Story, target: string, files: ToolFile[]) {
    const allContent = files.map((file) => `${file.path}\n${file.content}`).join('\n---\n')
    const checks: Record<string, boolean> = {
        enoughFiles: files.length >= (story.kind === 'website' ? 9 : 8), packageJson: await exists(path.join(target, 'package.json')), readme: await exists(path.join(target, 'README.md')), envExample: await exists(path.join(target, '.env.example')), dockerfile: await exists(path.join(target, 'Dockerfile')), compose: await exists(path.join(target, 'docker-compose.yml')), ci: await exists(path.join(target, '.github/workflows/ci.yml')), noHardcodedSecrets: !/(sk-[a-z0-9]|xox[baprs]-|DISCORD_TOKEN\s*=\s*[^\n]*[A-Za-z0-9]{20,})/i.test(allContent), noLorem: !/lorem ipsum|placeholder text|todo: write copy/i.test(allContent), handoff: /handoff|verification|docker compose|failure owner|rollback|restore|CI/i.test(await read(path.join(target, 'README.md'))), mentions: story.mustMention.every((pattern) => pattern.test(allContent)),
    }
    if (story.kind === 'website') { checks.page = await exists(path.join(target, 'src/app/page.tsx')); checks.layout = await exists(path.join(target, 'src/app/layout.tsx')); checks.accessible = /aria-label|<label|Skip to content/i.test(allContent); checks.responsive = /clamp\(|auto-fit|flexWrap|mobile/i.test(allContent); checks.exportable = /output:\s*'standalone'|docker compose/i.test(allContent); checks.trust = /No platform lock-in|Privacy and data seams documented|Backend contract|Rollback path/i.test(allContent) }
    if (story.kind === 'api') { checks.apiSource = await exists(path.join(target, 'src/index.ts')); checks.healthReady = /\/health|\/ready/.test(allContent); checks.validation = /title_required|Forbidden|setErrorHandler|request_error/i.test(allContent); checks.rateLimit = /rateBuckets|rateLimit|429|Limit reached/i.test(allContent); checks.scoped = /ownerId|x-account-id/i.test(allContent); checks.pagination = /nextCursor|limit = Math\.min|cursor/i.test(allContent); checks.schemaOwner = /schemaVersion|failureOwner/i.test(allContent); checks.auditPrivacy = /auditEvents|redact|WEBHOOK_SIGNING_SECRET|verifyWebhookSignature/i.test(allContent); checks.recovery = /requireRole|rolesFor|\/backup|\/restore|migrations|featureFlags|x-content-type-options/i.test(allContent); checks.operability = /x-request-id|\/openapi\.json|\/metrics|CACHE_TTL_SECONDS|withTransaction|ALLOWED_ORIGINS/i.test(allContent) }
    if (story.kind === 'bot') { checks.botSource = await exists(path.join(target, 'src/index.ts')); checks.audit = /auditLog|audit/i.test(allContent); checks.safeStubs = /restartRequests|Restart request logged|maintenance|stub|Destructive actions require explicit review/i.test(allContent) }
    if (story.kind === 'worker') { checks.workerSource = await exists(path.join(target, 'src/worker.ts')); checks.queueSource = await exists(path.join(target, 'src/queue.ts')); checks.idempotent = /idempotency|idempotencyKey/i.test(allContent); checks.workerStatus = /worker-status|dead|failed|retrying|retry|poison|cancelled/i.test(allContent); checks.eventLog = /events|event log|queue snapshot/i.test(allContent); checks.poison = /poisonJobs|poison/i.test(allContent); checks.cancelBackoff = /cancelJob|BACKOFF_MS|nextRunAt|\/api\/jobs\/:id\/cancel/i.test(allContent); checks.failureOwner = /FAILURE_OWNER|failure owner/i.test(allContent) }
    return checks
}
function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') }
await fs.rm(outRoot, { recursive: true, force: true }); await fs.mkdir(outRoot, { recursive: true })
const results = []
for (const story of stories) {
    const response = buildShareProjectResponse(story.prompt)
    if (!response) { results.push({ id: story.id, title: story.title, ok: false, reason: 'No builder response', checks: {} }); continue }
    const files = parseToolFiles(response.message); const target = await writeFiles(story, files); const checks = await verify(story, target, files); const ok = Object.values(checks).every(Boolean)
    results.push({ id: story.id, title: story.title, ok, target, fileCount: files.length, checks }); console.log(`${ok ? 'PASS' : 'FAIL'} ${story.id} ${story.title} (${files.length} files)`); if (!ok) console.log(Object.entries(checks).filter(([, value]) => !value).map(([key]) => `  - ${key}`).join('\n'))
}
const failed = results.filter((result) => !result.ok); await fs.writeFile(path.join(outRoot, 'results.json'), JSON.stringify({ generatedAt: new Date().toISOString(), results }, null, 2)); if (failed.length) throw new Error(`${failed.length} hardening cliff stories failed.`); console.log(`All ${results.length} hardening cliff stories passed.`)
