import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { requireAuditReason, cleanAuditReason } from '../src/utils/adminAudit.ts'

assert.equal(cleanAuditReason('  Customer   owner locked out  '), 'Customer owner locked out')
assert.equal(requireAuditReason('Customer owner locked out'), 'Customer owner locked out')
assert.throws(() => requireAuditReason('too short'), /at least 10 characters/)

const routes = await readFile(new URL('../src/routes.ts', import.meta.url), 'utf8')
assert.match(routes, /fastify\.get\('\/admin\/audit-events'/)
assert.match(routes, /fastify\.get\('\/admin\/support\/inspect'/)
assert.match(routes, /fastify\.get\('\/admin\/support\/users\/:id'/)
assert.match(routes, /fastify\.get\('\/admin\/support\/organizations\/:id'/)
assert.match(routes, /fastify\.get\('\/admin\/support\/access-recovery'/)
assert.match(routes, /fastify\.post\('\/admin\/support\/organizations\/:id\/invites'/)
assert.match(routes, /fastify\.post\('\/admin\/support\/organizations\/:id\/access-recovery'/)
assert.match(routes, /fastify\.post\('\/admin\/support\/access-recovery\/:requestId\/approve'/)
assert.match(routes, /fastify\.post\('\/admin\/support\/access-recovery\/:requestId\/deny'/)

const packageJson = await readFile(new URL('../package.json', import.meta.url), 'utf8')
assert.match(packageJson, /smoke:admin-support-live/)
assert.match(packageJson, /smoke-admin-access-recovery-live\.mjs/)

const ensureSchema = await readFile(new URL('../src/utils/db/ensureSchema.ts', import.meta.url), 'utf8')
assert.match(ensureSchema, /CREATE TABLE IF NOT EXISTS admin_audit_events/)
assert.match(ensureSchema, /action_type TEXT NOT NULL/)
assert.match(ensureSchema, /severity TEXT NOT NULL DEFAULT 'info'/)
assert.match(ensureSchema, /source TEXT NOT NULL DEFAULT 'admin'/)
assert.match(ensureSchema, /service TEXT NOT NULL DEFAULT 'hanasand-api'/)
assert.match(ensureSchema, /organization_id TEXT REFERENCES organizations\(id\)/)
assert.match(ensureSchema, /request_id TEXT/)
assert.match(ensureSchema, /outcome TEXT NOT NULL DEFAULT 'success'/)
assert.match(ensureSchema, /CREATE INDEX IF NOT EXISTS idx_admin_audit_events_org_created/)
assert.match(ensureSchema, /idx_admin_audit_events_source_service_created/)
assert.match(ensureSchema, /CREATE TABLE IF NOT EXISTS admin_access_recovery_approvals/)
assert.match(ensureSchema, /request_id TEXT PRIMARY KEY/)
assert.match(ensureSchema, /approved_by TEXT REFERENCES users/)
assert.match(ensureSchema, /approved_at TIMESTAMPTZ/)
assert.match(ensureSchema, /denied_by TEXT REFERENCES users/)
assert.match(ensureSchema, /status IN \('pending', 'approved', 'denied', 'not_required'\)/)
assert.match(ensureSchema, /idx_admin_access_recovery_org_status/)
assert.match(ensureSchema, /idx_admin_access_recovery_outcome_updated/)
assert.match(ensureSchema, /idx_admin_access_recovery_approved_by/)
assert.match(ensureSchema, /idx_admin_access_recovery_denied_by/)

const adminSupport = await readFile(new URL('../src/handlers/adminSupport.ts', import.meta.url), 'utf8')
for (const expected of ['q', 'org', 'actor', 'target', 'action', 'severity', 'source', 'service', 'entity', 'request', 'outcome', 'from', 'to']) {
    assert.match(adminSupport, new RegExp(`\\b${expected}\\b`), `Missing audit filter ${expected}.`)
}
for (const expected of ['requestId', 'status', 'requester', 'approver']) {
    assert.match(adminSupport, new RegExp(`\\b${expected}\\b`), `Missing approval search filter ${expected}.`)
}
for (const expected of ['orgId', 'userId', 'email', 'requestId']) {
    assert.match(adminSupport, new RegExp(`\\b${expected}\\b`), `Missing support inspection filter ${expected}.`)
}
assert.match(adminSupport, /getSupportInspection/)
assert.match(adminSupport, /support\.inspect/)
assert.match(adminSupport, /support\.inspection\.v1/)
assert.match(adminSupport, /loadInspectionOrganizations/)
assert.match(adminSupport, /loadInspectionUsers/)
assert.match(adminSupport, /loadInspectionMemberships/)
assert.match(adminSupport, /loadInspectionInvites/)
assert.match(adminSupport, /loadInspectionApprovals/)
assert.match(adminSupport, /loadInspectionAuditEvents/)
assert.match(adminSupport, /loadOrganizationAvailability/)
assert.match(adminSupport, /recoveryEligibility/)
assert.match(adminSupport, /support\.access_recovery\.eligibility\.v1/)
assert.match(adminSupport, /noSilentMembershipMutation/)
assert.match(adminSupport, /canCreateControlledInvite/)
assert.match(adminSupport, /hasAvailableOwner/)
assert.match(adminSupport, /hasAvailableAdmin/)
assert.match(adminSupport, /removed/)
assert.match(adminSupport, /deactivated/)
assert.match(adminSupport, /auditTimeline/)
assert.match(adminSupport, /toSupportAuditTimelineEvent/)
assert.match(adminSupport, /auditBeforeAfter/)
assert.match(adminSupport, /before:/)
assert.match(adminSupport, /after:/)
assert.match(adminSupport, /auditEventIds/)
assert.match(adminSupport, /approvalRequests/)
assert.match(adminSupport, /controlledActions/)
assert.match(adminSupport, /support\.organization\.inspect/)
assert.match(adminSupport, /support\.user\.inspect/)
assert.match(adminSupport, /support\.organization\.invite_assist/)
assert.match(adminSupport, /support\.organization\.access_recovery/)
assert.match(adminSupport, /support\.organization\.access_recovery\.approve/)
assert.match(adminSupport, /support\.organization\.access_recovery\.deny/)
assert.match(adminSupport, /requireAuditReason\(req\.body\?\.reason/)
assert.match(adminSupport, /Access recovery approval reason/)
assert.match(adminSupport, /Access recovery denial reason/)
assert.match(adminSupport, /Access recovery reason/)
assert.match(adminSupport, /Invite assistance reason/)
assert.match(adminSupport, /Only admins can use support operations/)
assert.match(adminSupport, /res\.status\(403\)/)
assert.match(adminSupport, /requireAdminSupport\(req, res\)/)
assert.match(adminSupport, /self_approval_denied/)
assert.match(adminSupport, /actorHasAdminSupportAccess/)
assert.match(adminSupport, /pendingInvites/)
assert.match(adminSupport, /watchlistItems/)
assert.match(adminSupport, /alertReadiness/)
assert.match(adminSupport, /supportLinks/)
assert.match(adminSupport, /schemaVersion: 'support\.access_recovery\.v1'/)
assert.match(adminSupport, /support\.access_recovery\.approval\.v1/)
assert.match(adminSupport, /requestedBy/)
assert.match(adminSupport, /approvalRequired/)
assert.match(adminSupport, /approvedBy/)
assert.match(adminSupport, /approvedAt/)
assert.match(adminSupport, /expiresAt: input\.expiresAt/)
assert.match(adminSupport, /requestId: input\.requestId/)
assert.match(adminSupport, /outcome: input\.outcome/)
assert.match(adminSupport, /context: input\.context/)
assert.match(adminSupport, /pending_approval/)
assert.match(adminSupport, /not_required/)
assert.match(adminSupport, /invite_revoked_until_approved/)
assert.match(adminSupport, /invite_pending_immediately/)
assert.match(adminSupport, /admin_access_recovery_approvals/)
assert.match(adminSupport, /status = 'approved'/)
assert.match(adminSupport, /status = 'denied'/)
assert.match(adminSupport, /status = 'revoked'/)
assert.match(adminSupport, /status = \$2/)
assert.match(adminSupport, /support\.access_recovery\.approval_decision\.v1/)
assert.match(adminSupport, /support\.access_recovery\.decision_audit\.v1/)
assert.match(adminSupport, /support\.access_recovery\.approval_search\.v1/)
assert.match(adminSupport, /getSupportAccessRecoveryApprovals/)
assert.match(adminSupport, /approval\.request_id ILIKE/)
assert.match(adminSupport, /approval\.status =/)
assert.match(adminSupport, /approval\.outcome =/)
assert.match(adminSupport, /approval\.requested_by ILIKE/)
assert.match(adminSupport, /approval\.approved_by ILIKE/)
assert.match(adminSupport, /approval\.denied_by ILIKE/)
assert.match(adminSupport, /approval\.created_at >=/)
assert.match(adminSupport, /admin_audit_events event/)
assert.match(adminSupport, /auditEventIds/)
assert.match(adminSupport, /Audit events:/)
assert.match(adminSupport, /copyText/)
assert.match(adminSupport, /mutation: 'controlled_invite_only'/)
assert.match(adminSupport, /source=admin&service=hanasand-api/)
assert.match(adminSupport, /e\.source ILIKE/)
assert.match(adminSupport, /e\.service ILIKE/)
assert.match(adminSupport, /e\.request_id ILIKE/)
assert.match(adminSupport, /e\.outcome =/)
assert.match(adminSupport, /toAdminAuditEvent/)

const impersonation = await readFile(new URL('../src/handlers/impersonation.ts', import.meta.url), 'utf8')
assert.match(impersonation, /requireAuditReason\(body\?\.reason/)
assert.match(impersonation, /normalizeDurationMinutes/)
assert.match(impersonation, /normalizeImpersonationScope/)
assert.match(impersonation, /impersonation\.start/)
assert.match(impersonation, /durationMinutes/)
assert.match(impersonation, /auditLink/)
assert.match(impersonation, /requestId/)

const auditPage = await readFile(new URL('../../frontend/src/app/dashboard/system/impersonation/page.tsx', import.meta.url), 'utf8')
assert.match(auditPage, /\/admin\/audit-events/)
assert.match(auditPage, /AccessRecoveryForm/)
assert.match(auditPage, /name='org'/)
assert.match(auditPage, /name='severity'/)
assert.match(auditPage, /name='source'/)
assert.match(auditPage, /name='service'/)
assert.match(auditPage, /name='outcome'/)
assert.match(auditPage, /name='request'/)

const recoveryForm = await readFile(new URL('../../frontend/src/app/dashboard/system/impersonation/accessRecoveryForm.tsx', import.meta.url), 'utf8')
assert.match(recoveryForm, /\/api\/backend\/admin\/support\/organizations\/.+\/access-recovery/)
assert.match(recoveryForm, /name='organizationId'/)
assert.match(recoveryForm, /name='email'/)
assert.match(recoveryForm, /name='targetUserId'/)
assert.match(recoveryForm, /name='reason'/)
assert.match(recoveryForm, /name='approvalRequired'/)
assert.match(recoveryForm, /name='requestId'/)
assert.match(recoveryForm, /name='action'/)
assert.match(recoveryForm, /approve/)
assert.match(recoveryForm, /deny/)
assert.match(recoveryForm, /Record decision/)
assert.match(recoveryForm, /Search approvals/)
assert.match(recoveryForm, /name='request'/)
assert.match(recoveryForm, /name='org'/)
assert.match(recoveryForm, /name='status'/)
assert.match(recoveryForm, /name='outcome'/)
assert.match(recoveryForm, /name='requester'/)
assert.match(recoveryForm, /name='approver'/)
assert.match(recoveryForm, /requestId/)
assert.match(recoveryForm, /approvalStatus/)
assert.match(recoveryForm, /auditEventIds/)
assert.match(recoveryForm, /Open request audit/)
assert.match(recoveryForm, /Open decision audit/)
assert.match(recoveryForm, /copyText/)
assert.match(recoveryForm, /Open audit trail/)

const liveSmoke = await readFile(new URL('./smoke-admin-access-recovery-live.mjs', import.meta.url), 'utf8')
assert.match(liveSmoke, /RUN_ADMIN_SUPPORT_LIVE_SMOKE/)
assert.match(liveSmoke, /DB_PASSWORD/)
assert.match(liveSmoke, /API_BASE/)
assert.match(liveSmoke, /Postgres is already listening/)
assert.match(liveSmoke, /this script will not start Docker/)
assert.match(liveSmoke, /KEEP_ADMIN_SUPPORT_SMOKE_DATA/)
assert.match(liveSmoke, /verifyUnauthorizedSearchIsBlocked/)
assert.match(liveSmoke, /inspectSupportState/)
assert.match(liveSmoke, /\/admin\/support\/inspect/)
assert.match(liveSmoke, /recoveryEligibility/)
assert.match(liveSmoke, /createRecovery/)
assert.match(liveSmoke, /approvalStatus === 'pending_approval'/)
assert.match(liveSmoke, /invite\.status === 'revoked'/)
assert.match(liveSmoke, /decide\(approveRequestId, 'approve', 'approved'\)/)
assert.match(liveSmoke, /invite\.status === 'pending'/)
assert.match(liveSmoke, /decide\(denyRequestId, 'deny', 'denied'\)/)
assert.match(liveSmoke, /status: 'approved'/)
assert.match(liveSmoke, /status: 'denied'/)
assert.match(liveSmoke, /outcome: 'success'/)
assert.match(liveSmoke, /outcome: 'denied'/)
assert.match(liveSmoke, /requester: adminOneId/)
assert.match(liveSmoke, /approver: adminTwoId/)
assert.match(liveSmoke, /auditEventIds/)
assert.match(liveSmoke, /support\.access_recovery\.live_smoke_result\.v1/)

console.log('Admin support and structured audit contract smoke passed.')
