import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import { requireAuditReason, cleanAuditReason, redactAuditValue, supportTimelineAuditBridgeEvent, recordSupportTimelineAuditBridgeEvent } from '../src/utils/adminAudit.ts'

assert.equal(cleanAuditReason('  Customer   owner locked out  '), 'Customer owner locked out')
assert.equal(requireAuditReason('Customer owner locked out'), 'Customer owner locked out')
assert.throws(() => requireAuditReason('too short'), /at least 10 characters/)
assert.deepEqual(redactAuditValue({
    password: 'secret',
    nested: { apiToken: 'tok', safe: 'kept', privateSourceUrl: 'https://private.example/source' },
    list: [{ authorization: 'bearer', webhookUrl: 'https://discord.example/hook', value: 1 }],
}), {
    password: '[redacted]',
    nested: { apiToken: '[redacted]', safe: 'kept', privateSourceUrl: '[redacted]' },
    list: [{ authorization: '[redacted]', webhookUrl: '[redacted]', value: 1 }],
})
const bridgedAudit = supportTimelineAuditBridgeEvent({
    workflow: 'watchlist',
    action: 'organization.watchlist.updated',
    actorId: 'support-admin-1',
    targetType: 'watchlist',
    targetId: 'watchlist-item-1',
    organizationId: 'org-1',
    entityId: 'watchlist-item-1',
    requestId: 'req-1',
    severity: 'notice',
    outcome: 'success',
    reason: 'Support inspected org watchlist update.',
    source: 'organization',
    service: 'hanasand-api',
    before: { status: 'paused', webhookUrl: 'https://private.example/hook' },
    after: { status: 'active', privateSourceUrl: 'https://private.example/source' },
    correlationId: 'corr-1',
    idempotencyKey: 'idem-1',
})
assert.equal(bridgedAudit.actionType, 'organization.watchlist.updated')
assert.equal(bridgedAudit.organizationId, 'org-1')
assert.equal(bridgedAudit.entityId, 'watchlist-item-1')
assert.equal(bridgedAudit.requestId, 'req-1')
assert.equal(bridgedAudit.source, 'organization')
assert.equal(bridgedAudit.context?.schemaVersion, 'support.audit.bridge_event.v1')
assert.deepEqual((bridgedAudit.context?.before as Record<string, unknown>), { status: 'paused', webhookUrl: '[redacted]' })
assert.deepEqual((bridgedAudit.context?.after as Record<string, unknown>), { status: 'active', privateSourceUrl: '[redacted]' })
assert.equal((bridgedAudit.context?.supportTimeline as Record<string, any>)?.filters?.action, 'organization.watchlist.updated')
assert.equal((bridgedAudit.context?.supportTimeline as Record<string, any>)?.detailRouteTemplate, '/api/admin/audit-events/:id')
assert.equal(typeof recordSupportTimelineAuditBridgeEvent, 'function')

const routes = await readFile(new URL('../src/routes.ts', import.meta.url), 'utf8')
assert.match(routes, /fastify\.get\('\/admin\/audit-events'/)
assert.match(routes, /fastify\.get\('\/admin\/audit-events\/:id'/)
assert.match(routes, /fastify\.get\('\/admin\/support\/inspect'/)
assert.match(routes, /fastify\.get\('\/admin\/support\/users\/:id'/)
assert.match(routes, /fastify\.get\('\/admin\/support\/organizations\/:id'/)
assert.match(routes, /fastify\.get\('\/admin\/support\/organizations\/:id\/invites\/:inviteId'/)
assert.match(routes, /fastify\.get\('\/admin\/support\/organizations\/:id\/members\/:userId'/)
assert.match(routes, /fastify\.get\('\/admin\/support\/access-recovery'/)
assert.match(routes, /fastify\.get\('\/admin\/support\/access-recovery\/:requestId'/)
assert.match(routes, /fastify\.get\('\/admin\/support\/sessions\/:sessionId'/)
assert.match(routes, /fastify\.post\('\/admin\/support\/sessions'/)
assert.match(routes, /fastify\.post\('\/admin\/support\/sessions\/:sessionId\/revoke'/)
assert.match(routes, /fastify\.post\('\/admin\/support\/organizations\/:id\/invites'/)
assert.match(routes, /fastify\.post\('\/admin\/support\/organizations\/:id\/invites\/:inviteId\/actions'/)
assert.match(routes, /fastify\.post\('\/admin\/support\/organizations\/:id\/members\/:userId\/role-recovery'/)
assert.match(routes, /fastify\.post\('\/admin\/support\/organizations\/:id\/access-recovery'/)
assert.match(routes, /fastify\.post\('\/admin\/support\/access-recovery\/:requestId\/approve'/)
assert.match(routes, /fastify\.post\('\/admin\/support\/access-recovery\/:requestId\/deny'/)

const packageJson = await readFile(new URL('../package.json', import.meta.url), 'utf8')
assert.match(packageJson, /smoke:admin-support-live/)
assert.match(packageJson, /smoke-admin-access-recovery-live\.mjs/)

const ensureSchema = await readFile(new URL('../src/utils/db/ensureSchema.ts', import.meta.url), 'utf8')
assert.match(ensureSchema, /CREATE TABLE IF NOT EXISTS admin_audit_events/)
assert.match(ensureSchema, /action_type TEXT NOT NULL/)
assert.match(ensureSchema, /severity TEXT NOT NULL DEFAULT 'info'/)
assert.match(ensureSchema, /source TEXT NOT NULL DEFAULT 'admin'/)
assert.match(ensureSchema, /service TEXT NOT NULL DEFAULT 'hanasand-api'/)
assert.match(ensureSchema, /organization_id TEXT REFERENCES organizations\(id\)/)
assert.match(ensureSchema, /request_id TEXT/)
assert.match(ensureSchema, /outcome TEXT NOT NULL DEFAULT 'success'/)
assert.match(ensureSchema, /CREATE INDEX IF NOT EXISTS idx_admin_audit_events_org_created/)
assert.match(ensureSchema, /idx_admin_audit_events_source_service_created/)
assert.match(ensureSchema, /CREATE TABLE IF NOT EXISTS admin_access_recovery_approvals/)
assert.match(ensureSchema, /request_id TEXT PRIMARY KEY/)
assert.match(ensureSchema, /approved_by TEXT REFERENCES users/)
assert.match(ensureSchema, /approved_at TIMESTAMPTZ/)
assert.match(ensureSchema, /denied_by TEXT REFERENCES users/)
assert.match(ensureSchema, /status IN \('pending', 'approved', 'denied', 'not_required'\)/)
assert.match(ensureSchema, /idx_admin_access_recovery_org_status/)
assert.match(ensureSchema, /idx_admin_access_recovery_outcome_updated/)
assert.match(ensureSchema, /idx_admin_access_recovery_approved_by/)
assert.match(ensureSchema, /idx_admin_access_recovery_denied_by/)

const adminSupport = await readFile(new URL('../src/handlers/adminSupport.ts', import.meta.url), 'utf8')
for (const expected of ['q', 'org', 'orgId', 'organizationId', 'actor', 'actorId', 'supportActor', 'supportActorId', 'target', 'targetId', 'user', 'userId', 'targetUserId', 'action', 'actionType', 'severity', 'source', 'service', 'entity', 'entityId', 'entityType', 'request', 'requestId', 'correlation', 'correlationId', 'idempotency', 'idempotencyKey', 'supportSession', 'supportSessionId', 'workflow', 'bridgeWorkflow', 'blocker', 'blockerCode', 'reason', 'supportReason', 'context', 'supportContext', 'outcome', 'from', 'to']) {
    assert.match(adminSupport, new RegExp(`\\b${expected}\\b`), `Missing audit filter ${expected}.`)
}
assert.match(adminSupport, /const org = text\(query\.org \|\| query\.orgId \|\| query\.organizationId\)/)
assert.match(adminSupport, /const actorFilter = text\(query\.actor \|\| query\.actorId \|\| query\.supportActor \|\| query\.supportActorId\)/)
assert.match(adminSupport, /const target = text\(query\.target \|\| query\.targetId \|\| query\.user \|\| query\.userId \|\| query\.targetUserId\)/)
assert.match(adminSupport, /const action = text\(query\.action \|\| query\.actionType\)/)
assert.match(adminSupport, /const entity = text\(query\.entity \|\| query\.entityId\)/)
assert.match(adminSupport, /const workflow = text\(query\.workflow \|\| query\.bridgeWorkflow\)/)
assert.match(adminSupport, /e\.context->>'workflow' ILIKE/)
assert.match(adminSupport, /const blocker = text\(query\.blocker \|\| query\.blockerCode\)/)
assert.match(adminSupport, /e\.context->>\\'blockerCode\\' ILIKE/)
assert.match(adminSupport, /e\.context->>\\'blocker\\' ILIKE/)
assert.match(adminSupport, /const reason = text\(query\.reason \|\| query\.supportReason\)/)
assert.match(adminSupport, /const contextFilter = text\(query\.context \|\| query\.supportContext\)/)
assert.match(adminSupport, /e\.context::text ILIKE/)
for (const expected of ['requestId', 'status', 'requester', 'approver']) {
    assert.match(adminSupport, new RegExp(`\\b${expected}\\b`), `Missing approval search filter ${expected}.`)
}
for (const expected of ['q', 'orgId', 'userId', 'email', 'requestId', 'entityId', 'entityType', 'supportSession', 'supportSessionId', 'action', 'severity', 'blocker', 'blockerCode', 'reason', 'supportReason', 'context', 'supportContext', 'from', 'to']) {
    assert.match(adminSupport, new RegExp(`\\b${expected}\\b`), `Missing support inspection filter ${expected}.`)
}
assert.match(adminSupport, /const q = text\(query\.q\)/)
assert.match(adminSupport, /const reason = text\(query\.reason \|\| query\.supportReason\)/)
assert.match(adminSupport, /const contextFilter = text\(query\.context \|\| query\.supportContext\)/)
assert.match(adminSupport, /loadInspectionOrganizations\(\{ q, org, user, email, request, limit \}\)/)
assert.match(adminSupport, /loadInspectionAuditEvents\(\{ q, org, user, email, request, entity, entityType, supportSession, action, severity, outcome, source, service, blocker, reason, context: contextFilter, from, to, limit \}\)/)
assert.match(adminSupport, /supportTimelineFilter\(\{ q, org, user, email, request, entity, entityType, supportSession, action, severity, outcome, source, service, blocker, reason, context: contextFilter, from, to, limit \}\)/)
assert.match(adminSupport, /event\.action_type ILIKE \${placeholder}/)
assert.match(adminSupport, /event\.reason ILIKE/)
assert.match(adminSupport, /event\.context::text ILIKE/)
assert.match(adminSupport, /event\.context->>\\'blockerCode\\' ILIKE/)
assert.match(adminSupport, /event\.context->>\\'blocker\\' ILIKE/)
assert.match(adminSupport, /q, org, user, email, request, entity, entityType, supportSession, action, blocker, reason, or context to inspect support state/)
assert.match(adminSupport, /getSupportInspection/)
assert.match(adminSupport, /getAdminAuditEvent/)
assert.match(adminSupport, /supportAuditEventDetailResponse/)
assert.match(adminSupport, /loadAdminAuditEventRelatedTimeline/)
assert.match(adminSupport, /admin\.audit\.event_related_timeline\.v1/)
assert.match(adminSupport, /filterContract: supportAuditFilterContract\(filters, relatedTimeline\)/)
assert.match(adminSupport, /exportProof: supportAuditExportProof\(filters, relatedTimeline\)/)
assert.match(adminSupport, /workflowRollup: supportAuditWorkflowRollup\(filters, relatedTimeline\)/)
assert.match(adminSupport, /compliancePacket: supportAuditCompliancePacket\(filters, timeline\)/)
assert.match(adminSupport, /timelineReplayContract: supportAuditTimelineReplayContract\(filters, timeline\)/)
assert.match(adminSupport, /supportWorkflowPacket: supportAuditSupportWorkflowPacket\(filters, timeline\)/)
assert.match(adminSupport, /actionEvidenceRollup: supportAuditActionEvidenceRollup\(timeline\)/)
assert.match(adminSupport, /decisionPackets: events\.slice\(0, 50\)\.map/)
assert.match(adminSupport, /supportAuditTimelineReplayContract/)
assert.match(adminSupport, /support\.audit\.timeline_replay_contract\.v1/)
assert.match(adminSupport, /supportAuditSupportWorkflowPacket/)
assert.match(adminSupport, /support\.audit\.support_workflow_packet\.v1/)
assert.match(adminSupport, /supportWorkflowPacket: supportAuditSupportWorkflowPacket\(auditTimelineFilters, timeline\)/)
assert.match(adminSupport, /supportWorkflowPacket: supportAuditSupportWorkflowPacket\(filters, relatedTimeline\.length \? relatedTimeline : \[timelineEvent\]\)/)
assert.match(adminSupport, /supportWorkflowPacket: supportAuditSupportWorkflowPacket\(filters, relatedTimeline\)/)
assert.match(adminSupport, /guardedActions: \['invite_assist', 'invite_action', 'member_role_recovery', 'access_recovery', 'impersonation'\]/)
assert.match(adminSupport, /missing_audit_events/)
assert.match(adminSupport, /missing_action_evidence/)
assert.match(adminSupport, /review_operator_rationale/)
assert.match(adminSupport, /review_scoped_session/)
assert.match(adminSupport, /detailRouteTemplate: '\/api\/admin\/audit-events\/:id'/)
assert.match(adminSupport, /detailPayloads: \['filterContract', 'exportProof', 'compliancePacket', 'workflowProof', 'integrationFixture', 'timelineReplayContract', 'supportWorkflowPacket', 'actionEvidenceRollup'\]/)
assert.match(adminSupport, /exampleQueries:\s+\{/)
assert.match(adminSupport, /actionOutcome: auditFilterQuery/)
assert.match(adminSupport, /textQuery: auditFilterQuery\(\{ q:/)
assert.match(adminSupport, /denialReplay: \{/)
assert.match(adminSupport, /support\.audit\.denial_replay\.v1/)
assert.match(adminSupport, /deniedActionQuery: auditFilterQuery/)
assert.match(adminSupport, /expectedDeniedActions/)
assert.match(adminSupport, /integrationReadiness: \{/)
assert.match(adminSupport, /fixtureName: 'support-audit-timeline-replay'/)
assert.match(adminSupport, /expectedResponsePath: 'detail\.timelineReplayContract'/)
assert.match(adminSupport, /focusedCheck: 'cd api && bun run smoke:admin-support-unit'/)
assert.match(adminSupport, /query: \['q'\]/)
assert.match(adminSupport, /workflowProof: supportAuditEventWorkflowProof/)
assert.match(adminSupport, /support\.audit\.event_workflow_proof\.v1/)
assert.match(adminSupport, /decisionPacket: supportAuditEventDecisionPacket/)
assert.match(adminSupport, /support\.audit\.event_decision_packet\.v1/)
assert.match(adminSupport, /operatorReviewRequired/)
assert.match(adminSupport, /requiredOperatorInputs/)
assert.match(adminSupport, /idempotencyKeyFor: \['invite_assistance', 'invite_action', 'member_role_recovery'\]/)
assert.match(adminSupport, /deniedOnly: auditFilterQuery/)
assert.match(adminSupport, /Support audit decision/)
assert.match(adminSupport, /supportAuditEventIntegrationFixture/)
assert.match(adminSupport, /support\.audit\.integration_fixture\.v1/)
assert.match(adminSupport, /fixtureName: 'support-audit-detail-timeline'/)
assert.match(adminSupport, /expectedAuditFields/)
assert.match(adminSupport, /reasonRequiredForSupportActions: true/)
assert.match(adminSupport, /availableActions/)
assert.match(adminSupport, /supportAuditEventActionTemplates/)
assert.match(adminSupport, /support\.audit\.event_action_templates\.v1/)
assert.match(adminSupport, /actionRequestTemplates/)
assert.match(adminSupport, /expectedAuditAction: 'support\.organization\.access_recovery'/)
assert.match(adminSupport, /durationRequired: true/)
assert.match(adminSupport, /guardedActionRequirements/)
assert.match(adminSupport, /noSilentMembershipMutation: true/)
assert.match(adminSupport, /missing_reason_on_source_event/)
assert.match(adminSupport, /details: relatedTimeline\.map\(item => item\.links\?\.detail\)\.filter\(Boolean\)/)
assert.match(adminSupport, /supportAuditEntityLinks/)
assert.match(adminSupport, /supportAuditEntityTimelineFilters/)
assert.match(adminSupport, /links\.entities/)
assert.match(adminSupport, /relatedEntityLinks: timelineEvent\.links\.entities/)
assert.match(adminSupport, /inspection: inspectionQuery \? `\/api\/admin\/support\/inspect\?\$\{inspectionQuery\}` : null/)
assert.match(adminSupport, /organization: organizationId \? `\/api\/admin\/support\/organizations\/\$\{encodeURIComponent\(organizationId\)\}` : null/)
assert.match(adminSupport, /inviteAction: organizationId && inviteId \? `\/api\/admin\/support\/organizations\/\$\{encodeURIComponent\(organizationId\)\}\/invites\/\$\{encodeURIComponent\(inviteId\)\}\/actions` : null/)
assert.match(adminSupport, /memberRoleRecovery: organizationId && targetUserId \? `\/api\/admin\/support\/organizations\/\$\{encodeURIComponent\(organizationId\)\}\/members\/\$\{encodeURIComponent\(targetUserId\)\}\/role-recovery` : null/)
assert.match(adminSupport, /impersonation: targetUserId \? `\/api\/impersonation\/events\?target=\$\{encodeURIComponent\(targetUserId\)\}` : null/)
assert.match(adminSupport, /member: memberId \? `\/api\/admin\/audit-events\?entity=\$\{encodeURIComponent\(memberId\)\}&entityType=member` : null/)
assert.match(adminSupport, /alert: alertId \? `\/api\/admin\/audit-events\?entity=\$\{encodeURIComponent\(alertId\)\}&action=alert` : null/)
assert.match(adminSupport, /watchlist: watchlistId \? `\/api\/admin\/audit-events\?entity=\$\{encodeURIComponent\(watchlistId\)\}&action=watchlist` : null/)
assert.match(adminSupport, /webhook: webhookId \? `\/api\/admin\/audit-events\?entity=\$\{encodeURIComponent\(webhookId\)\}&action=webhook` : null/)
assert.match(adminSupport, /support\.audit\.entity_timeline_filters\.v1/)
assert.match(adminSupport, /support\.audit_event\.inspect/)
assert.match(adminSupport, /support\.audit_event\.inspect\.v1/)
assert.match(adminSupport, /inspectedEventId/)
assert.match(adminSupport, /relatedEventIds/)
assert.match(adminSupport, /invalid_audit_event_id/)
assert.match(adminSupport, /audit_event_not_found/)
assert.match(adminSupport, /\/api\/admin\/audit-events\/\$\{encodeURIComponent\(String\(event\.id\)\)\}/)
assert.match(adminSupport, /links: \{\s+detail: `\/api\/admin\/audit-events\/\$\{encodeURIComponent\(String\(id\)\)\}`/)
assert.match(adminSupport, /detailRoute: `\/api\/admin\/audit-events\/\$\{encodeURIComponent\(String\(event\.id\)\)\}`/)
assert.match(adminSupport, /'links\.supportSession'/)
assert.match(adminSupport, /support\.inspect/)
assert.match(adminSupport, /support\.inspection\.v1/)
assert.match(adminSupport, /supportInspectionSearchProof/)
assert.match(adminSupport, /support\.inspection\.search_proof\.v1/)
assert.match(adminSupport, /missing_search_target/)
assert.match(adminSupport, /availableActions:\s+\{/)
assert.match(adminSupport, /support\.case_summary\.v1/)
assert.match(adminSupport, /support\.workbench\.v1/)
assert.match(adminSupport, /support\.workbench\.timeline_proof\.v1/)
assert.match(adminSupport, /support\.workbench\.readiness_proof\.v1/)
assert.match(adminSupport, /supportWorkbenchAdapter/)
assert.match(adminSupport, /support\.workbench\.adapter\.v1/)
assert.match(adminSupport, /support\.workbench\.list\.v1/)
assert.match(adminSupport, /support\.workbench\.detail\.v1/)
assert.match(adminSupport, /support\.workbench\.timeline_adapter\.v1/)
assert.match(adminSupport, /support\.workbench\.adapter_readiness\.v1/)
assert.match(adminSupport, /workbenchAdapter/)
assert.match(adminSupport, /searchableFields: \['type', 'label', 'organizationId', 'targetUserId', 'status', 'role', 'outcome', 'requestId'\]/)
assert.match(adminSupport, /requiredOperatorInputs/)
assert.match(adminSupport, /backedActions/)
assert.match(adminSupport, /support\.scoped_session\.v1/)
assert.match(adminSupport, /support\.scoped_session\.detail\.v1/)
assert.match(adminSupport, /support\.scoped_session\.audit_timeline\.v1/)
assert.match(adminSupport, /support\.scoped_session\.readiness_proof\.v1/)
assert.match(adminSupport, /support\.scoped_session\.authorization_proof\.v1/)
assert.match(adminSupport, /support\.scoped_session\.revoke\.v1/)
assert.match(adminSupport, /support\.action_prepare\.v1/)
assert.match(adminSupport, /support\.action_prepare\.audit_preview\.v1/)
assert.match(adminSupport, /support\.action_execution_handoff\.v1/)
assert.match(adminSupport, /support\.action_executor_readiness\.v1/)
assert.match(adminSupport, /support\.action_execute\.invite_assist\.v1/)
assert.match(adminSupport, /support\.action_execute\.invite_action\.v1/)
assert.match(adminSupport, /support\.action_execute\.member_role_recovery\.v1/)
assert.match(adminSupport, /support\.action_executor_blocker\.v1/)
assert.match(adminSupport, /support\.action_execute\.audit_preview\.v1/)
assert.match(adminSupport, /support\.audit\.filter_contract\.v1/)
assert.match(adminSupport, /supportAuditFilterReadiness/)
assert.match(adminSupport, /support\.audit\.filter_readiness\.v1/)
assert.match(adminSupport, /targetBounded/)
assert.match(adminSupport, /textQueryFilters/)
assert.match(adminSupport, /query: \['q'\]/)
assert.match(adminSupport, /Text query:/)
assert.match(adminSupport, /reasonContextFilters/)
assert.match(adminSupport, /supportedAliases/)
assert.match(adminSupport, /overbroad_audit_query/)
assert.match(adminSupport, /timeRange:\s+\{/)
assert.match(adminSupport, /support\.audit\.redacted_summary\.v1/)
assert.match(adminSupport, /supportAuditCompliancePacket/)
assert.match(adminSupport, /support\.audit\.compliance_packet\.v1/)
assert.match(adminSupport, /customer_support_evidence_review/)
assert.match(adminSupport, /redactionAttestation/)
assert.match(adminSupport, /missing_reason_on_some_events/)
assert.match(adminSupport, /caseSummary/)
assert.match(adminSupport, /workbench/)
assert.match(adminSupport, /accessRecoveryPlan/)
assert.match(adminSupport, /buildSupportAccessRecoveryPlan/)
assert.match(adminSupport, /support\.access_recovery\.plan\.v1/)
assert.match(adminSupport, /support\.access_recovery\.plan_item\.v1/)
assert.match(adminSupport, /guardedOperations/)
assert.match(adminSupport, /resend_pending_invite/)
assert.match(adminSupport, /create_controlled_recovery_invite/)
assert.match(adminSupport, /member_role_recovery/)
assert.match(adminSupport, /reasonRequiredForActions: true/)
assert.match(adminSupport, /contextRequiredForActions: true/)
assert.match(adminSupport, /scopedActionRequired: true/)
assert.match(adminSupport, /noMutation: true/)
assert.match(adminSupport, /filterContract: supportAuditFilterContract\(input\.timelineFilter, input\.timeline\)/)
assert.match(adminSupport, /Access recovery plan org=/)
assert.match(adminSupport, /buildSupportCaseSummary/)
assert.match(adminSupport, /buildSupportWorkbench/)
assert.match(adminSupport, /supportWorkbenchReadinessProof/)
assert.match(adminSupport, /getSupportSession/)
assert.match(adminSupport, /postSupportSession/)
assert.match(adminSupport, /postSupportSessionRevoke/)
assert.match(adminSupport, /loadSupportSessionState/)
assert.match(adminSupport, /loadSupportSessionTimeline/)
assert.match(adminSupport, /const timelineFilters = \{/)
assert.match(adminSupport, /filterContract: supportAuditFilterContract\(timelineFilters, timeline\)/)
assert.match(adminSupport, /exportProof: supportAuditExportProof\(timelineFilters, timeline\)/)
assert.match(adminSupport, /auditRoute: auditTimeline\.links\.timeline/)
assert.match(adminSupport, /recordSupportSessionRevokeAudit/)
assert.match(adminSupport, /supportSessionResponse/)
assert.match(adminSupport, /supportSessionWorkflowRoutes/)
assert.match(adminSupport, /supportSessionAuthorizationProof/)
assert.match(adminSupport, /matchesSessionActor/)
assert.match(adminSupport, /durationOrExpiryRequired: true/)
assert.match(adminSupport, /support_session_actor_mismatch/)
assert.match(adminSupport, /const sessionState = supportSession \? await loadSupportSessionState\(supportSession\) : null/)
assert.match(adminSupport, /supportSession: sessionState \? supportSessionResponse/)
assert.match(adminSupport, /buildSupportInspectionAuthorization/)
assert.match(adminSupport, /support\.inspection\.authorization\.v1/)
assert.match(adminSupport, /authorization,\n\s+organizations:/)
assert.match(adminSupport, /authorizationMatrix/)
assert.match(adminSupport, /supportInspectionAuthorizationMatrix/)
assert.match(adminSupport, /support\.inspection\.authorization_matrix\.v1/)
assert.match(adminSupport, /matrixReplay: auditFilterQuery\(input\.timelineFilter\)/)
assert.match(adminSupport, /deniedReplay: auditFilterQuery\(\{ \.\.\.input\.timelineFilter, outcome: 'denied' \}\)/)
assert.match(adminSupport, /reasonRequiredForActions: true/)
assert.match(adminSupport, /contextRequiredForActions: true/)
assert.match(adminSupport, /scopeRequiredForActions: true/)
assert.match(adminSupport, /noSilentMembershipMutation: true/)
assert.match(adminSupport, /Invite\/recovery\/member\/impersonation:/)
assert.match(adminSupport, /auditDetailPacket/)
assert.match(adminSupport, /supportInspectionAuditDetailPacket/)
assert.match(adminSupport, /support\.inspection\.audit_detail_packet\.v1/)
assert.match(adminSupport, /detailRetrievalRequiresSupport: true/)
assert.match(adminSupport, /reasonRequiredForSensitiveActions: true/)
assert.match(adminSupport, /supportActionRequirements:\s+\{/)
assert.match(adminSupport, /member: memberEntityIds\.map\(entityId => auditFilterQuery\(\{ entity: entityId, entityType: 'member' \}\)\)/)
assert.match(adminSupport, /invite: inviteEntityIds\.map\(entityId => auditFilterQuery\(\{ entity: entityId, entityType: 'invite' \}\)\)/)
assert.match(adminSupport, /Support inspection audit details org=/)
assert.match(adminSupport, /orgBoundaryProof/)
assert.match(adminSupport, /supportInspectionOrgBoundaryProof/)
assert.match(adminSupport, /support\.inspection\.org_boundary_proof\.v1/)
assert.match(adminSupport, /cross_org_match_requires_explicit_scope/)
assert.match(adminSupport, /support_session_org_mismatch/)
assert.match(adminSupport, /supportSessionScopeEnforced: true/)
assert.match(adminSupport, /deniedAccessIsAuditable: true/)
assert.match(adminSupport, /Support org boundary requested=/)
assert.match(adminSupport, /recoveryFixturePacket/)
assert.match(adminSupport, /supportInspectionRecoveryFixturePacket/)
assert.match(adminSupport, /support\.inspection\.recovery_fixture_packet\.v1/)
assert.match(adminSupport, /support_workbench_recovery_and_impersonation_validation/)
assert.match(adminSupport, /invite_resend_prepare/)
assert.match(adminSupport, /controlled_recovery_invite_prepare/)
assert.match(adminSupport, /member_role_recovery_prepare/)
assert.match(adminSupport, /impersonation_prepare/)
assert.match(adminSupport, /requiredFields: \['reason', 'context', 'scope', 'requestId', 'idempotencyKey\|durationMinutes\|expiresAt'\]/)
assert.match(adminSupport, /auditFilterCoverage/)
assert.match(adminSupport, /supportInspectionAuditFilterCoverage/)
assert.match(adminSupport, /support\.inspection\.audit_filter_coverage\.v1/)
assert.match(adminSupport, /targetBounded/)
assert.match(adminSupport, /requiredForBoundedSearch: \['org\|user\|email\|request\|entity\|supportSession'\]/)
assert.match(adminSupport, /unsupportedFiltersAreTyped: true/)
assert.match(adminSupport, /overbroad_support_inspection/)
assert.match(adminSupport, /byActionOutcome: actionValues\.flatMap/)
assert.match(adminSupport, /actionAuditContract/)
assert.match(adminSupport, /supportInspectionActionAuditContract/)
assert.match(adminSupport, /support\.inspection\.action_audit_contract\.v1/)
assert.match(adminSupport, /requiredForEverySensitiveAction:\s+\{/)
assert.match(adminSupport, /immutableAuditEvent: true/)
assert.match(adminSupport, /creationPreview:\s+\{/)
assert.match(adminSupport, /missing_reason_on_fixture/)
assert.match(adminSupport, /Support action audit contract request=/)
assert.match(adminSupport, /enterpriseReadiness/)
assert.match(adminSupport, /supportInspectionEnterpriseReadiness/)
assert.match(adminSupport, /support\.inspection\.enterprise_readiness\.v1/)
assert.match(adminSupport, /responsePath: 'inspection\.enterpriseReadiness'/)
assert.match(adminSupport, /expectedSchemas:\s+\[/)
assert.match(adminSupport, /sensitiveActionAudit:\s+\{/)
assert.match(adminSupport, /immutableAuditEventRequired/)
assert.match(adminSupport, /Enterprise support readiness:/)
assert.match(adminSupport, /supportRoleRequired: true/)
assert.match(adminSupport, /supportSessionScoped/)
assert.match(adminSupport, /effective:\s+\{/)
assert.match(adminSupport, /noCrossOrgLeakage: true/)
assert.match(adminSupport, /reasonRequiredForActions: true/)
assert.match(adminSupport, /supportSessionId\\' ILIKE/)
assert.match(adminSupport, /supportSession: input\.supportSession/)
assert.match(adminSupport, /filter\.supportSession/)
assert.match(adminSupport, /support\.inspection\.session_scope_guard\.v1/)
assert.match(adminSupport, /const org = sessionState\?\.organizationId \|\| requestedOrg \|\| ''/)
assert.match(adminSupport, /const user = sessionState\?\.targetUserId \|\| requestedUser \|\| ''/)
assert.match(adminSupport, /noCrossOrgLeakage: true/)
assert.match(adminSupport, /requestedOrg/)
assert.match(adminSupport, /scopedOrg/)
assert.match(adminSupport, /normalizeSupportSessionActions/)
assert.match(adminSupport, /normalizeSupportSessionScope/)
assert.match(adminSupport, /normalizeSupportSessionDuration/)
assert.match(adminSupport, /normalizeSupportSessionExpiry/)
assert.match(adminSupport, /buildSupportActionPreparation/)
assert.match(adminSupport, /supportActionPreparationInput/)
assert.match(adminSupport, /normalizeSupportPreparationScope/)
assert.match(adminSupport, /normalizeSupportPreparationDuration/)
assert.match(adminSupport, /normalizeSupportPreparationExpiry/)
assert.match(adminSupport, /supportActionExecutionHandoff/)
assert.match(adminSupport, /supportActionExecutorReadiness/)
assert.match(adminSupport, /supportActionExecutorRequiredBody/)
assert.match(adminSupport, /supportActionExecutionTarget/)
assert.match(adminSupport, /supportInviteAssistExecutorControls/)
assert.match(adminSupport, /supportInviteAssistExecutorDetail/)
assert.match(adminSupport, /supportInviteAssistExecutorBlocker/)
assert.match(adminSupport, /recordSupportInviteAssistExecutorBlock/)
assert.match(adminSupport, /loadSupportInviteAssistByIdempotencyKey/)
assert.match(adminSupport, /loadOrganizationInvitesByIds/)
assert.match(adminSupport, /supportInviteAssistAuditQuery/)
assert.match(adminSupport, /supportInviteActionExecutorControls/)
assert.match(adminSupport, /supportInviteActionExecutorDetail/)
assert.match(adminSupport, /recordSupportInviteActionExecutorBlock/)
assert.match(adminSupport, /loadSupportInviteActionByIdempotencyKey/)
assert.match(adminSupport, /supportInviteActionAuditQuery/)
assert.match(adminSupport, /supportMemberRoleRecoveryExecutorControls/)
assert.match(adminSupport, /supportMemberRoleRecoveryExecutorDetail/)
assert.match(adminSupport, /recordSupportMemberRoleRecoveryExecutorBlock/)
assert.match(adminSupport, /loadSupportMemberRoleRecoveryByIdempotencyKey/)
assert.match(adminSupport, /supportMemberRoleRecoveryAuditQuery/)
assert.match(adminSupport, /supportActionIdempotencyKey/)
assert.match(adminSupport, /adminAuditFilterError/)
assert.match(adminSupport, /supportAuditFilterContract/)
assert.match(adminSupport, /supportAuditExportProof/)
assert.match(adminSupport, /supportAuditBridgeAdapterContract/)
assert.match(adminSupport, /support\.audit\.bridge_adapter_contract\.v1/)
assert.match(adminSupport, /supportedWorkflows: \['organization', 'watchlist', 'webhook', 'alert', 'impersonation', 'support'\]/)
assert.match(adminSupport, /const filterFields = Array\.from\(adminAuditFilters\)/)
assert.match(adminSupport, /supportAliases: \{/)
assert.match(adminSupport, /supportActorId/)
assert.match(adminSupport, /supportContext/)
assert.match(adminSupport, /controlledRecoveryFixtures: supportControlledRecoveryAuditFixtures\(filters\)/)
assert.match(adminSupport, /support\.audit\.controlled_recovery_fixtures\.v1/)
assert.match(adminSupport, /invite_resend_allowed/)
assert.match(adminSupport, /access_recovery_pending_approval/)
assert.match(adminSupport, /member_role_recovery_denied/)
assert.match(adminSupport, /filterExpectations/)
assert.match(adminSupport, /forbiddenFields: \['token', 'secret', 'authorization', 'cookie', 'webhookUrl', 'privateSourceUrl'\]/)
assert.match(adminSupport, /expectedResponsePath: 'detail\.bridgeAdapter'/)
assert.match(adminSupport, /redaction: \{/)
assert.match(adminSupport, /supportAuditWorkflowRollup/)
assert.match(adminSupport, /supportAuditWorkflowName/)
assert.match(adminSupport, /support\.audit\.workflow_rollup\.v1/)
assert.match(adminSupport, /workflowRollup: supportAuditWorkflowRollup/)
assert.match(adminSupport, /action\.includes\('webhook'\)/)
assert.match(adminSupport, /supportAuditRedactedSummary/)
assert.match(adminSupport, /supportAuditEntityLinkRollup/)
assert.match(adminSupport, /support\.audit\.entity_link_rollup\.v1/)
assert.match(adminSupport, /entityLinkRollup/)
assert.match(adminSupport, /links\.entities/)
assert.match(adminSupport, /auditFilterQuery/)
assert.match(adminSupport, /timelineFilters: uniqueTimelineValues/)
assert.match(adminSupport, /activeMembershipCount/)
assert.match(adminSupport, /removedMembershipCount/)
assert.match(adminSupport, /inactiveMembershipCount/)
assert.match(adminSupport, /pendingInviteCount/)
assert.match(adminSupport, /recoveryRequests/)
assert.match(adminSupport, /impersonationRequests/)
assert.match(adminSupport, /inviteAssistance/)
assert.match(adminSupport, /accessRecovery/)
assert.match(adminSupport, /impersonationAssistance/)
assert.match(adminSupport, /timelineProof/)
assert.match(adminSupport, /readinessProof/)
assert.match(adminSupport, /supportActionsAvailable/)
assert.match(adminSupport, /auditFiltersAvailable/)
assert.match(adminSupport, /lastProof/)
assert.match(adminSupport, /scopedSession/)
assert.match(adminSupport, /allowedActions/)
assert.match(adminSupport, /actionPreparation/)
assert.match(adminSupport, /prepareAction/)
assert.match(adminSupport, /auditPreview/)
assert.match(adminSupport, /filterContract/)
assert.match(adminSupport, /exportProof/)
assert.match(adminSupport, /const auditTimelineFilters = \{/)
assert.match(adminSupport, /filterContract: supportAuditFilterContract\(auditTimelineFilters, timeline\)/)
assert.match(adminSupport, /exportProof: supportAuditExportProof\(auditTimelineFilters, timeline\)/)
assert.match(adminSupport, /workflowRollup: supportAuditWorkflowRollup\(auditTimelineFilters, timeline\)/)
assert.match(adminSupport, /timeline: auditFilterQuery\(auditTimelineFilters\)/)
assert.match(adminSupport, /redactedSummary/)
assert.match(adminSupport, /stableRequestIds/)
assert.match(adminSupport, /correlationIds/)
assert.match(adminSupport, /idempotencyKeys/)
assert.match(adminSupport, /handoffPreviewLinkage/)
assert.match(adminSupport, /executionHandoff/)
assert.match(adminSupport, /executorReadiness/)
assert.match(adminSupport, /controlledExecutor/)
assert.match(adminSupport, /mutationMode: 'controlled_invite_row_only'/)
assert.match(adminSupport, /mutationMode: 'no_mutation_readiness'/)
assert.match(adminSupport, /selectedAction: selectedSafeAction/)
assert.match(adminSupport, /selectedSafeAction: SupportActionPreparationInput\['action'\] = 'invite_assist'/)
assert.match(adminSupport, /idempotencyKey/)
assert.match(adminSupport, /supportSessionId/)
assert.match(adminSupport, /supportSession/)
assert.match(adminSupport, /x-idempotency-key/)
assert.match(adminSupport, /x-correlation-id/)
assert.match(adminSupport, /x-support-handoff-expires-at/)
assert.match(adminSupport, /x-support-session-id/)
assert.match(adminSupport, /supportSessionIdFromRequest/)
assert.match(adminSupport, /validateSupportSessionForAction/)
assert.match(adminSupport, /supportSessionId: text\(query\.session \|\| query\.supportSession \|\| query\.supportSessionId\)/)
assert.match(adminSupport, /supportSessionId: input\.input\.supportSessionId \|\| null/)
assert.match(adminSupport, /input\.supportSessionId[\s\S]*'x-support-session-id'/)
assert.match(adminSupport, /requiredHeaders/)
assert.match(adminSupport, /requiredBody/)
assert.match(adminSupport, /correlationId/)
assert.match(adminSupport, /stale_prepare_payload/)
assert.match(adminSupport, /stale_handoff/)
assert.match(adminSupport, /executor_must_reject_after_handoff_expires/)
assert.match(adminSupport, /duplicate_request/)
assert.match(adminSupport, /duplicate_idempotency_key/)
assert.match(adminSupport, /executor_must_reject_reused_key_for_target_and_action/)
assert.match(adminSupport, /idempotentReplay/)
assert.match(adminSupport, /context->>'idempotencyKey'/)
assert.match(adminSupport, /invite_\${action}/)
assert.match(adminSupport, /body\?\.idempotencyKey/)
assert.match(adminSupport, /executable/)
assert.match(adminSupport, /executableByExistingEndpoint/)
assert.match(adminSupport, /dryRun: true/)
assert.match(adminSupport, /noMutation: true/)
assert.match(adminSupport, /supportedActions: \['invite_assist', 'access_recovery', 'impersonation'\]/)
assert.match(adminSupport, /missing_support_reason/)
assert.match(adminSupport, /support_session_not_found/)
assert.match(adminSupport, /support_session_revoked/)
assert.match(adminSupport, /support_session_expired/)
assert.match(adminSupport, /support_session_actor_mismatch/)
assert.match(adminSupport, /support_session_org_mismatch/)
assert.match(adminSupport, /support_session_user_mismatch/)
assert.match(adminSupport, /support_session_action_denied/)
assert.match(adminSupport, /support_session_scope_denied/)
assert.match(adminSupport, /unsupported_support_action/)
assert.match(adminSupport, /unsupported_audit_filter/)
assert.match(adminSupport, /invalid_audit_filter/)
assert.match(adminSupport, /audit_unavailable/)
assert.match(adminSupport, /redaction_required/)
assert.match(adminSupport, /invalid_scope/)
assert.match(adminSupport, /invalid_duration/)
assert.match(adminSupport, /invalid_expiry/)
assert.match(adminSupport, /invite:create/)
assert.match(adminSupport, /recovery:invite/)
assert.match(adminSupport, /recovery:approve/)
assert.match(adminSupport, /recovery:deny/)
assert.match(adminSupport, /read_profile/)
assert.match(adminSupport, /contextRequired: true/)
assert.match(adminSupport, /missing_org_target/)
assert.match(adminSupport, /missing_user_target/)
assert.match(adminSupport, /ambiguous_target/)
assert.match(adminSupport, /inactive_member/)
assert.match(adminSupport, /no_admin_available/)
assert.match(adminSupport, /active_admin_available/)
assert.match(adminSupport, /mutation_unavailable/)
assert.match(adminSupport, /invite_unavailable/)
assert.match(adminSupport, /unsafe_impersonation/)
assert.match(adminSupport, /recovery_unavailable/)
assert.match(adminSupport, /impersonation_ineligible/)
assert.match(adminSupport, /audit_filter_unavailable/)
assert.match(adminSupport, /redactedAuditPreview/)
assert.match(adminSupport, /redactionRequired: true/)
assert.match(adminSupport, /reason: input\.reason/)
assert.match(adminSupport, /params\.set\('correlation'/)
assert.match(adminSupport, /params\.set\('idempotency'/)
assert.match(adminSupport, /params\.set\('reason'/)
assert.match(adminSupport, /params\.set\('org'/)
assert.match(adminSupport, /params\.set\('entity'/)
assert.match(adminSupport, /impersonationTimelineQuery/)
assert.match(adminSupport, /auditTimelineLink/)
assert.match(adminSupport, /support\.error\.v1/)
assert.match(adminSupport, /missing_support_target/)
assert.match(adminSupport, /support_role_required/)
assert.match(adminSupport, /loadInspectionOrganizations/)
assert.match(adminSupport, /loadInspectionUsers/)
assert.match(adminSupport, /loadInspectionMemberships/)
assert.match(adminSupport, /loadInspectionInvites/)
assert.match(adminSupport, /loadInspectionApprovals/)
assert.match(adminSupport, /loadInspectionAuditEvents/)
assert.match(adminSupport, /loadOrganizationAvailability/)
assert.match(adminSupport, /recoveryEligibility/)
assert.match(adminSupport, /support\.access_recovery\.eligibility\.v1/)
assert.match(adminSupport, /buildSupportAccessStatus/)
assert.match(adminSupport, /support\.access_status\.v1/)
assert.match(adminSupport, /accessStatus/)
assert.match(adminSupport, /active_access/)
assert.match(adminSupport, /invite_pending/)
assert.match(adminSupport, /recovery_recommended/)
assert.match(adminSupport, /access_unknown/)
assert.match(adminSupport, /openRecoveryRequests/)
assert.match(adminSupport, /activeMemberships/)
assert.match(adminSupport, /revokedInvites/)
assert.match(adminSupport, /expiredInvites/)
assert.match(adminSupport, /noMutation: true/)
assert.match(adminSupport, /Access status:/)
assert.match(adminSupport, /noSilentMembershipMutation/)
assert.match(adminSupport, /canCreateControlledInvite/)
assert.match(adminSupport, /hasAvailableOwner/)
assert.match(adminSupport, /hasAvailableAdmin/)
assert.match(adminSupport, /removed/)
assert.match(adminSupport, /deactivated/)
assert.match(adminSupport, /auditTimeline/)
assert.match(adminSupport, /toSupportAuditTimelineEvent/)
assert.match(adminSupport, /const context = redactAuditValue\(event\.context/)
assert.match(adminSupport, /auditBeforeAfter/)
assert.match(adminSupport, /before:/)
assert.match(adminSupport, /after:/)
assert.match(adminSupport, /supportAuditActionEvidence/)
assert.match(adminSupport, /support\.audit\.action_evidence\.v1/)
assert.match(adminSupport, /supportAuditActionEvidenceRollup/)
assert.match(adminSupport, /support\.audit\.action_evidence_rollup\.v1/)
assert.match(adminSupport, /actionEvidenceRollup: supportAuditActionEvidenceRollup\(timeline\)/)
assert.match(adminSupport, /actionEvidence: supportAuditActionEvidenceRollup\(timeline\)/)
assert.match(adminSupport, /supportActionEvidence: actionEvidence/)
assert.match(adminSupport, /actionEvidence,\n\s+context/)
assert.match(adminSupport, /actionEvidence: event\.actionEvidence/)
assert.match(adminSupport, /controls:\s+\{[\s\S]*supportRoleRequired/)
assert.match(adminSupport, /reasonRequired: requiresReason/)
assert.match(adminSupport, /scopeRequired: requiresScope/)
assert.match(adminSupport, /durationOrExpiryRequired: requiresDurationOrExpiry/)
assert.match(adminSupport, /reasonMissingEventIds/)
assert.match(adminSupport, /scopeMissingEventIds/)
assert.match(adminSupport, /durationMissingEventIds/)
assert.match(adminSupport, /missing_scope_on_source_event/)
assert.match(adminSupport, /missing_duration_or_expiry_on_source_event/)
assert.match(adminSupport, /missing_action_evidence/)
assert.match(adminSupport, /links:\s+\{[\s\S]*replay: auditFilterQuery\(actionLinkFilters\)/)
assert.match(adminSupport, /auditEventIds/)
assert.match(adminSupport, /approvalRequests/)
assert.match(adminSupport, /controlledActions/)
assert.match(adminSupport, /inviteActions/)
assert.match(adminSupport, /memberRoleRecovery/)
assert.match(adminSupport, /impersonationGuard/)
assert.match(adminSupport, /reasonRequired: true/)
assert.match(adminSupport, /durationRequired: true/)
assert.match(adminSupport, /scopeRequired: true/)
assert.match(adminSupport, /noSilentImpersonation: true/)
assert.match(adminSupport, /support\.organization\.inspect/)
assert.match(adminSupport, /support\.user\.inspect/)
assert.match(adminSupport, /support\.organization\.invite_assist/)
assert.match(adminSupport, /support\.invite_assist\.v1/)
assert.match(adminSupport, /const requestId = input\.requestId \|\| supportRequestId\(req\)/)
assert.match(adminSupport, /inviteAssistance/)
assert.match(adminSupport, /schemaVersion: 'support\.invite_assist\.v1'/)
assert.match(adminSupport, /scope: \{/)
assert.match(adminSupport, /organizationId: organization\.id/)
assert.match(adminSupport, /inviteIds/)
assert.match(adminSupport, /params\.set\('action', 'support\.organization\.invite_assist'\)/)
assert.match(adminSupport, /Support invite assistance for/)
assert.match(adminSupport, /postSupportOrganizationInviteAction/)
assert.match(adminSupport, /support\.organization\.invite_revoke/)
assert.match(adminSupport, /support\.organization\.invite_resend/)
assert.match(adminSupport, /getSupportOrganizationInvite/)
assert.match(adminSupport, /support\.organization\.invite\.inspect/)
assert.match(adminSupport, /support\.invite_inspection\.v1/)
assert.match(adminSupport, /inviteInspection/)
assert.match(adminSupport, /snapshot: inviteSnapshot\(invite\)/)
assert.match(adminSupport, /const inviteTimelineFilter = supportTimelineFilter/)
assert.match(adminSupport, /email: invite\.email,\n\s+request: inspectionAudit\.requestId/)
assert.match(adminSupport, /invites: \[invite as unknown as Record<string, unknown>\]/)
assert.match(adminSupport, /accessRecoveryPlan,\n\s+auditEventIds: recentAuditTimeline\.eventIds/)
assert.match(adminSupport, /noMutation: true/)
assert.match(adminSupport, /Invite not found for organization/)
assert.match(adminSupport, /support\.invite_action\.v1/)
assert.match(adminSupport, /support\.action_execute\.invite_action\.v1/)
assert.match(adminSupport, /Invite assistance action reason/)
assert.match(adminSupport, /action must be revoke or resend/)
assert.match(adminSupport, /invite:resend/)
assert.match(adminSupport, /invite:revoke/)
assert.match(adminSupport, /support invite action requires unavailable org administration/)
assert.match(adminSupport, /accepted_invite_not_mutable_by_support_action/)
assert.match(adminSupport, /inviteSnapshot/)
assert.match(adminSupport, /idempotentReplay/)
assert.match(adminSupport, /duplicate_idempotency_key/)
assert.match(adminSupport, /mutation: 'invite_row_only'/)
assert.match(adminSupport, /noSilentMembershipMutation: true/)
assert.match(adminSupport, /loadAdminAuditEventIds/)
assert.match(adminSupport, /postSupportOrganizationMemberRoleRecovery/)
assert.match(adminSupport, /getSupportOrganizationMember/)
assert.match(adminSupport, /support\.organization\.member\.inspect/)
assert.match(adminSupport, /support\.member_inspection\.v1/)
assert.match(adminSupport, /memberInspection/)
assert.match(adminSupport, /snapshot: membershipSnapshot\(member\)/)
assert.match(adminSupport, /const memberTimelineFilter = supportTimelineFilter/)
assert.match(adminSupport, /user: req\.params\.userId,\n\s+email: ''/)
assert.match(adminSupport, /memberships: \[member\]/)
assert.match(adminSupport, /timelineFilter: memberTimelineFilter/)
assert.match(adminSupport, /Organization member not found/)
assert.match(adminSupport, /support\.organization\.member_role_recovery/)
assert.match(adminSupport, /support\.member_role_recovery\.v1/)
assert.match(adminSupport, /support\.action_execute\.member_role_recovery\.v1/)
assert.match(adminSupport, /Member role recovery reason/)
assert.match(adminSupport, /member:role_recovery/)
assert.match(adminSupport, /controlled_member_role_only/)
assert.match(adminSupport, /Support role recovery requires an active organization member/)
assert.match(adminSupport, /support member role recovery requires unavailable org administration/)
assert.match(adminSupport, /normalizeMemberRoleInput/)
assert.match(adminSupport, /loadSupportMemberDetail/)
assert.match(adminSupport, /loadSupportMemberRoleRecoveryByIdempotencyKey/)
assert.match(adminSupport, /activeOwnerCount/)
assert.match(adminSupport, /supportRoleRecoveryPermissionError/)
assert.match(adminSupport, /membershipSnapshot/)
assert.match(adminSupport, /controlledExecutor: supportMemberRoleRecoveryExecutorDetail/)
assert.match(adminSupport, /revoked_member/)
assert.match(adminSupport, /targetUserId: input\.userId/)
assert.match(adminSupport, /mutation: 'member_role_only'/)
assert.match(adminSupport, /Support role recovery cannot grant organization owner/)
assert.match(adminSupport, /Support role recovery cannot demote the last active owner/)
assert.match(adminSupport, /member_role_already_set/)
assert.match(adminSupport, /support\.organization\.access_recovery/)
assert.match(adminSupport, /support\.organization\.access_recovery\.approve/)
assert.match(adminSupport, /support\.organization\.access_recovery\.deny/)
assert.match(adminSupport, /getSupportAccessRecoveryApproval/)
assert.match(adminSupport, /support\.organization\.access_recovery\.inspect/)
assert.match(adminSupport, /support\.access_recovery\.inspection\.v1/)
assert.match(adminSupport, /support\.access_recovery\.inspection_timeline\.v1/)
assert.match(adminSupport, /access_recovery_request_not_found/)
assert.match(adminSupport, /const accessRecoveryPlan = buildSupportAccessRecoveryPlan/)
assert.match(adminSupport, /approvalDetails: \[detail\]/)
assert.match(adminSupport, /timelineFilter,\n\s+\}\)/)
assert.match(adminSupport, /accessRecoveryPlan,\n\s+auditEventIds: timeline\.map/)
assert.match(adminSupport, /loadSupportMemberDetail\(approval\.organization_id, detail\.targetUserId\)/)
assert.match(adminSupport, /approvalTimeline/)
assert.match(adminSupport, /requiredScope: 'recovery:invite'/)
assert.match(adminSupport, /requiredScope = decision === 'approved' \? 'recovery:approve' : 'recovery:deny'/)
assert.match(adminSupport, /supportSessionId: supportSessionId \|\| null/)
assert.match(adminSupport, /requireAuditReason\(req\.body\?\.reason/)
assert.match(adminSupport, /Access recovery approval reason/)
assert.match(adminSupport, /Access recovery denial reason/)
assert.match(adminSupport, /Access recovery reason/)
assert.match(adminSupport, /Invite assistance reason/)
assert.match(adminSupport, /Only admins can use support operations/)
assert.match(adminSupport, /res\.status\(403\)/)
assert.match(adminSupport, /requireAdminSupport\(req, res\)/)
assert.match(adminSupport, /self_approval_denied/)
assert.match(adminSupport, /actorHasAdminSupportAccess/)
assert.match(adminSupport, /pendingInvites/)
assert.match(adminSupport, /watchlistItems/)
assert.match(adminSupport, /alertReadiness/)
assert.match(adminSupport, /support\.organization\.alert_readiness\.audit_bridge\.v1/)
assert.match(adminSupport, /supportTimelineBridge/)
assert.match(adminSupport, /supportTimelineAuditBridgeEvent\(\{/)
assert.match(adminSupport, /supportLinks/)
assert.match(adminSupport, /supportActivityRollup/)
assert.match(adminSupport, /supportOrganizationActivityRollup/)
assert.match(adminSupport, /support\.organization\.activity_rollup\.v1/)
assert.match(adminSupport, /actionCounts: \{/)
assert.match(adminSupport, /memberRoleRecovery: actions\.memberRoleRecovery\.length/)
assert.match(adminSupport, /denied: auditFilterQuery\(\{ org: input\.organizationId, outcome: 'denied'/)
assert.match(adminSupport, /noSilentMembershipMutation: true/)
assert.match(adminSupport, /supportRecentAuditTimeline/)
assert.match(adminSupport, /support\.recent_audit_timeline\.v1/)
assert.match(adminSupport, /summary: auditTimelineSummary\(timeline\)/)
assert.match(adminSupport, /filterContract: supportAuditFilterContract\(filters, timeline\)/)
assert.match(adminSupport, /exportProof: supportAuditExportProof\(filters, timeline\)/)
assert.match(adminSupport, /workflowRollup: supportAuditWorkflowRollup\(filters, timeline\)/)
assert.match(adminSupport, /Support recent timeline:/)
assert.match(adminSupport, /supportInspectionAuditMetadata/)
assert.match(adminSupport, /supportInspectionAuditContext/)
assert.match(adminSupport, /support\.inspection\.audit_context\.v1/)
assert.match(adminSupport, /reasonProvided: Boolean\(input\.reason\)/)
assert.match(adminSupport, /supportContext: input\.supportContext \|\| null/)
assert.match(adminSupport, /recentAuditEvents: recentAuditTimeline\.events/)
assert.match(adminSupport, /recentAuditTimeline/)
assert.match(adminSupport, /organizationAccessStatus/)
assert.match(adminSupport, /userAccessStatus/)
assert.match(adminSupport, /authorization,\n\s+accessStatus: organizationAccessStatus/)
assert.match(adminSupport, /authorization,\n\s+accessStatus: userAccessStatus/)
assert.match(adminSupport, /supportUserActivityRollup/)
assert.match(adminSupport, /support\.user\.activity_rollup\.v1/)
assert.match(adminSupport, /organizationTimelineLinks/)
assert.match(adminSupport, /scopedSessionRequiredForImpersonation: true/)
assert.match(adminSupport, /Support activity user=/)
assert.match(adminSupport, /organizationRecoveryEligibility/)
assert.match(adminSupport, /userRecoveryEligibility/)
assert.match(adminSupport, /const organizationTimelineFilter = supportTimelineFilter/)
assert.match(adminSupport, /const userTimelineFilter = supportTimelineFilter/)
assert.match(adminSupport, /organizationRecoveryEligibility,\n\s+availabilityByOrg,\n\s+timeline: recentAuditTimeline\.events,\n\s+timelineFilter: organizationTimelineFilter/)
assert.match(adminSupport, /userRecoveryEligibility,\n\s+availabilityByOrg,\n\s+timeline: recentAuditTimeline\.events,\n\s+timelineFilter: userTimelineFilter/)
assert.match(adminSupport, /accessRecoveryPlan,\n\s+members:/)
assert.match(adminSupport, /accessRecoveryPlan,\n\s+memberships:/)
assert.match(adminSupport, /om\.user_id,\n\s+om\.organization_id/)
assert.match(adminSupport, /accessStatus: organizationAccessStatus/)
assert.match(adminSupport, /accessStatus: userAccessStatus/)
assert.match(adminSupport, /requestedOrg: req\.params\.id/)
assert.match(adminSupport, /requestedUser: req\.params\.id/)
assert.match(adminSupport, /Authorization: \$\{authorization\.supportSessionScoped \? 'scoped support session' : 'support role'\}/)
assert.match(adminSupport, /Support organization inspection/)
assert.match(adminSupport, /Support user inspection/)
assert.match(adminSupport, /approvalRequests: approvalDetails/)
assert.match(adminSupport, /schemaVersion: 'support\.access_recovery\.v1'/)
assert.match(adminSupport, /support\.access_recovery\.session_guard\.v1/)
assert.match(adminSupport, /support\.access_recovery\.approval\.v1/)
assert.match(adminSupport, /requestedBy/)
assert.match(adminSupport, /approvalRequired/)
assert.match(adminSupport, /approvedBy/)
assert.match(adminSupport, /approvedAt/)
assert.match(adminSupport, /expiresAt: input\.expiresAt/)
assert.match(adminSupport, /requestId: input\.requestId/)
assert.match(adminSupport, /outcome: input\.outcome/)
assert.match(adminSupport, /context: input\.context/)
assert.match(adminSupport, /pending_approval/)
assert.match(adminSupport, /not_required/)
assert.match(adminSupport, /invite_revoked_until_approved/)
assert.match(adminSupport, /invite_pending_immediately/)
assert.match(adminSupport, /admin_access_recovery_approvals/)
assert.match(adminSupport, /status = 'approved'/)
assert.match(adminSupport, /status = 'denied'/)
assert.match(adminSupport, /status = 'revoked'/)
assert.match(adminSupport, /status = \$2/)
assert.match(adminSupport, /support\.access_recovery\.approval_decision\.v1/)
assert.match(adminSupport, /support\.access_recovery\.decision_audit\.v1/)
assert.match(adminSupport, /support\.access_recovery\.approval_search\.v1/)
assert.match(adminSupport, /support\.access_recovery\.approval_timeline\.v1/)
assert.match(adminSupport, /supportAccessRecoveryApprovalTimeline/)
assert.match(adminSupport, /accessRecoveryApprovalAuditFilters/)
assert.match(adminSupport, /approvalTimeline/)
assert.match(adminSupport, /filterContract: supportAuditFilterContract\(auditFilters, timeline\)/)
assert.match(adminSupport, /workflowRollup: supportAuditWorkflowRollup\(auditFilters, timeline\)/)
assert.match(adminSupport, /timeline: auditFilterQuery\(auditFilters\)/)
assert.match(adminSupport, /actionType: 'support\.organization\.access_recovery'[\s\S]+auditEventIds/)
assert.match(adminSupport, /getSupportAccessRecoveryApprovals/)
assert.match(adminSupport, /approval\.request_id ILIKE/)
assert.match(adminSupport, /approval\.status =/)
assert.match(adminSupport, /approval\.outcome =/)
assert.match(adminSupport, /approval\.requested_by ILIKE/)
assert.match(adminSupport, /approval\.approved_by ILIKE/)
assert.match(adminSupport, /approval\.denied_by ILIKE/)
assert.match(adminSupport, /approval\.created_at >=/)
assert.match(adminSupport, /admin_audit_events event/)
assert.match(adminSupport, /event\.entity_id ILIKE/)
assert.match(adminSupport, /event\.target_type ILIKE/)
assert.match(adminSupport, /event\.action_type ILIKE/)
assert.match(adminSupport, /event\.severity =/)
assert.match(adminSupport, /event\.created_at >=/)
assert.match(adminSupport, /event\.created_at <=/)
assert.match(adminSupport, /auditEventIds/)
assert.match(adminSupport, /Audit events:/)
assert.match(adminSupport, /copyText/)
assert.match(adminSupport, /mutation: 'controlled_invite_only'/)
assert.match(adminSupport, /source=admin&service=hanasand-api/)
assert.match(adminSupport, /e\.source ILIKE/)
assert.match(adminSupport, /e\.service ILIKE/)
assert.match(adminSupport, /e\.request_id ILIKE/)
assert.match(adminSupport, /e\.outcome =/)
assert.match(adminSupport, /toAdminAuditEvent/)
assert.match(adminSupport, /redactAuditValue/)
assert.match(adminSupport, /admin\.audit\.timeline_event\.v1/)
assert.match(adminSupport, /auditTimelineSummary/)
assert.match(adminSupport, /auditEventScope/)
assert.match(adminSupport, /organizationIds/)
assert.match(adminSupport, /actorIds/)
assert.match(adminSupport, /entityIds/)
assert.match(adminSupport, /durationMinutes/)
assert.match(adminSupport, /supportContext/)
assert.match(adminSupport, /timeline/)
assert.match(adminSupport, /support\.audit\.export_proof\.v1/)
assert.match(adminSupport, /compliancePacket: supportAuditCompliancePacket/)
assert.match(adminSupport, /immutableEventIds/)
assert.match(adminSupport, /entityLinks: supportAuditEntityLinkRollup\(timeline\)/)
assert.match(adminSupport, /support-audit-export-proof/)
assert.match(adminSupport, /expectedResponsePath: 'detail\.exportProof'/)
assert.match(adminSupport, /testCommand: 'cd api && bun run smoke:admin-support-unit'/)
assert.match(adminSupport, /supportWorkflows/)
assert.match(adminSupport, /support_session/)
assert.match(adminSupport, /support\.session\.inspect/)
assert.match(adminSupport, /workflowRoutes/)
assert.match(adminSupport, /availableActions/)
assert.match(adminSupport, /auditFields/)
assert.match(adminSupport, /route: '\/api\/admin\/support\/sessions\/:sessionId'/)

const impersonation = await readFile(new URL('../src/handlers/impersonation.ts', import.meta.url), 'utf8')
assert.match(impersonation, /requireAuditReason\(body\?\.reason/)
assert.match(impersonation, /normalizeDurationMinutes/)
assert.match(impersonation, /normalizeImpersonationScope/)
assert.match(impersonation, /Impersonation duration is required/)
assert.match(impersonation, /between 5 and 240 minutes/)
assert.match(impersonation, /Impersonation scope is required/)
assert.match(impersonation, /Unsupported impersonation scope/)
assert.match(impersonation, /support\.impersonation\.request\.v1/)
assert.match(impersonation, /support\.impersonation\.denied\.v1/)
assert.match(impersonation, /support\.impersonation\.error\.v1/)
assert.match(impersonation, /support\.impersonation\.stop\.v1/)
assert.match(impersonation, /support\.impersonation\.timeline\.v1/)
assert.match(impersonation, /support\.impersonation\.timeline_event\.v1/)
assert.match(impersonation, /support\.impersonation\.timeline_filter_contract\.v1/)
assert.match(impersonation, /support\.impersonation\.timeline_filter_readiness\.v1/)
assert.match(impersonation, /decisionPacket: impersonationTimelineDecisionPacket/)
assert.match(impersonation, /support\.impersonation\.decision_packet\.v1/)
assert.match(impersonation, /noSilentImpersonation: true/)
assert.match(impersonation, /missing_reason_on_impersonation_event/)
assert.match(impersonation, /missing_duration_on_impersonation_start/)
assert.match(impersonation, /review_active_impersonation_session/)
assert.match(impersonation, /const actionFilter = String\(query\.action/)
assert.match(impersonation, /const outcomeFilter = String\(query\.outcome/)
assert.match(impersonation, /const reasonFilter = String\(query\.reason/)
assert.match(impersonation, /query\.session \|\| query\.supportSession \|\| query\.supportSessionId/)
assert.match(impersonation, /supportedFilters: \['q', 'actor', 'target', 'action', 'outcome', 'method', 'path', 'session', 'supportSession', 'supportSessionId', 'reason', 'from', 'to', 'limit'\]/)
assert.match(impersonation, /filterReadiness: impersonationTimelineFilterReadiness/)
assert.match(impersonation, /overbroad_impersonation_timeline_filter/)
assert.match(impersonation, /unsupported_impersonation_action_filter/)
assert.match(impersonation, /unsupported_impersonation_outcome_filter/)
assert.match(impersonation, /auditRoute: '\/api\/admin\/audit-events\?action=impersonation&outcome=denied&source=admin&service=hanasand-api'/)
assert.match(impersonation, /impersonation\.start/)
assert.match(impersonation, /impersonation\.stop/)
assert.match(impersonation, /toImpersonationTimelineEvent/)
assert.match(impersonation, /impersonationTimelineSummary/)
assert.match(impersonation, /impersonationTimelineFilterContract/)
assert.match(impersonation, /impersonationEventsQuery/)
assert.match(impersonation, /filter: 'requestId'/)
assert.match(impersonation, /filter: 'deniedOutcome'/)
assert.match(impersonation, /session\.reason ILIKE/)
assert.match(impersonation, /LEFT JOIN impersonation_sessions session ON session\.id = e\.session_id/)
assert.match(impersonation, /impersonationSessionDurationMinutes/)
assert.match(impersonation, /supportSessionRequired: true/)
assert.match(impersonation, /auditRequired: true/)
assert.match(impersonation, /links: \{[\s\S]*audit: `\/api\/admin\/audit-events\?action=/)
assert.match(impersonation, /durationMinutes/)
assert.match(impersonation, /organizationId/)
assert.match(impersonation, /const stopReason = cleanText\(body\?\.reason\) \|\| 'Support ended impersonation session\.'/)
assert.match(impersonation, /cleanStopContext/)
assert.match(impersonation, /impersonationStop/)
assert.match(impersonation, /startReason: row\.reason \|\| null/)
assert.match(impersonation, /supportSessionIdFromRequest/)
assert.match(impersonation, /validateSupportSessionForImpersonation/)
assert.match(impersonation, /support_session_org_required/)
assert.match(impersonation, /support_session_duration_exceeds_scope/)
assert.match(impersonation, /x-support-session-id/)
assert.match(impersonation, /approvalRequired: false/)
assert.match(impersonation, /approvalStatus: 'not_required'/)
assert.match(impersonation, /noSilentImpersonation: true/)
assert.match(impersonation, /auditEventIds/)
assert.match(impersonation, /loadAdminAuditEventIds/)
assert.match(impersonation, /auditLink/)
assert.match(impersonation, /requestId/)

const tokenWrapper = await readFile(new URL('../src/utils/auth/tokenWrapper.ts', import.meta.url), 'utf8')
assert.match(tokenWrapper, /normalizeStoredImpersonationScope/)
assert.match(tokenWrapper, /isImpersonationScopeAllowed/)
assert.match(tokenWrapper, /impersonation\.scope_denied/)
assert.match(tokenWrapper, /support\.impersonation\.scope_denied\.v1/)
assert.match(tokenWrapper, /Impersonation scope does not allow this request/)

const auditPage = await readFile(new URL('../../frontend/src/app/dashboard/system/impersonation/page.tsx', import.meta.url), 'utf8')
assert.match(auditPage, /\/admin\/audit-events/)
assert.match(auditPage, /AccessRecoveryForm/)
assert.match(auditPage, /name='org'/)
assert.match(auditPage, /name='severity'/)
assert.match(auditPage, /name='source'/)
assert.match(auditPage, /name='service'/)
assert.match(auditPage, /name='outcome'/)
assert.match(auditPage, /name='request'/)

const recoveryForm = await readFile(new URL('../../frontend/src/app/dashboard/system/impersonation/accessRecoveryForm.tsx', import.meta.url), 'utf8')
assert.match(recoveryForm, /\/api\/backend\/admin\/support\/organizations\/.+\/access-recovery/)
assert.match(recoveryForm, /name='organizationId'/)
assert.match(recoveryForm, /name='email'/)
assert.match(recoveryForm, /name='targetUserId'/)
assert.match(recoveryForm, /name='reason'/)
assert.match(recoveryForm, /name='approvalRequired'/)
assert.match(recoveryForm, /name='requestId'/)
assert.match(recoveryForm, /name='action'/)
assert.match(recoveryForm, /approve/)
assert.match(recoveryForm, /deny/)
assert.match(recoveryForm, /Record decision/)
assert.match(recoveryForm, /Search approvals/)
assert.match(recoveryForm, /name='request'/)
assert.match(recoveryForm, /name='org'/)
assert.match(recoveryForm, /name='status'/)
assert.match(recoveryForm, /name='outcome'/)
assert.match(recoveryForm, /name='requester'/)
assert.match(recoveryForm, /name='approver'/)
assert.match(recoveryForm, /requestId/)
assert.match(recoveryForm, /approvalStatus/)
assert.match(recoveryForm, /auditEventIds/)
assert.match(recoveryForm, /Open request audit/)
assert.match(recoveryForm, /Open decision audit/)
assert.match(recoveryForm, /copyText/)
assert.match(recoveryForm, /Open audit trail/)

const liveSmoke = await readFile(new URL('./smoke-admin-access-recovery-live.mjs', import.meta.url), 'utf8')
assert.match(liveSmoke, /RUN_ADMIN_SUPPORT_LIVE_SMOKE/)
assert.match(liveSmoke, /DB_PASSWORD/)
assert.match(liveSmoke, /API_BASE/)
assert.match(liveSmoke, /Postgres is already listening/)
assert.match(liveSmoke, /this script will not start Docker/)
assert.match(liveSmoke, /KEEP_ADMIN_SUPPORT_SMOKE_DATA/)
assert.match(liveSmoke, /verifyUnauthorizedSearchIsBlocked/)
assert.match(liveSmoke, /verifyUnauthorizedInviteActionIsBlocked/)
assert.match(liveSmoke, /inspectSupportState/)
assert.match(liveSmoke, /\/admin\/support\/inspect/)
assert.match(liveSmoke, /recoveryEligibility/)
assert.match(liveSmoke, /supportInviteAction/)
assert.match(liveSmoke, /\/admin\/support\/organizations\/.+\/invites\/.+\/actions/)
assert.match(liveSmoke, /noSilentMembershipMutation/)
assert.match(liveSmoke, /invite_resend/)
assert.match(liveSmoke, /entityType: 'invite'/)
assert.match(liveSmoke, /createRecovery/)
assert.match(liveSmoke, /approvalStatus === 'pending_approval'/)
assert.match(liveSmoke, /invite\.status === 'revoked'/)
assert.match(liveSmoke, /decide\(approveRequestId, 'approve', 'approved'\)/)
assert.match(liveSmoke, /invite\.status === 'pending'/)
assert.match(liveSmoke, /decide\(denyRequestId, 'deny', 'denied'\)/)
assert.match(liveSmoke, /status: 'approved'/)
assert.match(liveSmoke, /status: 'denied'/)
assert.match(liveSmoke, /outcome: 'success'/)
assert.match(liveSmoke, /outcome: 'denied'/)
assert.match(liveSmoke, /requester: adminOneId/)
assert.match(liveSmoke, /approver: adminTwoId/)
assert.match(liveSmoke, /auditEventIds/)
assert.match(liveSmoke, /support\.access_recovery\.live_smoke_result\.v1/)

console.log('Admin support and structured audit contract smoke passed.')
