import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildShareProjectResponse } from '../src/handlers/tools/ai.ts'

type ToolFile = { action: string; path: string; content: string }
type Kind = 'website' | 'api' | 'bot' | 'worker'
type Story = { id: number; title: string; prompt: string; kind: Kind; mustMention: RegExp[] }

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(scriptDir, '..', '..')
const outRoot = path.join(repoRoot, 'sandbox', 'share-chat-enterprise-architecture-stories')

const stories: Story[] = [
    { id: 321, title: 'Tenant RLS Contract API', kind: 'api', prompt: 'Create tenant RLS contract API with rlsPolicies owner scoping RBAC request IDs audit hash chain data residency backup restore contract tests CI Docker.', mustMention: [/rlsPolicies/i, /ownerId/i, /requireRole/i, /x-request-id/i, /auditHash/i, /\/data-residency/i, /\/backup/i, /\/restore/i, /\/contract-tests/i] },
    { id: 322, title: 'Secrets Rotation Admin API', kind: 'api', prompt: 'Build secrets rotation admin API with /security/secrets/rotate secretsRotation appendAudit auditHash RBAC metrics security headers no hardcoded secrets.', mustMention: [/\/security\/secrets\/rotate/i, /secretsRotation/i, /appendAudit/i, /auditHash/i, /requireRole/i, /\/metrics/i, /x-content-type-options/i] },
    { id: 323, title: 'Legal Hold Delete API', kind: 'api', prompt: 'Create legal hold delete API with retentionHolds retention_hold_active role-gated delete PII redaction audit events data residency shaped conflict errors.', mustMention: [/retentionHolds/i, /retention_hold_active/i, /delete_/i, /redact/i, /appendAudit/i, /requireRole/i, /\/data-residency/i] },
    { id: 324, title: 'Outbox Webhook Reliability API', kind: 'api', prompt: 'Build outbox webhook reliability API with outbox events idempotency signature checks circuit breaker OpenAPI metrics request IDs.', mustMention: [/outboxEvents/i, /\/outbox/i, /idempotency/i, /verifyWebhookSignature/i, /circuitBreaker/i, /\/openapi\.json/i, /\/metrics/i, /x-request-id/i] },
    { id: 325, title: 'Contract Test Partner API', kind: 'api', prompt: 'Create contract test partner API with contract tests contractVersion OpenAPI request IDs shaped errors RBAC rate limits readiness.', mustMention: [/\/contract-tests/i, /contractVersion/i, /\/openapi\.json/i, /x-request-id/i, /request_error/i, /requireRole/i, /rateLimit/i, /\/ready/i] },
    { id: 326, title: 'Architecture Ownership Marketing Site', kind: 'website', prompt: 'Build architecture ownership marketing site with design spec security review CI no lock-in readable source export backend contract rollback path Docker.', mustMention: [/docs\/design-spec\.json/i, /docs\/security-review\.md/i, /\.github\/workflows\/ci\.yml/i, /No platform lock-in/i, /Readable source export/i, /Backend contract/i, /Rollback path/i, /Docker/i] },
    { id: 327, title: 'Worker Lease Heartbeat Queue', kind: 'worker', prompt: 'Create worker lease heartbeat queue with leaseUntil heartbeatAt backoff cancellation poison quarantine outbox events circuit breaker Redis worker status.', mustMention: [/leaseUntil/i, /heartbeatAt/i, /BACKOFF_MS/i, /cancelJob/i, /poisonJobs/i, /outboxEvents/i, /circuitBreaker/i, /Redis/i, /worker-status/i] },
    { id: 328, title: 'Data Residency Dashboard Site', kind: 'website', prompt: 'Build data residency compliance dashboard with PII handling deployment checks failure owner security review audit trail design docs CI Docker.', mustMention: [/PII handling/i, /Deployment checks/i, /Failure owner/i, /Security review/i, /Audit trail/i, /docs\/design-spec\.json/i, /docs\/security-review\.md/i, /\.github\/workflows\/ci\.yml/i] },
    { id: 329, title: 'Circuit Breaker Integration API', kind: 'api', prompt: 'Create circuit breaker integration API with assertCircuitClosed recordCircuitFailure metrics outbox request IDs transaction rollback shaped 503 errors.', mustMention: [/circuitBreaker/i, /assertCircuitClosed/i, /recordCircuitFailure/i, /\/metrics/i, /\/outbox/i, /x-request-id/i, /withTransaction/i, /503/i] },
    { id: 330, title: 'Immutable Audit Evidence API', kind: 'api', prompt: 'Build immutable audit evidence API with auditHash hashAudit appendAudit PII redaction backup export data residency retention holds restore rehearsal.', mustMention: [/auditHash/i, /hashAudit/i, /appendAudit/i, /redact/i, /\/backup/i, /\/data-residency/i, /retentionHolds/i, /\/restore/i] },
    { id: 331, title: 'SSO Boundary Admin API', kind: 'api', prompt: 'Create SSO RBAC boundary admin API with rolesFor requireRole ADMIN_ROLE tenant policies security review contract tests.', mustMention: [/rolesFor/i, /requireRole/i, /ADMIN_ROLE/i, /rlsPolicies/i, /docs\/security-review\.md/i, /\/contract-tests/i] },
    { id: 332, title: 'Outbox Worker Reliability Queue', kind: 'worker', prompt: 'Build outbox worker reliability queue with outboxEvents heartbeatAt leaseUntil BACKOFF_MS cancelJob circuitBreaker poisonJobs worker-status Redis.', mustMention: [/outboxEvents/i, /heartbeatAt/i, /leaseUntil/i, /BACKOFF_MS/i, /cancelJob/i, /circuitBreaker/i, /poisonJobs/i, /worker-status/i] },
    { id: 333, title: 'Release Evidence Cutover Site', kind: 'website', prompt: 'Create release evidence cutover site with design spec security review CI DNS checklist SSL checklist rollback plan verification failure owner source export Docker.', mustMention: [/docs\/design-spec\.json/i, /docs\/security-review\.md/i, /\.github\/workflows\/ci\.yml/i, /DNS checklist/i, /SSL checklist/i, /Rollback plan/i, /Verification/i, /Failure owner/i, /Source export/i] },
    { id: 334, title: 'Retention Hold Support API', kind: 'api', prompt: 'Create retention hold support API with retentionHolds retention_hold_active auditHash PII redaction owner scoping request_error 409 conflict.', mustMention: [/retentionHolds/i, /retention_hold_active/i, /auditHash/i, /redact/i, /ownerId/i, /request_error/i, /409/i] },
    { id: 335, title: 'Architecture Review Portfolio Site', kind: 'website', prompt: 'Build architecture review portfolio site with design spec security review CI mobile layout accessible controls readable source export no lock-in rollback path.', mustMention: [/docs\/design-spec\.json/i, /docs\/security-review\.md/i, /\.github\/workflows\/ci\.yml/i, /Mobile-first layout/i, /Accessible controls/i, /Readable source export/i, /No platform lock-in/i, /Rollback path/i] },
    { id: 336, title: 'Replay Outbox Payment API', kind: 'api', prompt: 'Build replay outbox payment API with webhook signature checks idempotency outbox events circuit breaker auditHash backup restore OpenAPI metrics.', mustMention: [/verifyWebhookSignature/i, /idempotency/i, /outboxEvents/i, /circuitBreaker/i, /auditHash/i, /\/backup/i, /\/restore/i, /\/openapi\.json/i, /\/metrics/i] },
    { id: 337, title: 'Multi-Tenant Export API', kind: 'api', prompt: 'Create multi tenant export API with owner scoping rlsPolicies data residency request IDs cache TTL pagination audit hash evidence.', mustMention: [/ownerId/i, /rlsPolicies/i, /\/data-residency/i, /x-request-id/i, /CACHE_TTL_SECONDS/i, /nextCursor/i, /auditHash/i] },
    { id: 338, title: 'Poison Lease Import Worker', kind: 'worker', prompt: 'Create poison lease import worker with leaseUntil heartbeatAt cancelJob BACKOFF_MS poison quarantine outboxEvents Redis circuitBreaker.', mustMention: [/leaseUntil/i, /heartbeatAt/i, /cancelJob/i, /BACKOFF_MS/i, /poisonJobs/i, /outboxEvents/i, /Redis/i, /circuitBreaker/i] },
    { id: 339, title: 'Enterprise Evidence Status Site', kind: 'website', prompt: 'Build enterprise evidence incident observability status page with incident timeline SLO evidence postmortems failure owner design spec security review CI Docker exportable source.', mustMention: [/Incident timeline/i, /SLO evidence/i, /Postmortems/i, /Failure owner/i, /docs\/design-spec\.json/i, /docs\/security-review\.md/i, /\.github\/workflows\/ci\.yml/i, /Docker/i] },
    { id: 340, title: 'Production Trust API', kind: 'api', prompt: 'Create production trust API with RLS policies data residency retention holds immutable audit hash chain secrets rotation outbox circuit breaker contract tests OpenAPI metrics request IDs CORS allowlist transaction rollback RBAC backup restore migrations feature flags security headers PII redaction audit events idempotency webhook signatures pagination schemaVersion failureOwner rate limiting token gate health readiness design spec security review CI Docker.', mustMention: [/rlsPolicies/i, /\/data-residency/i, /retentionHolds/i, /auditHash/i, /\/security\/secrets\/rotate/i, /outboxEvents/i, /circuitBreaker/i, /\/contract-tests/i, /\/openapi\.json/i, /\/metrics/i, /x-request-id/i, /ALLOWED_ORIGINS/i, /withTransaction/i, /requireRole/i, /\/backup/i, /\/restore/i, /migrations/i, /featureFlags/i, /x-content-type-options/i, /redact/i, /auditEvents/i, /idempotency/i, /verifyWebhookSignature/i, /nextCursor/i, /schemaVersion/i, /failureOwner/i, /rateLimit/i, /API_TOKEN/i, /docs\/design-spec\.json/i, /docs\/security-review\.md/i, /\.github\/workflows\/ci\.yml/i] },
]

function parseToolFiles(message: string) { return [...message.matchAll(/<hanasand-tool>([\s\S]*?)<\/hanasand-tool>/g)].map((match) => JSON.parse(match[1]) as ToolFile) }
async function exists(filePath: string) { try { await fs.access(filePath); return true } catch { return false } }
async function read(filePath: string) { return await fs.readFile(filePath, 'utf8').catch(() => '') }
async function writeFiles(story: Story, files: ToolFile[]) {
    const target = path.join(outRoot, `${story.id}-${slugify(story.title)}`)
    await fs.rm(target, { recursive: true, force: true })
    for (const file of files) { const filePath = path.join(target, file.path); await fs.mkdir(path.dirname(filePath), { recursive: true }); await fs.writeFile(filePath, file.content) }
    return target
}
async function verify(story: Story, target: string, files: ToolFile[]) {
    const allContent = files.map((file) => `${file.path}\n${file.content}`).join('\n---\n')
    const checks: Record<string, boolean> = {
        enoughFiles: files.length >= (story.kind === 'website' ? 12 : story.kind === 'worker' ? 12 : 10), packageJson: await exists(path.join(target, 'package.json')), readme: await exists(path.join(target, 'README.md')), envExample: await exists(path.join(target, '.env.example')), dockerfile: await exists(path.join(target, 'Dockerfile')), compose: await exists(path.join(target, 'docker-compose.yml')), ci: await exists(path.join(target, '.github/workflows/ci.yml')), designSpec: await exists(path.join(target, 'docs/design-spec.json')), securityReview: await exists(path.join(target, 'docs/security-review.md')), noHardcodedSecrets: !/(sk-[a-z0-9]|xox[baprs]-|DISCORD_TOKEN\s*=\s*[^\n]*[A-Za-z0-9]{20,})/i.test(allContent), noLorem: !/lorem ipsum|placeholder text|todo: write copy/i.test(allContent), delivery: /delivery|release notes|verification|docker compose|failure owner|rollback|restore|CI|security review/i.test(await read(path.join(target, 'README.md'))), mentions: story.mustMention.every((pattern) => pattern.test(allContent)),
    }
    if (story.kind === 'website') { checks.page = await exists(path.join(target, 'src/app/page.tsx')); checks.layout = await exists(path.join(target, 'src/app/layout.tsx')); checks.accessible = /aria-label|<label|Skip to content/i.test(allContent); checks.responsive = /clamp\(|auto-fit|flexWrap|mobile/i.test(allContent); checks.exportable = /output:\s*'standalone'|docker compose/i.test(allContent); checks.trust = /No platform lock-in|Privacy and data paths documented|Backend contract|Rollback path/i.test(allContent) }
    if (story.kind === 'api') { checks.apiSource = await exists(path.join(target, 'src/index.ts')); checks.healthReady = /\/health|\/ready/.test(allContent); checks.validation = /title_required|Forbidden|setErrorHandler|request_error/i.test(allContent); checks.rateLimit = /rateBuckets|rateLimit|429|Limit reached/i.test(allContent); checks.scoped = /ownerId|x-account-id|rlsPolicies/i.test(allContent); checks.operability = /x-request-id|\/openapi\.json|\/metrics|CACHE_TTL_SECONDS|withTransaction|ALLOWED_ORIGINS/i.test(allContent); checks.trustArchitecture = /auditHash|appendAudit|\/data-residency|retentionHolds|outboxEvents|circuitBreaker|\/security\/secrets\/rotate|\/contract-tests/i.test(allContent); checks.recovery = /requireRole|rolesFor|\/backup|\/restore|migrations|featureFlags|x-content-type-options/i.test(allContent) }
    if (story.kind === 'bot') { checks.botSource = await exists(path.join(target, 'src/index.ts')); checks.audit = /auditLog|audit/i.test(allContent); checks.safeStubs = /restartRequests|Restart request logged|maintenance|stub|Destructive actions require explicit review/i.test(allContent) }
    if (story.kind === 'worker') { checks.workerSource = await exists(path.join(target, 'src/worker.ts')); checks.queueSource = await exists(path.join(target, 'src/queue.ts')); checks.idempotent = /idempotency|idempotencyKey/i.test(allContent); checks.workerStatus = /worker-status|dead|failed|retrying|retry|poison|cancelled/i.test(allContent); checks.eventLog = /events|event log|queue snapshot/i.test(allContent); checks.poison = /poisonJobs|poison/i.test(allContent); checks.leaseOutbox = /leaseUntil|heartbeatAt|outboxEvents|circuitBreaker/i.test(allContent); checks.cancelBackoff = /cancelJob|BACKOFF_MS|nextRunAt|\/api\/jobs\/:id\/cancel/i.test(allContent); checks.failureOwner = /FAILURE_OWNER|failure owner/i.test(allContent) }
    return checks
}
function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') }
await fs.rm(outRoot, { recursive: true, force: true }); await fs.mkdir(outRoot, { recursive: true })
const results = []
for (const story of stories) {
    const response = buildShareProjectResponse(story.prompt)
    if (!response) { results.push({ id: story.id, title: story.title, ok: false, reason: 'No builder response', checks: {} }); continue }
    const files = parseToolFiles(response.message); const target = await writeFiles(story, files); const checks = await verify(story, target, files); const ok = Object.values(checks).every(Boolean)
    results.push({ id: story.id, title: story.title, ok, target, fileCount: files.length, checks }); console.log(`${ok ? 'PASS' : 'FAIL'} ${story.id} ${story.title} (${files.length} files)`); if (!ok) console.log(Object.entries(checks).filter(([, value]) => !value).map(([key]) => `  - ${key}`).join('\n'))
}
const failed = results.filter((result) => !result.ok); await fs.writeFile(path.join(outRoot, 'results.json'), JSON.stringify({ generatedAt: new Date().toISOString(), results }, null, 2)); if (failed.length) throw new Error(`${failed.length} enterprise architecture stories failed.`); console.log(`All ${results.length} enterprise architecture stories passed.`)
