import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildShareProjectResponse } from '../src/handlers/tools/ai.ts'

type ToolFile = { action: string; path: string; content: string }
type Kind = 'website' | 'api' | 'bot' | 'worker'
type Story = { id: number; title: string; prompt: string; kind: Kind; mustMention: RegExp[] }

const scriptDir = path.dirname(fileURLToPath(import.meta.url))
const repoRoot = path.resolve(scriptDir, '..', '..')
const outRoot = path.join(repoRoot, 'sandbox', 'share-chat-procurement-hardening-stories')

const stories: Story[] = [
    { id: 341, title: 'Procurement Evidence API', kind: 'api', prompt: 'Create procurement evidence API with SBOM license policy dependency review threat model DPIA SLO runbook contract tests CI Docker.', mustMention: [/docs\/sbom\.json/i, /docs\/procurement-review\.md/i, /docs\/threat-model\.md/i, /docs\/slo\.md/i, /docs\/runbook\.md/i, /\/dependency-review/i, /\/dpia/i, /\/contract-tests/i] },
    { id: 342, title: 'Payload Limit Security API', kind: 'api', prompt: 'Build payload limit security API with MAX_BODY_BYTES bodyLimit CSP security headers CORS allowlist request IDs shaped errors vulnerability findings.', mustMention: [/MAX_BODY_BYTES/i, /bodyLimit/i, /content-security-policy/i, /x-content-type-options/i, /ALLOWED_ORIGINS/i, /x-request-id/i, /request_error/i, /\/vulnerability-findings/i] },
    { id: 343, title: 'SLO Synthetic Checks API', kind: 'api', prompt: 'Create SLO synthetic checks API with SLO_TARGET syntheticChecks metrics incident drills request IDs readiness schema rollback.', mustMention: [/\/slo/i, /SLO_TARGET/i, /\/synthetic-checks/i, /syntheticChecks/i, /\/metrics/i, /\/incident-drills/i, /x-request-id/i, /\/ready/i, /\/schema-rollback/i] },
    { id: 344, title: 'Dependency License Review Site', kind: 'website', prompt: 'Build dependency license review site with procurement review SBOM license policy threat model security review CI no lock-in Docker delivery.', mustMention: [/docs\/procurement-review\.md/i, /docs\/sbom\.json/i, /blockedLicenses/i, /docs\/threat-model\.md/i, /docs\/security-review\.md/i, /\.github\/workflows\/ci\.yml/i, /No platform lock-in/i, /Docker/i] },
    { id: 345, title: 'Dead Letter Replay Worker', kind: 'worker', prompt: 'Create dead letter replay worker with replayDeadLetter replay endpoint replayRequests leases heartbeats backoff poison queue outbox circuit breaker.', mustMention: [/replayDeadLetter/i, /\/api\/jobs\/:id\/replay/i, /replayRequests/i, /leaseUntil/i, /heartbeatAt/i, /BACKOFF_MS/i, /poisonJobs/i, /outboxEvents/i, /circuitBreaker/i] },
    { id: 346, title: 'DPIA Data Residency API', kind: 'api', prompt: 'Build DPIA data residency API with dpia data residency retention holds PII redaction audit hash chain backup restore security review.', mustMention: [/\/dpia/i, /dpia/i, /\/data-residency/i, /retentionHolds/i, /redact/i, /auditHash/i, /\/backup/i, /\/restore/i, /docs\/security-review\.md/i] },
    { id: 347, title: 'Schema Rollback API', kind: 'api', prompt: 'Create schema rollback API with schemaRollback migrations backup restore contract tests synthetic checks metrics request IDs.', mustMention: [/\/schema-rollback/i, /schemaRollback/i, /migrations/i, /\/backup/i, /\/restore/i, /\/contract-tests/i, /\/synthetic-checks/i, /\/metrics/i, /x-request-id/i] },
    { id: 348, title: 'Incident Drill Status Site', kind: 'website', prompt: 'Build incident drill status site with SLO docs runbook security review incident timeline SLO evidence postmortems CI Docker.', mustMention: [/docs\/slo\.md/i, /docs\/runbook\.md/i, /docs\/security-review\.md/i, /Incident timeline/i, /SLO evidence/i, /Postmortems/i, /\.github\/workflows\/ci\.yml/i, /Docker/i] },
    { id: 349, title: 'Vulnerability Finding API', kind: 'api', prompt: 'Create vulnerability finding API with vulnerability findings dependency review SBOM threat model security headers audit events request IDs metrics.', mustMention: [/\/vulnerability-findings/i, /vulnerabilityFindings/i, /\/dependency-review/i, /docs\/sbom\.json/i, /docs\/threat-model\.md/i, /content-security-policy/i, /auditEvents/i, /x-request-id/i, /\/metrics/i] },
    { id: 350, title: 'Contract Drift API', kind: 'api', prompt: 'Build contract drift API with contract tests OpenAPI synthetic checks request IDs schema rollback outbox circuit breaker metrics.', mustMention: [/\/contract-tests/i, /\/openapi\.json/i, /\/synthetic-checks/i, /x-request-id/i, /\/schema-rollback/i, /\/outbox/i, /circuitBreaker/i, /\/metrics/i] },
    { id: 351, title: 'Security Procurement Bot', kind: 'bot', prompt: 'Create Discord security procurement bot with security review procurement review SBOM threat model CI audit log safe stubs no destructive actions.', mustMention: [/docs\/security-review\.md/i, /docs\/procurement-review\.md/i, /docs\/sbom\.json/i, /docs\/threat-model\.md/i, /\.github\/workflows\/ci\.yml/i, /auditLog/i, /stub/i, /Destructive actions require explicit review/i] },
    { id: 352, title: 'Synthetic Recovery Worker', kind: 'worker', prompt: 'Build synthetic recovery worker with replayable dead letters event logs outbox events circuit breaker leases heartbeats backoff Redis runbook SLO docs.', mustMention: [/replayDeadLetter/i, /replayRequests/i, /events/i, /outboxEvents/i, /circuitBreaker/i, /leaseUntil/i, /heartbeatAt/i, /BACKOFF_MS/i, /Redis/i, /docs\/runbook\.md/i, /docs\/slo\.md/i] },
    { id: 353, title: 'Privacy Procurement Portal Site', kind: 'website', prompt: 'Create privacy procurement portal site with procurement security threat model docs privacy data paths no lock-in source export backend contract CI Docker.', mustMention: [/docs\/procurement-review\.md/i, /docs\/security-review\.md/i, /docs\/threat-model\.md/i, /Privacy and data paths/i, /No platform lock-in/i, /Readable source export/i, /Backend contract/i, /\.github\/workflows\/ci\.yml/i, /Docker/i] },
    { id: 354, title: 'Integration Circuit Replay API', kind: 'api', prompt: 'Create integration circuit replay API with circuit breaker outbox dependency review threat model contract tests OpenAPI metrics request IDs.', mustMention: [/circuitBreaker/i, /\/outbox/i, /\/dependency-review/i, /docs\/threat-model\.md/i, /\/contract-tests/i, /\/openapi\.json/i, /\/metrics/i, /x-request-id/i] },
    { id: 355, title: 'Release Runbook Cutover Site', kind: 'website', prompt: 'Build release runbook cutover site with runbook SLO incident drills synthetic checks DNS SSL checklist rollback plan verification CI Docker source export.', mustMention: [/docs\/runbook\.md/i, /docs\/slo\.md/i, /incident drills/i, /synthetic checks/i, /DNS checklist/i, /SSL checklist/i, /Rollback plan/i, /Verification/i, /\.github\/workflows\/ci\.yml/i, /Docker/i] },
    { id: 356, title: 'Payload Abuse API', kind: 'api', prompt: 'Create payload abuse API with payload limits rate limits request IDs CORS allowlist CSP shaped errors metrics vulnerability tracking.', mustMention: [/MAX_BODY_BYTES/i, /bodyLimit/i, /rateLimit/i, /x-request-id/i, /ALLOWED_ORIGINS/i, /content-security-policy/i, /request_error/i, /\/metrics/i, /\/vulnerability-findings/i] },
    { id: 357, title: 'License Gate API', kind: 'api', prompt: 'Build license gate API with dependency review SBOM blocked licenses security review procurement review CI OpenAPI no hardcoded secrets.', mustMention: [/\/dependency-review/i, /docs\/sbom\.json/i, /blocked/i, /docs\/security-review\.md/i, /docs\/procurement-review\.md/i, /\.github\/workflows\/ci\.yml/i, /\/openapi\.json/i] },
    { id: 358, title: 'DLQ Replay Import Worker', kind: 'worker', prompt: 'Create DLQ replay import worker with replay endpoint replayRequests poison quarantine leases heartbeats backoff outbox circuit breaker.', mustMention: [/\/api\/jobs\/:id\/replay/i, /replayRequests/i, /poisonJobs/i, /leaseUntil/i, /heartbeatAt/i, /BACKOFF_MS/i, /outboxEvents/i, /circuitBreaker/i] },
    { id: 359, title: 'Security Evidence Portfolio Site', kind: 'website', prompt: 'Build security evidence portfolio site with SBOM security review threat model procurement review CI accessible controls mobile layout no lock-in rollback path.', mustMention: [/docs\/sbom/i, /docs\/security-review/i, /docs\/threat-model/i, /docs\/procurement-review/i, /\.github\/workflows\/ci\.yml/i, /Accessible controls/i, /Mobile-first layout/i, /No platform lock-in/i, /Rollback path/i] },
    { id: 360, title: 'Production Procurement API', kind: 'api', prompt: 'Create production procurement API with SBOM license review threat model DPIA SLOs runbooks incident drills synthetic checks schema rollback vulnerability findings payload limits CSP security headers request IDs CORS metrics RLS data residency retention holds audit hash chain secrets rotation outbox circuit breaker contract tests OpenAPI transactions RBAC backup restore migrations feature flags PII redaction idempotency webhook signatures pagination schemaVersion failureOwner rate limiting token gate health readiness CI Docker.', mustMention: [/docs\/sbom\.json/i, /\/dependency-review/i, /docs\/threat-model\.md/i, /\/dpia/i, /\/slo/i, /docs\/runbook\.md/i, /\/incident-drills/i, /\/synthetic-checks/i, /\/schema-rollback/i, /\/vulnerability-findings/i, /MAX_BODY_BYTES/i, /content-security-policy/i, /x-request-id/i, /ALLOWED_ORIGINS/i, /\/metrics/i, /rlsPolicies/i, /\/data-residency/i, /retentionHolds/i, /auditHash/i, /\/security\/secrets\/rotate/i, /outboxEvents/i, /circuitBreaker/i, /\/contract-tests/i, /\/openapi\.json/i, /withTransaction/i, /requireRole/i, /\/backup/i, /\/restore/i, /migrations/i, /featureFlags/i, /redact/i, /idempotency/i, /verifyWebhookSignature/i, /nextCursor/i, /schemaVersion/i, /failureOwner/i, /rateLimit/i, /API_TOKEN/i] },
]

function parseToolFiles(message: string) { return [...message.matchAll(/<hanasand-tool>([\s\S]*?)<\/hanasand-tool>/g)].map((match) => JSON.parse(match[1]) as ToolFile) }
async function exists(filePath: string) { try { await fs.access(filePath); return true } catch { return false } }
async function read(filePath: string) { return await fs.readFile(filePath, 'utf8').catch(() => '') }
async function writeFiles(story: Story, files: ToolFile[]) {
    const target = path.join(outRoot, `${story.id}-${slugify(story.title)}`)
    await fs.rm(target, { recursive: true, force: true })
    for (const file of files) { const filePath = path.join(target, file.path); await fs.mkdir(path.dirname(filePath), { recursive: true }); await fs.writeFile(filePath, file.content) }
    return target
}
async function verify(story: Story, target: string, files: ToolFile[]) {
    const allContent = files.map((file) => `${file.path}\n${file.content}`).join('\n---\n')
    const checks: Record<string, boolean> = {
        enoughFiles: files.length >= (story.kind === 'website' ? 17 : story.kind === 'worker' ? 17 : 15), packageJson: await exists(path.join(target, 'package.json')), readme: await exists(path.join(target, 'README.md')), envExample: await exists(path.join(target, '.env.example')), dockerfile: await exists(path.join(target, 'Dockerfile')), compose: await exists(path.join(target, 'docker-compose.yml')), ci: await exists(path.join(target, '.github/workflows/ci.yml')), designSpec: await exists(path.join(target, 'docs/design-spec.json')), securityReview: await exists(path.join(target, 'docs/security-review.md')), threatModel: await exists(path.join(target, 'docs/threat-model.md')), procurementReview: await exists(path.join(target, 'docs/procurement-review.md')), runbook: await exists(path.join(target, 'docs/runbook.md')), slo: await exists(path.join(target, 'docs/slo.md')), sbom: await exists(path.join(target, 'docs/sbom.json')), noHardcodedSecrets: !/(sk-[a-z0-9]|xox[baprs]-|DISCORD_TOKEN\s*=\s*[^\n]*[A-Za-z0-9]{20,})/i.test(allContent), noLorem: !/lorem ipsum|placeholder text|todo: write copy/i.test(allContent), delivery: /delivery|release notes|verification|docker compose|failure owner|rollback|restore|CI|security review|runbook/i.test(await read(path.join(target, 'README.md'))), mentions: story.mustMention.every((pattern) => pattern.test(allContent)),
    }
    if (story.kind === 'website') { checks.page = await exists(path.join(target, 'src/app/page.tsx')); checks.layout = await exists(path.join(target, 'src/app/layout.tsx')); checks.accessible = /aria-label|<label|Skip to content/i.test(allContent); checks.responsive = /clamp\(|auto-fit|flexWrap|mobile/i.test(allContent); checks.exportable = /output:\s*'standalone'|docker compose/i.test(allContent); checks.trust = /No platform lock-in|Privacy and data paths documented|Backend contract|Rollback path/i.test(allContent) }
    if (story.kind === 'api') { checks.apiSource = await exists(path.join(target, 'src/index.ts')); checks.healthReady = /\/health|\/ready/.test(allContent); checks.operability = /x-request-id|\/openapi\.json|\/metrics|CACHE_TTL_SECONDS|withTransaction|ALLOWED_ORIGINS/i.test(allContent); checks.procurement = /\/dependency-review|\/dpia|\/slo|\/incident-drills|\/synthetic-checks|\/schema-rollback|\/vulnerability-findings|MAX_BODY_BYTES|content-security-policy/i.test(allContent); checks.trustArchitecture = /auditHash|appendAudit|\/data-residency|retentionHolds|outboxEvents|circuitBreaker|\/security\/secrets\/rotate|\/contract-tests/i.test(allContent); checks.recovery = /requireRole|rolesFor|\/backup|\/restore|migrations|featureFlags|x-content-type-options/i.test(allContent) }
    if (story.kind === 'bot') { checks.botSource = await exists(path.join(target, 'src/index.ts')); checks.audit = /auditLog|audit/i.test(allContent); checks.safeStubs = /restartRequests|Restart request logged|maintenance|stub|Destructive actions require explicit review/i.test(allContent) }
    if (story.kind === 'worker') { checks.workerSource = await exists(path.join(target, 'src/worker.ts')); checks.queueSource = await exists(path.join(target, 'src/queue.ts')); checks.workerStatus = /worker-status|dead|failed|retrying|retry|poison|cancelled/i.test(allContent); checks.replay = /replayDeadLetter|replayRequests|\/api\/jobs\/:id\/replay/i.test(allContent); checks.leaseOutbox = /leaseUntil|heartbeatAt|outboxEvents|circuitBreaker/i.test(allContent); checks.cancelBackoff = /cancelJob|BACKOFF_MS|nextRunAt|\/api\/jobs\/:id\/cancel/i.test(allContent); checks.failureOwner = /FAILURE_OWNER|failure owner/i.test(allContent) }
    return checks
}
function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '') }
await fs.rm(outRoot, { recursive: true, force: true }); await fs.mkdir(outRoot, { recursive: true })
const results = []
for (const story of stories) {
    const response = buildShareProjectResponse(story.prompt)
    if (!response) { results.push({ id: story.id, title: story.title, ok: false, reason: 'No builder response', checks: {} }); continue }
    const files = parseToolFiles(response.message); const target = await writeFiles(story, files); const checks = await verify(story, target, files); const ok = Object.values(checks).every(Boolean)
    results.push({ id: story.id, title: story.title, ok, target, fileCount: files.length, checks }); console.log(`${ok ? 'PASS' : 'FAIL'} ${story.id} ${story.title} (${files.length} files)`); if (!ok) console.log(Object.entries(checks).filter(([, value]) => !value).map(([key]) => `  - ${key}`).join('\n'))
}
const failed = results.filter((result) => !result.ok); await fs.writeFile(path.join(outRoot, 'results.json'), JSON.stringify({ generatedAt: new Date().toISOString(), results }, null, 2)); if (failed.length) throw new Error(`${failed.length} procurement hardening stories failed.`); console.log(`All ${results.length} procurement hardening stories passed.`)
