// @ts-nocheck
import { FocusedFrontier } from "../frontier/frontier.ts";
import { nowIso, stableId } from "../utils.ts";
import { BUDGETS } from "./plannerBudgets.ts";
import { hour, reuseTerms, uniq } from "./plannerQuery.ts";
import { sourceMatchesScope } from "./plannerSources.ts";
import { createCollectionPlan } from "./plannerCollection.ts";

export function createLiveSearchPlan(input): any {
  const request = { ...input.request, budgetClass: "interactive_live_search", priority: input.request.priority ?? "urgent", maxTasks: input.request.maxTasks ?? BUDGETS.interactive_live_search[0] };
  const plan = createCollectionPlan(request, input.sources, input.frontier ?? new FocusedFrontier({ strategy: "balanced" }));
  const reuseKey = liveSearchReuseKey(plan.request, input.sources, plan.queryTerms), activeRun = activeFor(plan, input.activeRuns ?? [], input.activePlans ?? [], reuseKey);
  const zeroTaskReason = zeroReason(plan, activeRun), recommendedSourceActivations = recommended(plan, input.sources, input.queryDemand ?? {});
  const back = backpressure(plan, activeRun, zeroTaskReason, input.frontier, recommendedSourceActivations, input.queuePressureLimit);
  return { plan, dto: { mode: "interactive_live_search", planId: plan.id, reuseKey, activeRunId: activeRun?.id, attachedToActiveRun: Boolean(activeRun), backpressureState: back.state, backpressureReason: back.reason, retryAfterSeconds: back.retryAfterSeconds, queuedTaskCount: plan.tasks.length, reviewTaskCount: plan.reviewRequired.length, blockedSourceCount: (plan.explanations ?? []).filter((x) => x.status === "blocked-by-policy" || x.status === "blocked-by-approval").length, skippedTaskCount: (plan.explanations ?? []).filter((x) => x.status === "skipped" || x.status === "duplicate-suppressed").length, nextPollSeconds: nextPoll(plan, activeRun, back.state), zeroTaskReason, coverageGaps: gaps(plan), recommendedSourceActivations, decisions: plan.explanations ?? [], queryTerms: plan.queryTerms ?? [plan.request.query] } };
}

export function liveSearchReuseKey(request, sources, queryTerms) {
  const scoped = sources.filter((s) => sourceMatchesScope(s, { includeClearWeb: request.includeClearWeb ?? true, includeTelegram: request.includeTelegram ?? true, includeDarknetMetadata: request.includeDarknetMetadata ?? false }));
  return stableId("live-reuse", JSON.stringify({ tenantId: request.tenantId ?? "global", entityType: request.entityType, terms: reuseTerms(request.query, request.entityType, queryTerms), sourceScope: uniq(scoped.map((s) => s.type)), riskScope: uniq(scoped.map((s) => s.risk)), freshnessWindow: hour(request.createdAt ?? nowIso()) }));
}

function zeroReason(plan, activeRun) { const ex = plan.explanations ?? []; if (activeRun) return "duplicate_run_already_active"; if (plan.tasks.length || plan.reviewRequired.length) return "none"; if (/^(apt|ransomware|malware|cve|threat|actor|victim)$/i.test(plan.request.query.trim())) return "query_too_broad"; if (!ex.length) return "no_approved_sources"; if (ex.every((x) => x.status === "waiting-for-backoff" || x.status === "delayed")) return "all_sources_stale_or_backoff"; if (ex.every((x) => x.status === "blocked-by-policy" || x.status === "blocked-by-approval")) return "all_sources_blocked_by_risk"; if (ex.every((x) => x.reason.includes("disabled") || x.reason.includes("outside request scope"))) return "adapter_disabled"; if (ex.every((x) => x.reason.includes("budget"))) return "tenant_budget_exhausted"; return "no_approved_sources"; }
function activeFor(plan, runs, plans, reuseKey) { const byReq = new Map(plans.map((p) => [p.request.id, p])); return runs.find((r) => same(r, plan) && r.requestHash === reuseKey) ?? runs.find((r) => same(r, plan) && r.requestId === plan.request.id) ?? runs.find((r) => same(r, plan) && byReq.get(r.requestId)?.request.query.toLowerCase() === plan.request.query.toLowerCase() && byReq.get(r.requestId)?.request.entityType === plan.request.entityType); }
function same(run, plan) { return run.tenantId === plan.tenantId && (run.status === "queued" || run.status === "running"); }
function backpressure(plan, activeRun, zero, frontier, recommended, limit = 1000) { if (activeRun) return { state: "attached_to_active_run", reason: `attached to active run ${activeRun.id}`, retryAfterSeconds: 5 }; if (zero === "tenant_budget_exhausted") return { state: "deferred_by_budget", reason: "live-search task budget is exhausted", retryAfterSeconds: 60 }; if ((frontier?.groupedSnapshot().queued ?? 0) >= limit) return { state: "deferred_by_queue_pressure", retryAfterSeconds: 30 }; if (zero === "all_sources_stale_or_backoff" || (plan.tasks.length && plan.tasks.some((t) => t.availableAt))) return { state: "deferred_by_source_backoff", retryAfterSeconds: 15 }; if (zero === "all_sources_blocked_by_risk" && !recommended.some((r) => r.reason.includes("restricted"))) return { state: "needs_source_activation", retryAfterSeconds: 60 }; if (zero === "all_sources_blocked_by_risk") return { state: "blocked_by_policy", retryAfterSeconds: 60 }; if (!plan.tasks.length && recommended.length) return { state: "needs_source_activation", retryAfterSeconds: 60 }; if (zero === "no_approved_sources" || zero === "adapter_disabled") return { state: "needs_source_activation", retryAfterSeconds: 60 }; return { state: "accepted" }; }
function recommended(plan, sources, demand) { const byId = new Map(sources.map((s) => [s.id, s])); const gapsNow = gaps(plan); const demandCount = Math.max(1, ...plan.queryTerms.map((t) => demand[t.toLowerCase()] ?? 0)); return (plan.explanations ?? []).filter((x) => x.status === "blocked-by-approval" || x.status === "blocked-by-policy" || x.reason.includes("outside request scope")).map((x) => { const s = byId.get(x.sourceId), coverageGap = coverage(s); const requiredAction = s?.accessMethod === "disabled" ? "enable_adapter" : ["paused", "disabled", "quarantined"].includes(s?.status) ? "restore" : ["candidate", "needs_review"].includes(s?.status) || s?.approvalRequired ? "approve" : "add_source"; return { sourceId: x.sourceId, reason: x.reason, requiredAction, priority: demandCount * 10 + (coverageGap && gapsNow.includes(coverageGap) ? 30 : 0), coverageGap, demandCount }; }).sort((a, b) => b.priority - a.priority || a.sourceId.localeCompare(b.sourceId)).slice(0, 10); }
function gaps(plan) { const gaps = new Set(); if (!plan.tasks.some((t) => ["rss", "static_web", "api"].includes(t.sourceType))) gaps.add("clear_web"); if (plan.request.includeTelegram && !plan.tasks.some((t) => t.sourceType === "telegram_public")) gaps.add("public_chat"); if (plan.request.includeDarknetMetadata && !plan.tasks.some((t) => t.sourceType.endsWith("_metadata"))) gaps.add("darknet_metadata"); if ((plan.explanations ?? []).some((x) => x.status === "waiting-for-backoff")) gaps.add("freshness_waiting_for_backoff"); return [...gaps]; }
function coverage(s) { return !s ? undefined : s.type === "telegram_public" ? "public_chat" : s.type.endsWith("_metadata") ? "darknet_metadata" : "clear_web"; }
function nextPoll(plan, activeRun, state) { return activeRun ? 5 : state === "deferred_by_queue_pressure" ? 30 : state === "deferred_by_budget" || state === "needs_source_activation" || state === "blocked_by_policy" ? 60 : plan.tasks.some((t) => t.planning?.selectedFor === "interactive") ? 3 : plan.tasks.some((t) => t.availableAt) ? 15 : 30; }
