export const commercialAccessPlans = [
    {
        id: 'threat-intelligence',
        name: 'Threat Intelligence',
        priceNok: 299,
        priceLabel: '299 NOK / month',
        quota: '100 searches per day',
        summary: 'Search actors, domains, companies, and current public intelligence.',
        features: ['Threat actor profiles', 'Current intelligence results', 'API access', 'Saved searches'],
    },
    {
        id: 'monitoring',
        name: 'Dark Web Monitoring',
        priceNok: 999,
        priceLabel: '999 NOK / month',
        quota: '25 watch terms',
        summary: 'Monitor relevant public intelligence and turn matches into alerts and cases.',
        features: ['Customer watchlists', 'Evidence-backed alerts', 'Case workflow', 'Source health and freshness'],
    },
    {
        id: 'scanner',
        name: 'Security Scanner',
        priceNok: 499,
        priceLabel: '499 NOK / month',
        quota: '10 monitored targets',
        summary: 'Run scheduled security checks against approved websites and review the findings.',
        features: ['Scheduled scans', 'Severity-based findings', 'Scan history', 'Run-now controls'],
    },
    {
        id: 'browser',
        name: 'Browser',
        priceNok: 399,
        priceLabel: '399 NOK / month',
        quota: '100 browser runs',
        summary: 'Inspect clearweb and darkweb sources through the controlled Browser product.',
        features: ['Clearweb browsing', 'Safe darkweb previews', 'Evidence capture', 'Run history'],
    },
] as const
