export const commercialAccessPlans = [
    {
        id: 'evaluation',
        name: 'Evaluation',
        priceLabel: 'No card required',
        bestFor: 'Individuals validating threat search, the versioned JSON API, browser analysis, and organization workflows before monitored coverage is activated.',
        access: 'Self-serve console and API',
        delivery: 'Setup request',
        review: 'Product evaluation',
        cta: 'Create account and API key',
        href: '/register?path=%2Fdevelopers%23api-access',
        features: [
            'Console and organization workspace',
            'Public threat-intelligence search',
            'Organization-scoped 90-day API key',
            'Browser sandbox allowance shown in product',
        ],
    },
    {
        id: 'monitoring',
        name: 'Monitoring',
        priceLabel: 'Sales scoped',
        bestFor: 'Security teams that need organization watchlists, reviewable alerts, case routing, and delivery history.',
        access: 'Provisioned workspace',
        delivery: 'Webhook and cases',
        review: 'Order-form scope',
        cta: 'Scope monitoring',
        href: '/contact?plan=monitoring',
        features: [
            'Organization watchlists',
            'Dark-web alert review and cases',
            'Webhook destinations and delivery history',
            'Coverage and limits recorded in the order form',
        ],
    },
    {
        id: 'integration',
        name: 'Integration',
        priceLabel: 'Sales scoped',
        bestFor: 'Operational teams connecting threat intelligence and monitored alerts to existing security workflows.',
        access: 'Provisioned workspace',
        delivery: 'API and webhook',
        review: 'Security review',
        cta: 'Plan integration',
        href: '/contact?plan=integration',
        features: [
            'Everything in Monitoring',
            'Production API budgets and key lifecycle',
            'Authenticated batch search and pagination',
            'Security and procurement review before activation',
        ],
    },
] as const
